### ISSUE TITLE
Request for hosting virtual-smart-structures-and-dynamics-laboratory-iitd

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#100]
Please host the virtual-smart-structures-and-dynamics-laboratory-iitd.

virtual-smart-structures-and-dynamics-laboratory-iitd Repo Link: -
"https://github.com/Virtual-Labs/virtual-smart-structures-and-dynamics-laboratory-iitd.git".

**Comment by jayanthsagar** [comment]
Deployed. You can access your lab using http://vssd-iitd.vlabs.ac.in

**Comment by sumitdahiyavlab** [comment]
In the source code of the lab, some special characters(looking like white spaces) were present. Due to them some question marks "?" were appearing on the user interface of the lab. I have removed these special characters. Please again deploy the lab.

**Comment by jayanthsagar** [comment]
Done. Updated
