### ISSUE TITLE
Request for hosting queueing-networks-modelling-lab-iitd

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#101]
Please host the queueing-networks-modelling-lab-iitd.

queueing-networks-modelling-lab-iitd Repo Link: -

"https://github.com/Virtual-Labs/queueing-networks-modelling-lab-iitd.git".

**Comment by jayanthsagar** [comment]
Deployed. you can access your lab using http://qnm-iitd.vlabs.ac.in

**Comment by sumitdahiyavlab** [comment]
Please redeploy the lab on the cloud. I added 2-3 lines in the source code for displaying a note for the viewers of the experiments.

queueing-networks-modelling-lab-iitd Repo Link: -
"https://github.com/Virtual-Labs/queueing-networks-modelling-lab-iitd"
