### ISSUE TITLE
Some vlabs labs not reachable from IIIT-H network

### ISSUE THREAD

**Issue by mzs-vlabs** [Virtual-Labs/engineers-forum#11]
User Jayanthi reported that some labs on vlabs were not reacheable from within IIIT-H network.

The labs which were not reachable were the ones hosted on AWS. This was due to user setting proxy exception in his browser and the browser trying to reach the destination without proxy, which fails.

We have approached IIIT-H network team to allow our labs to be reachable by making an exception in the proxy server.

**Comment by AmulyaSri** [comment]
Systems team has approached IIIT H network  team to allow our labs to be reachable by making an exception in the proxy server.
