### ISSUE TITLE
error deploying protein engineering lab

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#119]
from the following repo.
https://github.com/pushpdeep/protein_engg_iitb
clone succesfull
container created
but sudo-apt get update failed

[root@localhost pushpdeep]# tail -f /root/logs/ovpl.log 
05/29/2015 08:54:58 AM: INFO: /root/ovpl/src/VMManager/LabActionRunner.py:54  -> Running the pre-build scripts...
05/29/2015 08:54:58 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:45  -> LabActionScript::run() - 
05/29/2015 08:54:58 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:46  -> LabActionScript::run() - sudo apt-get update
05/29/2015 08:54:58 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:47  -> LabActionScript::run() - /root/labs/protein_engg_iitb/scripts
05/29/2015 08:54:58 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:27  -> command: sudo apt-get update
05/29/2015 08:58:03 AM: ERROR: /root/ovpl/src/utils/execute_commands.py:34  -> Called Process Error: Command 'sudo apt-get update' returned non-zero exit status 100
05/29/2015 08:58:03 AM: ERROR: /root/ovpl/src/VMManager/LabActionScript.py:52  -> LabActionScript::run() exception is: Command 'sudo apt-get update' returned non-zero exit status 100
05/29/2015 08:58:03 AM: ERROR: /root/ovpl/src/VMManager/VMManager.py:118 -> VMManager.test_lab failed: Script sudo apt-get update failed
05/29/2015 08:58:03 AM: DEBUG: /root/ovpl/src/LabManager.py:58  -> response = <Response [200]>
05/29/2015 08:58:03 AM: ERROR: /root/ovpl/src/Controller.py:46  -> test_lab(); Test failed with error:Test lab failed

**Comment by hrishikeshbaruah** [comment]
@pushpdeep 

Can you please check whether your container is able access internet or not by using command
"ping 8.8.8.8" then let me know .....

**Comment by ecthiender** [comment]
If this issue is fixed, we can close it.

**Comment by pushpdeep** [comment]
Its perfect now.
Close it
Thanks
