### ISSUE TITLE
Issue in "prebuild" step in ovpl - labspec.json - [duplicate issue from ovpl]

### ISSUE THREAD

**Issue by anhsirksai** [Virtual-Labs/engineers-forum#12]
I am running a shell script to install packages required for a lab with in pre_build of the labspec.json.

I have tested the script on a vanila ubuntu container. The script runs fine without throwing any error.

The same script when passed to ovpl via labspec.json, installation fails. I have set the execute permissions too.
"pre_build": ["sh pre-build-script.sh "],

My script "pre-build-script.sh":
(sudo apt-get update; sudo apt-get install -y make m4 build-essential gcc gfortran libssl-dev python-software-properties; sudo -E apt-add-repository -y ppa:aims/sagemath; sudo apt-get update; sudo apt-get install -y dvipng; sudo dpkg --configure -a; sudo apt-get install -f; sudo apt-get install -y sagemath-upstream-binary --force-yes)

I have tested the same on a new container multiple times and it is successfull. but not via ovpl.

**Comment by ecthiender** [comment]
Can you attach the logs of when the installation fails vai OVPL?

**Comment by ecthiender** [comment]
Closing here. As duplicate exists here: https://github.com/vlead/ovpl/issues/29

**Comment by ecthiender** [comment]
vlead/ovpl#29
