### ISSUE TITLE
Request to host hybrid-electronics-lab-coep

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#120]
Hi,

Please host the hybrid-electronics-lab-coep

URL : "https://github.com/Virtual-Labs/hybrid-electronics-lab-coep"

**Comment by sushilmedhe** [comment]
Please host the hybrid-electronics-lab 

url : "https://github.com/Virtual-Labs/hybrid-electronics-lab-coep"

**Comment by jayanthsagar** [comment]
Hi,
We have deployed your lab.
You can access lab using http://he-coep.vlabs.ac.in
