### ISSUE TITLE
error deploying chemical engineering lab

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#121]
https://github.com/pushpdeep/che01
container created, apt-get update done,
 but the sql installtion steps are failing 

05/29/2015 09:53:34 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:27  -> command: sudo apt-get install -y php5 apache2 php5-mysql
05/29/2015 09:56:21 AM: INFO: /root/ovpl/src/VMManager/LabActionRunner.py:59  -> Running the build scripts...
05/29/2015 09:56:21 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:45  -> LabActionScript::run() - 
05/29/2015 09:56:21 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:46  -> LabActionScript::run() - make -C ../src
05/29/2015 09:56:21 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:47  -> LabActionScript::run() - /root/labs/che01/scripts
05/29/2015 09:56:21 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:27  -> command: make -C ../src
05/29/2015 09:56:22 AM: INFO: /root/ovpl/src/VMManager/LabActionRunner.py:64  -> Running the post-build scripts...
05/29/2015 09:56:22 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:45  -> LabActionScript::run() - 
05/29/2015 09:56:22 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:46  -> LabActionScript::run() - service apache2 restart
05/29/2015 09:56:22 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:47  -> LabActionScript::run() - /root/labs/che01/scripts
05/29/2015 09:56:22 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:27  -> command: service apache2 restart
05/29/2015 09:56:24 AM: INFO: /root/ovpl/src/VMManager/LabActionRunner.py:69  -> Checking the status of the build...
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/VMManager/LabActionRunner.py:82  -> LabActionRunner::run_init_lab()
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:45  -> LabActionScript::run() - 
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:46  -> LabActionScript::run() - mv /var/www/index.html index.html.default
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:47  -> LabActionScript::run() - /root/labs/che01/scripts
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:27  -> command: mv /var/www/index.html index.html.default
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:45  -> LabActionScript::run() - 
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:46  -> LabActionScript::run() - cp -r ../build/* /var/www/
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:27  -> command: cp -r ../build/* /var/www/
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:47  -> LabActionScript::run() - /root/labs/che01/scripts
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:45  -> LabActionScript::run() - 
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:46  -> LabActionScript::run() - sh db_config.sh
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:47  -> LabActionScript::run() - /root/labs/che01/scripts
05/29/2015 09:56:24 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:27  -> command: sh db_config.sh
05/29/2015 09:56:26 AM: ERROR: /root/ovpl/src/utils/execute_commands.py:34  -> Called Process Error: Command 'sh db_config.sh' returned non-zero exit status 127
05/29/2015 09:56:26 AM: ERROR: /root/ovpl/src/VMManager/LabActionScript.py:52  -> LabActionScript::run() exception is: Command 'sh db_config.sh' returned non-zero exit status 127
05/29/2015 09:56:26 AM: ERROR: /root/ovpl/src/VMManager/VMManager.py:118 -> VMManager.test_lab failed: Script sh db_config.sh failed
05/29/2015 09:56:26 AM: DEBUG: /root/ovpl/src/LabManager.py:58  -> response = <Response [200]>
05/29/2015 09:56:26 AM: ERROR: /root/ovpl/src/Controller.py:46  -> test_lab(); Test failed with error:Test lab failed

**Comment by hrishikeshbaruah** [comment]
@ pushpdeep

Can you please text me the following file contents....

Steps:-

1) . Enter into respective lab container and navigate to "cd /root /" directory
2).  Then execute "cat vm.log

**Comment by ksripathi** [comment]
@ pushpdeep

 hey its me Sripathi from VLEAD sorry I forgot to login to my account instead I use other account

**Comment by ecthiender** [comment]
I hope this is fixed, right?

**Comment by pushpdeep** [comment]
Yes its fixed.
Thanks
