### ISSUE TITLE
request to create repositry SIP lab

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#122]
please create a repo named
sattelite image processing lab

**Comment by soujanya123** [comment]
Github url:
https://github.com/Virtual-Labs/sattelite-image-processing-lab-iitb

Thanks and Regards
Soujanya J
Project Engineer
Virtual Labs Engineering and Architecture Division (VLEAD)
Vindhya B6-204, IIIT-H Campus
Gachibowli, Hyderabad 500 032
vlead.vlabs.ac.in
