### ISSUE TITLE
Request to host Colloid and Surface Chemistry Virtual Lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#124]
Hi,

Please host the Colloid and Surface Chemistry lab-IIITH. Lab is at level 5 and running on ADS.
Following is the URL for this lab.

"https://github.com/Virtual-Labs/colloid-and-surface-chemistry-iiith"

Lab developer wants this lab to be hosted as soon as possible, so kindly make this lab up and running as soon as possible. Let me know with the progress when its done.

Thanks & Regards, 
Sadhana.

**Comment by ecthiender** [comment]
You have to tag with "request for hosting" Label.

**Comment by jayanthsagar** [comment]
Deployed. URL- http://csc-iiith.vlabs.ac.in
