### ISSUE TITLE
Problem in hosting power-electronics-and-electric-drives-laboratory-iitd as the lab uses Windows Server 2008 and IIS6. 

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#125]
Problem in hosting power-electronics-and-electric-drives-laboratory-iitd as the lab uses Windows Server 2008 and IIS6. Kindly provide your suggestions, so that this lab can also be hosted on the cloud.

**Comment by ecthiender** [comment]
Currently, we cannot integrate a Windows machine into our current infrastructure due to its security, monitoring and backup implications.

**Comment by sanchita-dixit** [comment]
@sumitdahiyavlab If this issue was resolved, kindly close this issue.

**Comment by sumitdahiyavlab** [comment]
I have reported this issue to the respective Stakeholders/Lab developers. The issue is under consideration.
