### ISSUE TITLE
request to create repositry electrical engineering lab

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#126]

**Comment by ecthiender** [comment]
Request you to tag with "request to create repo" label. It becomes easy for us to categorize the coming requests.

Also, you have some previously created repos of electrical and chemical engg. Shall I remove them and create fresh repos?

**Comment by ecthiender** [comment]
Done. Link: https://github.com/Virtual-Labs/electrical-engg-iitb
