### ISSUE TITLE
Problem using OVPL with CentOS 7.0

### ISSUE THREAD

**Issue by geetabose** [Virtual-Labs/engineers-forum#13]
We at IIT Kharagpur are having problems with building the OVPL container.  

CentOS 6.5 is not available on the net. We are using CentOS 7.0. 
Kernel information is shown below. 
`# uname -a`
Linux localhost.localdomain 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

The OVPL setup scripts were downloaded from the following link
https://github.com/vlead/setup-ovpl-centos/archive/master.zip

When we try to run centos_prepare_ovpl.sh we get errors. The output 
as seen on the terminal is reproduced below. Please advise how these
problems can be overcome. Please reply at the earliest. 

]# ./centos_prepare_ovpl.sh
http://10.3.100.207:8080/
Invoking install_dependencies.sh

Setting up EPEL repo..
warning: ../meta/epel-release-6-8.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
Preparing...                          ################################# [100%]
    file /etc/rpm/macros.ghc-srpm from install of epel-release-6-8.noarch conflicts with file from package redhat-rpm-config-9.1.0-63.el7.centos.noarch

Installing dependencies.. yum -y install gcc python-devel.x86_64 python-pip ssh git
Loaded plugins: fastestmirror, langpacks
base                                                                                                                                                     | 3.6 kB  00:00:00     
extras                                                                                                                                                   | 3.4 kB  00:00:00     
mongodb                                                                                                                                                  |  951 B  00:00:00     
openvz-kernel-rhel6                                                                                                                                      | 2.8 kB  00:00:00     
openvz-utils                                                                                                                                             | 2.5 kB  00:00:00     
updates                                                                                                                                                  | 3.4 kB  00:00:00     
updates/7/x86_64/primary_db    FAILED                                          
http://centosmirror.go4hosting.in/centos/7.0.1406/updates/x86_64/repodata/db532afd5815bb2cc060f0f15402e619a3f1db81ef48c8a1d9a78b27dfca56de-primary.sqlite.bz2: [Errno 12] Timeout on http://centosmirror.go4hosting.in/centos/7.0.1406/updates/x86_64/repodata/db532afd5815bb2cc060f0f15402e619a3f1db81ef48c8a1d9a78b27dfca56de-primary.sqlite.bz2: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
updates/7/x86_64/primary_db                                                                                                                              | 6.6 MB  00:02:55     
Loading mirror speeds from cached hostfile
 * base: centos-hcm.viettelidc.com.vn
 * extras: centos.excellmedia.net
 * openvz-kernel-rhel6: download.openvz.org
 * openvz-utils: download.openvz.org
 * updates: centos-hn.viettelidc.com.vn
Package gcc-4.8.2-16.2.el7_0.x86_64 already installed and latest version
Package python-devel-2.7.5-16.el7.x86_64 already installed and latest version
No package python-pip available.
No package ssh available.
Package git-1.8.3.1-4.el7.x86_64 already installed and latest version
Nothing to do
Invoking install_openvz.sh

Setting up OpenVZ repo..

Installing the OpenVZ kernel..
Loaded plugins: fastestmirror, langpacks
openvz-kernel-rhel6                                                                                                                                      | 2.8 kB  00:00:00     
openvz-utils                                                                                                                                             | 2.5 kB  00:00:00     
Loading mirror speeds from cached hostfile
 * base: centos-hcm.viettelidc.com.vn
 * extras: centos.excellmedia.net
 * openvz-kernel-rhel6: download.openvz.org
 * openvz-utils: download.openvz.org
 * updates: centos-hn.viettelidc.com.vn
Resolving Dependencies
--> Running transaction check
---> Package vzkernel.x86_64 0:2.6.32-042stab104.1 will be installed
--> Processing Dependency: /sbin/mkinitrd for package: vzkernel-2.6.32-042stab104.1.x86_64
--> Processing Dependency: /sbin/mkinitrd for package: vzkernel-2.6.32-042stab104.1.x86_64
--> Finished Dependency Resolution
Error: Package: vzkernel-2.6.32-042stab104.1.x86_64 (openvz-kernel-rhel6)
           Requires: /sbin/mkinitrd
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Configuring OpenVZ..

Installing OpenVZ tools..
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos-hcm.viettelidc.com.vn
 * extras: centos.excellmedia.net
 * openvz-kernel-rhel6: download.openvz.org
 * openvz-utils: download.openvz.org
 * updates: centos-hn.viettelidc.com.vn
Resolving Dependencies
--> Running transaction check
---> Package ploop.x86_64 0:1.12.2-1 will be installed
--> Processing Dependency: ploop-lib = 1.12.2-1 for package: ploop-1.12.2-1.x86_64
--> Processing Dependency: libploop.so.1()(64bit) for package: ploop-1.12.2-1.x86_64
---> Package vzctl.x86_64 0:4.8-1 will be installed
--> Processing Dependency: vzctl-core = 4.8-1 for package: vzctl-4.8-1.x86_64
--> Processing Dependency: vzkernel for package: vzctl-4.8-1.x86_64
--> Processing Dependency: vzeventmod for package: vzctl-4.8-1.x86_64
--> Processing Dependency: libvzctl-4.8.so()(64bit) for package: vzctl-4.8-1.x86_64
---> Package vzquota.x86_64 0:3.1-1 will be installed
---> Package vzstats.noarch 0:0.5.3-1 will be installed
--> Running transaction check
---> Package ploop-lib.x86_64 0:1.12.2-1 will be installed
--> Processing Dependency: e2fsprogs-resize2fs-static for package: ploop-lib-1.12.2-1.x86_64
---> Package vzctl-core.x86_64 0:4.8-1 will be installed
---> Package vzkernel.x86_64 0:2.6.32-042stab104.1 will be installed
--> Processing Dependency: /sbin/mkinitrd for package: vzkernel-2.6.32-042stab104.1.x86_64
--> Running transaction check
---> Package e2fsprogs-resize2fs-static.x86_64 0:1.42.11-1.ovz will be installed
---> Package vzkernel.x86_64 0:2.6.32-042stab104.1 will be installed
--> Processing Dependency: /sbin/mkinitrd for package: vzkernel-2.6.32-042stab104.1.x86_64
--> Processing Dependency: /sbin/mkinitrd for package: vzkernel-2.6.32-042stab104.1.x86_64
--> Finished Dependency Resolution
Error: Package: vzkernel-2.6.32-042stab104.1.x86_64 (openvz-kernel-rhel6)
           Requires: /sbin/mkinitrd
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Copying the default OS template for containers..
cp: cannot create regular file ‘/vz/template/cache’: No such file or directory

Finished installing OpenVZ
Invoking install_mongodb.sh

Setting up MongoDB repo..

Installing MongoDB..
Loaded plugins: fastestmirror, langpacks
mongodb                                                                                                                                                  |  951 B  00:00:00     
Loading mirror speeds from cached hostfile
 * base: centos-hcm.viettelidc.com.vn
 * extras: centos.excellmedia.net
 * openvz-kernel-rhel6: download.openvz.org
 * openvz-utils: download.openvz.org
 * updates: centos-hn.viettelidc.com.vn
Package mongodb-org-2.6.7-1.x86_64 already installed and latest version
Nothing to do

Starting mongod service..
Starting mongod (via systemctl):                           [  OK  ]

**Comment by ecthiender** [comment]
OVPL will not work with CentOS 7.0. **Please use CentOS 6.6.**

There is a mistake in the documentation which says, OVPL works with CentOS 6.5 and above (during the documentation CentOS 7.0 did not come out).

CentOS 7.0 uses a newer version of the Linux kernel which is not compatible with OpenVZ used by OVPL.

**Comment by geetabose** [comment]
Dear VLEAD Team members,

The scripts are meant for an older distribution which is no longer
available. Also, there is a problem with the packages which are
attempted to be downloaded, as those also may be outdated.

For these reasons, it is only desirable that the script be urgently
upgraded to be usable on the version of CentOS that is currently
available, i.e. version 7.

We need urgent action on this as our work towards building the
OVPL for the labs is now held up.

Thanks and regards,
-Chitta

**Comment by ecthiender** [comment]
*The scripts should be run on CentOS 6.6*. 
The scripts do not install any OS. So please make sure you install CentOS 6.6 and then run the scripts.

The scripts won't work on CentOS 7. 

PS: There is no point upgrading our scripts to work for CentOS 7, because OpenVZ would not work on CentOS 7, and as a result our software OVPL also won't work.
