### ISSUE TITLE
request to delete repo 

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#131]
please delete the following repos
these are elarier ones and outdated
https://github.com/Virtual-Labs/ovpl-chemengg-iitb
https://github.com/Virtual-Labs/chemeng-iitbombay
https://github.com/Virtual-Labs/iitb-vlabs

**Comment by ecthiender** [comment]
Removed them. These changes cannot be reverted!

**Comment by pushpdeep** [comment]
Thanks
