### ISSUE TITLE
Deployment of 2 Labs of DEI.(both of them were hosted on cloud) but at present not working

### ISSUE THREAD

**Issue by samodk** [Virtual-Labs/engineers-forum#132]
Hello
We had hosted our 2 labs i.e Metal forming simulation lab and Power Lab in January, when we had a training at IIIT Hyderabad. Few months later, when we are trying to run through the IP Address which i get after deployment to the cloud, its not working..
Kindly check it and provide the feedback.
Thanks

**Comment by ecthiender** [comment]
@jayanthsagar I think we did not redeploy the two Dayalbagh labs that were there on Amazon previously. What is the protocol to proceed on this?

**Comment by jayanthsagar** [comment]
This is the size of the repo extracted using github API.
  "size": 2583684 kb,
ADS timed out when tried to deploy.
Can I do it manually?

**Comment by jayanthsagar** [comment]
Deployed.
You can access your labs using below URLs
http://msvs-dei.vlabs.ac.in
http://vp-dei.vlabs.ac.in
