### ISSUE TITLE
Deployment of Metal Forming Simulation Lab using database script file

### ISSUE THREAD

**Issue by samodk** [Virtual-Labs/engineers-forum#133]
This Lab has a database file which is used extensively. This issue was captured when it was deployed today. Kindly do the same with the database.
Sorry for the disturbance.

Thanks

**Comment by jayanthsagar** [comment]
Please update your labspec to deploy lab including database. we can't do it manually. Your labspec should include steps to install DB and do necessary actions like dump or restore etc., as per your requirements.
