### ISSUE TITLE
request to host sip lab iitb

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#137]
following is the link to the lab ,
its on level 3, its windows lab.
as the lab resource is huge
i cant upload on git. 
please see the follwing resource and use the maunal for installtion on the vm 
thanks

https://drive.google.com/folderview?id=0By-41PAA6wwefm15MTNqWFc4VlNCdmVQckVNZVJIOUp6NW84T1pPYm5KSXJhVHE5US1ZWU0&usp=sharing

**Comment by ecthiender** [comment]
I am not sure if we can bypass the hosting protocol to host your lab. Also, the lab is a Windows lab, we cannot integrate a Windows machine into our current infrastructure due to its security, monitoring and backup implications.

Comments from everyone are welcome.

**Comment by sanchita-dixit** [comment]
@pushpdeep Kindly follow up with the request whether it is still valid for hosting.

**Comment by sanchita-dixit** [comment]
@pushpdeep Can I close this issue as there has been no response on the validity of this request from your side.

**Comment by pushpdeep** [comment]
The lab developers haven't found a way to host this as its windows based.
Do you think the current repo is deploable, if not, then close it.

**Comment by sanchita-dixit** [comment]
@pushpdeep After a brief discussion here, it is concluded that we still don't have infrastructure to host this windows lab. The hosting protocol also can't be bypassed for this. The link which you provided above is showing a 404 page not found error. I am closing this issue for now. If some development happens on the same, we would reopen this issue again.
