### ISSUE TITLE
Error testing a lab on ADS

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#139]
I'm getting an error while testing a molecular-florescence-spectroscopy lab. Following is an error:

06/05/2015 12:22:50 PM: DEBUG: /root/ovpl/src/Controller.py:38  -> test_lab(): vmmgrurl = http://10.2.58.2
06/05/2015 12:22:50 PM: DEBUG: /root/ovpl/src/LabManager.py:47  -> vmmgr_ip = http://10.2.58.2, port = 9089, lab_src_url = https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-iiith
06/05/2015 12:22:50 PM: DEBUG: /root/ovpl/src/LabManager.py:53  -> url = http://10.2.58.2:9089/api/1.0/test-lab, payload = {'version': None, 'lab_src_url': 'https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-iiith'}
06/05/2015 12:23:02 PM: DEBUG: /root/ovpl/src/LabManager.py:60  -> response = <Response [200]>
06/05/2015 12:23:02 PM: ERROR: /root/ovpl/src/Controller.py:49  -> test_lab(); Test failed with error:Test lab failed

Can someone please resolve this issue.

**Comment by ecthiender** [comment]
@travula can you help them with this, if you are around?

The above bit of log is not helpful. 

@sadhanareddy can you put the entire log at http://pastebin.com/ and paste the link here.
Also can you do the same for vm.log file which will be in the container where the labs is getting deployed.

**Comment by sadhanareddy** [comment]
I have pasted the entire log at  http://pastebin.com/ . Following is the link:
http://pastebin.com/kaFHMYgW

**Comment by ecthiender** [comment]
Can you also paste the logs of vm.log file inside the container?

**Comment by sadhanareddy** [comment]
yaa.. pasted the logs of container too.. you can find the link here  
http://pastebin.com/pTFVeDSZ

**Comment by ecthiender** [comment]
If you see the end of the logs, apt-get installation fails. This is
probably due to network issues in the container. I am not sure though.

**Comment by ecthiender** [comment]
@sadhanareddy if this issue is resolved, please close the issue.

**Comment by sanchita-dixit** [comment]
@sadhanareddy As there is no further comment from the creator of this issue. I am thereby closing this issue.
