### ISSUE TITLE
Request for hosting Power lab dei

### ISSUE THREAD

**Issue by ajaykant00** [Virtual-Labs/engineers-forum#140]
I have pushed the required scripts into the script folder.
So host the Virtual Power Lab dei.
Git URL: https://github.com/Virtual-Labs/virtual-power-lab-dei

**Comment by jayanthsagar** [comment]
Already deployed. Updated with the latest sources.
Note: If you want to redeploy lab, please comment on same request which you raised to deploy you lab.
