### ISSUE TITLE
NITK labs in vlab.co.in 

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#145]
Sir/Madam,

The NITK labs updated in vlab.co.in ,have some issues in simulators .

Mechanics of machine Lab :http://mm-nitk.vlabs.ac.in/
Machine Dynamics & Vibration Lab : http://mdmv-nitk.vlabs.ac.in/
Process Control, Reaction Engineering and Unit Operations Lab : http://uorepc-nitk.vlabs.ac.in/

can you revert these lab links to old links of solve.nitk.ac.in.

Thanks and Regards,
Shivakumar s r

**Comment by jayanthsagar** [comment]
Vlab.co.in is not under VLEAD control. @geetabose can we drop mail to rohit to revert back to old links? . please comment.

**Comment by sanchita-dixit** [comment]
@geetabose Any updates on this.

**Comment by ecthiender** [comment]
@sranjanagi did this issue get resolved for you?

**Comment by ecthiender** [comment]
@sranjanagi did the issue get resolved?

**Comment by sanchita-dixit** [comment]
@sranjanagi @santhoshnitte87 Please comment whether this issue is still valid/invalid so that we can close it.

**Comment by sanchita-dixit** [comment]
@sranjanagi @santhoshnitte87 Since there has been no response on the issue from a very long time, it is being closed. Please re-open it whenever required.
