### ISSUE TITLE
Request for hosting engineering-electro-magnetics-laboratory-iitd

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#146]
Please host the engineering-electro-magnetics-laboratory-iitd.

engineering-electro-magnetics-laboratory-iitd Repo Link: -

"https://github.com/Virtual-Labs/engineering-electro-magnetics-laboratory-iitd.git".

**Comment by jayanthsagar** [comment]
We have deployed your lab.
you can access lab using http://eem-iitd.vlabs.ac.in

**Comment by sumitdahiyavlab** [comment]
Due to some mistake in labspec.json file, home.html was loading instead of index.html. Now, I have changed the labspec.json file.  Kindly redeploy the lab.

**Comment by jayanthsagar** [comment]
Updated
