### ISSUE TITLE
Unable to get internet connection to Open-VZ container 

### ISSUE THREAD

**Issue by GuptaManoj** [Virtual-Labs/engineers-forum#147]
@vlead-system-team

Dear vlead team,

I am trying to deploy a lab over ADS  I couldn't install pre-requisites inside container its due to internet issue can you please help me to resolve this issue.

**Comment by ayogi** [comment]
Fixed the issue.

**Comment by sanchita-dixit** [comment]
Is the issue resolved??
Please comment so that we can close this issue.

**Comment by sanchita-dixit** [comment]
@GuptaManoj I am hoping that the comment from @ayogi resolved your issue. There is no further query on this, I am thereby closing this issue.
