### ISSUE TITLE
Request for hosting Power lab dei and Virtual Chemistry Lab on AWS

### ISSUE THREAD

**Issue by samodk** [Virtual-Labs/engineers-forum#148]
These two labs are tested on ADS , Plz host these labs :
 Virtual Power Lab DEI
 Virtual Chemistry Lab DEI

**Comment by ecthiender** [comment]
You have to raise separate requests for each lab.

**Comment by jayanthsagar** [comment]
Tagging it invalid. Please raise separate request for each lab including URL of the repo.
