### ISSUE TITLE
Issue with SUBNET and HOST_NAME on my localhost

### ISSUE THREAD

**Issue by pkjana** [Virtual-Labs/engineers-forum#15]
Hi,

I have two confusion to configuring ovpl/src/settings.py file on my localhost  
1. What would be the SUBNET for my localhost where as my localhost(base machine) IP address is 10.11.56.57

2. What would be the HOST_NAME for my localhost where as my localhost(base machine) name is below

[root@localhost ~]# hostname
localhost.localdomain
[root@localhost ~]#

Thanks and regards,

Pabitra K Jana
IIT Kharagpur

**Comment by travula** [comment]
This could be the setting:
SUBNET = ["10.11.56.1/24"]

What this means is: the range of ip addresses will be 10.11.56.1 to
10.11.56.255.

You can ignore the host name and keep it as the default.

**Comment by ecthiender** [comment]
I am assuming your question has been resolved. Closing it. Please re-open the issue if you think it has not been resolved yet.
