### ISSUE TITLE
Hosting of Virtual Chemistry Lab DEI on AWS

### ISSUE THREAD

**Issue by samodk** [Virtual-Labs/engineers-forum#150]
Hi,
 As, I have tested this lab on ADS, Kindly host this lab on AWS

The URL of this Lab : 
https://github.com/Virtual-Labs/virtual-chemistry-lab-dei

**Comment by jayanthsagar** [comment]
Hi,

We have deployed your lab,
You can access lab using http://vc-dei.vlabs.ac.in

**Comment by jayanthsagar** [comment]
Looks like your lab is using Wordpress. Which version of wordpress are you using?. There are many known vulnerabilities in wordpress. Are you taking care of it?

@ecthiender please comment.

**Comment by samodk** [comment]
Since the landing page and template is not appearing....

On Thu, Jun 11, 2015 at 6:11 PM, jayanth sagar <notifications@github.com>
wrote:

> Looks like your lab is using Wordpress. Which version of wordpress are you
> using?. There are many known vulnerabilities in wordpress. Are you taking
> care of it?
>
> @ecthiender <https://github.com/ecthiender> please comment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Virtual-Labs/engineers-forum/issues/150#issuecomment-111119361>
> .
>



-- 

*Samod Kumar*
*M.Sc. (Computer Science)*
*Dayalbagh University*
*Dayalbagh Agra*

*"Stay Hungry !! Stay Foolish !!"*
