### ISSUE TITLE
NITK, mechanical labs are loading slow.

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#152]
Sir/Madam,

NITK labs like 
 Mechanics of machine Lab:   http://mm-nitk.vlabs.ac.in/
 Machine Dynamics & Vibration Lab :http://mdmv-nitk.vlabs.ac.in/

takes more time while loading the pages on these 2 labs (mainly in simulation ).

Please have look into it.

Thanks and Regards
Shivakumar s r

**Comment by sanchita-dixit** [comment]
@apurv111 Any updates on this.

**Comment by apurv111** [comment]
Checked the simulations. Seems Fine to me.
