### ISSUE TITLE
Issue with the lab sources

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#154]
In Analog CMOs VLSI Circuit Design and Mobile Robotics labs, sources are not built properly, it has only one experiment. Could you please check with this issue.

**Comment by apurv111** [comment]
@ayogi @MSSoumya . Could you please check for the sources on bitbucket repo for this lab.

**Comment by MSSoumya** [comment]
@sravanthimodepu The sources for both the labs are present on bitbucket. The lab experiments are not named as "exp2", "exp3" etc. They are named after their individual experiment names.

**Comment by apurv111** [comment]
@sravanthimodepu @MSSoumya The sources are present on github as well.
