### ISSUE TITLE
Request to host Colloid and Surface Chemistry Lab 

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#155]
Hi, 

Please host Colloid and Surface Chemistry Virtual Lab. Following is the link of the lab:

https://github.com/Virtual-Labs/colloid-and-surface-chemistry-iiith

**Comment by jayanthsagar** [comment]
This lab is already deployed but the correct sources were on develop branch. Looks like mereged develop to master.

Redeployed. Check now using same URL http://csc-iiith.virtual-labs.ac.in
