### ISSUE TITLE
Kindly tell me the correct UI Format

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#156]
Please tell me the correct UI format for virtual labs. It is much helpful if you could tell me the address of any existing lab which is following the correct UI format. So that we can follow the same for our labs.

**Comment by ecthiender** [comment]
Hi Sumit,

Please check this repo: https://github.com/vlead/ui-1.0-toolkit

The above repo is the UI toolkit, which contains documentation and the
samples for UI 1.0. Please go through it. You can use the same for
converting your labs to UI 1.0. If you are lab is in Amrita format, you can
use the automated scripts to automatically convert the labs from Amrita
format to UI 1.0.

Hope this resolves your query.

**Comment by sumitdahiyavlab** [comment]
Ok Anon.. Thanks.. I'll try the above procedure.
