### ISSUE TITLE
Request to host the labs

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#158]
Hi,
Please host the following labs.

Natural Language Processing : https://github.com/Virtual-Labs/natural-language-processing-iiith.git
Molecular Absorption Spectroscopy : https://github.com/Virtual-Labs/molecular-absorption-spectroscopy-iiith.git
Molecular Interactions : https://github.com/Virtual-Labs/molecular-interactions-iiith.git
Geotechnical Engineering Lab : https://github.com/Virtual-Labs/geotechnical-engineering-lab-iiith.git
Computational Linguistics : https://github.com/Virtual-Labs/computational-linguistics-iiith.git
Structural Dynamics : https://github.com/Virtual-Labs/structural-dynamics-iiith.git 
Speech Signal Processing : https://github.com/Virtual-Labs/speech-signal-processing-iiith.git
Soil Mechanics and Foundation Engineering : https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith.git
Molecular Florescence Spectroscopy : https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-iiith.git
Circular Dichronism Spectroscopy : https://github.com/Virtual-Labs/circular-dichronism-spectroscopy-iiith.git
Basic Structural Analysis : https://github.com/Virtual-Labs/basic-structural-analysis-iiith.git

**Comment by jayanthsagar** [comment]
please create a single request for single lab as we can track the progress. Bulk requests are not accepted.
