### ISSUE TITLE
Request to host Molecular Florescence Spectroscopy

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#160]
Hi,

Please host the Molecular Florescence Spectroscopy lab
Following is the lab url :

https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-iiith.git

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The lab has been hosted. Following is the url : http://mfs-iiith.vlabs.ac.in/
