### ISSUE TITLE
Request to host Molecular Absorption Spectroscopy lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#161]
Hi,
Please host Molecular Absorption Spectroscopy lab.
Following is the lab URL:

https://github.com/Virtual-Labs/molecular-absorption-spectroscopy-iiith.git

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The lab has been hosted. Following is the url : http://mas-iiith.vlabs.ac.in/
