### ISSUE TITLE
Request to host Geotechnical Engineering Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#163]
Hi,

Please host Geotechnical Engineering Lab.
Following is the lab URl:

https://github.com/Virtual-Labs/geotechnical-engineering-lab-iiith.git

**Comment by jayanthsagar** [comment]
We are not taking up any hosting requests as decided till our maintenance
tasks gets finished. And the previous request made to update links on
vlab.co.in is still pending.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The lab has been hosted. URL is : http://ge-iiith.vlabs.ac.in/
