### ISSUE TITLE
Request to host Speech Signal Processing Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#166]
Hi,

Please host Speech Signal Processing Lab.
Following is the lab URL:

https://github.com/Virtual-Labs/speech-signal-processing-iiith.git

**Comment by sanchita-dixit** [comment]
@sravanthimodepu I have hosted this lab. You can access the lab using the URL : http://ssp-iiith.vlabs.ac.in/
