### ISSUE TITLE
Request to host Soil Mechanics and Foundation Engineering Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#167]
Hi,

Please host Soil Mechanics and Foundation Engineering Lab.
Following is the lab URL:

https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith.git

**Comment by sanchita-dixit** [comment]
@sravanthimodepu I have hosted this lab. You can access the lab using the URL : http://smfe-iiith.vlabs.ac.in/
