### ISSUE TITLE
Request to host Circular Dichronism Spectroscopy Lab.

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#168]
Hi,

Please host Circular Dichronism Spectroscopy Lab.
Following is the lab URl:

https://github.com/Virtual-Labs/circular-dichronism-spectroscopy-iiith.git

**Comment by sanchita-dixit** [comment]
@sravanthimodepu I have hosted this lab. You can access the lab using the URL : http://cds-iiith.vlabs.ac.in/
