### ISSUE TITLE
Request to host Basic Structural Analysis Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#169]
Hi,

Please host Basic Structural Analysis Lab.
Following is the lab URl:

https://github.com/Virtual-Labs/basic-structural-analysis-iiith.git

**Comment by sanchita-dixit** [comment]
@sravanthimodepu I have hosted this lab. You can access the lab using the URL : http://bsa-iiith.vlabs.ac.in/. Please close the issue.
