### ISSUE TITLE
OVPL test error (NITK)

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#170]
I am trying to run the ovpl in NITK.

I am getting this error.
please ressolve it .

[I 150721 17:25:30 autoreload:204] /root/ovpl/src/adapters/settings.py modified; restarting server
[D 150721 17:25:30 ControllerServer:149] ControllerServer: It will run on port : 8080
10.100.83.177:8239
10.100.83.177:8239
[D 150721 17:25:30 git_commands:13] GIT_CLONE_LOC = /root/labs/
[D 150721 17:25:30 git_commands:14] LAB_SPEC_DIR = /scripts/
[D 150721 17:25:30 git_commands:15] LAB_SPEC_FILE = labspec.json
[D 150721 17:25:30 CentOSVZAdapter:216] CentOSVZAdapter: test_logging()
[D 150721 17:25:30 AdapterServer:117] __main__() PORT=8000, CreateURI=/api/1.0/vm/create, DestroyURI=/api/1.0/vm/destroy, RestartURI=/api/1.0/vm/restart
[I 150721 17:25:32 web:1908] 200 GET / (10.100.83.177) 9.99ms
[D 150721 17:25:34 ControllerServer:61] Lab Deployment: deployed by: sranjanagi@gmail.com, lab id: chem, URL: https://github.com/Virtual-Labs/unit-operation-reaction-engineering-and--process-control-nitk.git
[D 150721 17:25:34 Controller:24] test_lab() for lab ID chem and git url https://github.com/Virtual-Labs/unit-operation-reaction-engineering-and--process-control-nitk.git
[D 150721 17:25:34 LabManager:18] Will return lab spec
[D 150721 17:25:34 git_commands:25] lab_src_url: https://github.com/Virtual-Labs/unit-operation-reaction-engineering-and--process-control-nitk.git
[D 150721 17:25:34 git_commands:28] repo_name: unit-operation-reaction-engineering-and--process-control-nitk
[D 150721 17:25:34 git_commands:51] pull cmd: git --git-dir=/root/labs/unit-operation-reaction-engineering-and--process-control-nitk/.git pull
[D 150721 17:25:34 execute_commands:27] command: git --git-dir=/root/labs/unit-operation-reaction-engineering-and--process-control-nitk/.git pull
[D 150721 17:25:37 git_commands:54] Pull repo successful
[D 150721 17:25:37 git_commands:90] spec_file_path: /root/labs/unit-operation-reaction-engineering-and--process-control-nitk/scripts/labspec.json
[D 150721 17:25:37 git_commands:25] lab_src_url: https://github.com/Virtual-Labs/unit-operation-reaction-engineering-and--process-control-nitk.git
[D 150721 17:25:37 git_commands:28] repo_name: unit-operation-reaction-engineering-and--process-control-nitk
[D 150721 17:25:37 Controller:64] lab_repo_name: unit-operation-reaction-engineering-and--process-control-nitk
[D 150721 17:25:37 VMPoolManager:17] VMPoolManager: _init_()
[D 150721 17:25:37 VMPoolManager:40] VMPoolManager: add_vm_pool(); 1, LINUX, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150721 17:25:37 VMPool:31] VMPool: __init__(); poolID=1, Desciption=LINUX, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150721 17:25:37 VMPoolManager:40] VMPoolManager: add_vm_pool(); 2, WINDOWS, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150721 17:25:37 VMPool:31] VMPool: __init__(); poolID=2, Desciption=WINDOWS, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150721 17:25:37 VMPoolManager:40] VMPoolManager: add_vm_pool(); 3, AMAZONS3, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150721 17:25:37 VMPool:31] VMPool: __init__(); poolID=3, Desciption=AMAZONS3, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150721 17:25:37 VMPoolManager:40] VMPoolManager: add_vm_pool(); 4, AMAZONEC2, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150721 17:25:37 VMPool:31] VMPool: __init__(); poolID=4, Desciption=AMAZONEC2, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150721 17:25:37 VMPoolManager:35] VMPoolManager: _init_();  vm_pools = [<VMPool.VMPool instance at 0x24a7ea8>, <VMPool.VMPool instance at 0x24a7ef0>, <VMPool.VMPool instance at 0x24a7f38>, <VMPool.VMPool instance at 0x24b1050>]
[D 150721 17:25:37 Controller:32] test_lab(); invoking create_vm() on vmpoolmgr
[D 150721 17:25:37 VMPoolManager:66] VMPoolManager: create_vm()
[D 150721 17:25:37 VMPoolManager:51] VMPoolManager: get_available_pool()
[D 150721 17:25:37 VMPool:78] VMPool: create_vm(); poolID=1, Desciption=LINUX, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150721 17:25:37 VMPool:83] VMPool: create_vm(); adapter_url = http://localhost:8000/api/1.0/vm/create, payload = {'lab_spec': '{"lab_id": "chem", "revision_tag": null, "lab": {"build_requirements": {"platform": {"os": "ubuntu", "service_pack": "", "build_steps": {"status": [], "pre_build": [], "post_build": [], "build": ["make -C ../src"], "configure": []}, "installer": [], "osVersion": "12", "arch": "i386"}}, "runtime_requirements": {"platform": {"servicepack": "", "arch": "i386", "lab_actions": {"restore": [], "pause": [], "stats": [], "shutdown": ["service apache2 stop"], "resume": [], "stop": [], "publish": [], "start": ["service apache2 start"], "init": ["mv /var/www/index.html index.html.default", "cp -r ../build/* /var/www/"], "clean": [], "backup": []}, "storage": {"min_required": "10gb"}, "hosting": "dedicated", "memory": {"min_required": "256mb", "max_required": "2gb"}, "installer": ["sudo apt-get update", "sudo apt-get install -y php5 apache2"], "osVersion": "12", "os": "ubuntu"}, "hosting": "dedicated"}, "description": {"discipline": ["Unit-Operation-Reaction-Engg.-Process-Control"], "status": "Released", "name": "Chemical", "type": "", "server-side": true, "integration_level": 5, "id": "chem", "developer": [{"web": "", "name": "Mohit tahiliani", "title": "", "institute": "NITK Surathkal", "contact": {"alternate_email": "", "email": "tahiliani.nitk@gmail.com ", "office_number": "", "mobile_number": ""}, "role": "Lab Developer", "department": "", "organization": ""}, {"web": "", "name": "Mohit tahiliani", "title": "", "institute": "NITK Surathkal", "contact": {"alternate_email": "", "email": "tahiliani@nitk.edu.in", "office_number": "", "mobile_number": ""}, "role": "Lab RA", "department": "", "organization": ""}, {"web": "", "name": "Mohit tahiliani", "title": "", "institute": "NITK Surathkal", "contact": {"alternate_email": "", "email": "tahiliani@nitk.edu.in", "office_number": "", "mobile_number": ""}, "role": "Lab RA", "department": "", "organization": ""}, {"web": "", "name": "Mohit tahiliani", "title": "", "institute": "NITK Surathkal", "contact": {"alternate_email": "", "email": "tahiliani@nitk.edu.in", "office_number": "", "mobile_number": ""}, "role": "Lab RA", "department": "", "organization": ""}, {"web": "", "name": "Mohit tahiliani", "title": "", "institute": "NITK Surathkal", "contact": {"alternate_email": "", "email": "tahiliani@nitk.edu.in", "office_number": "", "mobile_number": ""}, "role": "Lab RA", "department": "", "organization": ""}]}}, "lab_repo_name": "unit-operation-reaction-engineering-and--process-control-nitk", "template": "1.0", "lab_src_url": "https://github.com/Virtual-Labs/unit-operation-reaction-engineering-and--process-control-nitk.git"}'}
[I 150721 17:25:37 connectionpool:203] Starting new HTTP connection (1): localhost
[D 150721 17:25:37 AdapterServer:33] post()
[D 150721 17:25:37 AdapterServer:35] post(); post_data = {'lab_spec': '{"lab_id": "chem", "revision_tag": null, "lab": {"build_requirements": {"platform": {"os": "ubuntu", "service_pack": "", "build_steps": {"status": [], "pre_build": [], "post_build": [], "build": ["make -C ../src"], "configure": []}, "installer": [], "osVersion": "12", "arch": "i386"}}, "runtime_requirements": {"platform": {"servicepack": "", "arch": "i386", "lab_actions": {"restore": [], "pause": [], "stats": [], "shutdown": ["service apache2 stop"], "resume": [], "stop": [], "publish": [], "start": ["service apache2 start"], "init": ["mv /var/www/index.html index.html.default", "cp -r ../build/* /var/www/"], "clean": [], "backup": []}, "storage": {"min_required": "10gb"}, "hosting": "dedicated", "memory": {"min_required": "256mb", "max_required": "2gb"}, "installer": ["sudo apt-get update", "sudo apt-get install -y php5 apache2"], "osVersion": "12", "os": "ubuntu"}, "hosting": "dedicated"}, "description": {"discipline": ["Unit-Operation-Reaction-Engg.-Process-Control"], "status": "Released", "name": "Chemical", "type": "", "server-side": true, "integration_level": 5, "id": "chem", "developer": [{"web": "", "name": "Mohit tahiliani", "title": "", "institute": "NITK Surathkal", "contact": {"alternate_email": "", "email": "tahiliani.nitk@gmail.com ", "office_number": "", "mobile_number": ""}, "role": "Lab Developer", "department": "", "organization": ""}, {"web": "", "name": "Mohit tahiliani", "title": "", "institute": "NITK Surathkal", "contact": {"alternate_email": "", "email": "tahiliani@nitk.edu.in", "office_number": "", "mobile_number": ""}, "role": "Lab RA", "department": "", "organization": ""}, {"web": "", "name": "Mohit tahiliani", "title": "", "institute": "NITK Surathkal", "contact": {"alternate_email": "", "email": "tahiliani@nitk.edu.in", "office_number": "", "mobile_number": ""}, "role": "Lab RA", "department": "", "organization": ""}, {"web": "", "name": "Mohit tahiliani", "title": "", "institute": "NITK Surathkal", "contact": {"alternate_email": "", "email": "tahiliani@nitk.edu.in", "office_number": "", "mobile_number": ""}, "role": "Lab RA", "department": "", "organization": ""}, {"web": "", "name": "Mohit tahiliani", "title": "", "institute": "NITK Surathkal", "contact": {"alternate_email": "", "email": "tahiliani@nitk.edu.in", "office_number": "", "mobile_number": ""}, "role": "Lab RA", "department": "", "organization": ""}]}}, "lab_repo_name": "unit-operation-reaction-engineering-and--process-control-nitk", "template": "1.0", "lab_src_url": "https://github.com/Virtual-Labs/unit-operation-reaction-engineering-and--process-control-nitk.git"}'}
[D 150721 17:25:37 CentOSVZAdapter:63] CentOSVZAdapter: create_vm()
[I 150721 17:25:37 sh:382] <Command '/bin/ping 10.100.83....(6 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
[I 150721 17:25:40 sh:382] <Command '/bin/ping 10.100.83....(6 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
[D 150721 17:25:43 CentOSVZAdapter:79] CentOSVZAdapter: create_vm(): ip = 10.100.83.1, vm_id = 831, vm_create_args =  --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 10.100.83.1 --diskspace 10G:15.0G --hostname chem.vlabs.ac.in, vm_set_args =  --nameserver inherit --ram 256M --swap 512M --onboot yes --save
[D 150721 17:25:43 CentOSVZAdapter:86] CentOSVZAdapter: create_vm(): create command = ssh -o "StrictHostKeyChecking no" root@10.100.83.177 "/usr/sbin/vzctl create 831  --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 10.100.83.1 --diskspace 10G:15.0G --hostname chem.vlabs.ac.in"
[D 150721 17:25:43 execute_commands:27] command: ssh -o "StrictHostKeyChecking no" root@10.100.83.177 "/usr/sbin/vzctl create 831  --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 10.100.83.1 --diskspace 10G:15.0G --hostname chem.vlabs.ac.in"
root@10.100.83.177's password: 
Permission denied, please try again.
root@10.100.83.177's password: 
Permission denied, please try again.
root@10.100.83.177's password: 
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[E 150721 17:25:43 execute_commands:34] Called Process Error: Command 'ssh -o "StrictHostKeyChecking no" root@10.100.83.177 "/usr/sbin/vzctl create 831  --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 10.100.83.1 --diskspace 10G:15.0G --hostname chem.vlabs.ac.in"' returned non-zero exit status 255
[E 150721 17:25:43 CentOSVZAdapter:113] Error creating VM: Command 'ssh -o "StrictHostKeyChecking no" root@10.100.83.177 "/usr/sbin/vzctl create 831  --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 10.100.83.1 --diskspace 10G:15.0G --hostname chem.vlabs.ac.in"' returned non-zero exit status 255
[D 150721 17:25:43 AdapterServer:57] success status returned False from create_vm
[D 150721 17:25:43 AdapterServer:61] result = Failed while creating VM
[E 150721 17:25:43 web:1908] 500 POST /api/1.0/vm/create (::1) 6154.57ms
[D 150721 17:25:43 VMPool:87] VMPool: create_vm(): Response text from adapter: Failed while creating VM
[E 150721 17:25:43 VMPool:96] VMPool: create_vm(): Error communicating with adapter: VMPool: create_vm(): Error creating VM: Failed while creating VM
[E 150721 17:25:43 Controller:55] test_lab(): Test failed with error: VMPool: create_vm(): Error creating VM: VMPool: create_vm(): Error creating VM: Failed while creating VM
[I 150721 17:25:43 web:1908] 200 POST / (10.100.83.177) 8542.66ms

**Comment by radheshanand** [comment]
Hi Shiva,

Kindly check for the password provided, as it is giving you "Permission
denied" error (marked in yellow, below). Fixing this, should resolve your
issue.

Regards,
Radhesh.

**Comment by ecthiender** [comment]
Shivakumar, while deploying a lab, if you get asked for a password, that means you have not copied the SSH key from your base machine to the base machine itself.

From your base machine, you have to copy the SSH key to the same machine to the file `~/.ssh/authorized_keys`, as OVPL will SSH to itself to issue commands.

To the above, please do this:

`ssh-copy-id root@<your-base-machine-ip>`

And for one time, you have to enter the root password of your base machine.

base machine = the machine where you installed OVPL and running it from.

If this resolves your issue, please close this ticket.

**Comment by sranjanagi** [comment]
issue is solved .

Thanks.
