### ISSUE TITLE
Please update the link of Engineering Electro-magnetics Laboratory IITD on vlab.co.in

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#171]
Kindly update the link of Engineering Electro-magnetics Laboratory on vlab.co.in. The lab is also hosted on the cloud. 

Virtual Lab Address on Cloud:  http://eem-iitd.vlabs.ac.in/
Github Repository- https://github.com/Virtual-Labs/engineering-electro-magnetics-laboratory-iitd

**Comment by ecthiender** [comment]
@jayanthsagar can we send a request to vlab.co.in ?

**Comment by sumitdahiyavlab** [comment]
Thank you. The link is now working fine on vlab.co.in.
