### ISSUE TITLE
Hosting of responsive Computer Programming lab

### ISSUE THREAD

**Issue by apurv111** [Virtual-Labs/engineers-forum#172]
Please host this lab with https certificate.
Here is the github URL:
https://github.com/vlead/computer-programming-responsive.git
It has already been tested on ADS.

**Comment by apurv111** [comment]
Please don't raise a request to update it on vlab.co.in as it is not yet listed there.

**Comment by sanchita-dixit** [comment]
@apurv111 The lab has been hosted. The URL is https://cp-iiith.vlabs.ac.in
