### ISSUE TITLE
OVPL ERROR

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#173]
Hi all,
        I am getting error while testing a lab on OVPL. when I paste the lab url and submit it, it shows "Test failed, see log files for errors." A screenshot is attached herewith.
![ovpl error](https://cloud.githubusercontent.com/assets/8788700/8975583/6b284e80-369e-11e5-922d-bd74f5e84f35.png)

**Comment by ambikakaul** [comment]
Hello Biju,    
     Please refer Issue #170 . Its solution should solve your problem.

**Comment by ecthiender** [comment]
@bijudas45 if this resolves your issue, please close this ticket.

**Comment by bijudas45** [comment]
thanks.. the issue is resolved.

**Comment by bijudas45** [comment]
thanks... the issue is resolved.

On Thu, Jul 30, 2015 at 2:20 PM, Anon Ray <notifications@github.com> wrote:

> @bijudas45 <https://github.com/bijudas45> if this resolves your issue,
> please close this ticket.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Virtual-Labs/engineers-forum/issues/173#issuecomment-126229910>
> .
>



-- 
Regards,
Biju Das
