### ISSUE TITLE
Please provide the hosted Url of the labs

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#174]
Whenever the lab is hosted, can you please provide hosted url of the lab, so that we can know whether the lab is hosted or not.

**Comment by ecthiender** [comment]
If you mean the labs hosted from requests from engineers-forum, each issue,
after hosting contains the URL of the hosted lab.

**Comment by sadhanareddy** [comment]
yaa...but for few labs we found that, labs are hosted, but the hosted urls are not provided in request for hosting issues.

**Comment by sanchita-dixit** [comment]
@sadhanareddy Whenever a lab hosting request is raised as an issue on Engineers Forum, after the lab has been hosted, URLs are always provided while closing the issue. You can check the closed issues.

**Comment by sravanthimodepu** [comment]
Issue...  resolved.

**Comment by sadhanareddy** [comment]
Since the issue.... is resolved, hence closing this issue.
