### ISSUE TITLE
General Purpose Production Shop Simulation Lab not working

### ISSUE THREAD

**Issue by apurv111** [Virtual-Labs/engineers-forum#176]
@Virtual-Labs/ie-iitk-team .. Please check this lab. The lab landing page is not loading up.
It is throwing the following error - 
Could not connect: mysqlnd cannot connect to MySQL 4.1+ using the old insecure authentication. Please use an administration tool to reset your password with the command SET PASSWORD = PASSWORD('your_existing_password'). This will store a new, and more secure, hash value in mysql.user. If this user is used in other scripts executed by PHP 5.2 or earlier you might need to remove the old-passwords flag from your my.cnf file

**Comment by sanchita-dixit** [comment]
@apurv111 @Virtual-Labs/ie-iitk-team.. Any updates on this issue? Please comment.

**Comment by sanchita-dixit** [comment]
@Virtual-Labs/ie-iitk-team Please update the issue with details. 
@khushpreet-kaur @sadhanareddy @sravanthimodepu Is this issue still valid? As apurv111 is no longer a member of VLEAD, please comment so that we can close this issue based on your inputs.

**Comment by khushpreet-kaur** [comment]
@sanchita-dixit General Purpose Production Shop Lab's landing page is opening fine now. 
Also, Apurv had not transferred any information regarding this to integration team, so currently we have no task related to this lab / even no idea why this issue has been reported. 
I guess you can close this issue for now, If in future we face same issue; we will open it again based on our requirement.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur @Virtual-Labs/ie-iitk-team @sadhanareddy @sravanthimodepu Based on inputs from @khushpreet-kaur and no response from @Virtual-Labs/ie-iitk-team from a very long time, we are closing this issue for now. If some problem is faced in the future, we would reopen it.
