### ISSUE TITLE
ADS Testing Failed

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#177]
Hi,
We are getting error while testing our electronic instrumentation lab on OVPL.
Enclosed herewith the screenshot of the error.
![screenshot-1](https://cloud.githubusercontent.com/assets/8788700/9105718/fb6237ec-3c37-11e5-9cd4-fba779a4acfe.png)

**Comment by ecthiender** [comment]
@bijudas45 what is the OS you are mentioning in the labspec.json file?

**Comment by bijudas45** [comment]
OS version mentioned in labspec.json file is 12.

On Thu, Aug 6, 2015 at 5:14 PM, Anon Ray <notifications@github.com> wrote:

> @bijudas45 <https://github.com/bijudas45> what is the OS you are
> mentioning in the labspec.json file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Virtual-Labs/engineers-forum/issues/177#issuecomment-128338212>
> .
>



-- 
Regards,
Biju Das

**Comment by ecthiender** [comment]
@bijudas45 you are mentioning "ubuntu" in the "os" field, and "12" in the "osVersion" field?

**Comment by bijudas45** [comment]
Yes, i have mentioned "ubuntu" in the "os" field and "12" in the "os
version" field

On Fri, Aug 7, 2015 at 9:48 AM, Anon Ray <notifications@github.com> wrote:

> @bijudas45 <https://github.com/bijudas45> you are mentioning "ubuntu" in
> the "os" field, and "12" in the "osVersion" field?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Virtual-Labs/engineers-forum/issues/177#issuecomment-128592768>
> .
>



-- 
Regards,
Biju Das

**Comment by ecthiender** [comment]
@bijudas45 did your issue get resolved?

**Comment by bijudas45** [comment]
No, the issue still persists. Can't identify the error.


On Tue, Aug 11, 2015 at 10:22 AM, Anon Ray <notifications@github.com> wrote:

> @bijudas45 <https://github.com/bijudas45> did your issue get resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Virtual-Labs/engineers-forum/issues/177#issuecomment-129704187>
> .
>



-- 
Regards,
Biju Das

**Comment by bijudas45** [comment]
The issue still persists. Can't able to solve it. Please suggest a solution for this problem. The url of the lab is "https://github.com/Virtual-Labs/electronic-instrumentation-laboratory-iitg"

**Comment by ecthiender** [comment]
@bijudas45 I tried deploying the lab on our test ADS machine and it worked.

Can you try logging into the ADS machine/container, and from `ovpl` directory:
1. `git checkout master`
2. `git pull origin master`

That will pull the latest ADS code. After that can you try deploying the lab again?

**Comment by bijudas45** [comment]
Hi,

 I tested the lab on an ADS machine and it worked.
Thanks for your help.

On Thu, Sep 10, 2015 at 1:51 PM, Anon Ray <notifications@github.com> wrote:

> @bijudas45 <https://github.com/bijudas45> I tried deploying the lab on
> our test ADS machine and it worked.
>
> Can you try logging into the ADS machine/container, and from ovpl
> directory:
> 1. git checkout master
> 2. git pull origin master
>
> That will pull the latest ADS code. After that can you try deploying the
> lab again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Virtual-Labs/engineers-forum/issues/177#issuecomment-139164608>
> .
>



-- 
Regards,
Biju Das
