### ISSUE TITLE
Request for Hosting of Signal and Systems Lab IITG

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#178]
Hi,
Please host the Signals and Systems Lab-IITG

URL: https://github.com/Virtual-Labs/signals-and-systems-laboratory-iitg

**Comment by sanchita-dixit** [comment]
@bijudas45 The lab has been hosted. Please follow the URL: https://ssl-iitg.virtual-labs.ac.in

**Comment by bijudas45** [comment]
Hi,
  The link of signals and systems lab of IITG i.e.
https://ssl-iitg.virtual-labs.ac.in is not working. Please look into the
matter.

On Wed, Sep 2, 2015 at 3:42 PM, sanchita-dixit <notifications@github.com>
wrote:

> @bijudas45 <https://github.com/bijudas45> The lab has been hosted. Please
> follow the URL: https://ssl-iitg.virtual-labs.ac.in
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Virtual-Labs/engineers-forum/issues/178#issuecomment-137013524>
> .
>



-- 
Regards,
Biju Das

**Comment by sivashankerN** [comment]
@bijudas45 Looking into the issue

**Comment by sivashankerN** [comment]
@bijudas45  Problem is resolved please check

**Comment by sanchita-dixit** [comment]
@bijudas45 Please close the issue if there is no further problem with the URL.
