### ISSUE TITLE
Problem in accessing experiment link and demo link in Engineering Electro-magnetics Laboratory IITD

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#179]
Hi Everyone,

I am facing some issues in Engineering Electro-magnetics laboratory IITD.

The issue is as follows: 

-> 1. when i open any experiment e.g. I opened experiment 1 as shown in fig below:

![1](https://cloud.githubusercontent.com/assets/11206668/9159871/c2c4dcae-3f4e-11e5-98ad-0fe6fdf98e2b.png)

-> 2. As soon as i click on the experiment link (the same problem is also happening with demo link) in the above figure, this message appears:

![2](https://cloud.githubusercontent.com/assets/11206668/9159882/dfa970be-3f4e-11e5-81e2-aaf8db4a8ef0.PNG)

-> 3. Although Application.exe is present at its designated place:

![3](https://cloud.githubusercontent.com/assets/11206668/9159907/5ad75788-3f4f-11e5-8743-e48289345043.PNG)

-> 4. The html code of exp1.html is also pointing at right place: 

![5](https://cloud.githubusercontent.com/assets/11206668/9159920/a4b5b14c-3f4f-11e5-9504-0fdabd05d153.PNG)

Still the Application.exe is not downloading.

Also, when i open application.exe on github. This message appears:
![6](https://cloud.githubusercontent.com/assets/11206668/9159933/d6aa9ba4-3f4f-11e5-9807-bd403d77f3ce.PNG)

This is happening for majority of the experiments in the lab. Kindly provide your suggestions.

Github Address of the lab: https://github.com/Virtual-Labs/engineering-electro-magnetics-laboratory-iitd

Address of the lab on cloud: http://eem-iitd.vlabs.ac.in/

**Comment by ecthiender** [comment]
@sumitdahiyavlab can you replicate the setup in your local machine? 
If you deploy this on your local machine using ADS, do you face the same issue?

**Comment by sumitdahiyavlab** [comment]
@ecthiender It may take some time. I currently don't have ADS setup on my machine. While re-installing Windows, Centos (Containing ADS) was formatted from my system, which was installed at IITG workshop. I will again try setting up ADS on my machine then only i can tell you, whether i would face the same issue or not. I hope i would be able to setup ADS on my machine as I have noted down all the steps at IITG workshop. For any further issue, i will use engineers-forum.

**Comment by ecthiender** [comment]
Okay.

**Comment by sumitdahiyavlab** [comment]
Currently I am closing this issue. I may reopen it later.
