### ISSUE TITLE
In-appropriate view of experiment list on vlabs.ac.in-COE Pune

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#182]
This is the COE pune link on new alpha version portal. The page is not in appropriate view as it should display.

http://vlabs.ac.in/pune-labs.html

also 
http://vlabs.ac.in/bmsp-coep.vlabs.ac.in 
says "404 Not Found" which was working previously. This lab was tested successfully. 

Check out the page and sort it out.

**Comment by sanchita-dixit** [comment]
@sushilmedhe We are looking into the issue. Will try to resolve it as soon as possible.

**Comment by sushilmedhe** [comment]
The first problem is solved yesterday about an appropriate view of the http://vlabs.ac.in/pune-labs.html page. 

the second is "Biomedical and Signal processing Laboratory" from same page link is still not working.
I think there is a problem in the link given to url source. it shows the link http://vlabs.ac.in/bmsp-coep.vlabs.ac.in but for other working labs it shows the url as <shortform lab name>-coep.vlabs.ac.in without "vlabs.ac.in" in the beginning.

So check out this issue.

**Comment by sushilmedhe** [comment]
Any updates for the above issue which I mentioned about Biomedical and Signal processing Laboratory Lab??

**Comment by sanchita-dixit** [comment]
The issue with the Biomedical and Signal processing Laboratory Lab has been resolved. Now the lab link is working fine. Apologies for the delay.
