### ISSUE TITLE
Request to redeploy Computer Programming Lab

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#183]
Please host computer programming  responsive lab on the same url where the non-responsive computer programming lab is running currently to keep the old lab's analytic in place.

Computer Programming Lab's URL: http://cse02-iiith.vlabs.ac.in/ 

Old repository URL: https://github.com/Virtual-Labs/computer-programming-iiith

New repository: https://github.com/Virtual-Labs/computer-programming-responsive-iiith

Please replace old sources  with new one and host it on same url: http://cse02-iiith.vlabs.ac.in/. So that we won't loose analytics.

**Comment by khushpreet-kaur** [comment]
FYI, Responsive computer programming lab is already tested on ADS.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur  Computer Programming Responsive lab is available on the given URL :  http://cse02-iiith.vlabs.ac.in/
None of the analytics have been lost.

**Comment by khushpreet-kaur** [comment]
Thanks.
