### ISSUE TITLE
Computer Organization

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#184]
Dear system team,

Please re-host the Computer Organization lab ,for this specific lab we have modified the make file and updated the lab with complete sources.

Here is the git-hub URL :
https://github.com/Virtual-Labs/computer-organization-iiith.git

Please make sure we don't loose the analytics of Computer Organization Lab. Once done with the hosting process, please share the URL.

**Comment by ecthiender** [comment]
@sravanthimodepu Please add the relevant tags to each issue. In this case "request for hosting".

And also please include one line detail in the title of the issue. The title of the issue cannot be a lab name. A lab name doesn't represent any issue.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu Computer Organization Lab has been re-hosted with the URL: https://cse11-iiith.vlabs.ac.in
The analytics are not lost.
