### ISSUE TITLE
Computer Graphics Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#185]
Dear system team,

Please re-host the Computer Graphics Lab, for this specific lab we have modified the make file and updated the lab with complete sources.

Here is the git-hub URL :
https://github.com/Virtual-Labs/computer-graphics-iiith.git

Please make sure we don't loose the analytics of Computer Graphics Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
The URL for re-hosted computer graphics labs with all the analytics is : https://cse18-iiith.vlabs.ac.in
