### ISSUE TITLE
Digital Logic Design Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#186]
Dear system team,

Please re-host the Digital Logic Design Lab, for this specific lab we have modified the make file and updated the lab with  complete sources.

Here is the git-hub URL:
https://github.com/Virtual-Labs/digital-logic-design-iiith.git

Please make sure we don't loose the analytics of Digital Logic Design Lab.Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
Following is the URL for the re-hosted Digital Logic Design Lab with all the analytics intact : https://cse15-iiith.vlabs.ac.in
