### ISSUE TITLE
VLSI Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#187]
Dear system team,

Please re-host the VLSI Lab, for this specific lab we have modified the make file and updated the lab with  complete sources.

Here is the git hub URL :
https://github.com/Virtual-Labs/vlsi-iiith.git

Please make sure we don't loose the analytics of VLSI Lab. Once done with the hosting process please share the URL.

**Comment by sanchita-dixit** [comment]
The URL for the re-hosted VLSI lab is : https://cse14-iiith.vlabs.ac.in
None of the analytics are lost.
