### ISSUE TITLE
Request to host analog-cmos-vlsi-circuit-design-iiith Lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#188]
Dear system team,

Please rehost the analog-cmos-vlsi-circuit-design-iiith lab ,for this specific lab we have modified the make file and updated the lab with  complete sources.

Here is the github url : 
https://github.com/Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith.git

Please make sure we don't loose the analytics of this lab analog-cmos-vlsi-circuit-design-iiith  .Once done with the hosting process please share the url.

**Comment by sanchita-dixit** [comment]
@sadhanareddy This lab is currently not hosted on amazon or anywhere on IIIT server. Hence the re-hosting request wont be valid. Please clarify the issue.

**Comment by sadhanareddy** [comment]
Yaa... there was a mistake from our end, we thought the lab was hosted. So, could you please host the lab now.

**Comment by khushpreet-kaur** [comment]
@sadhanareddy Have you tested this lab on ADS?

**Comment by sadhanareddy** [comment]
@sanchita-dixit  Please host the Analog CMOs VLSI Circuit Design Lab.
 
Below is the github url :
https://github.com/Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith.git

**Comment by sanchita-dixit** [comment]
@sadhanareddy The lab has been hosted. This lab is not hosted from Amazon and is hosted from IIIT-H server itself. Please follow the URL to access the same : http://cse30-iiith.vlabs.ac.in
