### ISSUE TITLE
Request to basic-structural-analysis-iiith lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#189]
Dear system team,

Please rehost the  basic-structural-analysis-iiith lab ,for this specific lab we have modified the make file and updated the lab with complete sources.

Here is the github url : 
https://github.com/Virtual-Labs/basic-structural-analysis-iiith.git

Please make sure we don't loose the analytics of this lab basic-structural-analysis-iiith .Once done with the hosting process please share the url.

**Comment by sanchita-dixit** [comment]
The lab has been re-hosted. Please follow the URL: https://bsa-iiith.vlabs.ac.in
The analytics of the lab are intact.
