### ISSUE TITLE
Regarding OVPL instalation 

### ISSUE THREAD

**Issue by praveenscreate** [Virtual-Labs/engineers-forum#19]
I installed centos 6.5( after yum upgradation it is centos 6.6) and completed level 3. In  level 4 we have to install OVPL in host machine ie centos 6.6 (as per the document https://github.com/vlead/setup-ovpl-centos) or the container (as per the document https://github.com/vlead/ovpl/wiki/Setting-up-OVPL-on-a-VM-using-Vagrant)?. Please help me to iron out the issue.

**Comment by ecthiender** [comment]
You should use: https://github.com/vlead/setup-ovpl-centos

The other one is the manual steps to install ovpl.

**Comment by praveenscreate** [comment]
Thanks
