### ISSUE TITLE
Request to host  hydraulics-and-fluid-mechanics-iiith

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#190]
Dear system team,

Please rehost the hydraulics-and-fluid-mechanics-iiith lab ,for this specific lab we have modified the make file and updated the lab with complete source files.

Here is the github url 

https://github.com/Virtual-Labs/hydraulics-and-fluid-mechanics-iiith.git

Please make sure we don't loose the analytics of this hydraulics-and-fluid-mechanics-iiith lab  .Once done with the hosting process please share the url.

**Comment by ecthiender** [comment]
@sadhanareddy please add the "request for hosting" tag

**Comment by sanchita-dixit** [comment]
The lab has been re-hosted and none of the analytics are lost. Please follow the URL: https://eerc03-iiith.vlabs.ac.in
