### ISSUE TITLE
Update sources of Basic Engineering Mechanics and Strength of Materials Lab

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#191]
Please update the 'Basic Engineering Mechanics and Strength of Materials Lab' with latest sources. 

Here is the link of repo: https://github.com/Virtual-Labs/basic-engineering-mechanics-and-strength-of-materials-iiith

**Comment by khushpreet-kaur** [comment]
@sanchita-dixit The source are updated in repo now. Can you please update the lab with latest sources by today?

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur The sources would be updated by end of the day.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur The sources of the lab has been updated. Please follow the URL: https://eerc01-iiith.vlabs.ac.in/
