### ISSUE TITLE
Hosting request for Heat & Thermodynamics Virtual Lab : Amrita University

### ISSUE THREAD

**Issue by sreejithsr-amrita** [Virtual-Labs/engineers-forum#193]
Please create new labs in 'Virtual-Labs' repository and fork the project from the given link.

Broad area: Physical Sciences
Lab: Heat & Thermodynamics Virtual Lab

fork lab from 
https://github.com/amritacreate/heat-thermodynamics-virtual-lab

**Comment by ecthiender** [comment]
@sreejithsr-amrita The protocol is to have your repositories under the Virtual Labs organization. Please create your repository under the Virtual Labs organization, and push your code there. We will give you admin rights to your repositories.

Forking your repository will create consistency problem in the future. Any changes you make, someone from our side has to pull the changes in the forked repo and then update, which can quickly become a bottleneck when you want to re-host/redeploy your lab.

Hence, I request you to please raise a request to create repos[1] under the Virtual Labs organization, and then once the repo is created you will be given admin access. Then you can push your current code into that new repo, and then raise the request for hosting again.

[1]: To create repos under the Virtual Labs organization, you have to raise a "request to create repo" in this forum only first.

Thanks for understanding and co-operating in advance!

**Comment by sreejithsr-amrita** [comment]
Hello,

We have discussed this with Geeta Bose yesterday, pls continue with hosting procedure from our repository.

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita @geetabose After the discussions and clarifications by VLEAD team and Geeta Bose, it is confirmed that we could not go ahead with the hosting procedure from your repository. We are in the process of rolling out an official document for the entire hosting process to be followed uniformly across all the institutes. We would keep you updated regarding the same. For further queries kindly contact Geeta Bose.

**Comment by sanchita-dixit** [comment]
@amritacreate This issue is already been taken care of and the lab is also hosted. #314
