### ISSUE TITLE
Hosting request for Cell biology Virtual Lab I : Amrita University

### ISSUE THREAD

**Issue by sreejithsr-amrita** [Virtual-Labs/engineers-forum#194]
Please create new labs in 'Virtual-Labs' repository and fork the project from the given link.

Broad area: Biotechnology and Biomedical Engineering
Lab: Cell biology Virtual Lab I

fork lab from 
https://github.com/amritacreate/cell-biology-virtual-lab-i

**Comment by ecthiender** [comment]
@sreejithsr-amrita The protocol is to have your repositories under the Virtual Labs organization. Please create your repository under the Virtual Labs organization, and push your code there. We will give you admin rights to your repositories.

Forking your repository will create consistency problem in the future. Any changes you make, someone from our side has to pull the changes in the forked repo and then update, which can quickly become a bottleneck when you want to re-host/redeploy your lab.

Hence, I request you to please raise a request to create repos[1] under the Virtual Labs organization, and then once the repo is created you will be given admin access. Then you can push your current code into that new repo, and then raise the request for hosting again.

[1]: To create repos under the Virtual Labs organization, you have to raise a "request to create repo" in this forum only first.

Thanks for understanding and co-operating in advance!

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita Please start the process of creating the repository under Virtual Labs organisation so that we can start the process of hosting the lab as soon as possible.

**Comment by sreejithsr-amrita** [comment]
Hello,

We have discussed this with Geeta Bose yesterday, pls continue with hosting procedure from our repository.

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita @anishasl-create @amritacreate The hosting can't be done from your repository which is not under Virtual-Labs organisation. Various issues were raised regarding the access permissions for creation of repos under virtual-labs, but they are not being followed up from your side. Due to this, 2 lab hosting requests are pending for your institute. Please follow up these issues, so that we can resolve other issues dependent on these.

**Comment by sanchita-dixit** [comment]
@amritacreate This issue is already been taken care of and the lab is also hosted. #311
