### ISSUE TITLE
Update sources of Speech Signal Processing Lab

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#195]
Please update the 'Basic Engineering Mechanics and Strength of Materials Lab' with latest sources.

Here is the link of repo: https://github.com/Virtual-Labs/speech-signal-processing-iiith

**Comment by khushpreet-kaur** [comment]
Sorry for entering the wrong name in description.
Please update the 'Speech Signal Processing Lab` with latest sources.

Here is the link of repo: https://github.com/Virtual-Labs/speech-signal-processing-iiith

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur The sources of the lab has been updated. Follow the URL: https://ssp-iiith.vlabs.ac.in
