### ISSUE TITLE
Update sources Colloid and Surface Chemistry Lab

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#196]
Please update the `Colloid and Surface Chemistry Lab` with latest sources.

Here is the link of repo: https://github.com/Virtual-Labs/colloid-and-surface-chemistry-iiith

**Comment by khushpreet-kaur** [comment]
@sanchita-dixit Can you please do this as soon as possible?

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur The sources would be updated by today.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur The lab sources has been updated. Please follow the URL: https://csc-iiith.vlabs.ac.in
