### ISSUE TITLE
Update existing lab: Population ecology Virtual Lab II : Amrita University

### ISSUE THREAD

**Issue by sreejithsr-amrita** [Virtual-Labs/engineers-forum#198]
Please update existing lab "Population ecology Virtual Lab II"

from 
https://github.com/amritacreate/population-ecology-virtual-lab-ii

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita Population Ecology Virtual Lab I was previously deployed with the github repo: https://github.com/amritacreate/population-ecology-virtual-lab-ii-au
For updating the sources the URL given now is : https://github.com/amritacreate/population-ecology-virtual-lab-ii
Should we go ahead with the current github repo url which you provided for updations?

**Comment by anishasl-create** [comment]
Please confirm the lab name with the repo name before updating. There are 'Population Ecology Virtual Lab I' and 'Population Ecology Virtual Lab II', https://github.com/amritacreate/population-ecology-virtual-lab-ii-au for Population Ecology Virtual Lab II and https://github.com/amritacreate/population-ecology-virtual-lab-i-au for Population Ecology Virtual Lab I

**Comment by sanchita-dixit** [comment]
@anishasl-create Sorry there was error while typing the name. I was mentioning Population Ecology Virtual Lab II.

**Comment by anishasl-create** [comment]
ok

**Comment by sreejithsr-amrita** [comment]
@sanchita-dixit, pls go ahead with https://github.com/amritacreate/population-ecology-virtual-lab-ii.

**Comment by sanchita-dixit** [comment]
@anishasl-create @sreejithsr-amrita As discussed earlier in issue #193 by @ecthiender , the repository needs to be created in Virtual Labs organisation. Please create your repository under the Virtual Labs organization, and push your code there. 
For more details please refer to issue #193.

**Comment by sreejithsr-amrita** [comment]
Hello,

We have discussed this with Geeta Bose yesterday, pls continue with hosting procedure from our repository.

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita @anishasl-create @amritacreate The hosting can't be done from your repository which is not under Virtual-Labs organisation. Various issues were raised regarding the access permissions for creation of repos under virtual-labs, but they are not being followed up from your side. Due to this, 2 lab hosting requests are pending for your institute. Please follow up these issues, so that we can resolve other issues dependent on these.

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita @anishasl-create @amritacreate Please refer to issue #239 for the latest movement on this issue.

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita @anishasl-create @amritacreate The lab has been re-hosted with the updated sources. Please follow the URL : http://pevii-au.vlabs.ac.in

**Comment by sanchita-dixit** [comment]
@sreejithsr-amrita @anishasl-create @amritacreate I am closing this issue as there are no further issues highlighted for this and I hope the updated sources are working as per requirements.
