### ISSUE TITLE
Hosting request for "Structural Dynamics" lab

### ISSUE THREAD

**Issue by apurv111** [Virtual-Labs/engineers-forum#199]
Please host this lab and post the URL of hosted lab in comment.
The lab has been tested on ADS.
Github URL - https://github.com/Virtual-Labs/structural-dynamics-iiith.git

**Comment by sanchita-dixit** [comment]
@apurv111 This lab has already been hosted. Whether this is a re-hosting request or updation of lab sources? Please clarify.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur @sadhanareddy @sravanthimodepu Is this request for hosting or re-hosting still valid? Please comment as per the query above and confirm the request.

**Comment by sanchita-dixit** [comment]
Since there is no response on this issue. I am closing this issue for now. Later on it can be reopened when necessary.
