### ISSUE TITLE
Porting of IIT-B labs - UI related issue to be resolved

### ISSUE THREAD

**Issue by geetabose** [Virtual-Labs/engineers-forum#2]
As per our recent discussion, we have identified the issue that IIT-B labs are facing w.r.t the porting to the new UI . We wish to port all of our labs as soon as possible to the new UI,  it shall be very helpful if VLEAD team can help us resolve the issue. The errors that we have been getting have been already communicated with Soujanya, Amulya & Prakash in your team. Please help us at the earliest. 
Pushpdeep Mishra
Project Manager
Virtual labs, IIT Bombay

**Comment by soujanya123** [comment]
I said earlier the scripts were not generalized to run over all the collaborative structured labs. We have our engineers working on the scripts to make them compatible with the labs structure following by different institutes. For time sake I would suggest Integration Engineers of IIT Bombay to manually convert the lab to ui-1.0 framework and go with the integration process. We will soon update once the scripts are ready.

**Comment by AmulyaSri** [comment]
As per the update received from Integration team, closing the issue. Team has asked IIT B Engineers to convert the lab to UI 1.0 manually.
