### ISSUE TITLE
Request to host the IIT Kanpur Labs

### ISSUE THREAD

**Issue by GuptaManoj** [Virtual-Labs/engineers-forum#20]
Dear Vlead Team,

Three labs of IIT Kanpur were successufully tested over ADS. Here are git hub URL's of the labs sources
1- https://github.com/Virtual-Labs/material-response-to-micro-structural-mechanical-thermal-and-biological-stimuli-iitk.
2- https://github.com/Virtual-Labs/virtual-astrophysics-lab-iitk.
3- https://github.com/Virtual-Labs/ultra-fast-laser-spectroscopy-iitk.
Can you please host them on Amazon and gives us the hosted URL.

**Comment by geetabose** [comment]
Dear Manoj,

Pls post this on Engineer's forum on GitHub as a hosting request.

Thanks
Geeta

**Comment by jayanthsagar** [comment]
Hi Manoj,

Your labs are deployed, use below urls to access labs.
http://mrmsmtbs-iitk.vlabs.ac.in
http://va-iitk.vlabs.ac.in
http://ufls-iitk.vlabs.ac.in

please check it and let us know if we miss anything.

**Comment by GuptaManoj** [comment]
Dear Jayanth,

Thank you, All link are work correctly.

Thanks and Regard
Manoj Gupta
