### ISSUE TITLE
Request for updation of sources of outreach portal.

### ISSUE THREAD

**Issue by ambikakaul** [Virtual-Labs/engineers-forum#201]
The sources  of outreach portal in the github repository have been updated. Repo url is : https://github.com/Virtual-Labs/outreach-portal.

Kindly treat this as an urgent request and update the sources and re-host again.

**Comment by sanchita-dixit** [comment]
@ambikakaul The sources have been updated. Please follow the URL: http://outreach.vlabs.ac.in

**Comment by ambikakaul** [comment]
Thanks.
