### ISSUE TITLE
Request to re-host Physical Chemistry Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#203]
Dear system team,

Please re-host the Physical Chemistry Lab, for this specific lab we have masked to two experiments simulations and updated the lab with complete sources.

Here is the git-hub URL :
https://github.com/Virtual-Labs/physical-chemistry-iiith.git

Please make sure we don't loose the analytics of Physical Chemistry Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The lab sources have been updated and the old analytics have not been lost. Please follow the URL: https://ccnsb06-iiith.vlabs.ac.in
