### ISSUE TITLE
Update sources for Physical Chemistry Lab

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#204]
Please update the sources of Physical Chemistry Lab with updated lab sources.

Here is the git-hub URL :
https://github.com/Virtual-Labs/physical-chemistry-iiith.git

Please make sure we don't loose the analytics of Physical Chemistry Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur I have updated the sources for this lab just 2 days before when the issue was raised by @sravanthimodepu #203 and closed the issue.

**Comment by khushpreet-kaur** [comment]
@sanchita-dixit I have updated the sources today morning, so lab needs to be updated with latest sources.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur The sources of Physical Chemistry Lab has been updated. Please follow the URL: https://ccnsb06-iiith.vlabs.ac.in
