### ISSUE TITLE
Request to host databases-and-datamining lab for testing

### ISSUE THREAD

**Issue by ecthiender** [Virtual-Labs/engineers-forum#205]
Request to host databases-and-datamining lab in the **testing** environment (**not** AWS).

Repo URL: https://github.com/Virtual-Labs/databases-and-datamining-iiith.git

Request you to consider this urgent, because Prof. Raghu and integration team wants to test this lab out before final deployment.

**Comment by ecthiender** [comment]
Please reply with the IP/URL of the hosted lab in testing.

**Comment by sanchita-dixit** [comment]
@ecthiender The lab has been deployed on testing environment. Please follow the URL: http://dbdm-iiith.base4.vlabs.ac.in
