### ISSUE TITLE
Regarding ie-iitd-team group

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#206]
Dear VLEAD team, One new member is added to ie-iitd-team at https://github.com/orgs/Virtual-Labs/teams/ie-iitd-team. In my view, the person specified does not belong to IITD integration team. Please look into this matter.

**Comment by ambikakaul** [comment]
@sumitdahiyavlab - The link given by you (https://github.com/orgs/Virtual-Labs/teams/ie-iitd-team)
is not valid.

**Comment by ambikakaul** [comment]
@sumitdahiyavlab - Sorry ! The link is infact valid.

**Comment by sumitdahiyavlab** [comment]
@ambikakaul Hi Ambika, No problem. Thanks for your comments.

**Comment by sumitdahiyavlab** [comment]
I think that the above message has reached to the VLEAD team. Therefore, i'm closing this issue. Thank you.
