### ISSUE TITLE
Update sources of `Computer Programming Lab`

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#207]
I have updated the sources to unmask 10th experiment.  Please update `computer programming Lab` with updated source code.

Link to repo: https://github.com/Virtual-Labs/computer-programming-responsive-iiith

**Comment by khushpreet-kaur** [comment]
Please update the sources.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur Please see whether the github url given is correct because lab to be updated is computer programming lab but the repo link says: computer-programming-responsive.
Please cross check once.

**Comment by khushpreet-kaur** [comment]
@sanchita-dixit Repo link is correct. Please go ahead and update the sources.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur The sources have been updated. Please follow the url: https://cse02-iiith.vlabs.ac.in

**Comment by khushpreet-kaur** [comment]
@sanchita-dixit Thanks! Lab is working fine.
