### ISSUE TITLE
Request to host data service in staging

### ISSUE THREAD

**Issue by ecthiender** [Virtual-Labs/engineers-forum#208]
Request to host "data service" in the staging environment.

Github URL: https://github.com/vlead/dataservice.git
Preferred deployed URL: http://data.base1.vlabs.ac.in

Let me know by when this can be hosted.

**Comment by ecthiender** [comment]
Please put this request on hold for now.

**Comment by ecthiender** [comment]
Request you to host the data service now according to the above mentioned information.

**Comment by ecthiender** [comment]
Request you to pull from the sources now and re-host the data service

**Comment by sanchita-dixit** [comment]
The data service has been hosted in the staging environment. Please follow the URL: http://data.base1.vlabs.ac.in
