### ISSUE TITLE
Request for hosting 5 labs which are shortlisted for Delhi meeting

### ISSUE THREAD

**Issue by ksripathi** [Virtual-Labs/engineers-forum#209]
Hello Team,

Pleas host the following 5 labs on Amazon cloud

1) https://github.com/Virtual-Labs/data-structures-iiith
2) https://github.com/Virtual-Labs/computer-programming-iiith
3) https://github.com/Virtual-Labs/chemical-engg-iitb
4) https://github.com/Virtual-Labs/fab-laboratory-coep
5) https://github.com/Virtual-Labs/bio-medical-signal-and-image-processing-lab-iitr

**Comment by sivashankerN** [comment]
We have updated sources of the labs mentioned in the above comment except https://github.comVirtual-Labs/computer-programming-iiith. 
Thirumal/ Sripathi may write a comment why we have not updated this lab sources on production

1) data-structures-iiith                           http://cse01-iiith.vlabs.ac.in
2) chemical-engg-iitb                             http://ce-iitb.vlabs.ac.in
3) fab-laboratory-coep                           http://fab-coep.vlabs.ac.in
4) bio-medical-signal-and-image-processing-lab-iitr    http://bmsip-iitr.vlabs.ac.in
5)5) Problem Solving-iiith                                    http://ps-iiith.vlabs.ac.in
