### ISSUE TITLE
Request to host "feedback-portal" in the staging environment.

### ISSUE THREAD

**Issue by ambikakaul** [Virtual-Labs/engineers-forum#211]
Please host the feedback portal in the staging environment.

Github URL : https://github.com/vlead/feedback-portal.git
Preferred deployed URL: feedback.base1.vlabs.ac.in

Let me know when this is done.

Thanks.

**Comment by sanchita-dixit** [comment]
The feedback portal has been hosted on staging environment. Please follow the URL: http://feedback.base1.vlabs.ac.in/
