### ISSUE TITLE
Request to rehost Pattern recognition lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#214]
Dear system team,

Please re-host the Pattern Recognition Lab, for this specific lab we have masked one experiment and updated the lab with complete sources.

Here is the git-hub URL :
https://github.com/Virtual-Labs/pattern-recognition-iiith.git

Please make sure we don't loose the analytics of Pattern Recognition Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sadhanareddy The sources have been updated for the pattern recognition lab. Please follow the URL: https://cse20-iiith.vlabs.ac.in/

**Comment by sravanthimodepu** [comment]
Dear system team,

Please re-host the Pattern Recognition Lab, for this specific lab I have updated the lab with complete sources and converted the lab to new UI.

Here is the git-hub URL :
https://github.com/Virtual-Labs/pattern-recognition-iiith

Please make sure we don't loose the analytics of Pattern Recognition Lab .Once done with the hosting process, please share the URL.
