### ISSUE TITLE
Content is not getting pushed into git hub.

### ISSUE THREAD

**Issue by santhoshnitte87** [Virtual-Labs/engineers-forum#216]
I tried to upload lab content  to the git hub which is modified but after uploading it shows 'everything up-to-date' message. I don't  understand this error. Can you suggest me how to rectify this. And the contents are in different size.

**Comment by madhavipuliraju** [comment]
please do a git pull and then try to commit and push. If your changes are not reflecting. please do a git log and check whether your commit message was there or not.

**Comment by santhoshnitte87** [comment]
am getting trouble in git pull, can you tell me how to pull.

**Comment by madhavipuliraju** [comment]
What is the trouble? Can you please post it here for us to see ?


Normally, this is what you need to do :

1. git pull origin <branch-name>
2. git add your changes.
3. git commit your changes.
4. git push origin <branch-name>

Regards,
Madhavi

**Comment by ambikakaul** [comment]
Can you please send the screenshot of the error ?

**Comment by santhoshnitte87** [comment]
![git hub](https://cloud.githubusercontent.com/assets/13462722/10960249/b6fedfde-83a8-11e5-9dbb-1c8c479cd1be.jpg)

**Comment by santhoshnitte87** [comment]
thank you.. I will follow the steps as told.

**Comment by khushpreet-kaur** [comment]
@santhoshnitte87  If you are from NIT-K, then you can take help of Shivakumar (@sranjanagi). He is familiar with git and github.

**Comment by santhoshnitte87** [comment]
@khushpreet-kaur , he is left from nitk.. am working in place of him, so am fresher to this.
