### ISSUE TITLE
Request to host Outreach-Portal

### ISSUE THREAD

**Issue by madhavipuliraju** [Virtual-Labs/engineers-forum#217]
Dear Team,

Please host the following outreach-portal on Staging
Github url : https://github.com/vlead/outreach-portal/

We have tested the same on Testing (base4).
Please find the testing URL: http://outreach.base4.virtual-labs.ac.in/

**Comment by sivashankerN** [comment]
On staging, outreach.base1.vlabs.ac.in container is already running. This was hosted one month ago on staging.

**Comment by madhavipuliraju** [comment]
Ok @sivashankerN.  There is a slight change in plan. We don't want this to be hosted right now on Base1.

Hence, I am closing this request.
