### ISSUE TITLE
'Out of Memory' error while uploading  Animation 

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#218]
When we are trying to upload animation having 240MB size into our lab it will shows an error ' Out of Memory'. We can commit it on Github, but unable to sync.

**Comment by amritacreate** [comment]
Please give a follow up for this issue. We have some experiments with animation only. So How we can add our source to git, if there is a size limitation

**Comment by sanchita-dixit** [comment]
@amritacreate The file size limit of GitHub is 100 MB. For more details you can go through this link : https://help.github.com/articles/working-with-large-files/

**Comment by sanchita-dixit** [comment]
@amritacreate Are you trying to push a folder of this size or this is a single file? If this is folder, then we can break it into files and push individual files into the repo. That would be the only way of pushing such a large file.

**Comment by travula** [comment]
The animation is an executable.  one should not version control executables.
The sources to build the animation should be part of the repository and makefile should create the executable which will be hosted.
