### ISSUE TITLE
Regarding github account

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#219]
Dear VLEAD team,

I will not work on the project after 31st December, 2015. Kindly suggest me what should i do of my Github account.

I also request you to remove my write access or any other kind of access to the repositories and also detach my account from ie-iitd-team group which is available at: https://github.com/orgs/Virtual-Labs/teams/ie-iitd-team

Thanks and Regards,
Sumit Dahiya
Integration Engineer 
IIT Delhi

**Comment by sumitdahiyavlab** [comment]
I also request you to withdraw my write access to the repositories.

**Comment by ayogi** [comment]
@sumitdahiyavlab : Okay we will remove your write access from Virtual-Labs repositories and detach you from iitd team. You don't have to do anything from your side, you may continue using your github account.

**Comment by sumitdahiyavlab** [comment]
@ayogi Thanks Yogesh & Thank you very much to all VLEAD team members for their kind cooperation.

**Comment by sumitdahiyavlab** [comment]
Dear VLEAD team,

Sorry for the inconvinience. Kindly resume my write access to the repositories. I will continue working on the project after 31st December 2015.

Thanks and Regards,
Sumit Dahiya

**Comment by sanchita-dixit** [comment]
@sumitdahiyavlab Your write access is resumed to the respositories you were working with and you are also attached to ie-iitd-team group.

**Comment by sumitdahiyavlab** [comment]
Thank you very much.
