### ISSUE TITLE
Error in last step of level 4

### ISSUE THREAD

**Issue by anuuuanitha** [Virtual-Labs/engineers-forum#22]
The following error is coming while submit the query using lab id and repo url.

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/tornado/web.py", line 987, in _execute
    getattr(self, self.request.method.lower())(*args, **kwargs)
  File "ControllerServer.py", line 37, in post
    c = Controller.Controller()
  File "/root/ovpl/src/Controller.py", line 19, in __init__
    self.system = State.Instance()
  File "/root/ovpl/src/Singleton.py", line 33, in Instance
    self._instance = self._decorated()
  File "/root/ovpl/src/State.py", line 14, in __init__
    self.db = pymongo.MongoClient().ovpl
  File "/usr/lib/python2.6/site-packages/pymongo-2.8-py2.6-linux-x86_64.egg/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
ConnectionFailure: [Errno 111] Connection refused

**Comment by ecthiender** [comment]
See in the last line, the error comes from mongo_client.py and the error
says 'Connection refused'.

So most likely, your mongodb database service is not running.

Check your mongodb status with: `service mongodb status`

If it is not running, you can start mongodb with: `service mongodb start`

Please get back, if this does not solve your problem.

**Comment by anuuuanitha** [comment]
service mongod status
mongod (pid 2347) is running...

**Comment by ecthiender** [comment]
Did you try again,  after checking mongodb is running?

Do you have proxy in your institute?

**Comment by anuuuanitha** [comment]
Yes we tried after checking mongodb. Same error.
We don't have proxy.

**Comment by ecthiender** [comment]
Can you check your PROXY config settings in config/config.json file in the ovpl folder?

If you don't have proxy in your institute, you should set those values to empty in the config.json file.

**Comment by anuuuanitha** [comment]
Its already set empty.

    "ENVIRONMENT": {
        "HTTP_PROXY":"",
        "HTTPS_PROXY":""
    },

**Comment by ecthiender** [comment]
Were you able to resolve the issue?
