### ISSUE TITLE
Updated lab experiments are not moved into server

### ISSUE THREAD

**Issue by santhoshnitte87** [Virtual-Labs/engineers-forum#220]
hello Sir/Madam,

We have already  uploaded all the updated lab experiments into git. Since these lab experiments are not pushed into server. I am requesting you to upload all the files into server which are in the git.

Thanking you.

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 We are unable to understand which lab experiments are being referred to here. Kindly provide details.

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 Please close this issue as it has been resolved through other issues created by you for the hosting of labs.
