### ISSUE TITLE
Update sources of Vlabs landing page

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#221]
Need to update sources of vlabs landing page to update Problem Solving Lab's link. 

Earlier the link under "institute wise labs" (in landing page) was redirecting to the lab with old UI. This is to make consistency within landing page. Now all the links i.e "Featured lab", "Discipline wise labs" and "Institute wise labs" will redirect to the same new UI.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur The sources of vlabs landing page has been updated. Please follow the URL : https://vlabs.ac.in

**Comment by khushpreet-kaur** [comment]
Thanks. Link is working fine.
