### ISSUE TITLE
Hosting request for the updated content of Sensor lab - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#224]
Please host the sensor lab.
Link is given below.

https://github.com/Virtual-Labs/sensor-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The requested lab has been hosted with the updated sources. Please follow the URL : http://sl-coep.base1.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
As per index.html changes in lab introduction description please host the lab again.

https://github.com/Virtual-Labs/sensor-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The requested lab has been re-hosted. Please follow the URL : http://sl-coep.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
@sanchita-dixit Please re-host the sensor lab due to script addition of pre test and post test. link is given below.

https://github.com/Virtual-Labs/sensor-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The sensor lab has been re-hosted. The pre and post test is working. Please check and verify. You can follow the URL : http://sl-coep.vlabs.ac.in/
