### ISSUE TITLE
Hosting request for the updated content of fab Lab - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#225]
Please host the fab lab.
Link is given below.

https://github.com/Virtual-Labs/fab-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe Fab lab has been hosted with the latest sources. Please follow the URL : http://fab-coep.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
The lab contents are modified. Please host the lab.

https://github.com/Virtual-Labs/fab-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The updated lab has been re-hosted. Please follow the URL : http://fab-coep.vlabs.ac.in/
