### ISSUE TITLE
Hosting request for the updated content of programmable-logic-controller - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#227]
Please host the lab.
Link is given below.

https://github.com/Virtual-Labs/programmable-logic-controller-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab has been hosted with the updated content. Kindly follow the URL : http://plc-coep.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
Please host the lab again

https://github.com/Virtual-Labs/programmable-logic-controller-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab has been hosted again. Kindly follow the URL : http://plc-coep.vlabs.ac.in/
