### ISSUE TITLE
Hosting request for the updated content of industrial-automation-laboratory - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#228]
Please host the lab.
Link is given below.

https://github.com/Virtual-Labs/industrial-automation-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe industrial-automation-laboratory has been hosted with the updated content. Please follow the URL : http://ial-coep.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
Please host the lab again.

https://github.com/Virtual-Labs/industrial-automation-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab has been re-hosted. Kindly follow the URL : http://ial-coep.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
Changes made for introduction of lab. Kindly host the lab again.

https://github.com/Virtual-Labs/industrial-automation-laboratory-coep

**Comment by vaibhavkurhe** [comment]
@khushpreet-kaur @sanchita-dixit Please host the lab again and check whether pre test and post test results are working fine or not. So I can implement for rest of our labs. 

Link is given below. Please do it ASAP.
https://github.com/Virtual-Labs/industrial-automation-laboratory-coep

**Comment by sanchita-dixit** [comment]
@vaibhavkurhe The lab has been re-hosted. I have tested the above results and they are working fine. Please check and verify. Kindly follow the URL : http://ial-coep.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
@sanchita-dixit Yes. They are working fine. Thanks.
