### ISSUE TITLE
Hosting request for the updated content of hybrid-electronics-lab - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#229]
Please host the lab.
Link is given below.

https://github.com/Virtual-Labs/hybrid-electronics-lab-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe Since this is a new lab hosting request, it might take few more days from our end to resolve.

**Comment by sushilmedhe** [comment]
@sanchita-dixit I have updated the pretest and posttest content and added script files.
Please re-host the lab. Link is given below.

https://github.com/Virtual-Labs/hybrid-electronics-lab-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The requested lab has been re-hosted. The changes are not reflected in the production. Please follow the URL : http://he-coep.vlabs.ac.in/

**Comment by sanchita-dixit** [comment]
@sushilmedhe Since the re-hosted lab went down after 10 minutes of re-hosting with the latest sources, lab is reverted back to older version. Now it is working as before.

**Comment by sushilmedhe** [comment]
@sanchita-dixit what is the defect it have with the new version?? 
In hybrid lab the last experiment is not in proper format as you want. last experiment was added later. So someone should take care of this experiment. This contains only content.html file. It should be divided in different files like aim.html, pretest.html etc.
Look into this matter.

**Comment by sanchita-dixit** [comment]
@sushilmedhe The problem is that it is showing a blank screen on browser after hosting with the latest sources. Since the re-hosting process for all the labs is exactly identical and other labs work properly, then for such cases we cant find any issue from systems side. Please go through the code and try to find out any issue which is causing this problem.

**Comment by sushilmedhe** [comment]
@sanchita-dixit I have updated the UI from 1.0 to 3.0. Please host this lab.
link is given below

https://github.com/Virtual-Labs/hybrid-electronics-lab-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The requested lab has been hosted. UI 3.0 is working fine. Kindly verify. Please follow the URL : http://he-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
@sanchita-dixit The lab is working fine. Thank you.
