### ISSUE TITLE
error while submiting "test your lab" page

### ISSUE THREAD

**Issue by praveenscreate** [Virtual-Labs/engineers-forum#23]
I am getting an error while clicking on the submit button of the page " Test your lab". This is the error 

[I 150302 12:43:35 web:1392] 200 POST / (::1) 233356.23ms
[I 150302 15:24:37 web:1392] 200 GET / (::1) 7.27ms
[D 150302 15:24:42 Controller:24] Controller.test_lab() for lab ID POE2 and git url https://github.com/Virtual-Labs/population-ecology-virtual-lab-i-au.git
[D 150302 15:24:42 LabManager:25] LabManager: get_lab_reqs():  Invoked from Controller
[D 150302 15:24:42 LabManager:30] LabManager: GIT_CLONE_LOC = /root/labs/lab-repo-cache/
[D 150302 15:24:42 LabManager:31] LabManager: LAB_SPEC_LOC = /scripts/labspec.json
[D 150302 15:24:42 LabManager:35] LabManager: construct_repo_name()
[D 150302 15:24:42 LabManager:41] LabManager: repo_exists()
[D 150302 15:24:42 LabManager:46] LabManager, clone_repo(): git clone https://github.com/Virtual-Labs/population-ecology-virtual-lab-i-au.git /root/labs/lab-repo-cache/POE2population-ecology-virtual-lab-i-au
[D 150302 15:24:42 LabManager:49] LabManager, clone_repo(): clone_cmd = ['git', 'clone', 'https://github.com/Virtual-Labs/population-ecology-virtual-lab-i-au.git', '/root/labs/lab-repo-cache/POE2population-ecology-virtual-lab-i-au']
[E 150302 15:55:13 LabManager:78] LabManager: checkout_version(), repo_name = POE2population-ecology-virtual-lab-i-au
[E 150302 15:55:13 LabManager:90] LabManager: get_lab_spec(); repo_name = POE2population-ecology-virtual-lab-i-au
[D 150302 15:55:13 Controller:71] Controller.undeploy_lab for lab_id POE2
[D 150302 15:55:13 VMPoolManager:17] VMPoolManager: _init_()
[D 150302 15:55:13 VMPoolManager:40] VMPoolManager: add_vm_pool(); 1, LINUX, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150302 15:55:13 VMPool:32] VMPool: __init__(); poolID=1, Desciption=LINUX, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150302 15:55:13 VMPoolManager:40] VMPoolManager: add_vm_pool(); 2, WINDOWS, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150302 15:55:13 VMPool:32] VMPool: __init__(); poolID=2, Desciption=WINDOWS, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150302 15:55:13 VMPoolManager:40] VMPoolManager: add_vm_pool(); 3, AMAZONS3, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150302 15:55:13 VMPool:32] VMPool: __init__(); poolID=3, Desciption=AMAZONS3, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150302 15:55:13 VMPoolManager:40] VMPoolManager: add_vm_pool(); 4, AMAZONEC2, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150302 15:55:13 VMPool:32] VMPool: __init__(); poolID=4, Desciption=AMAZONEC2, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150302 15:55:13 VMPoolManager:35] VMPoolManager: _init_();  vm_pools = [<VMPool.VMPool instance at 0x1cec560>, <VMPool.VMPool instance at 0x1cec440>, <VMPool.VMPool instance at 0x1cec248>, <VMPool.VMPool instance at 0x1cec290>]
[D 150302 15:55:13 VMPoolManager:71] VMPoolManager: undeploy_lab()
[D 150302 15:55:13 VMPoolManager:77] VMPoolManager: get_used_pools()
[D 150302 15:55:13 VMPoolManager:17] VMPoolManager: _init_()
[D 150302 15:55:13 VMPoolManager:40] VMPoolManager: add_vm_pool(); 1, LINUX, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150302 15:55:13 VMPool:32] VMPool: __init__(); poolID=1, Desciption=LINUX, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150302 15:55:13 VMPoolManager:40] VMPoolManager: add_vm_pool(); 2, WINDOWS, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150302 15:55:13 VMPool:32] VMPool: __init__(); poolID=2, Desciption=WINDOWS, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150302 15:55:13 VMPoolManager:40] VMPoolManager: add_vm_pool(); 3, AMAZONS3, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150302 15:55:13 VMPool:32] VMPool: __init__(); poolID=3, Desciption=AMAZONS3, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150302 15:55:13 VMPoolManager:40] VMPoolManager: add_vm_pool(); 4, AMAZONEC2, http://localhost, 8000, /api/1.0/vm/create, /api/1.0/vm/destroy
[D 150302 15:55:13 VMPool:32] VMPool: __init__(); poolID=4, Desciption=AMAZONEC2, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150302 15:55:13 VMPoolManager:35] VMPoolManager: _init_();  vm_pools = [<VMPool.VMPool instance at 0x1cec3b0>, <VMPool.VMPool instance at 0x1cec5a8>, <VMPool.VMPool instance at 0x1cec638>, <VMPool.VMPool instance at 0x1cec3f8>]
[D 150302 15:55:13 Controller:32] Controller: test_lab(); invoking create_vm() on vmpoolmgr
[D 150302 15:55:13 VMPoolManager:66] VMPoolManager: create_vm()
[D 150302 15:55:13 VMPoolManager:51] VMPoolManager: get_available_pool()
[D 150302 15:55:13 VMPool:79] VMPool: create_vm(); poolID=1, Desciption=LINUX, AdapterIP=http://localhost, AdapterPort=8000, CreatePath=/api/1.0/vm/create, DestroyPath=/api/1.0/vm/destroy
[D 150302 15:55:13 VMPool:84] VMPool: create_vm(); adapter_url = http://localhost:8000/api/1.0/vm/create, payload = {'lab_spec': '{"lab_id": "POE2", "revision_tag": null, "template": "1.0", "lab": {"build_requirements": {"platform": {"os": "ubuntu", "service_pack": "", "build_steps": {"status": [], "pre_build": [], "post_build": [], "build": ["make -C ../src"], "configure": []}, "installer": [], "osVersion": "12", "arch": "i386"}}, "runtime_requirements": {"platform": {"servicepack": "", "arch": "i386", "lab_actions": {"restore": [], "pause": [], "stats": [], "shutdown": ["service apache2 stop"], "resume": [], "stop": [], "publish": [], "start": ["service apache2 start"], "init": ["mv /var/www/index.html index.html.default", "cp -r ../build/* /var/www/"], "clean": [], "backup": []}, "storage": {"min_required": "10gb"}, "hosting": "dedicated", "memory": {"min_required": "256mb", "max_required": "2gb"}, "installer": ["sudo apt-get update", "sudo apt-get install -y php5 apache2"], "osVersion": "12", "os": "ubuntu"}, "hosting": "dedicated"}, "description": {"discipline": ["Computer Science & Engineering"], "status": "Released", "name": "Computer Programming", "type": "", "server-side": true, "integration_level": 5, "id": "POE2", "developer": [{"web": "", "name": "Rathish G", "title": "", "institute": "Amrita", "contact": {"alternate_email": "", "email": "rathishg@am.amrita.edu", "office_number": "", "mobile_number": ""}, "role": "Project Manager", "department": "CREATE", "organization": ""}, {"web": "", "name": "Sreejith S R", "title": "", "institute": "Amrita", "contact": {"alternate_email": "", "email": "sreejithsr@am.amrita.edu", "office_number": "", "mobile_number": ""}, "role": "Lab Developer", "department": "CREATE", "organization": ""}, {"web": "", "name": "Praveen S", "title": "", "institute": "Amrita", "contact": {"alternate_email": "", "email": "praveens@am.amrita.edu", "office_number": "", "mobile_number": ""}, "role": "Lab Developer", "department": "CREATE", "organization": ""}, {"web": "", "name": "Sruthi Mangala", "title": "", "institute": "Amrita", "contact": {"alternate_email": "", "email": "sruthimangala@am.amrita.edu", "office_number": "", "mobile_number": ""}, "role": "Lab Developer", "department": "CREATE", "organization": ""}, {"web": "", "name": "Anitha B", "title": "", "institute": "Amrita", "contact": {"alternate_email": "", "email": "anithab@am.amrita.edu", "office_number": "", "mobile_number": ""}, "role": "Lab Developer", "department": "CREATE", "organization": ""}]}}, "lab_src_url": "https://github.com/Virtual-Labs/population-ecology-virtual-lab-i-au.git"}'}
[I 150302 15:55:13 connectionpool:203] Starting new HTTP connection (1): localhost
[D 150302 15:55:13 AdapterServer:33] post()
[D 150302 15:55:13 AdapterServer:35] post(); post_data = {'lab_spec': '{"lab_id": "POE2", "revision_tag": null, "template": "1.0", "lab": {"build_requirements": {"platform": {"os": "ubuntu", "service_pack": "", "build_steps": {"status": [], "pre_build": [], "post_build": [], "build": ["make -C ../src"], "configure": []}, "installer": [], "osVersion": "12", "arch": "i386"}}, "runtime_requirements": {"platform": {"servicepack": "", "arch": "i386", "lab_actions": {"restore": [], "pause": [], "stats": [], "shutdown": ["service apache2 stop"], "resume": [], "stop": [], "publish": [], "start": ["service apache2 start"], "init": ["mv /var/www/index.html index.html.default", "cp -r ../build/* /var/www/"], "clean": [], "backup": []}, "storage": {"min_required": "10gb"}, "hosting": "dedicated", "memory": {"min_required": "256mb", "max_required": "2gb"}, "installer": ["sudo apt-get update", "sudo apt-get install -y php5 apache2"], "osVersion": "12", "os": "ubuntu"}, "hosting": "dedicated"}, "description": {"discipline": ["Computer Science & Engineering"], "status": "Released", "name": "Computer Programming", "type": "", "server-side": true, "integration_level": 5, "id": "POE2", "developer": [{"web": "", "name": "Rathish G", "title": "", "institute": "Amrita", "contact": {"alternate_email": "", "email": "rathishg@am.amrita.edu", "office_number": "", "mobile_number": ""}, "role": "Project Manager", "department": "CREATE", "organization": ""}, {"web": "", "name": "Sreejith S R", "title": "", "institute": "Amrita", "contact": {"alternate_email": "", "email": "sreejithsr@am.amrita.edu", "office_number": "", "mobile_number": ""}, "role": "Lab Developer", "department": "CREATE", "organization": ""}, {"web": "", "name": "Praveen S", "title": "", "institute": "Amrita", "contact": {"alternate_email": "", "email": "praveens@am.amrita.edu", "office_number": "", "mobile_number": ""}, "role": "Lab Developer", "department": "CREATE", "organization": ""}, {"web": "", "name": "Sruthi Mangala", "title": "", "institute": "Amrita", "contact": {"alternate_email": "", "email": "sruthimangala@am.amrita.edu", "office_number": "", "mobile_number": ""}, "role": "Lab Developer", "department": "CREATE", "organization": ""}, {"web": "", "name": "Anitha B", "title": "", "institute": "Amrita", "contact": {"alternate_email": "", "email": "anithab@am.amrita.edu", "office_number": "", "mobile_number": ""}, "role": "Lab Developer", "department": "CREATE", "organization": ""}]}}, "lab_src_url": "https://github.com/Virtual-Labs/population-ecology-virtual-lab-i-au.git"}'}
[D 150302 15:55:13 CentOSVZAdapter:85] CentOSVZAdapter: create_vm()
[I 150302 15:55:13 sh:382] <Command '/bin/ping 192.168.17...(9 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
[I 150302 15:55:13 sh:382] <Command '/bin/ping 192.168.17...(9 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
[I 150302 15:55:23 sh:382] <Command '/bin/ping 192.168.17...(9 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
[I 150302 15:55:23 sh:382] <Command '/bin/ping 192.168.17...(9 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
[D 150302 15:55:33 CentOSVZAdapter:99] CentOSVZAdapter: create_vm(): ip = 192.168.171.18, vm_id = 17118, vm_create_args =  --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 192.168.171.18 --diskspace 10G:15.0G --hostname POE2.vlabs.ac.in, vm_set_args =  --nameserver inherit --ram 256M --swap 512M --onboot yes --save
[E 150302 15:55:34 CentOSVZAdapter:109] Error creating VM: Command '/usr/sbin/vzctl create 17118 --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 192.168.171.18 --diskspace 10G:15.0G --hostname POE2.vlabs.ac.in' returned non-zero exit status 91
[D 150302 15:55:34 AdapterServer:38] created VM id = 105
[D 150302 15:55:34 CentOSVZAdapter:114] CentOSVZAdapter: init_vm(): vm_id = 105
[D 150302 15:55:34 CentOSVZAdapter:187] CentOSVZAdapter: copy_vm_manager_files(): vm_id = 105
[D 150302 15:55:34 CentOSVZAdapter:191] CentOSVZAdapter: copy_vm_manager_files(): dest_dir = /vz/root/105/root/VMManager, src_dir = /root/ovpl/src/adapters/../VMManager
[E 150302 15:55:34 CentOSVZAdapter:200] CentOSVZAdapter: copy_vm_manager_files():  dest_dir = /vz/root/105/root/VMManager, src_dir = /root/ovpl/src/adapters/../VMManager, ERROR = [Errno 17] File exists: '/vz/root/105/root/VMManager'
[E 150302 15:55:34 web:1030] Uncaught exception POST /api/1.0/vm/create (::1)
    HTTPRequest(protocol='http', host='localhost:8000', method='POST', uri='/api/1.0/vm/create', version='HTTP/1.1', remote_ip='::1', body='lab_spec=%7B%22lab_id%22%3A+%22POE2%22%2C+%22revision_tag%22%3A+null%2C+%22template%22%3A+%221.0%22%2C+%22lab%22%3A+%7B%22build_requirements%22%3A+%7B%22platform%22%3A+%7B%22os%22%3A+%22ubuntu%22%2C+%22service_pack%22%3A+%22%22%2C+%22build_steps%22%3A+%7B%22status%22%3A+%5B%5D%2C+%22pre_build%22%3A+%5B%5D%2C+%22post_build%22%3A+%5B%5D%2C+%22build%22%3A+%5B%22make+-C+..%2Fsrc%22%5D%2C+%22configure%22%3A+%5B%5D%7D%2C+%22installer%22%3A+%5B%5D%2C+%22osVersion%22%3A+%2212%22%2C+%22arch%22%3A+%22i386%22%7D%7D%2C+%22runtime_requirements%22%3A+%7B%22platform%22%3A+%7B%22servicepack%22%3A+%22%22%2C+%22arch%22%3A+%22i386%22%2C+%22lab_actions%22%3A+%7B%22restore%22%3A+%5B%5D%2C+%22pause%22%3A+%5B%5D%2C+%22stats%22%3A+%5B%5D%2C+%22shutdown%22%3A+%5B%22service+apache2+stop%22%5D%2C+%22resume%22%3A+%5B%5D%2C+%22stop%22%3A+%5B%5D%2C+%22publish%22%3A+%5B%5D%2C+%22start%22%3A+%5B%22service+apache2+start%22%5D%2C+%22init%22%3A+%5B%22mv+%2Fvar%2Fwww%2Findex.html+index.html.default%22%2C+%22cp+-r+..%2Fbuild%2F%2A+%2Fvar%2Fwww%2F%22%5D%2C+%22clean%22%3A+%5B%5D%2C+%22backup%22%3A+%5B%5D%7D%2C+%22storage%22%3A+%7B%22min_required%22%3A+%2210gb%22%7D%2C+%22hosting%22%3A+%22dedicated%22%2C+%22memory%22%3A+%7B%22min_required%22%3A+%22256mb%22%2C+%22max_required%22%3A+%222gb%22%7D%2C+%22installer%22%3A+%5B%22sudo+apt-get+update%22%2C+%22sudo+apt-get+install+-y+php5+apache2%22%5D%2C+%22osVersion%22%3A+%2212%22%2C+%22os%22%3A+%22ubuntu%22%7D%2C+%22hosting%22%3A+%22dedicated%22%7D%2C+%22description%22%3A+%7B%22discipline%22%3A+%5B%22Computer+Science+%26+Engineering%22%5D%2C+%22status%22%3A+%22Released%22%2C+%22name%22%3A+%22Computer+Programming%22%2C+%22type%22%3A+%22%22%2C+%22server-side%22%3A+true%2C+%22integration_level%22%3A+5%2C+%22id%22%3A+%22POE2%22%2C+%22developer%22%3A+%5B%7B%22web%22%3A+%22%22%2C+%22name%22%3A+%22Rathish+G%22%2C+%22title%22%3A+%22%22%2C+%22institute%22%3A+%22Amrita%22%2C+%22contact%22%3A+%7B%22alternate_email%22%3A+%22%22%2C+%22email%22%3A+%22rathishg%40am.amrita.edu%22%2C+%22office_number%22%3A+%22%22%2C+%22mobile_number%22%3A+%22%22%7D%2C+%22role%22%3A+%22Project+Manager%22%2C+%22department%22%3A+%22CREATE%22%2C+%22organization%22%3A+%22%22%7D%2C+%7B%22web%22%3A+%22%22%2C+%22name%22%3A+%22Sreejith+S+R%22%2C+%22title%22%3A+%22%22%2C+%22institute%22%3A+%22Amrita%22%2C+%22contact%22%3A+%7B%22alternate_email%22%3A+%22%22%2C+%22email%22%3A+%22sreejithsr%40am.amrita.edu%22%2C+%22office_number%22%3A+%22%22%2C+%22mobile_number%22%3A+%22%22%7D%2C+%22role%22%3A+%22Lab+Developer%22%2C+%22department%22%3A+%22CREATE%22%2C+%22organization%22%3A+%22%22%7D%2C+%7B%22web%22%3A+%22%22%2C+%22name%22%3A+%22Praveen+S%22%2C+%22title%22%3A+%22%22%2C+%22institute%22%3A+%22Amrita%22%2C+%22contact%22%3A+%7B%22alternate_email%22%3A+%22%22%2C+%22email%22%3A+%22praveens%40am.amrita.edu%22%2C+%22office_number%22%3A+%22%22%2C+%22mobile_number%22%3A+%22%22%7D%2C+%22role%22%3A+%22Lab+Developer%22%2C+%22department%22%3A+%22CREATE%22%2C+%22organization%22%3A+%22%22%7D%2C+%7B%22web%22%3A+%22%22%2C+%22name%22%3A+%22Sruthi+Mangala%22%2C+%22title%22%3A+%22%22%2C+%22institute%22%3A+%22Amrita%22%2C+%22contact%22%3A+%7B%22alternate_email%22%3A+%22%22%2C+%22email%22%3A+%22sruthimangala%40am.amrita.edu%22%2C+%22office_number%22%3A+%22%22%2C+%22mobile_number%22%3A+%22%22%7D%2C+%22role%22%3A+%22Lab+Developer%22%2C+%22department%22%3A+%22CREATE%22%2C+%22organization%22%3A+%22%22%7D%2C+%7B%22web%22%3A+%22%22%2C+%22name%22%3A+%22Anitha+B%22%2C+%22title%22%3A+%22%22%2C+%22institute%22%3A+%22Amrita%22%2C+%22contact%22%3A+%7B%22alternate_email%22%3A+%22%22%2C+%22email%22%3A+%22anithab%40am.amrita.edu%22%2C+%22office_number%22%3A+%22%22%2C+%22mobile_number%22%3A+%22%22%7D%2C+%22role%22%3A+%22Lab+Developer%22%2C+%22department%22%3A+%22CREATE%22%2C+%22organization%22%3A+%22%22%7D%5D%7D%7D%2C+%22lab_src_url%22%3A+%22https%3A%2F%2Fgithub.com%2FVirtual-Labs%2Fpopulation-ecology-virtual-lab-i-au.git%22%7D', headers={'Content-Length': '3917', 'Host': 'localhost:8000', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/x-www-form-urlencoded', 'Connection': 'keep-alive', 'Accept': '*/*', 'User-Agent': 'python-requests/2.5.3 CPython/2.6.6 Linux/2.6.32-042stab104.1'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 987, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "adapters/AdapterServer.py", line 40, in post
        (success, result) = adapter_instance.init_vm(vm_id)
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 121, in init_vm
        response = {"vm_id": vm_id, "vm_ip": get_vm_ip(vm_id), "vmm_port": settings.VM_MANAGER_PORT}
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 215, in get_vm_ip
        raise e
    CalledProcessError: Command '/usr/sbin/vzlist -a | grep 105' returned non-zero exit status 1
[E 150302 15:55:34 web:1392] 500 POST /api/1.0/vm/create (::1) 21009.39ms
[D 150302 15:55:34 VMPool:88] VMPool: create_vm(): Response text from adapter: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 987, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "adapters/AdapterServer.py", line 40, in post
        (success, result) = adapter_instance.init_vm(vm_id)
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 121, in init_vm
        response = {"vm_id": vm_id, "vm_ip": get_vm_ip(vm_id), "vmm_port": settings.VM_MANAGER_PORT}
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 215, in get_vm_ip
        raise e
    CalledProcessError: Command '/usr/sbin/vzlist -a | grep 105' returned non-zero exit status 1
    
[E 150302 15:55:34 VMPool:97] VMPool: create_vm(): Error communicating with adapter: VMPool: create_vm(): Error creating VM: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 987, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "adapters/AdapterServer.py", line 40, in post
        (success, result) = adapter_instance.init_vm(vm_id)
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 121, in init_vm
        response = {"vm_id": vm_id, "vm_ip": get_vm_ip(vm_id), "vmm_port": settings.VM_MANAGER_PORT}
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 215, in get_vm_ip
        raise e
    CalledProcessError: Command '/usr/sbin/vzlist -a | grep 105' returned non-zero exit status 1
    
[E 150302 15:55:34 Controller:55] Controller: test_lab(): Test failed with error: VMPool: create_vm(): Error creating VM: VMPool: create_vm(): Error creating VM: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 987, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "adapters/AdapterServer.py", line 40, in post
        (success, result) = adapter_instance.init_vm(vm_id)
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 121, in init_vm
        response = {"vm_id": vm_id, "vm_ip": get_vm_ip(vm_id), "vmm_port": settings.VM_MANAGER_PORT}
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 215, in get_vm_ip
        raise e
    CalledProcessError: Command '/usr/sbin/vzlist -a | grep 105' returned non-zero exit status 1
    
[I 150302 15:55:34 web:1392] 200 POST / (::1) 1851792.71ms

Please help me to fix this.

**Comment by travula** [comment]
Can you please run 'vzlist -a | grep 105' on the same container manually? I
think openvz is not properly installed.

**Comment by praveenscreate** [comment]
after running that command, nothing showed. 101 is manually  created container. Here is the code

root@centos /]# vzlist -a | grep 105
[root@centos /]# vzlist -a 
      CTID      NPROC STATUS    IP_ADDR         HOSTNAME
       101         19 running   -               -
[root@centos /]# vzlist -a | grep 101
       101         19 running   -               -

**Comment by ecthiender** [comment]
Were you able to solve the issue?
