### ISSUE TITLE
Hosting request for the updated content of electrical-machines - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#231]
Please host the lab.
Link is given below.

https://github.com/Virtual-Labs/electrical-machines-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The requested lab has been hosted with the updated content. Please follow the URL : http://em-coep.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
As per index.html changes in lab introduction description please host the lab again.

https://github.com/Virtual-Labs/electrical-machines-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab has been hosted again. Please follow the URL : http://em-coep.vlabs.ac.in/
