### ISSUE TITLE
Hosting request for the updated content of FPGA lab - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#232]
Please host the lab.
Link is given below.

https://github.com/Virtual-Labs/fpga-and-embedded-systems-lab-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe This lab hosting request might take few more days to resolve.

**Comment by sushilmedhe** [comment]
@sanchita-dixit No problem. But make sure that you will share the lab issue with your team about FPGA lab which I have shared you already.

**Comment by sushilmedhe** [comment]
@sanchita-dixit  @khushpreet-kaur  Refer issue #151 to solve the problem.Detailed description of how this lab run on our server is given.
