### ISSUE TITLE
Repository access permission for users

### ISSUE THREAD

**Issue by sreejithsr-amrita** [Virtual-Labs/engineers-forum#233]
Hello,

Please remove the user 'praveenscreate' and add new user 'amritacreate@gmail.com' in 'ie-au-team'.

**Comment by vleadadmin** [comment]
Dear Sreejithsr,
Please provide more details with us like user name of 'amritacreate@gmail.com'  in github account so that we can  add amritacreate@gmail.com to "ie-au-team". Email id is not enough.
we have removed praveenscreate user from "ie-au-team"

**Comment by sreejithsr-amrita** [comment]
Hello,

Username is 'amritacreate'.

**Comment by vleadadmin** [comment]
We have added. Please check your email

**Comment by sreejithsr-amrita** [comment]
Hello, We haven't received any email so far.

**Comment by vleadadmin** [comment]
Have you checked amritacreate@gmail.com. Please check if not
