### ISSUE TITLE
question about introduction

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#234]
When we want to change the introduction of lab on welcome page then which github file we have to modify??? 

I think that should be <lab-name>/src/lab/introduction.html

is it??
Please reply ASAP.

**Comment by khushpreet-kaur** [comment]
Can you please specify the lab name? Or you can figure it out by yourself by seeing the url on the same page or by viewing the source file.

**Comment by sushilmedhe** [comment]
Actually I have made changes for all lab introduction.

In case of electrical machines I had updated file with this path - electrical-machines-coep/src/lab/introduction.html

and now as per hosting request it is hosted but still the changes are not reflected in the introduction.

**Comment by khushpreet-kaur** [comment]
@sushilmedhe  Ok. Have you tried on your local machine, are the changes reflecting there? @sanchita-dixit Can you please look into the issue?

**Comment by sushilmedhe** [comment]
@khushpreet-kaur  No I am not able to check on my local machine. As it through some errors.

**Comment by sanchita-dixit** [comment]
@sushilmedhe The changes are reflected. You made changes to the introduction.html file but not to the index.html page. Hence correct introduction content is displayed when you click the Introduction link. 
![screenshot from 2016-01-28 16 52 09](https://cloud.githubusercontent.com/assets/13132618/12643028/a3ce56be-c5df-11e5-8f80-b9b458239895.png)

**Comment by sushilmedhe** [comment]
I got this now. And I have made changes in index.html also. We have to host it again. But in case of Bio-medical and signal processing lab,Industrial Automation lab, PLC, vibration and acoustics lab there is no such content in index.html. Then where I have to make changes?

**Comment by sushilmedhe** [comment]
And should I have to create again new issue to re - host the sensor lab and electrical machines lab?? Or I can comment in previous hosting request for the same?

**Comment by khushpreet-kaur** [comment]
Please check carefully, Index files for all the labs, mentioned in previous comment, are available under /src/lab directory. 
Please comment to the same issue to re-host the lab after changes.

**Comment by sushilmedhe** [comment]
I have check the following labs which are having different index.html file.

1) Hybrid lab
2) Bio-medical and signal processing lab
3) Fab lab
4) Vibration and acoustics lab
5) Micromachining lab
6) FPGA lab.

In this index.html page there is no such content block. Can you please go through any one of them? and reply me

**Comment by khushpreet-kaur** [comment]
Please refer to "content.html" for the labs with old UI. It is also available under /src/lab repository.

**Comment by sanchita-dixit** [comment]
@sushilmedhe Please close the issue if it is resolved.
