### ISSUE TITLE
Request to create new repo Cell biology Virtual Lab II

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#236]
Please create a new repo by forking the content from https://github.com/CreateAmrita/cell-biology-virtual-lab-II.git and give access to @Virtual-Labs/ie-au-team users

or give create repo access to @amritacreate

Broad area: Biotechnology and Biomedical Engineering
Lab name: Cell biology Virtual Lab II

**Comment by sanchita-dixit** [comment]
@amritacreate amritacreate already has write access to create new repositories in virtual-labs. Please try to create a new repository and if faced with any issues, kindly get back to us.

**Comment by sanchita-dixit** [comment]
@amritacreate This issue is already been taken care of and the lab is also hosted. #312
