### ISSUE TITLE
Request to create new repo Electricity & Magnetism Virtual Lab

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#237]
Please create a new repo by forking the content from https://github.com/CreateAmrita/electricity-magnetism-virtual-lab.git and give access to @Virtual-Labs/ie-au-team users

or give create repo access to @amritacreate

Broad area: Physical Sciences
Lab name: Electricity & Magnetism Virtual Lab

**Comment by sanchita-dixit** [comment]
@amritacreate amritacreate already has write access to create new repositories in virtual-labs. Please try to create a new repository and if faced with any issues, kindly get back to us.

**Comment by sanchita-dixit** [comment]
@amritacreate This issue is already been taken care of and the lab is also hosted. #313
