### ISSUE TITLE
Request to create new repo Optics Virtual Lab

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#239]
Please create a new repo by forking the content from https://github.com/CreateAmrita/optics-virtual-lab.git and give access to @Virtual-Labs/ie-au-team users

or give create repo access to @amritacreate

Broad area: Physical Sciences
Lab name: Optics Virtual Lab

**Comment by sanchita-dixit** [comment]
@amritacreate  amritacreate already has write access to create new repositories in virtual-labs. Please try to create a new repository and if faced with any issues, kindly get back to us.

**Comment by sanchita-dixit** [comment]
@amritacreate Any updates on this issue. Kindly respond with your queries and if no problem exists, you can close this issue and other issues related to it.  Related issues : #235 , #236, #237 and #238

**Comment by sanchita-dixit** [comment]
@amritacreate Please provide some update on this issue as there are 4 other similar issues #235 , #236, #237 and #238 open because of this.

**Comment by amritacreate** [comment]
@sanchita-dixit We dont have permission to create repo

![image](https://cloud.githubusercontent.com/assets/11895447/14040970/a7122208-f292-11e5-8feb-4644b5754a50.png)

**Comment by sanchita-dixit** [comment]
@amritacreate As per discussions on email with Mr. Shyam and Thirumal, to bring all the lab sources on GitHub and host the Amrita labs, 2 options were given : 

1. Creation of repositories
http://github.com/virtual-labs holds all the repositories for all the labs of
all the institutions.  Once Amrita provides VLEAD a list of the names of the
repositories, the admin of the 'virtual-labs' will create these repositories.

- Creation of Team
If Amrita provides a list of github handles that they wish to be administrators of
the repositories that were created in step 1 above, the provided users will be
make administrators of these of these repositories.

2. Choice Two
Amrita could create the repositories on github outside the organization 'virtual
labs' and be the sole administrators.  For the VLEAD's auto
deployment service which requires a url of a public repository of a lab to be
deployed, choice two will also work.

Second option has been chosen. We are waiting for Amrita team to create all the repos as per the option above and provide us with the Github URL of the lab. Once that is done, hosting requests need to be raised on Engineers-forum for hosting of labs.

**Comment by sanchita-dixit** [comment]
@amritacreate The same response applies for issues : #235 , #236 , #237 and #238

**Comment by sanchita-dixit** [comment]
@amritacreate This issue is already been taken care of and the lab is also hosted. #310
