### ISSUE TITLE
Request to host the IIT Kanpur Labs

### ISSUE THREAD

**Issue by GuptaManoj** [Virtual-Labs/engineers-forum#24]
Dear Vlead Team,

Today, Two labs of IIT Kanpur were successufully tested over ADS. Here are git hub URL's of the labs sources

1- https://github.com/Virtual-Labs/virtual-lab-aerospace-engg-iitk
2- https://github.com/Virtual-Labs/virtual-combustion-and-automization-lab-iitk

Can you please host them on Amazon and gives us the hosted URL.

**Comment by MSSoumya** [comment]
Dear Manoj and Dhananjay,

We tried to deploy the lab on amazon but we faced some issues. We couldn't deploy the Aerospace engineering and Combustion and atomization labs. I sent you the error logs via emailbecause this issues do not support such file types. Please do the needful. 

With regards,
Soumya

**Comment by jayanthsagar** [comment]
Hi Manoj and Dhananjay,

We tried deploying your lab using Automated Deployment Service but the following lab https://github.com/Virtual-Labs/virtual-combustion-and-automization-lab-iitk is throwing errors.
**And we have noticed that your lab requires php-mysql if you are installing mysql server and triying to connect database using php.**
Please update your labspec.json with following
In Runtime requirements, include "-y" for mysql-server.
                "sudo apt-get install -y php5 apache2",
                "sudo apt-get install -y mysql-server"

**we have also noticed that your labspec is not configuring your database anywhere, there is a file in src/database/db_config.sh which is not used. seems like it should be calling that script to configure Database if your lab requires database.**
**Please update your Labspec ASAP**

**Comment by jayanthsagar** [comment]
Hi Manoj,

We have deployed virtual aerospace engg lab. you can access the lab using http://vlae-iitk.vlabs.ac.in
there is a issue with combution and automization lab.
Please make appropriate changes and open a fresh request for hosting for that lab.

**Comment by GuptaManoj** [comment]
Dear Jayanth,

Please send the Log file of server if possible.

Thanks & Regards
 Manoj Gupta

**Comment by jayanthsagar** [comment]
05/05/2015 05:47:30 AM: DEBUG: /root/ovpl/src/utils/git_commands.py:28  -> repo_name: virtual-combustion-and-automization-lab-iitk
05/05/2015 05:47:30 AM: DEBUG: /root/ovpl/src/utils/git_commands.py:90  -> spec_file_path: /root/labs/virtual-combustion-and-automization-lab-iitk/scripts/labspec.json
05/05/2015 05:47:30 AM: DEBUG: /root/ovpl/src/VMManager/VMManager.py:98  -> spec_path: /root/labs/virtual-combustion-and-automization-lab-iitk/scripts/
05/05/2015 05:47:30 AM: DEBUG: /root/ovpl/src/VMManager/VMManager.py:100 -> Changed to Diretory: /root/labs/virtual-combustion-and-automization-lab-iitk/scripts/
05/05/2015 05:47:30 AM: DEBUG: /root/ovpl/src/VMManager/VMManager.py:101 -> CWD: /root/labs/virtual-combustion-and-automization-lab-iitk/scripts
05/05/2015 05:47:30 AM: INFO: /root/ovpl/src/VMManager/LabActionRunner.py:49  -> Configuring the lab...
05/05/2015 05:47:30 AM: INFO: /root/ovpl/src/VMManager/LabActionRunner.py:54  -> Running the pre-build scripts...
05/05/2015 05:47:30 AM: INFO: /root/ovpl/src/VMManager/LabActionRunner.py:59  -> Running the build scripts...
05/05/2015 05:47:30 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:45  -> LabActionScript::run() -
05/05/2015 05:47:30 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:46  -> LabActionScript::run() - make -C ../src
05/05/2015 05:47:30 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:47  -> LabActionScript::run() - /root/labs/virtual-combustion-and-automization-lab-iitk/scripts
05/05/2015 05:47:30 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:27  -> command: make -C ../src
05/05/2015 05:47:31 AM: INFO: /root/ovpl/src/VMManager/LabActionRunner.py:64  -> Running the post-build scripts...
05/05/2015 05:47:31 AM: INFO: /root/ovpl/src/VMManager/LabActionRunner.py:69  -> Checking the status of the build...
05/05/2015 05:47:31 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:45  -> LabActionScript::run() -
05/05/2015 05:47:31 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:46  -> LabActionScript::run() - sudo apt-get update
05/05/2015 05:47:31 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:47  -> LabActionScript::run() - /root/labs/virtual-combustion-and-automization-lab-iitk/scripts
05/05/2015 05:47:31 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:27  -> command: sudo apt-get update
05/05/2015 05:48:14 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:45  -> LabActionScript::run() -
05/05/2015 05:48:14 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:46  -> LabActionScript::run() - sudo apt-get install -y php5 apache2
05/05/2015 05:48:14 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:47  -> LabActionScript::run() - /root/labs/virtual-combustion-and-automization-lab-iitk/scripts
05/05/2015 05:48:14 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:27  -> command: sudo apt-get install -y php5 apache2
05/05/2015 05:48:46 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:45  -> LabActionScript::run() -
05/05/2015 05:48:46 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:46  -> LabActionScript::run() - sudo apt-get install mysql-server
05/05/2015 05:48:46 AM: DEBUG: /root/ovpl/src/VMManager/LabActionScript.py:47  -> LabActionScript::run() - /root/labs/virtual-combustion-and-automization-lab-iitk/scripts
05/05/2015 05:48:46 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:27  -> command: sudo apt-get install mysql-server
05/05/2015 05:48:47 AM: ERROR: /root/ovpl/src/utils/execute_commands.py:34  -> Called Process Error: Command 'sudo apt-get install mysql-server' returned non-zero exit status 1
05/05/2015 05:48:47 AM: ERROR: /root/ovpl/src/VMManager/LabActionScript.py:52  -> LabActionScript::run() exception is: Command 'sudo apt-get install mysql-server' returned non-zero exit status 1
05/05/2015 05:48:47 AM: ERROR: /root/ovpl/src/VMManager/VMManager.py:118 -> VMManager.test_lab failed: Script sudo apt-get install mysql-server failed
05/05/2015 05:48:47 AM: DEBUG: /root/ovpl/src/LabManager.py:58  -> response = <Response [200]>
05/05/2015 05:48:47 AM: ERROR: /root/ovpl/src/Controller.py:46  -> test_lab(); Test failed with error:Test lab failed

**Comment by GuptaManoj** [comment]
Dear Jayanth,

I am change the labspec.json file of  Virtual Combustain and Automization(
https://github.com/Virtual-Labs/virtual-combustion-and-automization-lab-iitk)
Lab.

Please try Hosting.

Thanks & Regards
Manoj Gupta

**Comment by jayanthsagar** [comment]
Hi Manoj,
we have deployed your lab, you can access lab using http://vcal-iitk.vlabs.ac.in

We have noticed that your lab is not using any database but installing mysql.
please check whether your requires a database and if so, you should update your labspec to configure database which is missing in current deployed state.
