### ISSUE TITLE
Request to join VLEAD membership IIT Kanpur

### ISSUE THREAD

**Issue by govind1790** [Virtual-Labs/engineers-forum#240]
My name is govind from IIT Kanpur, I am new to virtual lab so i need to join the VLEAD 
Email id : govind0190@gmail.com

**Comment by umraodhananjay** [comment]
I am requesting to  Add Govind's ID in IITK Team...

**Comment by govind1790** [comment]
Github handle: govind1790
Repository :  1.https://github.com/Virtual-Labs/virtual-lab-aerospace-engg-iitk
                     2.https://github.com/Virtual-Labs/virtual-combustion-and-automization-lab-iitk
                     3.https://github.com/Virtual-Labs/material-response-to-micro-structural-mechanical-
                     thermal-and-biological-stimuli-iitk
                     4.https://github.com/Virtual-Labs/virtual-astrophysics-lab-iitk
                     5.https://github.com/Virtual-Labs/transducers-and-instrument-vlab-iitk
Access : read and write

**Comment by ayogi** [comment]
Write access are given to "govind1790" for following five repositories:
 1.https://github.com/Virtual-Labs/virtual-lab-aerospace-engg-iitk
2.https://github.com/Virtual-Labs/virtual-combustion-and-automization-lab-iitk
3. https://github.com/Virtual-Labs/material-response-to-micro-structural-mechanical-thermal-and-biological-stimuli-iitk/settings/collaboration
4.https://github.com/Virtual-Labs/virtual-astrophysics-lab-iitk
5.https://github.com/Virtual-Labs/transducers-and-instrument-vlab-iitk

Closing this issue.
