### ISSUE TITLE
Requesting for update the url change _NIT-K

### ISSUE THREAD

**Issue by santhoshnitte87** [Virtual-Labs/engineers-forum#249]
Inside the landing page , we find nit-k labs http://vlabs.ac.in/nit-labs.html  in that list the **Strength of Materials and Fluid Mechanics** lab is redirecting into invalid page. It should redirect into http://sm-nitk.vlabs.ac.in/ page please can you update this url .

it is an  urgent request.

**Comment by santhoshnitte87** [comment]
Please  host the content .. we have a workshop on this...

**Comment by santhoshnitte87** [comment]
Please modify the content .. we have a workshop on this...

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 The request is currently being processed.

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 The requested lab has been updated with the URL on http://vlabs.ac.in. Strength of Materials and Fluid Mechanics lab is redirecting into http://sm-nitk.vlabs.ac.in/ page.
