### ISSUE TITLE
Issue with the ubuntu custom template!

### ISSUE THREAD

**Issue by anhsirksai** [Virtual-Labs/engineers-forum#25]
Expect could not SPAWN the current shell.

expect script spaws a shell while running the below command:
"spawn $env(SHELL)"

Result of executing the command on a normal ubuntu machine:
expect1.1> spawn $env(SHELL)
spawn /bin/bash
183628

Result of running the command on the custom template provided by ovpl:
expect1.1> spawn $env(SHELL)
no such variable
    (read trace on "env(SHELL)")
    invoked from within
"spawn $env(SHELL)"

As a part of the expect script, This is the first command to be executed. Due to this, The script fails to execute. Link to the script.
https://github.com/Virtual-Labs/databases-and-datamining-iiith/blob/master/scripts/create-sage.exp

**Comment by ecthiender** [comment]
Resolved after talking to @anhsirksai
