### ISSUE TITLE
Request to host Dataservice

### ISSUE THREAD

**Issue by madhavipuliraju** [Virtual-Labs/engineers-forum#250]
Dear Team,

Please host the dataservice on Staging
Github url : https://github.com/vlead/dataservice/

We have tested the same on Testing (base4).
Please find the testing URL: http://data.base4.vlabs.ac.in

**Comment by sanchita-dixit** [comment]
@ksripathi Please comment here on the status of the request.

**Comment by ksripathi** [comment]
@madhavipuliraju 
Please don't raise the request on this forum for deploying labs on stagging.
