### ISSUE TITLE
Request for the git link for the chem engg lab

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#252]
wanted the repo link from which the lab below is hosted
http://ce-iitb.vlabs.ac.in

there is problem in the content of this lab,
acroding to me , the source of the content displayed on the above link
" Welcome to the security lab! In this lab, we will do virtual experiments to understand Newton's laws of motion. We will start with a simple pendulum, and from then on, the experiments get more interesting. "
should be the link below.
https://github.com/Virtual-Labs/chemical-engg-iitb/blob/master/src/lab/default.html

However, in the above link the content is 

      <p>Welcome to the Physics lab! In this lab, we will do 
74                         virtual experiments to understand Newton's laws of 
75                         motion. We will start with a simple pendulum, and from 
76                         then on, the experiments get more interesting.</p> 

tried to trace the last update, it was made by Sripathi , I think he added wrong content.
Please help me trace the problem and provide me with the correct link so that I can rectify the issue
![Uploading content.png…]()

**Comment by pushpdeep** [comment]
![content](https://cloud.githubusercontent.com/assets/7886419/12871771/1f58cc06-cdb0-11e5-96b3-6aaf1237e2ef.png)

**Comment by ksripathi** [comment]
@pushpdeep ,
Yes last updates made by me only but that is related to converting UI3.0 to ADS deployable. I didn't change any source code of the lab. Content was changed from the commit made  at https://github.com/Virtual-Labs/chemical-engg-iitb/commit/9e4d5086eb8ea92c4086c4f5e3966badc5d11c4b by @pushpdeep

**Comment by pushpdeep** [comment]
@ksripathi  did you request for re-hosting after committing changes in the src/lab/introduction.html & index.html ? I see some deletions and additions .

**Comment by pushpdeep** [comment]
@ksripathi  alright, ill make necessary changes, then do I need to ask for rehosting again ?

**Comment by ksripathi** [comment]
Yes @pushpdeep  once you are done with changes please raise request for hosting

**Comment by pushpdeep** [comment]
Raised hosting request. thanks
