### ISSUE TITLE
Adding lab to the list from NIT-K Surathkal

### ISSUE THREAD

**Issue by santhoshnitte87** [Virtual-Labs/engineers-forum#258]
This is regarding adding of one more lab into the list of labs from NIT-K Surathkal.
http://vlabs.ac.in/nit-labs.html
here we want to add one more lab called  **Remote Triggered Vibration Lab**  and it has to redirect http://rtlabs.nitk.ac.in/?q=page/vibration-lab

**Comment by santhoshnitte87** [comment]
Can you please update it as soon as possible. We have several workshop on it.

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 This is lab is currently not hosted on production. We cannot add this link on vlabs.ac .in page unless it is hosted on amazon. You need to make a hosting request first, then link updation request.
