### ISSUE TITLE
Hosting request for the updated content of programmable logic controller - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#261]
@sanchita-dixit I have updated the pre test and post test please host this lab.

Link is given below.
https://github.com/Virtual-Labs/programmable-logic-controller-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The requested lab has been re-hosted. Please follow the URL : http://plc-coep.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
@sanchita-dixit Lab is working fine. Thank you.
