### ISSUE TITLE
Hosting request for the updated content of electrical machines - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#263]
@sanchita-dixit I have updated the content and added script for pre test and post test. Please re-host the lab.

link is given below

https://github.com/Virtual-Labs/electrical-machines-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The requested lab has been re-hosted. The pre and post test conditions are working. Please check and verify. Kindly follow the URL : http://em-coep.vlabs.ac.in/
