### ISSUE TITLE
Issue related to ADS setup

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#264]
Kindly help in resolving the issue regarding ADS in Ubuntu 14.04. I have also set the proxies in etc/bash.bashrc as well as etc/apt/apt.conf files.

When i execute bash install_vagrant.sh, i face the error as shown below.

![screenshot from 2016-02-24 11 26 59](https://cloud.githubusercontent.com/assets/11206668/13276935/54ced0fa-daea-11e5-8989-8cd02084e806.png)

**Comment by ksripathi** [comment]
@sumitdahiyavlab 

Please try to install above mentioned dependencies and execute "sudo apt-get -f install" command

**Comment by sumitdahiyavlab** [comment]
@ksripathi Ok. I will try it.

**Comment by sumitdahiyavlab** [comment]
@ksripathi I have done the above steps. Now the following error is coming. Please suggest some solution.

![screenshot from 2016-03-01 10 04 53](https://cloud.githubusercontent.com/assets/11206668/13417845/775aadf6-df95-11e5-9c2a-93a76433bcf1.png)

**Comment by sumitdahiyavlab** [comment]
For setting up ADS, should i refer to both repositories ovpl and setup-ovpl-centos ? or Could it be done by only referring setup-ovpl-centos repository ?

**Comment by ksripathi** [comment]
For setting up ADS you need to refer to setup-ovpl-centos repository. To
run ADS refer to ovpl repository.
Fine,
Coming to solution for your problem, I advise not to use vagrant to run ADS
instead use CentOS as base machine and follow the setup-ovpl-centos
instructions to configure centos

**Comment by sumitdahiyavlab** [comment]
@ksripathi Ok. Thank you.
