### ISSUE TITLE
Requet to re-host the Strength of Materials Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#265]
Dear system team,

Please re-host the Basic Engineering Mechanics and Strength of Materials Lab. In this lab, some of the flash simulations are not working so, we have masked those simulations and updated the lab with complete sources.

Here is the git-hub URL:
https://github.com/Virtual-Labs/basic-engineering-mechanics-and-strength-of-materials-iiith.git

Please make sure we don't loose the analytics of  Basic Engineering Mechanics and Strength of Materials Lab. Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The requested lab has been re-hosted. Please follow the URL : http://eerc01-iiith.vlabs.ac.in
