### ISSUE TITLE
Request to re-host Physical-Chemistry-Lab-iiith

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#266]
Dear system team,

Please re-host the Physical Chemistry Lab. In this lab, experiments which are not working are been listed under upcoming experiments list and updated the lab with complete sources.

Here is the git-hub URL :
https://github.com/Virtual-Labs/physical-chemistry-iiith.git

Please make sure we don't loose the analytics of Physical Chemistry Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sadhanareddy the requested lab has been re-hosted. None of analytics have been lost. Please follow the URL : http://ccnsb06-iiith.vlabs.ac.in/

**Comment by sadhanareddy** [comment]
As the changes are not reflected, please re-host the lab again.

https://github.com/Virtual-Labs/physical-chemistry-iiith.git

**Comment by sanchita-dixit** [comment]
@sadhanareddy I re-hosted the lab again, still the changes are not reflected. Please go through the code to resolve any issues there.

**Comment by sadhanareddy** [comment]
Please re-host the lab following is the url of the lab:

https://github.com/Virtual-Labs/physical-chemistry-iiith.git

**Comment by sanchita-dixit** [comment]
@sadhanareddy The lab has been re-hosted. Please follow the URL : http://ccnsb06-iiith.vlabs.ac.in/
