### ISSUE TITLE
Request to re-host basic-structural-analysis-iiith

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#267]
Dear system team,

Please re-host the Basic Structural Analysis Lab. In this lab, flash experiments( 7,8, 10) are been masked, since they are under progress and updated the lab with complete sources.

Here is the git-hub URL :
https://github.com/Virtual-Labs/basic-structural-analysis-iiith.git

Please make sure we don't loose the analytics of Basic Structural Analysis  Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sadhanareddy The requested lab has been re-hosted. Please follow the URL : http://bsa-iiith.virtual-labs.ac.in/
