### ISSUE TITLE
Request to re-host soil-mechanics-and-foundation-engineering-iiith

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#268]
Dear system team,

Please re-host the soil-mechanics-and-foundation-engineering-iiith Lab. In this lab, flash experiment(5) is been masked, since it is under progress and updated the lab with complete sources.

Here is the git-hub URL :
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith.git

Please make sure we don't loose the analytics of  soil-mechanics-and-foundation-engineering-iiith Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sadhanareddy The requested lab has been re-hosted with no loss in analytics. Please follow the URL to access it : http://smfe-iiith.vlabs.ac.in/
