### ISSUE TITLE
Request to re-host Hydraulics and Fluid Mechanics lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#269]
Dear system team,

Please re-host the Hydraulics and Fluid Mechanics Lab. In this lab, some of the flash simulations are not working so, we have masked those simulations and updated the lab with complete sources.

Here is the git-hub URL:
https://github.com/Virtual-Labs/hydraulics-and-fluid-mechanics-iiith.git

Please make sure we don't loose the analytics of Hydraulics and Fluid Mechanics Lab. Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The requested lab has been re-hosted. Kindly follow the given URL to access it : http://eerc03-iiith.virtual-labs.ac.in/
