### ISSUE TITLE
Request to re-host artificial-neural-networks-iiith

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#270]
Dear system team,

Please re-host the artificial-neural-networks Lab. In this lab, experiments which are not working are been listed under upcoming experiments list and updated the lab with complete sources.

Here is the git-hub URL :
https://github.com/Virtual-Labs/artificial-neural-networks-iiith.git

Please make sure we don't loose the analytics of artificial-neural-networks-iiith Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sadhanareddy The lab is re-hosted with all the analytics intact. Kindly follow the URL : http://cse22-iiith.vlabs.ac.in/
