### ISSUE TITLE
Request to re-host molecular-interactions-iiith

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#271]
Dear system team,

Please re-host the Lab. In this lab, experiments, which are not working are been listed under upcoming experiments list and masked the simulation link of experiment one and updated the lab with complete sources.

Here is the git-hub URL :
https://github.com/Virtual-Labs/molecular-interactions-iiith.git

Please make sure we don't loose the analytics of molecular-interactions-iiith Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sadhanareddy The lab has been re-hosted. Please follow the URL : http://mi-iiith.vlabs.ac.in/
