### ISSUE TITLE
Request to re-host Geotechnical Engineeering Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#272]
Dear system team,

Please re-host the Geotechnical Engineering Lab. In this lab, some of the Java3D simulations are not working so, we have masked those simulations and updated the lab with complete sources.

Here is the git-hub URL:
https://github.com/Virtual-Labs/geotechnical-engineering-lab-iiith.git

Please make sure we don't loose the analytics of Geotechnical Engineering Lab. Once done with the hosting process, please share the URL.

**Comment by khushpreet-kaur** [comment]
What is the status of this lab?

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The requested lab has been re-hosted. Please follow the URL : http://ge-iiith.vlabs.ac.in/
