### ISSUE TITLE
Request to host "vlab-web-pages" 

### ISSUE THREAD

**Issue by madhavipuliraju** [Virtual-Labs/engineers-forum#273]
Dear Systems team,

Please host the vlab-web-pages
Link to github url: https://github.com/vlead/vlab-web-pages

Please host this as soon as possible because we need this for the R&D showcase.

**Comment by sanchita-dixit** [comment]
@madhavipuliraju The vlab-web-pages have been hosted. Please follow the URL : http://vlabs.ac.in
