### ISSUE TITLE
Issue regarding the unavailability of vibration and acoustics lab - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#274]
We are unable to load the lab from vlabs.ac.in portal.  We got report from Delhi that it is not working. Kindly please someone should take responsibility and take a look on this. And solve the problem ASAP. 
It just display a blank page.Refer the following image. People are waiting to use this.

![screenshot from 2016-02-29 16 01 14](https://cloud.githubusercontent.com/assets/8788705/13392019/c4212a7c-defd-11e5-8b2e-0988d1e22384.png)

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab is working now. Please check and verify. You can follow the URL : http://va-coep.vlabs.ac.in/
