### ISSUE TITLE
Revoke Access of Vikas Kashyap

### ISSUE THREAD

**Issue by chetandhiman** [Virtual-Labs/engineers-forum#277]
Please revoke access of @vikas-kashyap (Vikas Kashyap) from virtual-labs repo & IITR team on github.
As he has left virtual labs IIT Roorkee effective immediately as of Mar 1, 2016.

**Comment by sanchita-dixit** [comment]
@chetandhiman : Access of Vikas Kashyap has been revoked from Virtual-labs organisation in GitHub and also from IITR team.
