### ISSUE TITLE
Request to re-host lab from NITK

### ISSUE THREAD

**Issue by santhoshnitte87** [Virtual-Labs/engineers-forum#278]
We have updated the contents of **Strength-of-Materials-Labs**  https://github.com/Virtual-Labs/strength-of-materials-nitk can you please host it to the server.

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 The lab has been hosted. You can follow the URL : http://sm-nitk.vlabs.ac.in to access it.

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 Please close this issue if it is resolved completely.
