### ISSUE TITLE
Problems with OVPL while using HTTPS URLs for lab repository

### ISSUE THREAD

**Issue by sruthimangala** [Virtual-Labs/engineers-forum#28]
To access a git repository from container, We need to edit the config file of git inside the container  using a command (git config --global http.sslverify false) just after the git is installed in the container using ovpl.

How to do this?

**Comment by AmulyaSri** [comment]
I didn't get your question. Do you want to manually enter the container ? or using OVPL ? 
Manually you can do,
$ vzctl enter container_id

**Comment by sruthimangala** [comment]
When we use OVPL to deploy a lab, the container (say 101) created using ovpl will have to access git repo rite...

In our university network, we have an security certificate issue, so that this container can not access git repo by default.

For this container to access a git repo, we need to provide the following command to bypass certificate "git config --global http.sslverify false".

Manually we are able to do this.

But when using OVPL, where these steps are automated, after creating container and git is installed, we need to run this command. 

How to do this?

**Comment by ecthiender** [comment]
One workaround I can think of is to use a git protocol-ed URL instead of
the default https URL.

So for the computer-programming-iith repo it will be: git://
github.com/Virtual-Labs/computer-programming-iiith.git

**Comment by ecthiender** [comment]
So when you paste the URL in the OVPL's test lab page, paste the git
protocol URL and try.

**Comment by sanchita-dixit** [comment]
@sruthimangala Was this issue resolved? 
If yes kindly close the issue.

**Comment by sanchita-dixit** [comment]
@sruthimangala As there is no longer any reply from the creator of this issue, I am thereby closing this issue.
