### ISSUE TITLE
Adding lab link to the list of experiment from NIT-K Surathkal

### ISSUE THREAD

**Issue by santhoshnitte87** [Virtual-Labs/engineers-forum#280]
This is regarding adding link to the list of experiment in http://vlabs.ac.in/civil-engineering-labs.html 
here i can see in list 

**Strength of Materials and Fluid Mechanics** - **NIT KARNATAKA**

but it is not linking the particular web link , I am requesting you to update this link to redirect(link)  http://sm-nitk.vlabs.ac.in/ .

**Comment by sanchita-dixit** [comment]
The link has been updated for Strength of Materials and Fluid Mechanics lab. Now the link is redirecting correctly to http://sm-nitk.vlabs.ac.in/. Please follow the URL :  http://vlabs.ac.in/civil-engineering-labs.html to verify the same.

**Comment by santhoshnitte87** [comment]
I have checked, it is not redirecting.. i have selected the lab to be redirect in the below picture.

![vlabz](https://cloud.githubusercontent.com/assets/13462722/13735695/b0954224-e9d2-11e5-8db2-7ea026b529c0.png)

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 There is a slight mistake from our side while updation of links for the requested lab due to same names of 2 labs. I would rectify it and let you know as soon as possible.

**Comment by santhoshnitte87** [comment]
@sanchita-dixit  can you resolve this problem as soon as possible, because we have review in two days.

**Comment by sanchita-dixit** [comment]
@santoshnitte87 Please understand that we are preoccupied with the April 9th Delhi meeting deadlines. This would definitely get resolved after 2 days. Apologies for the delay.

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 The link has been updated correctly. You can verify the same using the link : http://vlabs.ac.in/civil-engineering-labs.html
