### ISSUE TITLE
Hosting request for the updated content of electrical machines - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#281]
@sanchita-dixit Re-host the electrical machines lab again. I have made changed in the content of the lab experiments.

link is given below
https://github.com/Virtual-Labs/electrical-machines-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab has been re-hosted. Kindly follow the URL : http://em-coep.vlabs.ac.in
