### ISSUE TITLE
Hosting request for the updated content of programmable logic controller - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#282]
@sanchita-dixit Re-host programmable logic controller lab. I have modified the contents.
Link is given below

https://github.com/Virtual-Labs/programmable-logic-controller-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab has been re-hosted. Kindly follow the URL : http://plc-coep.vlabs.ac.in
