### ISSUE TITLE
Hosting request for the updated content of Sensor Lab - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#286]
@sanchita-dixit I have updated the content of sensor lab. Kindly re-host the lab.

link is given below
https://github.com/Virtual-Labs/sensor-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab has been re-hosted. Kindly follow the URL : http://sl-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
@sanchita-dixit lab is working fine.
