### ISSUE TITLE
Hosting request for the updated content of Fab Lab - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#287]
@sanchita-dixit I have updated content of the fab lab. Re-host the lab again.

link is given below
https://github.com/Virtual-Labs/fab-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab has been re-hosted. Please follow the URL http://fab-coep.vlabs.ac.in to access it.

**Comment by sushilmedhe** [comment]
@sanchita-dixit lab is working fine.
