### ISSUE TITLE
Hosting request for the updated content of "Aerospace Virtual Laboratory" Lab 

### ISSUE THREAD

**Issue by umraodhananjay** [Virtual-Labs/engineers-forum#288]
I have updated content of the  lab. Re-host the "Aerospace Virtual Laboratory"  lab again.

link is given below

https://github.com/Virtual-Labs/virtual-lab-aerospace-engg-iitk

Thanks

**Comment by sanchita-dixit** [comment]
@umraodhananjay The requested lab has been re-hosted. Please follow the URL : http://vlae-iitk.vlabs.ac.in

**Comment by sanchita-dixit** [comment]
@umraodhananjay Please check whether the re-hosted lab is working as per expectations and close this issue.

**Comment by umraodhananjay** [comment]
ok , Thanks
