### ISSUE TITLE
Convert UI and file structure of experiment in Hybrid lab - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#290]
Hi, 
We have added a new experiment in hybrid lab called Exp8. I need to update this experiment with new format. It contains only content.html file where we want it in theory, procedure files format. Different file for different menu. I request you to please do the required changes so I can add this experiment in the lab and in list of experiments also.

**Comment by BSravanthi** [comment]
@sushilmedhe Please share the git hub  URL for the sources of the lab.

**Comment by sushilmedhe** [comment]
@BSravanthi link is given below. experiment 8 should be modified.

https://github.com/Virtual-Labs/hybrid-electronics-lab-coep

**Comment by sanchita-dixit** [comment]
@BSravanthi Any updates on this ?

**Comment by khushpreet-kaur** [comment]
@sushilmedhe  We are not suppose to edit your labs(COEP labs) code as per process. You have to update you lab's sources on your own. we can guide/help you out if you face any difficulty.

**Comment by sushilmedhe** [comment]
@sanchita-dixit I have modified the structure for the experiment. I hope it must be proper. Can you please host the lab so I can check and make changes if required.

Link is given below.
https://github.com/Virtual-Labs/hybrid-electronics-lab-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab has been re-hosted. I have verified the changes and the new experiment added is showing properly. Please verify once. U can follow the URL : http://he-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
@sanchita-dixit  Some little changes was there which I have changed now. Can you please re-host the lab again.

**Comment by sanchita-dixit** [comment]
@sushilmedhe Please test all the changes which you make to the sources of a lab on the local ADS setup on your machine before making hosting requests. For every little change, it is very inappropriate to request for re-hosting everytime in such short span of timeline. You need to provide release-notes from now on for every hosting/re-hosting request of a lab in the required format.

**Comment by sushilmedhe** [comment]
@sanchita-dixit I requested much time to sort out my local machine ADS problem. I am able to give incredential for remote access. I am not able to check lab manually without this setup. How can I check the lab then? 

I have check all the required  changed in the lab now and sorted out too.

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab is re-hosted. Please follow the URL : http://he-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
@sanchita-dixit It is working fine. Thank you.
