### ISSUE TITLE
Need help in setting up the ADS on local machine - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#292]
I need help to run ADS on my local machine to run the fpga lab. I am trying to run the ADS on centos machine. I have configured files. It allow me to verify with persona when we run make file. It ask for lab link and all 3 fields. I gave link to the ADS and clicked on submit button. It display error message. 

I am having screenshots for the same. Check it out and tell me the solution what is the problem with it.

![screenshot](https://cloud.githubusercontent.com/assets/8788705/13915394/7c7901bc-ef7a-11e5-973a-70a25a9af812.png)

![screenshot-1](https://cloud.githubusercontent.com/assets/8788705/13915303/e4d7986e-ef79-11e5-9e4e-669a49ed223e.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/8788705/13915302/e4d65ca6-ef79-11e5-9f91-8b81ad38612e.png)

**Comment by sushilmedhe** [comment]
@ksripathi Have you check the ADS problem which I am having. I want to setup the ADS. And check the lab.

**Comment by ksripathi** [comment]
Hello @sushilmedhe ,
By looking at screeshot it seems Mongodb is not running on your machine or either your not configured properly. Please check status of mongodb server.

**Comment by sushilmedhe** [comment]
@ksripathi I have check the mongod service. It was stopped. now I have started service. Still it is having different error now. Refer the following screenshot.

![screenshot-3](https://cloud.githubusercontent.com/assets/8788705/14075524/7c1761d2-f4f7-11e5-8cbb-6834790aae67.png)

**Comment by ksripathi** [comment]
Please remove lab directory from /root/labs/labname, in your case execute
following commad

*rm -rf /root/labs/<yourlabreponame>*
 and try to deploy same again it should work.

**Comment by sushilmedhe** [comment]
@ksripathi I have removed the repo from lab directory. Still having following error. refer the image below.

![screenshot-5](https://cloud.githubusercontent.com/assets/8788705/14098716/61862268-f59c-11e5-93f4-a380a292d4d5.png)

**Comment by sushilmedhe** [comment]
@ksripathi Have you got the issue in above referred image? What is going wrong??

**Comment by ksripathi** [comment]
@sushilmedhe ,
If you are network is using proxy server please mention http and https proxies in ADS configuration files. If there is no proxy at your network. Please firstly, try to clone lab manually whether you are able to clone or not , if its works it should also work using ADS.

**Comment by sushilmedhe** [comment]
@ksripathi  we dont have proxy to the respective network connection where I am using ADS. I have tried to clone the lab manually first time cloning was successful but at second attempt for another lab it is not working. It display "fatal : http request failed" as you can see in image.

**Comment by sushilmedhe** [comment]
@ksripathi  You can refer this image below. When I use to clone the lab without 
 root it works fine and when I use root to clone the lab. It shows http request failed.

![screenshot](https://cloud.githubusercontent.com/assets/8788705/14166535/f7d8b924-f731-11e5-95ec-127e559174f4.png)

**Comment by ksripathi** [comment]
Hello @sushilmedhe 
That is the issue with internet, and please note that whenever you are trying to deploy the lab using ADS your /root/labs shouldn't contain lab-repo-folder you should remove that otherwise ADS will through an error.
If this doesn't work please share your system credentials so that I can remotely connect and help you in setting up ADS on your machine.

**Comment by sushilmedhe** [comment]
@ksripathi I had removed the lab from lab repo. I am having problem with the root login and without root login authentication to clone the lab. As I have referred previous image. If I used to clone using root login it through error and if I clone without root login it clone the lab properly.

**Comment by sushilmedhe** [comment]
@ksripathi  I have tried to solve the problem with clone using root account. Now it is working. but having problem with something called process error. check out the following screen-shot.
![screenshot](https://cloud.githubusercontent.com/assets/8788705/14423172/f8f84e2c-fff7-11e5-9371-dad614a80de3.png)

**Comment by ksripathi** [comment]
@sushilmedhe 
It seems you have mentioned **mm-coep** as a tag while deploying lab. ADS will use this as a branch name of your lab. I hope there is no branch exists with mentioned name. Please let me know if I am wrong.
leave tag as empty feild so that it will pickup master branch as default

**Comment by sushilmedhe** [comment]
@ksripathi  Yes I had used Lab ID and Tag as mm-coep. I will check again with empty tag name. And will let you know the result. Thank you.

**Comment by sushilmedhe** [comment]
@ksripathi I have check the lab with empty tag it creates vm container now. but having following error with test fail. refer the following screen shot.

![screenshot](https://cloud.githubusercontent.com/assets/8788705/14452177/774c84a2-00aa-11e6-9f4b-b747f92fc704.png)

**Comment by ksripathi** [comment]
Please ensure that your mongodb service is running.

**Comment by sushilmedhe** [comment]
Yes mongod service is running.

**Comment by sushilmedhe** [comment]
Can I get any update on this??? It has been last 6 days I have commented but no reply and no answer from anyone.

**Comment by ksripathi** [comment]
@sushilmedhe 
Sorry for the late reply as we were in busy with other deadlines I couldn't check issues.Ok
It is been log discussion answering for all your issues. Rather i suggest  to solve all ADS issues remotely by sharing team viewer credentials i have asked the same couple of times could please share your credentials over msg or by email.

**Comment by ksripathi** [comment]
@sushilmedhe ,

Could please try to execute the same command "sudo apt-get install -y apache2" on created container. And let me know the status

**Comment by sushilmedhe** [comment]
@ksripathi OK. I will try this command once. If it will not work will send you incredentials on gmail hangout or by mail.

**Comment by sushilmedhe** [comment]
@ksripathi I have tried the above command. Refer the following image.

![screenshot-2](https://cloud.githubusercontent.com/assets/8788705/14598453/e36aaa32-056f-11e6-81c6-2664abfc6dfb.png)

**Comment by ksripathi** [comment]
@sushilmedhe 
Execute the command on created container (ubuntu ) not on your base machine. I hope you are using ubuntu template to create containers

**Comment by sushilmedhe** [comment]
@ksripathi You mean I have to enter in respective lab vz container and execute this command.. right??

**Comment by ksripathi** [comment]
Yes, but I suggest, Please deploy your lab manually by creating container
and execute all the labspec steps on container then we can go head with
deployment using ADS. I hope you are following same??

**Comment by sushilmedhe** [comment]
@ksripathi I was following the deployment steps which you people have shown to us in Guwahati workshop. by ovpl make file. I don't know how to create container manually and at which location.

**Comment by sushilmedhe** [comment]
@ksripathi @sanchita-dixit  can you please take remote access of my machine and check out the  problem once. I am not able to do it manually.

**Comment by sushilmedhe** [comment]
@ksripathi I am still waiting for response.

**Comment by sanchita-dixit** [comment]
@sushilmedhe We will get back to you in some time.

**Comment by sushilmedhe** [comment]
@ksripathi This is the screenshot for ovpl.log file.

![screenshot-3](https://cloud.githubusercontent.com/assets/8788705/14807506/c179cf58-0b9a-11e6-8ee6-97ef2392591f.png)

**Comment by ksripathi** [comment]
@sushilmedhe 
I am looking into all your ADS issues in detail  today and i will follow up you over phone call.

**Comment by sushilmedhe** [comment]
@ksripathi Ok. No problem.

**Comment by ksripathi** [comment]
Please execute the command "service iptables restart" on centos machine(base  machine)

**Comment by sushilmedhe** [comment]
@ksripathi Thank you ksripathi. It is working fine. I thing for the last error it was firewall problem.

**Comment by ksripathi** [comment]
@sushilmedhe 
Your welcome please alway do post your log file contents if any errors in ADS so that for us it easy to debug.

**Comment by sushilmedhe** [comment]
@ksripathi ok. I will do it from next time if required.
