### ISSUE TITLE
Request to host Outreach Portal V2.0.5 on production

### ISSUE THREAD

**Issue by madhavipuliraju** [Virtual-Labs/engineers-forum#293]
Dear Systems Team,

Please host the Outreach Portal V2.0.5 on production:
Github url : https://github.com/vlead/outreach-portal

We have tested the same on Staging (base1).

Please find the testing URL:  http://outreach-develop-test1.base1.virtual-labs.ac.in/

**Comment by sanchita-dixit** [comment]
@madhavipuliraju Is this request still valid? If not please close this issue. I suppose this hosting is already been done.
