### ISSUE TITLE
Issue while generating test report

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#294]
I first clone the repository export-csv-data-to-org and when I try to run the python script from the src folder to generate the test report, I am getting an error. The error is attached below
root@hrishikesh-
![screenshot from 2016-03-30 14 36 34](https://cloud.githubusercontent.com/assets/8788700/14137292/dd7182bc-f684-11e5-89cf-2ddb5cc739a7.png)
HP-EliteDesk-800-G1-SFF:/home/hrishikesh/Desktop/LAB/export-csv-data-to-org/src# python testreport.py '/home/hrishikesh/Desktop/LAB/digital-vlsi-design-iitg/' '/home/hrishikesh/Desktop/'
Traceback (most recent call last):
  File "testreport.py", line 160, in <module>
    main(sys.argv)
  File "testreport.py", line 40, in main
    walk_over_path(path, targetDir)
  File "testreport.py", line 68, in walk_over_path
    createTestReport(projectName, gitLabUrl, allTestCasesLink, targetDir)
UnboundLocalError: local variable 'gitLabUrl' referenced before assignment
root@hrishikesh-HP-EliteDesk-800-G1-SFF:/home/hrishikesh/Desktop/LAB/export-csv-data-to-org/src#

**Comment by ayogi** [comment]
The problem is due to the structure of the source folder is not as per the assumptions of the script.
You can refer "README_testreport.txt" file after doing git pull. 

You will have to structure the source folder should contain "/Test Cases/Integration Test Cases/" folders. Inside this folder individual experiment folder will exist with test cases. 

Once the source folder is properly structured then you the script should run without any error.

If you face any error after performing this, please again post it here.

**Comment by bijudas45** [comment]
I have individual experiment folders in test cases. I am unable to figure out the error. I am sending the link of the repository for which I have designed the test cases. Please look into the repository and tell me the error.
https://github.com/Virtual-Labs/digital-vlsi-design-iitg

**Comment by varshanihanth** [comment]
@bijudas45 , modify the "Test Cases" to test-cases and run the script again.I'd tried it and it's working

Please let me know if you face any issues

**Comment by bijudas45** [comment]
Thanks, I have modified the test-cases and now I am able to run the script. But I am facing problem after this step. when I try to run the statistics, then I am facing a problem which is attached below
![screenshot from 2016-03-31 13 21 43](https://cloud.githubusercontent.com/assets/8788700/14169640/980633cc-f746-11e5-9c46-442dcd83762f.png)
Also when I click on  the link " View Test Reports for digital-vlsi-design-iitg Lab", I am getting a 404 error. 
please send me the steps what needed to be done after modifying the test report in emacs.

**Comment by bijudas45** [comment]
I have pushed my lab in github, the link of which is given below:
https://github.com/Virtual-Labs/digital-vlsi-design-iitg

**Comment by varshanihanth** [comment]
@bijudas45 ,Place your test report in the lab folder which consists of test-cases in org format and run the script
Kindly see the below screen shot

Please let me know if you face any issues

![dvd iitg](https://cloud.githubusercontent.com/assets/14229099/14170112/668a0744-f749-11e5-805f-31aeb80a2923.png)

**Comment by bijudas45** [comment]
I am still getting the same error. I have one folder named "31-3-2016_4ca51ed40d01c13770c04f32f971e5c9446600fc" in git hub where the actual  testreport.org is present. what should be done with this folder because when i compared it with the problem solving lab of IIITH, I did not find any such folder. Also when i open the testreport.org file and click on the " View Test Reports for digital-vlsi-design-iitg Lab" link, i got error 404 the screenshot of which is pasted below.
Please provide me the steps to nullify the error.
![screenshot from 2016-03-31 16 10 32](https://cloud.githubusercontent.com/assets/8788700/14173374/264b3a10-f75b-11e5-917f-337eb369d824.png)

**Comment by ayogi** [comment]
@bijudas45 : We are busy with other deadlines right now. We will get back to you on this later.
