### ISSUE TITLE
Request for Hosting Digital VLSI Design Lab IITG

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#295]
I have updated content of the lab.Please host the Digital VLSI Design Lab of IITG.

The link is given below

https://github.com/Virtual-Labs/digital-vlsi-design-iitg

**Comment by bijudas45** [comment]
Please host this lab as soon as possible as it will be required for the 9th April meeting

**Comment by sanchita-dixit** [comment]
@bijudas45 The requested lab has been hosted. Please follow the URL : http://vlsi-iitg.vlabs.ac.in
