### ISSUE TITLE
Request to host Electronic Instrumentation Lab IITG

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#296]
I have updated content of the lab.Please host the Electronic Instrumentation Lab of IITG.

The link is given below

https://github.com/Virtual-Labs/electronic-instrumentation-laboratory-iitg

**Comment by bijudas45** [comment]
Please host this lab as soon as possible as it will be required for the 9th April meeting

**Comment by sanchita-dixit** [comment]
@bijudas45 The requested lab has been hosted. Please follow the URL : http://eil-iitg.vlabs.ac.in
