### ISSUE TITLE
Problem with the internet access while using terminal on centos - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#297]
I have installed virtual box on my machine which is having **proxy** setting. I have installed Ubuntu 14.04 and centos 6 on virtual box. I have configured the **proxy** setting to both of the environment. When I browse anything on internet on browser with **proxy** setting it works fine. 

But when I export same proxy on terminal and use to ping google.com it won't reply. I am trying to **build ADS environment** on this centos. So I am having problem with the terminal. Help me out in this issue.

**Comment by ashay-maheshwari** [comment]
@sushilmedhe 

An elaborate information about the issue can help us to resolve the issue. Please answer the following -
1. Which browser you are using ?
2. Output of command "set | grep proxy"
3. This can/cannot be the problem, but can you ping Google's IP instead of domain name. If by chance you can ping Google's IP then its /etc/resolv.conf which needs a fix.

Please attach snapshots of problem and let us know.

**Comment by sushilmedhe** [comment]
I am using mozilla firefox on virtual machine centos.
For the output of grep proxy it display the proxy which I use for my machine.
If I use to ping google by domain name it wont reply and if I use IP of google it also wont able to reply.

**Comment by ashay-maheshwari** [comment]
@sushilmedhe 
Facing this problem for the first time. Firewall can play a role in this. It might be allowing http request but blocking ICMP echo request/reply.

Can we check the same turning off your firewall ?

You can also visit [https://www.google.co.in/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=I+can+access+google+in+browser+but+cant+ping+it+on+terminal]

You will get solutions which you can try and depending on the problem related to your case, we can come up to the solution.

**Comment by sushilmedhe** [comment]
We are not using firewall. and I have tried the google. but I wont get any proper solution.

**Comment by ashay-maheshwari** [comment]
Which OS you are using as a host machine(Os on which Virtual box is installed) ? If it is windows then check the following -


1. Check if you can ping from windows cmd
2. Check if proxy settings are configured in Internet Explorer
3. If ping works then fire "tracert google.com"

Share the out put of these commands if possible.

Also check what adapters are used(NAT, Bridge) while creating VM in Virtual box

**Comment by sushilmedhe** [comment]
I have check windows cmd. It wont ping the request. proxy is configured in internet explorer. I have tried tracert cmd it goes to gateway. but It can not cross the gateway.

**Comment by ashay-maheshwari** [comment]
With following information -

1. Host OS - Windows
2. Virtual box installed on windows is running Two VMs - Centos and Ubuntu 
3. Proxy settings are configured in Internet Explorer in host windows machine.
4. Proxy settings are configured in Centos and Ubuntu.
5. You can access internet from any browser on Windows.
6. You can access internet from any browser in VM (if VM is desktop version)
7. You cannot ping google.com from windows CMD and also from terminal of both VMs.
8. You can ping your gateway from Windows cmd and also from terminal of both VMs
9. traceroute is reaching gateway in Windows and in VMs.

If all the above scenarios are true in your case, the only thing I can suspect is that your gateway is dropping your ICMP echo/request reply packets and allowing http and https (port 80 and 443).
Should contact your local System admin for this.
