### ISSUE TITLE
Need to re-host Computer Programming Lab

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#299]
Please re-host computer Programming Lab. 
link to repo: https://github.com/Virtual-Labs/computer-programming-responsive-iiith.git 

Please do this as soon as possible as this lab has been selected for demo.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur Computer Programming Lab has been re-hosted. Please follow the URL : http://cse02-iiith.vlabs.ac.in/

**Comment by vlabiitd** [comment]
hello

please delete or unsubscribe my mail id from vlead-integration
team.because. i resigned from virtual lab team of IIT Delhi.

Thanks
bhairab

**Comment by sanchita-dixit** [comment]
@vlabiitd You have been removed from the integrators team and also removed from Virtual-Labs organisation in Github. You will no longer be subscribed to any repository and would not receive any email notifications from now onwards.
