### ISSUE TITLE
Two labs were not accessible.

### ISSUE THREAD

**Issue by mzs-vlabs** [Virtual-Labs/engineers-forum#3]
Sanjeet Kumar reported that two labs were not accessible.
One was computer programming, the other was data structures.

Resolution: 
I checked whether the labs were opening using the URLs, they were accessible.
There were no issues with the labs.

http://ds.virtual-labs.ac.in/
http://cpl.virtual-labs.ac.in/

Note: These labs have been migrated to Amazon now, please change the URLs pointing on Amrita's vlab.co.in to the new location approriately or redirect them from the DC hosted machines

**Comment by ecthiender** [comment]
Isn't this related to #11 ?

**Comment by mzs-vlabs** [comment]
No, this was when this user browsed on vlab.co.in from outside and when we had the power outage.

The URLs on vlab.co.in are still pointing to the IIIT-H servers which were down for sometime.
We either have to change the URLs on vlab.co.in or redirect them after the request reaches IIIT-H servers.

On Thirumal's suggestion we planned to redirect it, but the configuration is very convluted(which was not necessary) and I could not fix it immediately. We need to plan, test and make sure it works, this might take a sprint.
This is one among the maintenance items in the to do list of systems.

**Comment by ecthiender** [comment]
Oh okay. Thanks for the clarification.

**Comment by AmulyaSri** [comment]
Labs are accessible.
