### ISSUE TITLE
Replacing the html page to PHP pages

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#30]
Can i replace the content.html pages with content.php pages in the experiment.

**Comment by soujanya123** [comment]
You should not do that because content.html is part of ui template1.0, it comes entirely as a framework. You just have to edit/add your content.

**Comment by radheshanand** [comment]
Hi,

You can use content.html to redirect to content.php, I agree it's an extra
step,but it's best to follow and universal structure/template.

A sample code for redirect is as below:
 <meta http-equiv="refresh" content="5; URL=content.php">

Regards,
Radhesh.

**Comment by soujanya123** [comment]
Shivakumar, try the above procedure and let us know if it resolves.

**Comment by sranjanagi** [comment]
Sure I will tell. If it resolves.

**Comment by AmulyaSri** [comment]
Issue was resolved by redirecting to content.php.
