### ISSUE TITLE
Request to host Vlabs Landing page V1.7 on production

### ISSUE THREAD

**Issue by madhavipuliraju** [Virtual-Labs/engineers-forum#300]
Dear Systems Team,

Please host the Vlabs Landing page V1.7 on production:
Github url : https://github.com/vlead/vlab-web-pages

We have tested the same on Staging (base1).

Please find the testing URL:  http://landingpage.base1.vlabs.ac.in

**Comment by sanchita-dixit** [comment]
@madhavipuliraju The vlabs landing page V1.7 has been hosted on production. Please follow the URL : http://vlabs.ac.in
