### ISSUE TITLE
Request to host Feedback Portal V1.1 on production

### ISSUE THREAD

**Issue by madhavipuliraju** [Virtual-Labs/engineers-forum#301]
Dear Systems Team,

Please host the Feedback Portal V1.1 on production:
Github url : https://github.com/vlead/feedback-portal

We have tested the same on Staging (base1).

Please find the testing URL:  http://feedback-portal.base1.vlabs.ac.in

**Comment by ayogi** [comment]
@madhavipuliraju Latest changes are applied in the portal hosted on production.

**Comment by madhavipuliraju** [comment]
Thanks yogesh.

Regards,
Madhavi
