### ISSUE TITLE
Issue related to ADS

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#303]
Dear VLEAD Team,

I have setup ADS in Centos 6.5. I am facing some problem in running it. Please help.
I have attached the screen-shots below showing terminal and base_config.py file respectively.

![screenshot-1](https://cloud.githubusercontent.com/assets/11206668/14375580/f581236a-fd7f-11e5-9711-0ae138c1ad14.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/11206668/14375582/fad3c0d4-fd7f-11e5-811b-59cfc597e9bf.png)

Regards,
Sumit Dahiya

**Comment by ksripathi** [comment]
@sumitdahiyavlab 
Sorry for the late action, and could you please let us know which version of ADS that you are running. It seems you are trying to run "make" but in since last two releases ADS don't support  "make" command to run service instead it supports "./manage_services start" command any how please first let us know ADS version that you are running so that I will guide you accordingly.

**Comment by sumitdahiyavlab** [comment]
Thanks @ksripathi for your reply. I checked the version of ADS in index.org file in OVPL directory. I think my ADS version is v1.0.2. I also attached excerpts of index.org below. 

#+TITLE: Design of ADS and related services
#+Author: VLEAD
#+Date: [2015-03-20 Fri]

* Introduction

* Requirements
** For release v1.0.2
  1. ADS, when deployed on a machine (VM/container) creates containers on a
     specified machine running centos 6.6 and openVZ kernel 2.6.32-042stab103.6

  2. ADS, when deployed on a machine (VM/container) starts the =VMManager=
     service on port =9089= on the newly created containers.

**Comment by ksripathi** [comment]
@sumitdahiyavlab 
It seems in your base_config.py settings SUBNET and BASE_IP_ADDRESS are invalid. Please validate them. Please share your contact details or call me over phone call so that I can guide you in better way.

**Comment by sumitdahiyavlab** [comment]
Hi @ksripathi ,

My contact no is 9813429057. I would call you in the coming week regarding this issue.

With regard to base_config.py settings, I found the BASE_IP_ADDRESS by ifconfig command but i am not sure about SUBNET address. I use Ethernet LAN cable for internet connectivity with proxy settings.
