### ISSUE TITLE
Request t o re-host Pattern Recognition Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#307]
Dear system team,

Please re-host the Pattern Recognition Lab, for this specific lab we have updated the lab with complete sources and converted the lab to new UI.

Here is the git-hub URL :
https://github.com/Virtual-Labs/pattern-recognition-iiith.git

Please make sure we don't loose the analytics of Pattern Recognition Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The requested lab has been re-hosted but the UI is breaking and inappropriate as expected. Please look into the issue and raise the re-hosting request again. Below is the screen-shot attached of the final UI after re-hosting. I have reverted back the lab to previous version.

![re-hosted-pattern-recognition-lab](https://cloud.githubusercontent.com/assets/13132618/14775094/046e97ce-0ada-11e6-8c78-18df0420af58.png)

**Comment by madhavipuliraju** [comment]
@sravanthimodepu please run the sources behind apache and test.

Regards,
Madhavi

**Comment by sanchita-dixit** [comment]
@sravanthimodepu Is the issue of breaking of UI resolved, so that we can re-host this lab again.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu Any updates on this?

**Comment by sravanthimodepu** [comment]
Issue is resolved. Hence closing the issue.
