### ISSUE TITLE
Issue realted to setup ADS in cent os 6.5 

### ISSUE THREAD

**Issue by evalidate** [Virtual-Labs/engineers-forum#308]
Dear VLED team 

Earlier we setup ADS in centos 6.4 we don't have any issue .. but when we setup new version of ADS the we face some issue please help me .. I have attached all screen shots. 

![ovpl1](https://cloud.githubusercontent.com/assets/12808302/14816383/2ff5936c-0bce-11e6-95bc-26d312d63a95.png)
![ovpl2](https://cloud.githubusercontent.com/assets/12808302/14816382/2ff1cf66-0bce-11e6-8a9e-ea9bbf1c47f2.png)
![ovpl1](https://cloud.githubusercontent.com/assets/12808302/14816390/42df35a0-0bce-11e6-9d52-ae1d8c9e93de.png)
![ovpl2](https://cloud.githubusercontent.com/assets/12808302/14816391/42df9e14-0bce-11e6-92a2-c47457770999.png)
![ovpl3](https://cloud.githubusercontent.com/assets/12808302/14816392/42e921f0-0bce-11e6-88a6-573007fc9a70.png)

![ovpl3](https://cloud.githubusercontent.com/assets/12808302/14816381/2feaec5a-0bce-11e6-818b-db13bf281802.png)

**Comment by ksripathi** [comment]
@evalidate 
Before you start ADS services install all pre requisties by running  setup.py file. Use below commands to run
1) cd ovpl
2) python setup.py install
And try to restart the ADS services and let me know the status

**Comment by evalidate** [comment]
We did that but it show error .

[root@localhost ovpl]# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from setuptools import setup
ImportError: No module named setuptools

**Comment by ksripathi** [comment]
@evalidate 

This is the python related error..okay
please install python setuptools using below command
"sudo yum install python-setuptools" and try to execute setup.py file as mentioned above

**Comment by evalidate** [comment]
[root@localhost ovpl]# /etc/init.d/mongod restart
Stopping mongod:                                           [  OK  ]
Starting mongod:                                           [  OK  ]
[root@localhost ovpl]# ./manage_services.sh start
mongodb: unrecognized service
service mongod is not running
mongodb: unrecognized service
stopping mongod
./manage_services.sh: line 162: mongodb: command not found
restarting mongod
mongodb: unrecognized service
service mongod successfully restarted
Starting all services.
LOGGER exists in pid file, now checking if
      it is alive
LOGGER service was stopped unexpectedly. Process
        with 1654 pid is dead. Removing it from pid file now...
Traceback (most recent call last):
  File "src/httplogging/http_logging_server.py", line 17, in <module>
    import httplogging.helper as helper
  File "/root/ovpl/src/httplogging/helper.py", line 10, in <module>
    env = EnvSetUp.Instance()
  File "/root/ovpl/src/singleton.py", line 34, in Instance
    self._instance = self._decorated()
  File "/root/ovpl/src/utils/envsetup.py", line 19, in __init__
    self.set_config_spec()
  File "/root/ovpl/src/utils/envsetup.py", line 33, in set_config_spec
    "/config/config.json").read())
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 336, in raw_decode
    obj, end = self._scanner.iterscan(s, **kw).next()
  File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
    value, end = iterscan(s, idx=end, context=context).next()
  File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib64/python2.6/json/decoder.py", line 180, in JSONObject
    raise ValueError(errmsg("Expecting : delimiter", s, end))
ValueError: Expecting : delimiter: line 3 column 21 (char 44)
ADAPTER exists in pid file, now checking if
      it is alive
ADAPTER service was stopped unexpectedly. Process
        with 1679 pid is dead. Removing it from pid file now...
Traceback (most recent call last):
  File "src/adapters/adapter_server.py", line 17, in <module>
    from httplogging.http_logger import logger
  File "/root/ovpl/src/httplogging/http_logger.py", line 29, in <module>
    logger = __create_logger("ovpl")
  File "/root/ovpl/src/httplogging/http_logger.py", line 10, in __create_logger
    env = EnvSetUp.Instance()
  File "/root/ovpl/src/singleton.py", line 34, in Instance
    self._instance = self._decorated()
  File "/root/ovpl/src/utils/envsetup.py", line 19, in __init__
    self.set_config_spec()
  File "/root/ovpl/src/utils/envsetup.py", line 33, in set_config_spec
    "/config/config.json").read())
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 336, in raw_decode
    obj, end = self._scanner.iterscan(s, **kw).next()
  File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
    value, end = iterscan(s, idx=end, context=context).next()
  File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib64/python2.6/json/decoder.py", line 180, in JSONObject
    raise ValueError(errmsg("Expecting : delimiter", s, end))
ValueError: Expecting : delimiter: line 3 column 21 (char 44)
CONTROLLER exists in pid file, now checking if
      it is alive
CONTROLLER service was stopped unexpectedly. Process
        with 1704 pid is dead. Removing it from pid file now...
Traceback (most recent call last):
  File "src/controller_server.py", line 27, in <module>
    from httplogging.http_logger import logger
  File "/root/ovpl/src/httplogging/http_logger.py", line 29, in <module>
    logger = __create_logger("ovpl")
  File "/root/ovpl/src/httplogging/http_logger.py", line 10, in __create_logger
    env = EnvSetUp.Instance()
  File "/root/ovpl/src/singleton.py", line 34, in Instance
    self._instance = self._decorated()
  File "/root/ovpl/src/utils/envsetup.py", line 19, in __init__
    self.set_config_spec()
  File "/root/ovpl/src/utils/envsetup.py", line 33, in set_config_spec
    "/config/config.json").read())
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 336, in raw_decode
    obj, end = self._scanner.iterscan(s, **kw).next()
  File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
    value, end = iterscan(s, idx=end, context=context).next()
  File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib64/python2.6/json/decoder.py", line 180, in JSONObject
    raise ValueError(errmsg("Expecting : delimiter", s, end))
ValueError: Expecting : delimiter: line 3 column 21 (char 44)
[root@localhost ovpl]#

**Comment by ksripathi** [comment]
@evalidate 
It seems you made a syntax mistake in json file while making entries in either labspec.json or in ovpl/config/config.json

**Comment by ksripathi** [comment]
@evalidate 
Please observe the attached 2nd screen shot. You made syntax mistake at proxy settings
it should be like 
{
-----------------
"HTTP_PROXY" : "your pxoy",
"HTTPS_PROXY" : "your pxoy",

--------

}

**Comment by evalidate** [comment]
"ENVIRONMENT": {
        "HTTP_PROXY"http://mhrdvlsi:mhrdvlsi@10.151.0.13:3128"",
        "HTTPS_PROXY"http://mhrdvlsi:mhrdvlsi@10.151.0.13:3128""
    },

    "CONTROLLER_CONFIG": {
        "SERVER_PORT": 8080,
        "COOKIE_SECRET": "<generate a long random UUID",
        "PERSONA_VERIFIER": "https://verifier.login.persona.org/verify",
        "APP_URL": "http://localhost:8080",
        "LOG_FILENAME": "/root/logs/ovpl.log"
    },

    "LABMANAGER_CONFIG": {
        "GIT_CLONE_LOC":"/root/labs/",
        "LAB_SPEC_DIR":"/scripts/",
        "LAB_SPEC_FILE":"labspec.json"
    },

    "VMMANAGER_CONFIG": {
        "DISK_USAGE_URI":"/api/1.0/disk-usage",
        "MEMORY_USAGE_URI":"/api/1.0/mem-usage",
        "RUNNING_TIME_URI":"/api/1.0/running-time",
        "RUNNING_PROCESSES_URI":"/api/1.0/running-processes",
        "CPU_LOAD_URI":"/api/1.0/cpu_load",
        "EXECUTE_URI":"/api/1.0/execute/([\\w*\\d*\\%\\-]+)",
        "TEST_LAB_URI":"/api/1.0/test-lab",
        "SERVER_PORT":9089
    },

    "VMPOOL_CONFIGURATION": {
      "__comment__":"used by vm pool manager",
        "ADAPTER_ENDPOINTS": {
            "CREATE_URI":"/api/1.0/vm/create",
            "DESTROY_URI":"/api/1.0/vm/destroy",
            "RESTART_URI":"/api/1.0/vm/restart"
        },
        "VMPOOLS": [
            {
                "POOLID":1,
                "DESCRIPTION":"LINUX",
                "ADAPTERIP":"http://localhost",
                "PORT":"8000",
                "__comment__":"adapters in this pool, module & class",
                "ADAPTERS": [
                    {"ADAPTERID" : 1, "MODULE" : "aws_adapter", "ADAPTER" : "AWSAdapter"},
                    {"ADAPTERID" : 2, "MODULE" : "centos_openvz_adapter", "ADAPTER" : "CentOSVZAdapter"},
                    {"ADAPTERID" : 3, "MODULE" : "centos_bridged_adapter", "ADAPTER" : "CentOSBridgeVZAdapter"}
                ]
            },
            {
                "POOLID":2,
                "DESCRIPTION":"WINDOWS",
                "ADAPTERIP":"http://localhost",
                "PORT":"8000"
            },
            {
                "POOLID":3,
                "DESCRIPTION":"AMAZONS3",

**Comment by evalidate** [comment]
{
    "ENVIRONMENT": {
        "HTTP_PROXY"http://mhrdvlsi:mhrdvlsi@10.151.0.13:3128",
        "HTTPS_PROXY"http://mhrdvlsi:mhrdvlsi@10.151.0.13:3128"
    },

    "CONTROLLER_CONFIG": {
        "SERVER_PORT": 8080,
        "COOKIE_SECRET": "<generate a long random UUID",
        "PERSONA_VERIFIER": "https://verifier.login.persona.org/verify",
        "APP_URL": "http://localhost:8080",
        "LOG_FILENAME": "/root/logs/ovpl.log"
    },

    "LABMANAGER_CONFIG": {
        "GIT_CLONE_LOC":"/root/labs/",
        "LAB_SPEC_DIR":"/scripts/",
        "LAB_SPEC_FILE":"labspec.json"
    },

    "VMMANAGER_CONFIG": {
        "DISK_USAGE_URI":"/api/1.0/disk-usage",
        "MEMORY_USAGE_URI":"/api/1.0/mem-usage",
        "RUNNING_TIME_URI":"/api/1.0/running-time",
        "RUNNING_PROCESSES_URI":"/api/1.0/running-processes",
        "CPU_LOAD_URI":"/api/1.0/cpu_load",
        "EXECUTE_URI":"/api/1.0/execute/([\\w*\\d*\\%\\-]+)",
        "TEST_LAB_URI":"/api/1.0/test-lab",
        "SERVER_PORT":9089
    },

    "VMPOOL_CONFIGURATION": {
      "__comment__":"used by vm pool manager",
        "ADAPTER_ENDPOINTS": {
            "CREATE_URI":"/api/1.0/vm/create",
            "DESTROY_URI":"/api/1.0/vm/destroy",
            "RESTART_URI":"/api/1.0/vm/restart"
        },
        "VMPOOLS": [
            {
                "POOLID":1,
                "DESCRIPTION":"LINUX",
                "ADAPTERIP":"http://localhost",
                "PORT":"8000",
                "__comment__":"adapters in this pool, module & class",
                "ADAPTERS": [
                    {"ADAPTERID" : 1, "MODULE" : "aws_adapter", "ADAPTER" : "AWSAdapter"},
                    {"ADAPTERID" : 2, "MODULE" : "centos_openvz_adapter", "ADAPTER" : "CentOSVZAdapter"},
                    {"ADAPTERID" : 3, "MODULE" : "centos_bridged_adapter", "ADAPTER" : "CentOSBridgeVZAdapter"}
                ]
            },
            {
                "POOLID":2,
                "DESCRIPTION":"WINDOWS",
                "ADAPTERIP":"http://localhost",
                "PORT":"8000"
            },
            {
                "POOLID":3,
                "DESCRIPTION":"AMAZONS3",

**Comment by ashay-maheshwari** [comment]
Please replace below lines as shown -
Observe the changed in red color

{
"ENVIRONMENT": {
"HTTP_PROXY":"http://mhrdvlsi:mhrdvlsi@10.151.0.13:3128",
"HTTPS_PROXY":"http://mhrdvlsi:mhrdvlsi@10.151.0.13:3128"
},

and then proceed ahead.

**Comment by evalidate** [comment]
Thanks ashay, 
 but i did that

**Comment by ksripathi** [comment]
@evalidate 
k now try to start the services by running "./manage_server start". and paste me the error

**Comment by ksripathi** [comment]
@evalidate 

After had lot of conversation over phone and working remotely using Teamviewr now it seems now you are able deploy labs using ADS.
Please feel free to post your queries on this forum if anymore. Please let me now its working or now so that we can close the issue

**Comment by gotuam** [comment]
Thanks sripathi my problem is resolved now .. and very very thanks ..

**Comment by ksripathi** [comment]
@evalidate 
Your welcome
