### ISSUE TITLE
Request for re-hosting of Virtual Power Lab

### ISSUE THREAD

**Issue by ajaykant00** [Virtual-Labs/engineers-forum#309]
Virtual Power Lab has been updated.
All issues related to this lab have been resolved.

Please re-host this virtual power lab.

github URL
https://github.com/Virtual-Labs/virtual-power-lab-dei

The dependency is php5 and the lab code is eee06

**Comment by sanchita-dixit** [comment]
@ajaykant00 The Virtual Power Lab has been re-hosted. Please follow the URL : http://vp-dei.vlabs.ac.in to access it.

**Comment by ajaykant00** [comment]
Thank you for re-hosting
