### ISSUE TITLE
Container needed with public IP address

### ISSUE THREAD

**Issue by apurv111** [Virtual-Labs/engineers-forum#31]
IIIT-H integration team needs a container with a public IP address to host all the clients side dependencies. It could be on Amazon or IIIT-H infrastructure.
We should be having the permissions to log into the container, start/stop services, install packages and other basic permissions.

**Comment by soujanya123** [comment]
Gentle reminder, the Integration Team needs a container on Amazon or on IITH server(whichever is feasible right now) to host all the client side dependencies. We need this at the earliest as it's halting some of the processes at our end. Please consider this as immediate. In case you need any help regarding anything, do let us know.

**Comment by sanchita-dixit** [comment]
This issue has already been tracked in bitbucket and been worked upon. Please refer the following bitbucket issue link for the same.

https://bitbucket.org/vlead/systems/issue/148/container-needed-with-public-ip-address
