### ISSUE TITLE
Hosting request for Optics Virtual Lab : Amrita University

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#310]
Please host our lab "Optics Virtual Lab" from the url 
https://github.com/CreateAmrita/optics-virtual-lab.git 

Broad area: Physical Sciences
Lab name: Optics Virtual Lab

**Comment by sanchita-dixit** [comment]
@amritacreate Optics Virtual Lab has been hosted. Kindly follow the URL : http://ov-au.vlabs.ac.in/ to access it.
