### ISSUE TITLE
Hosting request for Cell biology Virtual Lab I : Amrita University

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#311]
Please host the lab "Cell biology Virtual Lab I" in the url 
https://github.com/CreateAmrita/cell-biology-virtual-lab-i.git 

Broad area: Biotechnology and Biomedical Engineering
Lab name: Cell biology Virtual Lab I

**Comment by sanchita-dixit** [comment]
@amritacreate The Cell biology Virtual Lab I is hosted as per requested. Please follow the URL : http://cbi-au.vlabs.ac.in/ to access it.
