### ISSUE TITLE
Hosting request for Cell biology Virtual Lab II : Amrita University

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#312]
Please host the lab "Cell biology Virtual Lab II" in the url 
https://github.com/CreateAmrita/cell-biology-virtual-lab-II.git

Broad area: Biotechnology and Biomedical Engineering
Lab name: Cell biology Virtual Lab II

**Comment by sanchita-dixit** [comment]
@amritacreate The requested Cell biology Virtual Lab II has been hosted. Please follow the URL : http://cbii-au.vlabs.ac.in/ to access it.
