### ISSUE TITLE
Hosting request for Electricity & Magnetism Virtual Lab : Amrita University

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#313]
Please host the lab "Electricity & Magnetism Virtual Lab" in the url 
https://github.com/CreateAmrita/electricity-magnetism-virtual-lab.git

Broad area: Physical Sciences
Lab name: Electricity & Magnetism Virtual Lab

**Comment by sanchita-dixit** [comment]
@amritacreate The requested "Electricity & Magnetism Virtual Lab" has been hosted. Please follow the URL : http://emv-au.vlabs.ac.in/ to access the same.
