### ISSUE TITLE
Hosting request for Heat & Thermodynamics Virtual Lab: Amrita University

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#314]
Please host the lab "Heat & Thermodynamics Virtual Lab" in the url 
https://github.com/CreateAmrita/heat-thermodynamics-virtual-lab.git 

Broad area: Physical Sciences
Lab name: Heat & Thermodynamics Virtual Lab

**Comment by sanchita-dixit** [comment]
@amritacreate Heat & Thermodynamics Virtual Lab has been hosted. Please follow the URL : http://htv-au.vlabs.ac.in
