### ISSUE TITLE
Request to host problem solving lab 

### ISSUE THREAD

**Issue by khushpreet-kaur** [virtual-labs/engineers-forum#315]
Please host Problem Solving Lab.  (Need to give all permissions  to /var/www to this lab) 
Link to github url: https://github.com/Virtual-Labs/problem-solving-iiith

Please deploy this lab for QA team to test it again on QA environment.

**Comment by sanchita-dixit** [comment]
@khushpreet-kaur Problem Solving Lab has been deployed on staging environment for QA testing. All the permissions have been provided to /var/www. Please follow the URL : http://ps-iiith.base1.vlabs.ac.in

**Comment by khushpreet-kaur** [comment]
@sanchita-dixit Thanks. Lab is working as expected.

**Comment by sravanthimodepu** [comment]
Dear System Team,

The QA testing for  Problem Solving  lab with base1 URL is done. Request to re-host the Problem Solving Lab.

Below is the github url of the Problem Solving Lab :
https://github.com/Virtual-Labs/problem-solving-iiith.git

**Comment by sanchita-dixit** [comment]
@sravanthimodepu Please create a new issue whenever hosting request is made even for the labs which have already been requested for hosting/re-hosting before many times. Re-opening the same issue makes it difficult to track the progress for any new request made on the same. For this lab, I would resolve the same in this same issue itself.

One more query, is this re-hosting request for production or Base1?

**Comment by sravanthimodepu** [comment]
Please hold this lab for hosting in production.

**Comment by pavanchow** [comment]
Duplicate. Use https://github.com/virtual-labs/engineers-forum/issues/536 for hosting related issues.
