### ISSUE TITLE
Issue with the container to download and install dependency - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#316]
I am working on fpga lab. Where we need to install iverilog setup with the version 0.9.7-1. I have noted down the dependency in labspec.json as "sudo apt-get install -y iverilog=0.9.7-1". but when container install dependencies it fails to download and install this version. When we install manually using terminal to our machine, this command works fine and install successfully. 

Help me out with this container problem.
I have screenshot with the vm.log file of the container.
![screenshot](https://cloud.githubusercontent.com/assets/8788705/14883974/6183071a-0d5f-11e6-8b27-97095411b3da.png)

This is the log from ovpl.log file of the ovpl logs.
![screenshot-1](https://cloud.githubusercontent.com/assets/8788705/14883977/677065be-0d5f-11e6-9f4e-cd9550bc9801.png)

**Comment by sushilmedhe** [comment]
Anyone have seen this issue? This issue is related with lab but more than that with vz container. As I have mention earlier the same command work fine on base machine using terminal but not in vz container.

**Comment by ksripathi** [comment]
@sushilmedhe 

We are looking into this issue we will let you know once we are done with it.

**Comment by ksripathi** [comment]
@sushilmedhe 

We are able to install the above mentioned package for 0.9.5.1 version on container please let us know is this version is suffiecient run the lab??

**Comment by sushilmedhe** [comment]
What should be the command in labspec.json to install this version. "sudo apt-get install -y iverilog=0.9.7-1". This is installation for iverilog with 0.9.7-1 version. What should I write. give me the command line so I will change the link and try on localhost.

**Comment by ksripathi** [comment]
@sushilmedhe 
In labspec.json file before "sudo apt-get update command" add following two commands as well
1. echo "deb http://ftp.iitm.ac.in/ubuntu/ precise main universe" >> /etc/apt/sources.list
and then install the package using below command
" sudo apt-get install iverilog"

**Comment by sushilmedhe** [comment]
@ksripathi which one is second command?? I will try to use this version on localhost. can you please tell me exact words of commands which I have to paste in lapspec.json file? and the installation of iverilog with 0.9.5.1 version also. What commands should I write in lapspec.json fil?? Please do reply asap.

**Comment by ashay-maheshwari** [comment]
@sushilmedhe : Here are the two commands -

1. **echo "deb http://ftp.iitm.ac.in/ubuntu/ precise main universe" >> /etc/apt/sources.list**
2. **sudo apt-get install iverilog**

Please copy paste the commands shown in BOLD. We were able to install iverilog using these commands.
Please try and come again if you face more problems.

**Comment by sushilmedhe** [comment]
@ashay-maheshwari We can not add the lines as it is in the labspec.json. The command already contains double quotes and we have to write the command in double quote. it shows error. How can we add the lines without error?

**Comment by ashay-maheshwari** [comment]
Assuming that the section you are editing in labspec.json is as given below, Please see how I added two commands  -

"runtime_requirements": {
           "platform": {
               "arch": "i386", 
               "hosting": "dedicated", 
               "installer": ["sudo apt-get update", **"echo 'deb http://ftp.iitm.ac.in/ubuntu/ precise main universe' >> /etc/apt/sources.list"**, "**sudo apt-get install iverilog**"
                               "sudo apt-get install -y php5 apache2 gcc g++ libapache2-mod-python libapache2-mod-wsgi", 
                                 "chmod 777 ./configure.sh",
                               "sh configure.sh", 
                               "service apache2 restart"
       ],

**Comment by ashay-maheshwari** [comment]
Received the following mail from @sushilmedhe and confirm that issues is closed.


`

Vaibhav Kurhe <vrk.vlab@coep.ac.in>	Tue, May 10, 2016 at 2:55 PM
To: "ashay@vlabs.ac.in" <ashay@vlabs.ac.in>
Cc: "sda.instru@coep.ac.in" <sda.instru@coep.ac.in>, Lalit Mohan <lalit@vlabs.ac.in>, "dns.instru@coep.ac.in" <dns.instru@coep.ac.in>
Hi Ashay,


You have mentioned about adding 2 lines of code in labspec.json. I have doubt about it. The relative issue is https://github.com/Virtual-Labs/engineers-forum/issues/316 .


My doubt is when we write the lines in lapspec.json we have to give command in double/single quotes. But command have quotes already so it will not accept the line and throws error when we run on localhost. Then how we can add the same line in labspec.json. Can you just show me the screenshot how you have done at your side so I can add with the same format. 

As I am not having linux background so I am not sure about it in linux environment. please reply ASAP.

Thank you.

`
