### ISSUE TITLE
Request to re-host Digital VLSI Lab IITG

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#317]
I have made some changes in the images of the Digital VLSI Lab. Please re-host the lab. The github url is as follows:
 https://github.com/Virtual-Labs/digital-vlsi-design-iitg

**Comment by sanchita-dixit** [comment]
@bijudas45 Digital VLSI Lab has been re-hosted. Please follow the URL : http://vlsi-iitg.vlabs.ac.in to access it.

**Comment by sanchita-dixit** [comment]
@bijudas45 Please close this issue if it is resolved completely.
