### ISSUE TITLE
Issue with OVPL creating Ubuntu 10.04 container

### ISSUE THREAD

**Issue by pkjana** [Virtual-Labs/engineers-forum#32]
Dear all,

One of our repositories is following...

https://github.com/barun-saha/cse08-se

When I am trying to deploying lab automatically by OVPL deployment tool kit the following errors are coming...

[I 150312 01:55:53 sh:382] <Command '/bin/ping 10.11.56.7...(5 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
[E 150312 01:55:56 web:1421] Uncaught exception POST /api/1.0/vm/create (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/api/1.0/vm/create', version='HTTP/1.1', remote_ip='::1', headers={'Content-Length': '3730', 'Host': 'localhost:8000', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/x-www-form-urlencoded', 'Connection': 'keep-alive', 'Accept': '*/*', 'User-Agent': 'python-requests/2.5.3 CPython/2.6.6 Linux/2.6.32-042stab104.1'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado-4.1-py2.6-linux-x86_64.egg/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "adapters/AdapterServer.py", line 37, in post
        vm_id = adapter_instance.create_vm(json.loads(post_data['lab_spec']))
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 97, in create_vm
        (vm_create_args, vm_set_args) = construct_vzctl_args(lab_spec)
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 245, in construct_vzctl_args
        " --hostname " + host_name
    TypeError: cannot concatenate 'str' and 'NoneType' objects
[E 150312 01:55:56 web:1825] 500 POST /api/1.0/vm/create (::1) 6213.37ms
[D 150312 01:55:56 VMPool:88] VMPool: create_vm(): Response text from adapter: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado-4.1-py2.6-linux-x86_64.egg/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "adapters/AdapterServer.py", line 37, in post
        vm_id = adapter_instance.create_vm(json.loads(post_data['lab_spec']))
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 97, in create_vm
        (vm_create_args, vm_set_args) = construct_vzctl_args(lab_spec)
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 245, in construct_vzctl_args
        " --hostname " + host_name
    TypeError: cannot concatenate 'str' and 'NoneType' objects
    
[E 150312 01:55:56 VMPool:97] VMPool: create_vm(): Error communicating with adapter: VMPool: create_vm(): Error creating VM: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado-4.1-py2.6-linux-x86_64.egg/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "adapters/AdapterServer.py", line 37, in post
        vm_id = adapter_instance.create_vm(json.loads(post_data['lab_spec']))
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 97, in create_vm
        (vm_create_args, vm_set_args) = construct_vzctl_args(lab_spec)
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 245, in construct_vzctl_args
        " --hostname " + host_name
    TypeError: cannot concatenate 'str' and 'NoneType' objects
    
[E 150312 01:55:56 Controller:55] Controller: test_lab(): Test failed with error: VMPool: create_vm(): Error creating VM: VMPool: create_vm(): Error creating VM: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado-4.1-py2.6-linux-x86_64.egg/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "adapters/AdapterServer.py", line 37, in post
        vm_id = adapter_instance.create_vm(json.loads(post_data['lab_spec']))
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 97, in create_vm
        (vm_create_args, vm_set_args) = construct_vzctl_args(lab_spec)
      File "/root/ovpl/src/adapters/CentOSVZAdapter.py", line 245, in construct_vzctl_args
        " --hostname " + host_name
    TypeError: cannot concatenate 'str' and 'NoneType' objects
    
[I 150312 01:55:56 web:1825] 200 POST / (10.11.56.81) 273930.56ms

Regards,
pkjana
IIT Kharagpur

**Comment by AmulyaSri** [comment]
Are you able to create container manually using Ubuntu 10.04 ?

**Comment by pkjana** [comment]
Yes

**Comment by ecthiender** [comment]
Which template file are you using to create the container for ubuntu 10.04?

Did you download template file from here:
http://wiki.openvz.org/Download/template/precreated ?

**Comment by ecthiender** [comment]
Unfortunately, at the moment, we only support Ubuntu 11.10 and 12.04.

What packages/dependencies do you use which requires you to use only Ubuntu
10.04?

**Comment by pkjana** [comment]
I have downloaded ubuntu 10.04 from following link...
http://download.openvz.org/template/precreated/ubuntu-10.04-x86.tar.gz

**Comment by ecthiender** [comment]
Unfortunately, at the moment, we only support Ubuntu 11.10 and 12.04. What packages/dependencies do you use which requires you to use only Ubuntu 10.04?

**Comment by barun-saha** [comment]
@ecthiender The cse28 lab uses NS-2 and NS-3 network simulators that have strong dependencies on the versions of gcc/g++. Building NS-2 fails even when the same version of compilers are used on a 64-bit machine. Similarly, cse08 uses a specific switch of gcc, which has been discontinued in the latter versions. Therefore, the choice of Ubuntu 10.04 is very much desirable.

**Comment by sanchita-dixit** [comment]
@pkjana Kindly close the issue if it was resolved.

**Comment by sanchita-dixit** [comment]
@pkjana As there is no longer any reply from the creator of this issue, I am thereby closing this issue.
