### ISSUE TITLE
Request to re-host Anthropology lab of IITG

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#321]
Please re-host the anthropology lab of IITG as some changes have been made in the quizes.
The git hub link is as follows:
https://github.com/Virtual-Labs/anthropology-iitg

**Comment by sanchita-dixit** [comment]
@bijudas45 anthropology lab of IITG has been re-hosted. Please follow the URL : http://anthropology-iitg.vlabs.ac.in/ to access it.
