### ISSUE TITLE
Request to re-host the virtual power lab

### ISSUE THREAD

**Issue by ajaykant00** [Virtual-Labs/engineers-forum#324]
Some files are not working properly from hosted server, so we have changed the code and updated on git hub. 

Please re-host this virtual power lab.

github URL
https://github.com/Virtual-Labs/virtual-power-lab-dei
The dependency is php5 and the lab code is eee06

**Comment by sanchita-dixit** [comment]
@ajaykant00 Virtual power lab has been re-hosted. Please follow the URL : http://vp-dei.vlabs.ac.in

**Comment by ajaykant00** [comment]
Thank you for re-hosting the lab. Now this is working fine and mail process in feedback form is also working properly.
