### ISSUE TITLE
Request to re-host Metal Forming Virtual Simulation Lab

### ISSUE THREAD

**Issue by samodk** [Virtual-Labs/engineers-forum#325]
The current code is not working with database. Please re-host this website with database configuration.
Please re-host Metal Forming Virtual Simulation Lab.

github URL
https://github.com/Virtual-Labs/metal-forming-virtual-simulation-lab-dei

The dependencies are php5 and mysql database.
The lab code is mech26

**Comment by sanchita-dixit** [comment]
@samodk I assume that code of connecting database is added as a new feature to this lab. We are unable to find labspec.json file in sources.

I suppose, database is introduced now and was not a feature when lab was previously hosted months back. Please point your labspec.json file (if any).

**Comment by samodk** [comment]
Dear vlead team,
labspec.json file is available in script folder with runtime requirements function shown below

"runtime_requirements": {
            "platform": {
                "arch": "i386", 
                "hosting": "dedicated", 
                "installer": ["sudo apt-get update",
                "sudo apt-get install -y php5 apache2"], 
                "lab_actions": {
                    "backup": [], 
                    "clean": [], 
                    "init": ["mv /var/www/index.html index.html.default",
                        "cp -r ../build/* /var/www/"
                        ], 
                    "pause": [], 
                    "publish": [], 
                    "restore": [], 
                    "resume": [], 
                    "shutdown": ["service apache2 stop"], 
                    "start": ["service apache2 start"],  
                    "stats": [], 
                    "stop": []
                },

**Comment by sanchita-dixit** [comment]
@samodk For re-hosting the lab with database, you need to update the labspec.json file with the database configuration steps which I couldn't find after going the existing file.  You can go through this example labspec file for updating the same : [Example labspec.json file](https://github.com/Virtual-Labs/fpga-and-embedded-systems-lab-coep/blob/master/scripts/labspec.json)

**Comment by samodk** [comment]
This is the structure for installing the database. Please check the code given below is correct or not. Should i update the website on github with the following code to re-host "Metal Forming Virtual Simulation Lab" with database.

"runtime_requirements": {
            "platform": {
                "arch": "i386", 
                "hosting": "dedicated", 
                "installer": ["sudo apt-get update",
						"sudo apt-get install -y php5",
						"sudo apt-get install -y mysql-server",
						"sudo apt-get install -y apache2"], 
                "lab_actions": {
                    "backup": [], 
                    "clean": [], 
                    "init": ["bash ../src/lab/db_config.sh",
                            "cp ../src/lab/virtuallab.sql /usr/local/Temp",
							"mv /var/www/index.html index.html.default",
                            "cp -r ../build/* /var/www/",
                            "service apache2 restart"],
                    "pause": [], 
                    "publish": [], 
                    "restore": [], 
                    "resume": [], 
                    "shutdown": ["./stop"], 
                    "start": ["./start"],  
                    "stats": [], 
                    "stop": []
                },

**Comment by samodk** [comment]
Database Issue
