### ISSUE TITLE
Request to re-host  Image Processing Lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#329]
Please re-host Image Processing Lab. (Need to give all permissions to /var/www to this lab)
Link to github url:   https://github.com/Virtual-Labs/image-processing-iiith.git

Please deploy this lab for QA team to test it again on QA environment.

**Comment by sanchita-dixit** [comment]
@sadhanareddy Image Processing Lab has been hosted on QA environment. All the permissions have been given to /var/www/ folder. Please follow the URL : http://cse19-iiith.base1.vlabs.ac.in to access it.
