### ISSUE TITLE
problem regarding FPGA & Embedded lab

### ISSUE THREAD

**Issue by AmulyaSri** [Virtual-Labs/engineers-forum#33]
User Mukhesh has reported that  FPGA lab from vlab.ac.in website is not accessible. It is throwing, 

"Requested URL is not found on this server" Error.

**Comment by ecthiender** [comment]
What is the URL?

**Comment by AmulyaSri** [comment]
http://virtual-labs.ac.in/labs/cse12/

is the URL. I checked with Apurv and it is working fine, from IIIT network, however, am facing the same issue from outside.

Internally, from IIIT network, it was getting redirected to COEP lab (http://coep.vlab.co.in/?sub=29) but I was getting the following error:

![capture](https://cloud.githubusercontent.com/assets/3667651/6633377/8d8b29aa-c96d-11e4-93c3-53cd661f9994.JPG)
