### ISSUE TITLE
Request to re-host Physical Sciences Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#330]
Dear System Team,

Physical Sciences Lab has been tested at  QA environment  following the base1 url ( http://phy14-iiith.base1.vlabs.ac.in ). As, all the issues are fixed,  request you to host the lab on production.

Following is the github URL : 
https://github.com/Virtual-Labs/physical-sciences-iiith.git  

Please make sure we don't loose the analytics of Physical Sciences Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu Physical Sciences Lab has been hosted on production. None of the analytics have been lost. Please follow the URL : http://phy14-iiith.vlabs.ac.in to access it.
