### ISSUE TITLE
Please Unsubscribe me

### ISSUE THREAD

**Issue by amolwandrekar** [Virtual-Labs/engineers-forum#331]
I am not memeber of Virtual labs project since 15th May 2016.

Please unsubscribe me from the Virtual Labs notifications

**Comment by sanchita-dixit** [comment]
@amolwandrekar You can unsubscribe from the notifications of Github repositories yourself. From whichever repositories' notification you receive, there is an Unsubscribe option under Notifications section (Right side of the page below Assignees, Milestone and Labels). We will remove you from the Virtual - Labs organisation from GitHub after some time.

**Comment by sanchita-dixit** [comment]
@amolwandrekar We have removed you from Virtual Labs organisation in Github. Your write access to 12 repositories you were associated with has been revoked as a result. You still have read access. You will no longer receive any notifications from any repository under Virtual Labs organisation in GitHub.
