### ISSUE TITLE
Request to re-host the Image Processing Lab

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/engineers-forum#332]
@Systems Team,

Image Processing Lab has been tested at QA environment following the base1 url (http://cse19-iiith.base1.vlabs.ac.in/). As, all the issues are fixed, request you to host the lab on production.

Following is the github URL :
https://github.com/Virtual-Labs/image-processing-iiith.git

Please make sure we don't loose the analytics of Image Processing Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@BSravanthi Image Processing Lab has been hosted on production. Please follow the URL : http://cse19-iiith.vlabs.ac.in

**Comment by BSravanthi** [comment]
**@sanchita-dixit**  The images are not loading for most of the experiments in the above URL, where as in base 1 URL the there was no problem while loading the images. Could you please look into this issue.

**Comment by sanchita-dixit** [comment]
@BSravanthi Can you provide me with few links where images are not loading properly. You may try clearing your cache (ctrl+shift r) and try again also.

**Comment by BSravanthi** [comment]
@sanchita-dixit  Please find the following links for your reference..
http://cse19-iiith.vlabs.ac.in/diff.php
http://cse19-iiith.vlabs.ac.in/arith.php
http://cse19-iiith.vlabs.ac.in/neigh.php
http://cse19-iiith.vlabs.ac.in/fourier.php
![cse19-loading-image](https://cloud.githubusercontent.com/assets/13479177/15886030/1f55eba2-2d74-11e6-978a-09a4f1b4cdba.png)

**Comment by sanchita-dixit** [comment]
@BSravanthi Please check and verify whether now the images are loading properly.

**Comment by BSravanthi** [comment]
@sanchita-dixit  The images are loading properly in all the experiments.
