### ISSUE TITLE
Request to re-host the Computer Programming Responsive Lab

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/engineers-forum#333]
@Systems Team,

Computer Programming Responsive Lab has been tested at QA environment following the base1 URL (http://cse02-iiith.base1.vlabs.ac.in/). As, all the issues are fixed, request you to host the lab on production.

Following is the git hub URL :
https://github.com/Virtual-Labs/computer-programming-responsive-iiith.git

Please make sure we don't loose the analytics of Computer Programming Responsive  Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@BSravanthi Computer Programming Responsive Lab has been hosted on production. Please follow the URL : http://cse02-iiith.vlabs.ac.in

**Comment by BSravanthi** [comment]
@sanchita-dixit  Thank you Sanchita. The lab is working fine.
