### ISSUE TITLE
Request to re-host Speech Signal Processing Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#334]
Please re-host Speech Signal Processing  Lab. (Need to give all permissions to /var/www to this lab)
Link to  https://github.com/Virtual-Labs/speech-signal-processing-iiith.git

Please deploy this lab for QA team to test it again on QA environment.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The Speech Signal Processing Lab has been re-hosted on QA environment for testing. All permissions are given. Please follow URL : http://ssp-iiith.base1.vlabs.ac.in

**Comment by sravanthimodepu** [comment]
After re-hosting the lab on QA environment for testing, some issues are raised, so I have resolved all the issues .

Please re-host Speech Signal Processing Lab Lab.
Link to https://github.com/Virtual-Labs/speech-signal-processing-iiith.git

Please deploy this lab for QA team to test it again on QA environment.

**Comment by sravanthimodepu** [comment]
@sanchita-dixit Gentle reminder.

**Comment by sravanthimodepu** [comment]
@sanchita-dixit Please deploy the lab on base1as soon as possible, as the lab is on hold for testing.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The lab is hosted on QA. Please follow the URL : http://ssp-iiith.base1.vlabs.ac.in

**Comment by BSravanthi** [comment]
@sravanthimodepu Two links were not added in the Reference link of all the experiments in Speech Signal Processing Lab.

**Comment by sravanthimodepu** [comment]
@BSravanthi  Links are updated in all experiments in this lab.
