### ISSUE TITLE
Request to host Structural Dynamics Lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#337]
Please host Structural Dynamics Lab. (Need to give all permissions to /var/www to this lab)
Link to github url:  https://github.com/Virtual-Labs/structural-dynamics-iiith.git

Please deploy this lab for QA team to test it again on QA environment.

**Comment by sanchita-dixit** [comment]
@sadhanareddy The lab is hosted on QA. Please follow the URL : http://sd-iiith.base1.vlabs.ac.in
