### ISSUE TITLE
Request to host Computer Organization Lab.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/engineers-forum#338]
@Systems Team,

The Computer Organization Lab  has been tested at QA environment following the base1 url (http://cse11-iiith.base1.vlabs.ac.in). As, all the issues are fixed, request you to host the lab on production.

Following is the github URL
https://github.com/Virtual-Labs/computer-organization-iiith.git

Please make sure we don't loose the analytics of The Computer Organization Lab. Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@BSravanthi The lab is hosted on production. Please follow the URL : http://cse11-iiith.vlabs.ac.in
