### ISSUE TITLE
Request to host Image Processing Lab.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/engineers-forum#339]
@Systems Team,

The Image Processing Lab has been tested at QA environment following is the base1 URL (http://cse19-iiith.base1.vlabs.ac.in/). As, all the issues are fixed, request you to host the lab on production.

Please find the git hub URL
https://github.com/Virtual-Labs/image-processing-iiith.git

Please make sure we don't loose the analytics of The Image Processing Lab. Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@BSravanthi The lab is hosted on production. Please follow the URL : http://cse19-iiith.vlabs.ac.in
