### ISSUE TITLE
Error creating VM

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#34]
When I run physical-chemistry-iiith lab over ADS and I get the following error:

test_lab(): Test failed with error: VMPool: create_vm(): Error creating VM: VMPool: create_vm(): Error creating VM: Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "adapters/AdapterServer.py", line 43, in post
    (success, result) = adapter_instance.init_vm(vm_id, lab_repo_name)
  File "/home/v/ovpl/src/adapters/CentOSVZAdapter.py", line 99, in init_vm
    response = {"vm_id": vm_id, "vm_ip": get_vm_ip(vm_id), "vmm_port": settings.VM_MANAGER_PORT}
  File "/home/v/ovpl/src/adapters/CentOSVZAdapter.py", line 213, in get_vm_ip
    raise e
CalledProcessError: Command '/usr/sbin/vzlist -a | grep 105' returned non-zero exit status 1

Could someone help me resolve this.

**Comment by AmulyaSri** [comment]
1. Can you please run 'vzlist -a | grep 105' on the container manually ? to check OpenVZ is installed correctly or not.

2. Check whether the ubuntu template is placed in correct directory(/vz/root/template/cache) as mentioned in LIK kit.

**Comment by AmulyaSri** [comment]
Sorry, in /vz/template/cache.

**Comment by apurv111** [comment]
running vzlist -a | grep 105 gave and the ubuntu template is present at /vz/template/cache.

**Comment by AmulyaSri** [comment]
are you running as root only?

**Comment by AmulyaSri** [comment]
Lab was deployed using ADS successfully and hence, closing the issue.
