### ISSUE TITLE
Request to host Speech Signal Processing Lab.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/engineers-forum#340]
@Systems team,

The Speech Signal Processing Lab has been tested at QA environment following is the base1 URL ( http://ssp-iiith.base1.vlabs.ac.in). As, all the issues are fixed, request you to host the lab on production.

Please find the git hub URL
https://github.com/Virtual-Labs/speech-signal-processing-iiith.git

Please make sure we don't loose the analytics of The Speech Signal Processing Lab. Once done with the hosting process, please share the URL.

**Comment by BSravanthi** [comment]
Dear Systems Team,
Please host the lab on production as early as possible.

**Comment by ashay-maheshwari** [comment]
@BSravanthi ,

Lab was hosted in production, but had UI issues. On updating sources, UI was as shown.
![ssp-iiit-home-page](https://cloud.githubusercontent.com/assets/16608791/16228195/2e0757a8-37d3-11e6-8c1d-5b0ed5b71a49.png).


Hence, sources were reverted to previous state. 
Please check.

**Comment by BSravanthi** [comment]
@ashay-maheshwari 
We will verify from our end and revert back to you.

**Comment by sravanthimodepu** [comment]
@ashay-maheshwari  I re-checked the sources of the lab,  everthing is fine,  css is not breaking.  Even its working fine in base1.
Everything is working fine from our end.  I think there might be problem while deployment. Please re-deploy the lab.

**Comment by ashay-maheshwari** [comment]
@BSravanthi . Siva identified it as a permission issue on css files. Problem is solved and resources are updated. Please check the changes.

**Comment by ashay-maheshwari** [comment]
@BSravanthi , this is URL - http://ssp-iiith.vlabs.ac.in

**Comment by BSravanthi** [comment]
Dear Systems Team,
After hosting the lab, an issue is identified and which is rectified. Request to re-host the lab on production with the same git hub URL.

**Comment by ashay-maheshwari** [comment]
@BSravanthi - Source updated. Visit http://ssp-iiith.vlabs.ac.in/

**Comment by BSravanthi** [comment]
@ashay-maheshwari 
Thanks!!
Seems that the updated sources have not been pulled as required. Please pull the sources and re host the lab.

**Comment by ashay-maheshwari** [comment]
@BSravanthi , sources are updated. Please check.

**Comment by BSravanthi** [comment]
The lab is hosted on production. Hence closing the issue.
