### ISSUE TITLE
Request to re-host Pattern Recognition Lab

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#341]
Dear Systems Team,

Please re-host Pattern Recognition Lab. (Need to give all permissions to /var/www to this lab)
Link to https://github.com/Virtual-Labs/pattern-recognition-iiith

Please deploy this lab for QA team to test it  on QA environment.

**Comment by BSravanthi** [comment]
@Systems Team,
Host the lab on base 1 for testing.

**Comment by ashay-maheshwari** [comment]
@BSravanthi , sources are updated. Please check

**Comment by BSravanthi** [comment]
@ashay-maheshwari 
While testing the Pattern Recognition Lab few bugs have been identified and raised issues against them. Now the issue are fixed. Please re host the at base 1 for re testing the lab.

**Comment by BSravanthi** [comment]
A gentle reminder..

**Comment by sivashankerN** [comment]
@sravanthimodepu, lab has been re hosted on staging environment. Please check the lab for the changes which are made by you and get back to us if sources are not updated properly.

**Comment by sravanthimodepu** [comment]
@sivashankerN , Please update the sources and re-host the lab on base1, as the sources are not updated properly.

**Comment by ashay-maheshwari** [comment]
@sravanthimodepu , Sources are updated please visit http://cse20-iiith.base1.vlabs.ac.in/

**Comment by sravanthimodepu** [comment]
Please host the lab on base1 for testing as early as possible.

**Comment by kraghupathi** [comment]
@sravanthimodepu : The lab is re-hosted on base1. Please check it

**Comment by sravanthimodepu** [comment]
@kraghupathi, Please host the lab on base1, as the couple of issues are fixed.

**Comment by kraghupathi** [comment]
@sravanthimodepu : Sources are updated on base1. Please check it

**Comment by sravanthimodepu** [comment]
Please update the lab sources on base1.
Following is the URL  https://github.com/Virtual-Labs/pattern-recognition-iiith.git

**Comment by kraghupathi** [comment]
@sravanthimodepu : Sources are updated on base1. Please check it

**Comment by sravanthimodepu** [comment]
As couple of changes have been made after hosting the lab on production, need to test the changes made. Request to host the lab on base1 for testing with the same URL.

**Comment by kraghupathi** [comment]
@sravanthimodepu : The lab is re-hosted on base1. Please check the lab for the changes which are made by you and get back to us if sources are not updated properly. Please visit http://cse20-iiith.base1.vlabs.ac.in/

**Comment by sravanthimodepu** [comment]
@kraghupathi, Few changes have been made, request to host the lab on base1 for testing.

**Comment by kraghupathi** [comment]
@sravanthimodepu : Sources are updated on base1. Please visit http://cse20-iiith.base1.vlabs.ac.in/
