### ISSUE TITLE
Request to update the Problem Solving Lab sources.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/engineers-forum#342]
Please host Problem Solving Lab. (Need to give all permissions to /var/www to this lab)
Link to git hub URL: https://github.com/Virtual-Labs/problem-solving-iiith.git

Please deploy this lab for QA team to test it again on QA environment.

**Comment by sivashankerN** [comment]
I just want to know that what do you by  "Need to give all permissions to /var/www"
If we give like that, we may face some problems in future.

**Comment by BSravanthi** [comment]
Please give the suitable permission to access the files of the lab.

**Comment by ashay-maheshwari** [comment]
@BSravanthi , can you please share the url for this lab.

**Comment by ashay-maheshwari** [comment]
@BSravanthi , sources are updated. Please check.

**Comment by BSravanthi** [comment]
@ashay-maheshwari Please provide the URL.

**Comment by ashay-maheshwari** [comment]
@BSravanthi , Here is the base 1 URL - http://cse20-iiith.base1.vlabs.ac.in/ . Please check

**Comment by BSravanthi** [comment]
@ashay-maheshwari The above provided URL is for Pattern Recognition Lab. Request to provide Problem Solving Lab Base 1 URL.

**Comment by ashay-maheshwari** [comment]
@BSravanthi , please check - http://ps-iiith.base1.vlabs.ac.in/

**Comment by BSravanthi** [comment]
@ashay-maheshwari The sources are not updated.

**Comment by ashay-maheshwari** [comment]
@BSravanthi , Sources are updated on testing machine . Please visit URL
http://ps-iiith.base1.vlabs.ac.in/

**Comment by BSravanthi** [comment]
@ashay-maheshwari , The sources are not updated properly. Please update the sources again.

**Comment by ashay-maheshwari** [comment]
@BSravanthi , Sources are updated. Please visit  http://ps-iiith.base1.vlabs.ac.in/
