### ISSUE TITLE
Request to update sources and host Digital Logic Design Lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#343]
Please host  Digital Logic Design Lab. Also give the suitable permissions to /var/www to access the files of this Lab.
Link to git hub URL: https://github.com/Virtual-Labs/digital-logic-design-iiith.git

Please deploy this lab for QA team to test it again on QA environment.

**Comment by ashay-maheshwari** [comment]
@sadhanareddy , I cannot find this lab deployed in QA/staging environment . If it is already, there can you please share the URL.

**Comment by ashay-maheshwari** [comment]
@sadhanareddy , sources updated. Please check
