### ISSUE TITLE
Request to update sources and host Digital Logic Design Lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#344]
Please host Digital Logic Design Lab. Also give the suitable permissions to /var/www to access the files of this Lab.
Link to git hub URL:  https://github.com/Virtual-Labs/digital-logic-design-iiith

Please deploy this lab for QA team to test it again on QA environment.

**Comment by sadhanareddy** [comment]
@ashay-maheshwari  A Gentle Remainder

**Comment by ashay-maheshwari** [comment]
@sadhanareddy , Sources are updated on base machine . Here is the base1 URL -
 http://cse15-iiith.base1.vlabs.ac.in/
