### ISSUE TITLE
Request to re-host Digital Logic Design Lab on Production

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#346]
@Systems Team,

The Digital Logic Design Lab has been tested at QA environment following the base1 url (http://cse15-iiith.base1.vlabs.ac.in/). As, all the issues are fixed, request you to host the lab on production.

Following is the github URL
https://github.com/Virtual-Labs/digital-logic-design-iiith

Please make sure we don't loose the analytics of The Digital Logic Design Lab Lab. Once done with the hosting process, please share the URL.

**Comment by sravanthimodepu** [comment]
A Gentle Reminder.

**Comment by sivashankerN** [comment]
@sravanthimodepu  Lab is re-hosted on production as per your request. Please check the link http://cse15-iiith.vlabs.ac.in. Please close the issue if lab is updated properly.
