### ISSUE TITLE
Request to host Soil Mechanics Lab 

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#347]
Please host Soil Mechanics Lab.  
Link to repo: https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith

Please deploy this lab for QA team to test it on QA environment.

**Comment by BSravanthi** [comment]
A gentle reminder..

**Comment by sivashankerN** [comment]
Lab sources  have  been updated on staging. please check the lab.

**Comment by sivashankerN** [comment]
@BSravanthi and @khushpreet-kaur  please check the lab : http://smfe-iiith.base1.vlabs.ac.in

**Comment by BSravanthi** [comment]
@ Systems team,
The lab is tested at base 1 and during testing new issues are raised and those issues are fixed. Please host the lab at base 1 to retest the new issues.

**Comment by sivashankerN** [comment]
@BSravanthi Lab has been updated with the latest updates. Please check
