### ISSUE TITLE
Request to update the sources and host the Structural Dynamics Lab 

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#348]
Please host structural-dynamics  Lab. Also give the suitable permissions to /var/www to access the files of this Lab.
Link to git hub URL :  https://github.com/Virtual-Labs/structural-dynamics-iiith.git

Please deploy this lab for QA team on base1 to test it again on QA environment.

**Comment by ashay-maheshwari** [comment]
@sadhanareddy , sources updated. Please check http://sd-iiith.base1.vlabs.ac.in/
