### ISSUE TITLE
 Request to host Computer Graphics Lab

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#349]
Please host Computer Graphics Lab

Link to repo: https://github.com/Virtual-Labs/computer-graphics-iiith

Please deploy this lab for QA team to test it on QA environment.

**Comment by sivashankerN** [comment]
@khushpreet-kaur  Lab sources have been updated on Staging environment . Please check.

**Comment by khushpreet-kaur** [comment]
New sources have been pushed. Please deploy this lab on staging now.

**Comment by sivashankerN** [comment]
@khushpreet-kaur Sources are updated. Please close this issue as well as the other issue #354  if it is deployed.
