### ISSUE TITLE
Problem in setting up NFS server

### ISSUE THREAD

**Issue by apurv111** [Virtual-Labs/engineers-forum#35]
I am trying to Insert the kernel module for quotas version 2 while setting up NFS server for POPL lab. For this, I am running:
# modprobe quota_v2

And the output that I get after running this command is:
# WARNING: Deprecated config file /etc/modprobe.conf, all config files belong into /etc/modprobe.d/.
# FATAL: Module quota_v2 not found.

Can anyone tell me a fix for this problem?

**Comment by ecthiender** [comment]
Looks like the quota_v2 module is not present in the kernel. Apart from
that I have no idea about this particular module or the issue.

What module is this? Is this part of the kernel? Since which version? What
does doing an internet search with this issue/problem tell you?

**Comment by apurv111** [comment]
It seems that this quota package is not present in the kernel by default.
That's why we have to add it ourselves.
This is a  module that limits user's access on a file system.
Labs that emulates bash shells for users, use this module to limit their access.
Internet says that it doesn't have support for kernels( higher than 2.4 versions ).

**Comment by sigsevneo** [comment]
The following links are bugs that exist in the given kernel, which we are mostly facing. They are logged at :
[Bug 1](https://bugzilla.openvz.org/show_bug.cgi?id=1721)
[Bug 2](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/761809)

[An alternative to it would be vzquota.]
(https://openvz.org/Man/vzquota.8)

**Comment by sanchita-dixit** [comment]
@apurv111 If the issue was resolved, kindly close the issue.
