### ISSUE TITLE
Request to re-host the Structural Dynamics Lab on Production.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/engineers-forum#350]
@Systems Team,

The Structural Dynamics Lab has been tested at QA environment following the base1 URL (http://sd-iiith.base1.vlabs.ac.in/). As, all the issues are fixed, request you to host the lab on production.

Following is the github URL
https://github.com/Virtual-Labs/structural-dynamics-iiith.git

Please make sure we don't loose the analytics of The Structural Dynamics Lab. Once done with the hosting process, please share the URL.

**Comment by sivashankerN** [comment]
@BSravanthi Lab has been updated with the latest changes/updates on production. Please check the lab and close the issue if it is hosted properly.
