### ISSUE TITLE
Request to update the sources and host the VLSI Lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#351]
Please host VLSI Lab.  Also give the suitable permissions to /var/www to access the files of this Lab.
Link to git hub URL :  https://github.com/Virtual-Labs/vlsi-iiith.git
Following is the hosted url of the Lab  on production :
http://cse14-iiith.vlabs.ac.in/
Please deploy this lab for QA team on base1 to test it again on QA environment.

**Comment by sivashankerN** [comment]
@sadhanareddy  Lab sources are updated on staging environment as per you r request. Please check it once.

**Comment by sivashankerN** [comment]
@sadhanareddy Please share the lab URL with us, so that we can update sources as soon as possible.
For this lab, url is : http://cse14-iiith.base1.vlabs.ac.in
