### ISSUE TITLE
Request to re-host the VLSI Lab on Production. 

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#352]
@Systems Team,

As, all the issues are fixed, request you to host the lab on production.

Following is the github URL
https://github.com/Virtual-Labs/vlsi-iiith.git

Please make sure we don't loose the analytics of The VLSi Lab. Once done with the hosting process, please share the URL.

**Comment by sivashankerN** [comment]
Lab has been updated on production please check it.

**Comment by sanchita-dixit** [comment]
@sadhanareddy The lab URL is : http://cse14-iiith.vlabs.ac.in/
