### ISSUE TITLE
Request to host Soil Mechanics Lab

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#353]
Please host Soil Mechanics Lab on staging environment for testing. 

Link to repo: https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith

**Comment by sivashankerN** [comment]
@khushpreet-kaur  Lab has been updated with the latest sources on staging environment.

**Comment by khushpreet-kaur** [comment]
@sivashankerN  Can you please provide the lab link?

**Comment by sivashankerN** [comment]
http://smfe-iiith.base1.vlabs.ac.in

**Comment by khushpreet-kaur** [comment]
Thank you. Lab is working fine as expected.
