### ISSUE TITLE
Request to host Computer Graphics Lab

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#354]
Please host Computer Graphics Lab on staging environment for testing.

Link to repo: https://github.com/Virtual-Labs/computer-graphics-iiith

**Comment by sivashankerN** [comment]
It seems, it is already hosted. Please check the lab.  Last commit in github was on July 8th 2016 after this  there are no changes made to this lab sources. 
Have look at  #349 closed issue.

**Comment by khushpreet-kaur** [comment]
@sivashankerN  Sources are updated now. Please deploy the lab on staging.

**Comment by ashay-maheshwari** [comment]
@khushpreet-kaur , sources are updated , please go ahead and check http://cse18-iiith.base1.vlabs.ac.in/.

**Comment by sravanthimodepu** [comment]
Need to fix the few bugs in this lab which have been raised after re-testing. Hence reopening this issue.

**Comment by khushpreet-kaur** [comment]
Please re-host the lab on Base1.  
Link to repo: https://github.com/Virtual-Labs/computer-graphics-iiith

**Comment by khushpreet-kaur** [comment]
@sivashankerN  A gentle reminder.

**Comment by sivashankerN** [comment]
Re-hosted, please check

**Comment by khushpreet-kaur** [comment]
Please re-host the lab on base1 for final testing before moving it to production. Link: https://github.com/Virtual-Labs/computer-graphics-iiith

**Comment by kraghupathi** [comment]
@khushpreet-kaur : Sources are updated. Please check it

**Comment by khushpreet-kaur** [comment]
@kraghupathi  Please re host the lab on base1.

**Comment by kraghupathi** [comment]
@khushpreet-kaur : Sources are updated on base1. Please check it

**Comment by sanchita-dixit** [comment]
@kraghupathi Please provide the URL of the lab as well after updating the sources.
