### ISSUE TITLE
Request to update sources and host the Problem Solving lab.

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#355]
Please host Problem Solving Lab.  Also give 755 permissions to /var/www and 766 permissions to "experiments"  to access the files of this Lab.
Link to git hub URL :  https://github.com/Virtual-Labs/problem-solving-iiith.git

Following is the hosted url of the Lab on production :
http://ps-iiith.vlabs.ac.in/
Please deploy this lab for QA team on base1 to test it again on QA environment.

**Comment by sadhanareddy** [comment]
@System Team 
Gentle remainder :   Please hose the lab on base 1 as soon as possible as we need to test the lab and move it to production.

**Comment by ashay-maheshwari** [comment]
@sadhanareddy , sources are updated. Visit http://ps-iiith.base1.vlabs.ac.in/

**Comment by sadhanareddy** [comment]
@ashay-maheshwari ,  Experiments simulations are not opening previously.  It seem's like permission's are given properly.  Shiva has set the permissions, now it's opening.
