### ISSUE TITLE
Request to host Data Structures Lab

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/engineers-forum#356]
Please host Data Structures Lab on Base1 for testing. 

Link to repo: https://github.com/Virtual-Labs/data-structures-iiith/

**Comment by BSravanthi** [comment]
A gentle reminder..

**Comment by ashay-maheshwari** [comment]
@BSravanthi , Sources are updated. Please visit - http://cse01-iiith.base1.vlabs.ac.in/

**Comment by khushpreet-kaur** [comment]
@ashay-maheshwari  Please re-host the lab on Base1 for testing.

**Comment by kraghupathi** [comment]
@khushpreet-kaur : The lab is re-hosted. Please check it

**Comment by khushpreet-kaur** [comment]
@kraghupathi  Please re-host the lab on base1. Link: https://github.com/Virtual-Labs/data-structures-iiith/

**Comment by kraghupathi** [comment]
@khushpreet-kaur : Sources are updated. Please check it

**Comment by khushpreet-kaur** [comment]
Please re-host the lab for final testing before moving it to production.

**Comment by kraghupathi** [comment]
@khushpreet-kaur : Sources are updated. Please check it

**Comment by BSravanthi** [comment]
Lab is working fine. Closing the issue and lab is ready to move to production.
