### ISSUE TITLE
Request to re-host Soil Mechanics Lab on production.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/engineers-forum#357]
@Systems Team,

The Soil Mechanics and Foundation Engineering Lab has been tested at QA environment. Lab is working as desired. Following is the base1 url ( http://smfe-iiith.base1.vlabs.ac.in). As, all the issues are fixed, and done with the testing, request you to host the lab on production.

Following is the github URL
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith

Please make sure we don't loose the analytics of the Soil Mechanics and Foundation Engineering Lab. Once done with the hosting process, please share the URL.

**Comment by BSravanthi** [comment]
A Gentle reminder..

**Comment by sivashankerN** [comment]
@BSravanthi Lab sources have been updated, Please visit the lab http://smfe-iiith.vlabs.ac.in and check your changes.

**Comment by BSravanthi** [comment]
Thank you Shiva Shanker..
The lab is working as desired. Hence closing the issue.
