### ISSUE TITLE
Request to re-host the Problem Solving Lab on production

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#358]
The Problem Solving Lab has been tested at QA environment following is the base1 URL (http://ps-iiith.base1.vlabs.ac.in/). As, all the issues are fixed, request you to host the lab on production.

Please find the git hub URL
https://github.com/Virtual-Labs/problem-solving-iiith.git

Please make sure we don't loose the analytics of the Lab. Once done with the hosting process, please share the URL.

**Comment by sivashankerN** [comment]
It's done. Please check the lab

**Comment by sadhanareddy** [comment]
Experiment simulations are not working.  Unable to compile the code, getting an internal server error. Whereas with base1 URL (  ps-iiith.base1.vlabs.ac.in ) we are able to open the experiment and compile the code.
Below is the screenshot of the error : 

![internal](https://cloud.githubusercontent.com/assets/11345237/17047128/13d86fc4-4ff8-11e6-9746-600025403ee5.png)

Following is the hosted URL on production.
http://ps-iiith.vlabs.ac.in/

**Comment by sivashankerN** [comment]
@sadhanareddy Please check now. Issue is resolved.

**Comment by sadhanareddy** [comment]
@sivashankerN  Thanks ..!  it's  working now.
