### ISSUE TITLE
Request to re-host the VLSI Lab on production

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#359]
@System's Team :  Please re-host the lab on production.

Please find the git hub URL
https://github.com/Virtual-Labs/vlsi-iiith.git

Please make sure we don't loose the analytics of the Lab. Once done with the hosting process, please share the URL.

**Comment by sivashankerN** [comment]
is it hosted on staging/QA environment?

**Comment by sivashankerN** [comment]
@sadhanareddy looks like it is not hosted on staging.  First we have to host this in staging environment, then on production.

**Comment by sadhanareddy** [comment]
@sivashankerN : Request you to host the Lab on base1 not on production.

**Comment by kraghupathi** [comment]
@sadhanareddy : The lab is re-hosted on base1, please check it
