### ISSUE TITLE
OVPL testing in local machine

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#36]
i am getting -----

Test failed: See log file for errors,

in log i am getting......
[E 150315 23:44:10 LabManager:54] LabManager: clone_repo(): git clone failed: cse02NewUnit Command '['git', 'clone', 'https://sranjanagi@github.com/sranjanagi/NewUnit.git', '/root/labs/lab-repo-cache/cse02NewUnit']' returned non-zero exit status 128
[E 150315 23:44:10 Controller:55] Controller: test_lab(): Test failed with error: Command '['git', 'clone', 'https://sranjanagi@github.com/sranjanagi/NewUnit.git', '/root/labs/lab-repo-cache/cse02NewUnit']' returned non-zero exit status 128
[I 150315 23:44:10 web:1811] 200 POST / (127.0.0.1) 7950.30ms

**Comment by AmulyaSri** [comment]
Shivkumar, Are you able to clone manually inside the container ?

**Comment by sranjanagi** [comment]
yes, I am able to clone  it.
