### ISSUE TITLE
 Request to re-host the Computer Graphics Lab on production

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#360]
@System's Team : Please re-host the Computer Graphics Lab on production.

Please find the git hub URL
https://github.com/Virtual-Labs/computer-graphics-iiith

Below is the production URL:
http://cse18-iiith.vlabs.ac.in/

Please make sure we don't loose the analytics of the Lab. Once done with the hosting process, please share the URL.

**Comment by sravanthimodepu** [comment]
A gentle reminder.

**Comment by sivashankerN** [comment]
@sravanthimodepu  It seams you are not tested on Testing/Staging environment. Please host this lab on staging environment.  Please make a another request for hosting this lab on staging.

Thanks

**Comment by sravanthimodepu** [comment]
Issue is resolved. Hence closing the issue.
