### ISSUE TITLE
Request to host the VLSI Lab.

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#361]
Please host VLSI Lab on base1.
Link to git hub URL :  https://github.com/Virtual-Labs/vlsi-iiith.git

Following is the hosted url of the Lab on production :
http://cse14-iiith.vlabs.ac.in/

Please deploy this lab for QA team on base1 to test it again on QA environment.

**Comment by sivashankerN** [comment]
@sadhanareddy Re-hosted, Please check the lab for changes you made.

**Comment by sanchita-dixit** [comment]
@sivashankerN Please provide the URL as well after the hosting is done. Becomes convenient for reference.
