### ISSUE TITLE
Request to re-host Data Structures Lab on production.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/engineers-forum#362]
@Systems Team,

The Data Structures Lab has been tested at QA environment. Lab is working as desired.  As, all the issues are fixed, and done with the testing, request you to host the lab on production.

Following is the base1 URL: 
(http://cse01-iiith.base1.vlabs.ac.in/).
Following is the git hub URL:
https://github.com/Virtual-Labs/data-structures-iiith/

Please make sure we don't loose the analytics of the Data Structures Lab. Once done with the hosting process, please share the URL.

**Comment by sivashankerN** [comment]
@BSravanthi  As per your request, we have updated lab on production. Please visit the lab ( http://cse01-iiith.vlabs.ac.in) and make sure that it is working.

**Comment by BSravanthi** [comment]
Thank you Shiva Shankar..
Lab is working fine. Hence closing the issue.
