### ISSUE TITLE
Request to re-host Computer Graphics Lab on Production

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#364]
@Systems Team,

The Computer Graphics Lab has been tested at QA environment. Lab is working as desired. As, all the issues are fixed, and done with the testing, request you to host the lab on production.

Following is the base1 URL:
http://cse18-iiith.base1.vlabs.ac.in/

Following is the git hub URL:
https://github.com/Virtual-Labs/computer-graphics-iiith.git

Please make sure that we don't loose the analytics of the Computer Graphics Lab. Once done with the hosting process, please share the URL.

**Comment by sivashankerN** [comment]
@sravanthimodepu Lab sources have been updated on production. Please visit the lab (http://cse18-iiith.vlabs.ac.in)

**Comment by sravanthimodepu** [comment]
Lab is hosted on production and working fine. Hence closing the issue.
