### ISSUE TITLE
Request to re-host VLSI Lab on production.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/engineers-forum#365]
@Systems Team,

The VLSI Lab has been tested at QA environment. Lab is working as desired. As, all the issues are fixed, and done with the testing, request you to host the lab on production.

Following is the base1 URL:
http://cse14-iiith.base1.vlabs.ac.in
Following is the git hub URL:
https://github.com/Virtual-Labs/vlsi-iiith/issues

Please make sure that we don't loose the analytics of the VLSI Lab. Once done with the hosting process, please share the URL.

**Comment by sivashankerN** [comment]
@BSravanthi Hosted this lab on production and lab url is http://cse14-iiith.vlabs.ac.in

**Comment by BSravanthi** [comment]
The Lab is working fine. Hence closing the issue.
