### ISSUE TITLE
Request to update sources and host Image Processing Lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#366]
Please host Image Processing Lab on base1.
Link to git hub URL :   https://github.com/Virtual-Labs/image-processing-iiith.git

Following is the hosted url of the Lab on production :
http://cse19-iiith.vlabs.ac.in

Please deploy this lab for QA team on base1 to test it again on QA environment.

**Comment by kraghupathi** [comment]
@sadhanareddy :  Sources are updated on base1. Please check the lab for the changes which are made by you and get back to us if sources are not updated properly.

**Comment by BSravanthi** [comment]
@kraghupathi share base 1 URL

**Comment by BSravanthi** [comment]
@kraghupathi After the changes made the lab is hosted on base 4 and tested. Working fine. Please host the lab on base 1. 
URL is :

**Comment by kraghupathi** [comment]
@sadhanareddy : Sources are updated on base1. Please check the lab for the changes which are made by you and get back to us if sources are not updated properly.
Please visit http://cse19-iiith.base1.vlabs.ac.in/
