### ISSUE TITLE
Request to host Natural Language Processing Lab on Base1

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#367]
Dear Systems Team,

Please host Natural Language Processing Lab on base1.
Link to git hub URL : https://github.com/Virtual-Labs/natural-language-processing-iiith/tree/master

Following is the hosted url of the Lab on production :
http://nlp-iiith.vlabs.ac.in/

Please deploy this lab for QA team on base1 to test it again on QA environment.

**Comment by kraghupathi** [comment]
@sravanthimodepu :  The lab is hosted on base1. Please check the lab for the changes which are made by you and get back to us if sources are not updated properly.

**Comment by sravanthimodepu** [comment]
Thanks..

**Comment by BSravanthi** [comment]
@kraghupathi 
Please provide base 1 URL

**Comment by kraghupathi** [comment]
@BSravanthi : The lab is hosted on base1. Please visit http://nlp-iiith.base1.vlabs.ac.in/

**Comment by sravanthimodepu** [comment]
@System-team : After hosting the lab on base1, few issues have been raised and was fixed.
So, host the lab on base1 for testing with the same URL.

**Comment by kraghupathi** [comment]
@sravanthimodepu : Sources are updated on base1. Please visit lab http://nlp-iiith.base1.vlabs.ac.in/

**Comment by sravanthimodepu** [comment]
@System-team : After hosting the lab on base1, few issues have been raised and was fixed.
So, host the lab on base1 for testing with the same URL.

**Comment by kraghupathi** [comment]
@sravanthimodepu : The lab is hosted on base1. Please check the lab for the changes which are made by you and get back to us if sources are not updated properly. Please visit http://nlp-iiith.base1.vlabs.ac.in/

**Comment by sravanthimodepu** [comment]
@System-team : Please host the lab on base1 for testing with the same URL.

**Comment by kraghupathi** [comment]
@sravanthimodepu : The lab is re-hosted on base1. Please visit http://nlp-iiith.base1.vlabs.ac.in/
