### ISSUE TITLE
Request to host Image Processing Lab  on base1 and in production

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#368]
Please host the lab on base1 and in production.  There  are no much changes in the source,  earlier the lab was pointing to index.php. Now changed it to index.html. Issue is solved.

Following is the URL -
https://github.com/Virtual-Labs/image-processing-iiith.git

**Comment by kraghupathi** [comment]
@sadhanareddy : Sources are updated on base1. Please visit http://cse19-iiith.base1.vlabs.ac.in

**Comment by sivashankerN** [comment]
Updated the sources of this lab on production. Please see the #371 issue.
