### ISSUE TITLE
Request to host the Molecular Absorption Lab.

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#369]
Dear Systems Team,

Please host Molecular Absorption Lab on base1.
Link to git hub URL :  https://github.com/integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab.git

Please deploy this lab for QA team on base1 to test it  on QA environment.

**Comment by kraghupathi** [comment]
@sadhanareddy : The lab is hosted on base1. Please check the lab for the changes which are made by you and get back to us if sources are not updated properly. Please visit http://mas-iiith.base1.vlabs.ac.in/
