### ISSUE TITLE
Request to re-host Image Processing Lab on production.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/engineers-forum#371]
@Systems Team,

The Image Processing Lab has been tested at QA environment and all the issues are fixed. Lab is working as desired. Hence request you to host the lab on production.

Following the base1 url (http://cse19-iiith.base1.vlabs.ac.in/). 

Following is the github URL :
https://github.com/Virtual-Labs/image-processing-iiith.git

Please make sure we don't loose the analytics of Image Processing Lab .Once done with the hosting process, please share the URL.

**Comment by sivashankerN** [comment]
Please check the updates on the lab (http://cse19-iiith.vlabs.ac.in) which is re-hosted on production.
