### ISSUE TITLE
Request to host the Pattern Recognition  Lab.

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#372]
Dear Systems Team,

Please host Pattern Recognition  Lab on base1.
Link to git hub URL :  https://github.com/Virtual-Labs/pattern-recognition-iiith.git

Following is the hosted url of the Lab on production :
http://cse20-iiith.vlabs.ac.in/

Please deploy this lab for QA team on base1 to test it again on QA environment.

**Comment by kraghupathi** [comment]
@sadhanareddy : Sources are updated on base1. Please visit the lab http://cse20-iiith.base1.vlabs.ac.in/

**Comment by sanchita-dixit** [comment]
@sadhanareddy @sravanthimodepu @BSravanthi Please close the issues once the request is resolved after verification by the integration team. There are so many resolved yet open issues on engineers-forum. Kindly close such issues as soon as possible.
