### ISSUE TITLE
Request to re-host the Pattern Recognition Lab.

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#373]
@Systems Team,

The Pattern Recognition Lab has been tested at QA environment and all the issues are fixed. Lab is working as desired. Hence request you to host the lab on production.

Following the base1 url (http://cse20-iiith.base1.vlabs.ac.in/).

Following is the github URL :
 https://github.com/Virtual-Labs/pattern-recognition-iiith.git

Please make sure we don't loose the analytics of Pattern Recognition Lab .Once done with the hosting process, please share the URL.

**Comment by sravanthimodepu** [comment]
@Systems team, A gentle reminder

**Comment by sanchita-dixit** [comment]
@sravanthimodepu The lab has been re-hosted on production with all the analytics intact. Please follow the URL : http://cse20-iiith.vlabs.ac.in

**Comment by sravanthimodepu** [comment]
@sanchita-dixit  Thank you.
