### ISSUE TITLE
Request for hosting Virtual Mass Transfer Lab IITG

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#374]
Please host the Virtual Mass Transfer lab of IITG 
The git hub link is as follows:
https://github.com/Virtual-Labs/virtual-mass-transfer-lab-iitg

**Comment by sanchita-dixit** [comment]
@bijudas45 We apologise for the delay in the resolution of the request as we have some internal issues with our staging servers. We could not host this lab on production until we are sure that it works fine with our staging servers. We would try to resolve it as soon as possible.

**Comment by sanchita-dixit** [comment]
@bijudas45 Virtual Mass Transfer Lab has been hosted. Please follow the URL : http://vmt-iitg.vlabs.ac.in/
