### ISSUE TITLE
Request for hosting Virtual lab for Mechanical Vibration of IITG

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#375]
Please host the mechanicla vibration lab of IITG.
The git hub link is as follows:
https://github.com/Virtual-Labs/virtual-lab-for-mechanical-vibrations-iitg

**Comment by sanchita-dixit** [comment]
@bijudas45 We apologise for the delay in the resolution of the request as we have some internal issues with our staging servers. We could not host this lab on production until we are sure that it works fine with our staging servers. We would try to resolve it as soon as possible.

**Comment by sanchita-dixit** [comment]
@bijudas45 The hosting for this lab failed due to absence of makefile in the lab sources. Please include the same and notify here for the hosting.

**Comment by hrishikeshbaruah** [comment]
The makefile has been included in the src folder. Please host the lab.
The github link is as follows: 
 https://github.com/Virtual-Labs/virtual-lab-for-mechanical-vibrations-iitg

**Comment by sanchita-dixit** [comment]
@bijudas45 Mechanical Vibration Lab has been hosted. Please follow the URL to access the same : http://mv-iitg.vlabs.ac.in
