### ISSUE TITLE
Request to host Mechanical Fluid and thermal sciences lab of IITG

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#376]
Please host the lab of mechanical fluid and thermal sciences lab of IITG
The github link is as follows:
https://github.com/Virtual-Labs/virtual-laboratory-experience-in-fluid-and-thermal-sciences-iitg

**Comment by sanchita-dixit** [comment]
@bijudas45 We apologise for the delay in the resolution of the request as we have some internal issues with our staging servers. We could not host this lab on production until we are sure that it works fine with our staging servers. We would try to resolve it as soon as possible.

**Comment by sanchita-dixit** [comment]
@bijudas45 We are unable to host this lab because of missing makefile in src for this lab. Please include the same and notify us for hosting here.

**Comment by hrishikeshbaruah** [comment]
The makefile has been included in the src folder. Please host the lab.
The github link is as follows: 
https://github.com/Virtual-Labs/virtual-laboratory-experience-in-fluid-and-thermal-sciences-iitg

**Comment by sanchita-dixit** [comment]
@bijudas45 Mechanical fluid and thermal sciences lab has been hosted. Please follow the URL : http://mfts-iitg.vlabs.ac.in

Please rename the index2.html to index.html in the lab sources in GitHub. I have directly made the change in the /var/www/ in production for correct UI. This would prevent issues in the future when source updation requests are made.
