### ISSUE TITLE
Request to host the Molecular Absorption  Spectroscopy Lab.

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#377]
Dear Systems Team,

Please host Molecular Absorption Spectroscopy Lab on base1.
Link to git hub URL :   https://github.com/Virtual-Labs/molecular-absorption-spectroscopy-responsive-lab.git

Please deploy this lab for QA team on base1 to test it on QA environment.

**Comment by kraghupathi** [comment]
@sadhanareddy : The lab is hosted on base1. Please visit http://mas-iiith.base1.vlabs.ac.in/
