### ISSUE TITLE
Regarding new lab creation - NITK Surathkal

### ISSUE THREAD

**Issue by santhoshnitte87** [Virtual-Labs/engineers-forum#378]
How to add new lab to the list of labs, what are the procedures to do. 
Can you please tell me.

thank you

**Comment by khushpreet-kaur** [comment]
@santhoshnitte87  Could you please be more specific?  
Please confirm if you are asking about adding the new labs to this list/page - http://vlabs.ac.in/nit-labs.html
If not, Please share the appropriate link.

**Comment by santhoshnitte87** [comment]
yes ma'am you are right, and we need repositories for that labs which are newly added.

**Comment by khushpreet-kaur** [comment]
@sanchita-dixit Can you please take this conversation up?  And help/guide @santhoshnitte87  further.

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 In which all pages in the vlabs.ac.in , the lab needs to be listed. Please specify so that we do not miss out on anything.

**Comment by santhoshnitte87** [comment]
yes ma'am I understood whatever you said @sanchita-dixit,  I am asking about creating new repositories for our new labs. I have no access to create new repository under **Virtual-Labs**.

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 Yes creation of a new repository also needs to be requested as the access is required to be admin for the same. We would create a new repository under Virtual-Labs organisation if you provide us the lab name. Another way would be if you already have this new lab repository populated with the sources existing in github (somewhere outside Virtual-Labs organisation), we can transfer this to a new repo under Virtual-Labs organisation as it is.

**Comment by santhoshnitte87** [comment]
Ok ma'am, I will provide you all the lab names , these are new labs which are not exist in the **Virtual-Labs** repository list. 
I will send you all the names in few times. @sanchita-dixit 

thank you

**Comment by santhoshnitte87** [comment]
I have got the list of lab **names** and  **url**  for particular lab , they are as follows,

FLUID MACHINERY LAB  --( fmc-nitk )

MARINE STRUCTURES LAB  --( ms-nitk )

DYNAMICS OF MACHINES LAB --( dom-nitk )

COMPUTER NETWORKING LAB --( cn-nitk )

I am requesting you to create a new repository for these labs, and  **url**  for particular labs.
thank you.
@sanchita-dixit 
@khushpreet-kaur

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 I understood that for the above labs, you need a repository under Virtual-Labs organisation in Github. These would be empty repos created by us and you would have to populate them with the lab sources. I am unable to understand the url part you referred above. Are you referring to the Github URL to be shared with you for the above labs or you are referring to some other URLs. Please clarify.

**Comment by santhoshnitte87** [comment]
that url are for contents in the repositories which u host to the server,
for ex: **strength-of-materials-nitk** - https://github.com/Virtual-Labs/strength-of-materials-nitk.git 
which is under  http://sm-nitk.vlabs.ac.in/ 

same here **sm-nitk** is given as url.

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 This is what I understood your requirement to be. Please clarify if I am wrong anywhere. The steps to be followed here would be -
1) Four new Github repos under Virtual-Labs would be created for the labs listed above. 
2) The repos would be empty and the github URL for those repos would be shared with you here. For eg for FLUID MACHINERY LAB, the corresponding XYZ.git would be the URL. Likewise for other labs as well.
3) Please populate the repos with the lab sources in the same directory structure as you have done for other nitk labs.
4) Once it is done, please raise hosting requests for each of these labs along with their github repo links in separate issues here in engg-forum.
5) Once the hosting is done, we would share the URL which would be somewhat like the URLs : fmc-nitk.vlabs.ac.in
6) Once these labs are hosted on production, we can add them on vlabs.ac.in website under NITK labs list.

**Comment by santhoshnitte87** [comment]
Ok ma'am,  I understood.

and let me know once you done with creation of repositories

thank you.

**Comment by sanchita-dixit** [comment]
The repositories created for the above labs with their github urls are given below. Please populate them with the lab sources in the correct structure.
1. FLUID MACHINERY LAB - https://github.com/Virtual-Labs/fluid-machinery-lab-nitk
2. MARINE STRUCTURES LAB - https://github.com/Virtual-Labs/marine-structures-lab-nitk
3. DYNAMICS OF MACHINES LAB - https://github.com/Virtual-Labs/dynamics-of-machines-lab-nitk
4. COMPUTER NETWORKING LAB - https://github.com/Virtual-Labs/computer-networking-lab-nitk
