### ISSUE TITLE
Request to host the lab from NITK Surathkal

### ISSUE THREAD

**Issue by santhoshnitte87** [Virtual-Labs/engineers-forum#379]
I have uploaded the **fluid-machinery-lab-nitk** into the git. 
could you please host the lab @sanchita-dixit 
lab link is given below 

https://github.com/Virtual-Labs/fluid-machinery-lab-nitk.git

**Comment by santhoshnitte87** [comment]
We have demo on this lab coming Thursday. so can you please host @sanchita-dixit , 

thank you

**Comment by santhoshnitte87** [comment]
Can you please host the lab @sanchita-dixit 

thank you.

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 I have seen the request and also started working on the same. Due to some internal server issues, it couldn't be completed yesterday. Will try to do it today.

**Comment by santhoshnitte87** [comment]
@sanchita-dixit  ok ma'am..

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 Fluid Machinery Lab has been hosted. Please follow the URL : http://fmc-nitk.vlabs.ac.in

**Comment by santhoshnitte87** [comment]
ok thank you ma'am, can you please update it in vlabs list of labs.

**Comment by santhoshnitte87** [comment]
can you please update it in NIT list of labs in vlabs ( http://vlabs.ac.in/nit-labs.html )

 @sanchita-dixit

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 The lab has been updated in the list of NITK labs at :  http://vlabs.ac.in/nit-labs.html

**Comment by santhoshnitte87** [comment]
can you please update it under civil engineering labs (http://vlabs.ac.in/civil-engineering-labs.html)

@sanchita-dixit

**Comment by sanchita-dixit** [comment]
@santhoshnitte87 The fluid machinery lab has been listed under civil engineering labs (http://vlabs.ac.in/civil-engineering-labs.html)

**Comment by santhoshnitte87** [comment]
Under civil engineering labs, the **fluid-mechanics lab** has been listed twice and **fluid machinery lab** is not listed.

![ss3](https://cloud.githubusercontent.com/assets/13462722/23054068/9686c6ae-f503-11e6-9eb0-b314902a37aa.png).

Can you please update **fluid machinery lab** under civil engineering labs . 
(http://vlabs.ac.in/civil-engineering-labs.html)

@sanchita-dixit

**Comment by BalammaBoya** [comment]
Issue resolved. Please find this updated link below.

http://vlabs.ac.in:5959/search_feature/disciplines/CivilEngineering/index.html
