### ISSUE TITLE
Update the IE-roadmap.org with the process flow for hosting of labs from Level 5

### ISSUE THREAD

**Issue by geetabose** [Virtual-Labs/engineers-forum#38]
Hello team,

Can someone please update the process of sending a "request for hosting" of labs after the labs are at Level 5? It needs to be updated in the "Roadmap for Integration Engineers" documented on github.

https://github.com/Virtual-Labs/roadmap-for-integration-engineers/blob/master/IE-roadmap.org

The process needs to be updated as below:
Here is the process of labs from L5 to VLEAD:

1. After the lab is at level 5, the lab-integrator must post a hosting request that should include: lab name, institute name, and the link to repository of the lab sources. This needs to be  posted on the engineers forum at:
https://github.com/Virtual-Labs/engineers-forum

2. The lab-integrator must put this hosting request under the label "request-for-hosting".

3. Then VLEAD will host the lab and the lab-integrator will be informed if the hosting is successful or not.

Thanks,
Geeta

**Comment by AmulyaSri** [comment]
Geeta, I tried to update in roadmap.org. But I don't have access to it. I created a pull request for the same. Please check it.

**Comment by AmulyaSri** [comment]
"Roadmap-for-IE" document has been updated.
