### ISSUE TITLE
Request to host Creative Design Prototyping and Experimental Simulation in HCI Lab of IITG

### ISSUE THREAD

**Issue by bijudas45** [Virtual-Labs/engineers-forum#380]
Please host the lab of creative design prototyping lab of IITG
The github link is as follows:
https://github.com/Virtual-Labs/creative-design-prototyping-lab-iitg

**Comment by sanchita-dixit** [comment]
@bijudas45 Creative Design Prototyping and Experimental Simulation in HCI Lab is hosted. Please follow the URL : http://hci-iitg.vlabs.ac.in
