### ISSUE TITLE
Request to host Natural Language Processing Lab on production. 

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#381]
@Systems Team,

The Natural Language Processing Lab has been tested at QA environment and all the issues are fixed. Lab is working as desired. Hence request you to host the lab on production.

Following the base1 url (http://nlp-iiith.base1.vlabs.ac.in).

Following is the github URL :
https://github.com/Virtual-Labs/natural-language-processing-iiith

Please make sure we don't loose the analytics of Natural Language Processing Lab .Once done with the hosting process, please share the URL.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu Natural Language Processing Lab has been hosted on production. Please follow the URL : http://nlp-iiith.vlabs.ac.in/
