### ISSUE TITLE
Request to rehost the vlabs web pages 

### ISSUE THREAD

**Issue by madhavipuliraju** [Virtual-Labs/engineers-forum#383]
Dear Systems Team,

Please re-host the following vlab-web-pages on Production
Github url : https://github.com/vlead/vlab-web-pages

Please find the changes list release notes at https://github.com/vlead/vlabs-web-pages/releases/tag/v2.0

It was also tested on Stagging Machine (base1)

Please find the testing URL: http://landingpage.base1.vlabs.ac.in/

**Comment by sanchita-dixit** [comment]
@madhavipuliraju Vlabs-web page has been hosted on production. Please follow the URL : https://vlabs.ac.in
