### ISSUE TITLE
request to host traffic engg lab - IITB

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#385]
Hi Team,
its a kind request to host Traffic engg lab.
here is the repo link
https://github.com/Virtual-Labs/traffic-engg-iitb

Regards

**Comment by sanchita-dixit** [comment]
@pushpdeep The traffic engineering lab has been hosted on AWS. Please follow the URL : http://tel-iitb.vlabs.ac.in to access it.

**Comment by pushpdeep** [comment]
Thanks
