### ISSUE TITLE
resquest to host maglev lab - IITB

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#386]
Hi Team,
here is the repo link of maglev lab
https://github.com/Virtual-Labs/maglev-iitb
kindly request to host the same

regards

**Comment by sanchita-dixit** [comment]
@pushpdeep The Maglev lab has been hosted on AWS. Please follow the URL : http://ml-iitb.vlabs.ac.in to access it.

**Comment by pushpdeep** [comment]
Thanks
