### ISSUE TITLE
Request to re-host the  Artificial Neural Networks Lab.

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#387]
Please host the Artificial Neural Networks Lab on base1.
Following is the url:

https://github.com/Virtual-Labs/artificial-neural-networks-iiith.git

**Comment by kraghupathi** [comment]
@sadhanareddy : The Lab has been hosted on base1. 

Follow the base1 URL:
 http://cse22-iiith.base1.vlabs.ac.in/
