### ISSUE TITLE
Request to re-host the  Artificial Neural Networks Lab.

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#388]
Please host the Artificial Neural Networks Lab on production.
Following is the url:

https://github.com/Virtual-Labs/artificial-neural-networks-iiith.git

**Comment by sanchita-dixit** [comment]
@sadhanareddy Artificial Neural Networks Lab is re-hosted on production. Please follow the URL : http://cse22-iiith.vlabs.ac.in
