### ISSUE TITLE
Request to host the lab Population ecology Virtual Lab I - Amrita university 

### ISSUE THREAD

**Issue by sruthimangala** [Virtual-Labs/engineers-forum#39]
Dear Vlead Team,

The lab Population ecology Virtual Lab I  of Amrita University was successfully tested. Here is the git hub URL  of the lab sources
https://github.com/Virtual-Labs/population-ecology-virtual-lab-i-au

Please host  and provide URL.

**Comment by sreejithsr-amrita** [comment]
Hello Team,

Let us know the status of hosting this lab.

**Comment by sreejithsr-amrita** [comment]
A gentle reminder.

**Comment by jayanthsagar** [comment]
Hi sreejith,

Your lab is deployed.
you can access your lab using http://pev-au.vlabs.ac.in/

Please check it and reply if we are missing anything.

**Comment by sreejithsr-amrita** [comment]
Hello Jayanthsagar,

We have committed few bug fixes in this lab. pls update to the hosted server.

**Comment by jayanthsagar** [comment]
There are recent commits on this repo. your last commit was on May2nd 2015 and we have deployed your lab on April30th 2015.
If you want us to update the deployed lab please reopen the issue.

**Comment by sreejithsr-amrita** [comment]
Yes, pls update.

**Comment by sruthimangala** [comment]
Dear Jayanth Sagar,

Pls update the lab and let us know. We are unable to reopen this issue.

**Comment by jayanthsagar** [comment]
We have updated your lab with recent changes.
