### ISSUE TITLE
Request to re-host the vlabs web pages on Production

### ISSUE THREAD

**Issue by madhavipuliraju** [Virtual-Labs/engineers-forum#395]
Dear Systems Team,

Please host the vlabs web pages on Production

Please find the url : https://github.com/vlead/vlabs-web-pages

Please find the release notes at: https://github.com/vlead/vlabs-web-pages/releases/tag/v2.1

Same is tested on Base1: http://landingpage.base1.virtual-labs.ac.in/

**Comment by sanchita-dixit** [comment]
@madhavipuliraju The vlabs web pages have been hosted. Please follow the URL : https://vlabs.ac.in

**Comment by madhavipuliraju** [comment]
@sanchita-dixit  will you please rehost the same sources again. because I have updated the static usages.

**Comment by sanchita-dixit** [comment]
@madhavipuliraju Hosted. Please check the URL : https://vlabs.ac.in
