### ISSUE TITLE
Request for Hosting Electronics Devices and Circuits Lab -IITB

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#396]
Hi,
Kind request to  Electronics Devices and Circuits Lab.
https://github.com/Virtual-Labs/electrical-engg-iitb

Thanks

**Comment by sanchita-dixit** [comment]
@pushpdeep Is it a new lab to be hosted or source updation request?

**Comment by pushpdeep** [comment]
its request for new hosting.
The lab exists but its sources wasn't on cloud, so sharing the resources for cloud hosting.

**Comment by sanchita-dixit** [comment]
@pushpdeep The github lab source URL : https://github.com/Virtual-Labs/electrical-engg-iitb is already hosted on cloud with the lab name : Electronics Devices and Circuits and lab URL : http://ee-iitb.vlabs.ac.in

**Comment by pushpdeep** [comment]
Resolved
