### ISSUE TITLE
Request to host molecular fluroscence spectroscopy lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#398]
Please host the molecular fluroscence spectroscopy lab( converted lab) on base1.Give full permissions to /var/www/html to access the files.
Find the url:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith.git

**Comment by kraghupathi** [comment]
@sadhanareddy : Lab has been hosted on base1 and gave full permissions in **/var/www/** files.
please visit http://mfs-iiith.vlabs.ac.in/
