### ISSUE TITLE
Website is not running from amazon server http://metal-forming.virtual-labs.ac.in/ and http://virtual-power.virtual-labs.ac.in

### ISSUE THREAD

**Issue by ajaykant00** [Virtual-Labs/engineers-forum#40]
Dear Sir/Madam,
I Ajay Kant Upadhyay, from Dayalbagh Educational Institute, Daylbagh, Agra.

The website we have hosted on amazon are not running

http://metal-forming.virtual-labs.ac.in/

http://virtual-power.virtual-labs.ac.in

Please short out the issue (problems) and make its runnable (accessible).

-- 
Thanks and Regards
Ajay Kant Upadhyay

**Comment by AmulyaSri** [comment]
Hello Ajay, Labs were down as we had breach on Amazon.

**Comment by ajaykant00** [comment]
Thank you for your reply.

On Wed, Mar 18, 2015 at 4:57 PM, AmulyaSri <notifications@github.com> wrote:

> Hello Ajay, Labs were down as we had breach on Amazon.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Virtual-Labs/engineers-forum/issues/40#issuecomment-82913421>
> .
>



-- 
Thanks and Regards
Ajay Kant Upadhyay

**Comment by vxc** [comment]
Is the lab on a IIIT-H server?

- venkatesh

Sincerely,

Venkatesh Choppella, PhD.
Associate Professor
IIIT Hyderabad
Gachibowli, Hyderabad 500 032
Ph: +91-965-274-0281

**Comment by AmulyaSri** [comment]
No Sir. They are on Amazon server. Due to security breach, they were down.
