### ISSUE TITLE
Hosting request for Inorganic Chemistry Virtual Lab : Amrita University

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#400]
Please host the lab "Inorganic Chemistry Virtual Lab" in the url
https://github.com/CreateAmrita/inorganic-chemistry-virtual-lab.git

Broad area: Chemical Sciences
Lab name: Inorganic Chemistry Virtual Lab

**Comment by sanchita-dixit** [comment]
@amritacreate Inorganic Chemistry Virtual Lab has been hosted on cloud. Please follow the URL : https://icv-au.vlabs.ac.in

**Comment by sanchita-dixit** [comment]
@amritacreate Please mark "Y" in the "Hosted on cloud? (Y/N)" column (column H) in the [Phase II labs info sheet](https://docs.google.com/spreadsheets/d/1m9nZzl_ehYNaTwX-92DI0GsgSkXRNPK2-Ay26fUmvWc/edit#gid=556701317) for this lab as this lab is hosted on cloud.

**Comment by amritacreate** [comment]
We dont have the edit permission on the shared doc. Please do the needful

**Comment by sanchita-dixit** [comment]
@amritacreate The edit permissions for the sheet are only provided to the IIC. Please use the IIC account to edit the sheet or kindly contact your IIC for the same.
