### ISSUE TITLE
Hosting request for Biochemistry Virtual Lab I : Amrita University

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#401]
Please host the lab "Biochemistry Virtual Lab I" in the url
https://github.com/CreateAmrita/biochemistry-virtual-lab-I.git

Broad area: Biotechnology and Biomedical Engineering
Lab name: Biochemistry Virtual Lab I

**Comment by sanchita-dixit** [comment]
@amritacreate Biochemistry Virtual Lab I has been hosted on cloud. Please follow the URL : http://biotech01.vlabs.ac.in to access it.

**Comment by sanchita-dixit** [comment]
@amritacreate Please mark "Y" in the "Hosted on cloud? (Y/N)" column (column H) in the [Phase II labs info sheet](https://docs.google.com/spreadsheets/d/1m9nZzl_ehYNaTwX-92DI0GsgSkXRNPK2-Ay26fUmvWc/edit#gid=556701317) for this lab as this lab is hosted on cloud.
