### ISSUE TITLE
Hosting request for Organic Chemistry Virtual Lab : Amrita University

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#402]
Please host the lab "Organic Chemistry Virtual Lab" in the url
https://github.com/CreateAmrita/organic-chemistry-virtual-lab.git

Broad area: Chemical Sciences
Lab name: Organic Chemistry Virtual Lab

**Comment by sanchita-dixit** [comment]
@amritacreate After testing this lab on the staging server, all the experiments are leading to a 404 error page. Please look into this issue and get back to us for hosting request.

**Comment by amritacreate** [comment]
We will update the source soon.

**Comment by amritacreate** [comment]
Please update the source of the lab Organic Chemistry Virtual lab in the url
https://github.com/CreateAmrita/organic-chemistry-virtual-lab.git 

Broad area: Chemical Sciences
Lab name: Organic Chemistry Virtual Lab

**Comment by sanchita-dixit** [comment]
@amritacreate  Organic Chemistry Virtual lab has been hosted on cloud. Please follow the URL : http://ocv-au.vlabs.ac.in to access it.

**Comment by sanchita-dixit** [comment]
@amritacreate Please mark "Y" in the "Hosted on cloud? (Y/N)" column (column H) in the [Phase II labs info sheet](https://docs.google.com/spreadsheets/d/1m9nZzl_ehYNaTwX-92DI0GsgSkXRNPK2-Ay26fUmvWc/edit#gid=556701317) for this lab as this lab is hosted on cloud.

**Comment by amritacreate** [comment]
Some lab sources have been updated. Please update the lab "Organic Chemistry Virtual lab" from the url
https://github.com/CreateAmrita/organic-chemistry-virtual-lab.git

**Comment by sanchita-dixit** [comment]
@amritacreate The lab sources have been updated. Kindly follow the URL : http://ocv-au.vlabs.ac.in
