### ISSUE TITLE
Hosting request for Mechanics Virtual Lab (Pilot) : Amrita University

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#405]
Please host the lab "Mechanics Virtual Lab (Pilot)"  in the url
https://github.com/CreateAmrita/mechanics-virtual-lab-pilot.git

Broad area: Physical Sciences
Lab name: Mechanics Virtual Lab (Pilot)

**Comment by sanchita-dixit** [comment]
@amritacreate When we tested this lab on the staging server, the experiments "Collision Balls" and "Torsional Oscillations in Different Liquids" are leading to a 404 error page. All other experiments are working fine. Please look into this issue and get back to us for hosting request.

**Comment by amritacreate** [comment]
We will update the source soon.

**Comment by sanchita-dixit** [comment]
@amritacreate Mechanics Virtual Lab (Pilot) has been hosted on cloud. Please follow the URL : http://phy-sc22-au.vlabs.ac.in to access it.

**Comment by sanchita-dixit** [comment]
@amritacreate Please mark "Y" in the "Hosted on cloud? (Y/N)" column (column H) in the Phase II labs info sheet for this lab as this lab is hosted on cloud.

**Comment by amritacreate** [comment]
Some lab sources have been updated. Please update the lab "Mechanics Virtual Lab (Pilot)" from the url
https://github.com/CreateAmrita/mechanics-virtual-lab-pilot.git

**Comment by sanchita-dixit** [comment]
@amritacreate The lab sources have been updated. Please follow the URL : http://phy-sc22-au.vlabs.ac.in
