### ISSUE TITLE
Hosting request for for Molecular Biology Virtual Lab II : Amrita University

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#406]
Please host the lab "Molecular Biology Virtual Lab II" in the url
https://github.com/CreateAmrita/molecular-biology-virtual-lab-II.git

Broad area: Biotechnology and Biomedical Engineering
Lab name: Molecular Biology Virtual Lab II

**Comment by sanchita-dixit** [comment]
@amritacreate When we tested this lab on staging server, the experiment "Extraction of Bacteriophage DNA from Large Scale Cultures Using Proteinase K and SDS" is leading to a 404 error page. All other experiments are working fine. Please look into this issue and get back for hosting request.

**Comment by amritacreate** [comment]
We will update the source soon.

**Comment by amritacreate** [comment]
The lab updated. Please host the lab"Molecular Biology Virtual Lab II" from the url
https://github.com/CreateAmrita/molecular-biology-virtual-lab-II.git

Broad area: Biotechnology and Biomedical Engineering
Lab name: Molecular Biology Virtual Lab II

**Comment by sanchita-dixit** [comment]
@amritacreate Molecular Biology Virtual Lab II has been hosted on cloud. Please follow the URL : http://mbvII-au.vlabs.ac.in to access it.

**Comment by sanchita-dixit** [comment]
@amritacreate Please mark "Y" in the "Hosted on cloud? (Y/N)" column (column H) in the [Phase II labs info sheet](https://docs.google.com/spreadsheets/d/1m9nZzl_ehYNaTwX-92DI0GsgSkXRNPK2-Ay26fUmvWc/edit#gid=556701317) for this lab as this lab is hosted on cloud.

**Comment by amritacreate** [comment]
The sources of some have been updated. Please update the lab"Molecular Biology Virtual Lab II" from the url
https://github.com/CreateAmrita/molecular-biology-virtual-lab-II.git

**Comment by sanchita-dixit** [comment]
@amritacreate The lab sources have been updated. Kindly follow the URL : http://mbvii-au.vlabs.ac.in/
