### ISSUE TITLE
 Request to re-host artificial-neural-networks Lab 

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#409]
Please re-host the artificial-neural-networks lab on production. Give full permissions to /var/www/html to access the files.
Find the url:
https://github.com/Virtual-Labs/artificial-neural-networks-iiith.git

**Comment by sivashankerN** [comment]
@sadhanareddy Lab has been re-hosted on production. Please use http://cse22-iiith.vlabs.ac.in to access the lab
