### ISSUE TITLE
Request to re-host the Molecular Absorption Spectroscopy  Lab on base1

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#410]
Please re-host the Molecular Absorption Spectroscopy  lab on base1. Give full permissions to /var/www/html to access the files.
Find the url:
https://github.com/Virtual-Labs/molecular-absorption-spectroscopy-responsive-lab.git

**Comment by kraghupathi** [comment]
@sadhanareddy : Lab has been re-hosted on Base1 and gave full permissions in **/var/www/**.
Please visit: http://mas-iiith.base1.vlabs.ac.in/
