### ISSUE TITLE
request to host Modern Digital Design Lab

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#412]
Hi Team,
request to host the Modern Digital Design Lab.
https://github.com/pushpdeep/modern_digital_design-Lab-IITB

Thanks

**Comment by sanchita-dixit** [comment]
@pushpdeep For a new lab hosting, the lab sources must be in Virtual-Labs organisation in Github. Kindly send a request for a new repo creation in the Virtual-Labs organisation, push all your lab sources in the repo and then we can host the lab on cloud.

**Comment by pushpdeep** [comment]
resolved
