### ISSUE TITLE
Request to re-host Molecular Fluorescence Spectroscopy Lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#416]
Please re-host Molecular Fluorescence Spectroscopy Lab. Also give full permissions to /var/www to access the files of this Lab.
Link to git hub URL :
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith.git
Following is the hosted url of the Lab on base4 :
http://mfs-iiith.base4.vlabs.ac.in/
Please deploy this lab for QA team on base1 to test it on QA environment.

**Comment by sravanthimodepu** [comment]
[Lab](http://mfs-iiith.virtual-labs.ac.in) is hosted on production. Hence closing the issue.
