### ISSUE TITLE
Request to host molecular-florescence-spectroscopy-lab

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#417]
Please host molecular-florescence-spectroscopy-lab on production. Give full permissions to /var/www/html to access the files.

Find the url:
https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith.git

**Comment by sivashankerN** [comment]
@sadhanareddy  hosting this lab on production VM(mfs-iiith.vlabs.ac.in) may effect the lab ported to vlabs.ac.in page since this lab gui has been changed and Simullation URLs would have been changed. If this is the case. We have to update Simulations /experiment urls in each experiment.

**Comment by sadhanareddy** [comment]
@sivashankerN 
Gentle Remainer: 
Yes I agree. As per the discussion, we had the other day with Priya and Lalit, porting to open edx should be done by us(Integration Team) after hosting it on production. Requesting you to host the lab on production so, we can re-port the lab on to openedx.

**Comment by sravanthimodepu** [comment]
Lab is ported to open-edx and hosted on production. Hence closing the issue.
