### ISSUE TITLE
Request to re-host the Molecular Absorption Spectroscopy Lab on base1

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#418]
Please re-host the Molecular Absorption Spectroscopy lab on base1. Give full permissions to /var/www/html to access the files.

Find the url:
https://github.com/Virtual-Labs/molecular-absorption-spectroscopy-responsive-lab.git

**Comment by sravanthimodepu** [comment]
Gentle Reminder..

**Comment by kraghupathi** [comment]
@sravanthimodepu : Lab has been hosted on staging environment and given full permissions to /var/www/html

Please visit: http://mas-iiith.base1.vlabs.ac.in/
