### ISSUE TITLE
Analytic Report

### ISSUE THREAD

**Issue by ajaykant00** [Virtual-Labs/engineers-forum#42]
Dear Sir/ Madam
The website those we have hosted on amazon server are not running.
is this possible to get the analytic report of the following websites.
1. Metal Forming Lab
http://metal-forming.virtual-labs.ac.in/

2. Virtual Power Lab
http://virtual-power.virtual-labs.ac.in/

Please Provide the Analytic report for the Metal Forming Lab and Virtual Power Lab those have been hosted on amazon server.

Ajay kant

**Comment by AmulyaSri** [comment]
All the virtual machines of Amazon are destroyed. I don't think it is possible to get the analytics of the labs, after destroying the virtual machines.

**Comment by ecthiender** [comment]
As you are already aware of the incident and of the consequences of the analytics data, closing this for now. If you have further questions, please don't hesitate to re-open the issue.
