### ISSUE TITLE
Request to host the Molecular Absorption Spectroscopy Lab on

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#420]
Dear System team,

Please host the Molecular Absorption Spectroscopy lab on production. Give full permissions to /var/www/html to access the files.

Find the url:
https://github.com/Virtual-Labs/molecular-absorption-spectroscopy-responsive-lab.git

**Comment by sanchita-dixit** [comment]
@kraghupati Please look into this request.

**Comment by sanchita-dixit** [comment]
@kraghupathi Please respond to it ASAP.

**Comment by kraghupathi** [comment]
@sanchita-dixit  :  The lab is already hosted on production the URL is http://mas-iiith.vlabs.ac.in/

**Comment by sanchita-dixit** [comment]
@kraghupathi Please close the issue in that case.

**Comment by sravanthimodepu** [comment]
As the lab is hosted on production, closing the issue.
