### ISSUE TITLE
Request to host colloid-and-surface-chemistry-flash-to-javascript-iiith

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#423]
Please host the colloid-and-surface-chemistry-flash-to-javascript-iiith lab on base1.
Find the url:
https://github.com/Virtual-Labs/colloid-and-surface-chemistry-flash-to-javascript-iiith.git

**Comment by sadhanareddy** [comment]
@systems-team 
Gentle Remainder

**Comment by kraghupathi** [comment]
@sadhanareddy : Lab has been hosted on staging environment.

Please visit : http://csc-iiith.base1.vlabs.ac.in/

**Comment by sadhanareddy** [comment]
Lab is working on base1. Hence closing the issue.
