### ISSUE TITLE
Request to host the updated lab contents from NITK Surathkal

### ISSUE THREAD

**Issue by santhoshnitte87** [Virtual-Labs/engineers-forum#424]
I have updated the lab contents of Marine Structures requesting you to host the lab.
link is given below.

https://github.com/Virtual-Labs/marine-structures-lab-nitk

Please update it under civil engineering labs and also update it in NITK list of labs in vlabs. @sanchita-dixit

Thank you.

**Comment by sanchita-dixit** [comment]
@ sivashankerN @ashay-maheshwari @kraghupathi Kindly look into this request.

**Comment by ashay-maheshwari** [comment]
@santhoshnitte87 , sorry as we were involved in conducting Integration workshop. It would be great if you can point out the hosted URL of the lab whose sources are to be updated.

**Comment by ashay-maheshwari** [comment]
@santhoshnitte87 , Based on the issue #424, I got the hosted URL of the lab http://civ02.vlabs.ac.in/
Kindly ignore my previous request.

**Comment by ashay-maheshwari** [comment]
@santhoshnitte87 , sources are updated. Please check http://civ02.vlabs.ac.in/

**Comment by santhoshnitte87** [comment]
Hello,

In the link provided [http://civ02.vlabs.ac.in/](url) ,some **images are not being displayed**. Can you please resolve this issue.

Thank you,
@ashay-maheshwari

**Comment by ashay-maheshwari** [comment]
@santhoshnitte87 , please check now. 
In case you see some issue, please mention the link here.

**Comment by santhoshnitte87** [comment]
@ashay-maheshwari 

Now also I am facing same issue.In **every experiment** most of the images are not being displayed. Like [http://civ02.vlabs.ac.in/exp4/index.html#](url) .

Please find the screenshot sample below.



![error1](https://cloud.githubusercontent.com/assets/13462722/24649693/95a89044-1945-11e7-94a2-a995cfcac051.PNG)
![error2](https://cloud.githubusercontent.com/assets/13462722/24649701/9bea93ee-1945-11e7-8df9-6787991bc90d.PNG)

Thank you.

**Comment by ashay-maheshwari** [comment]
@santhoshnitte87 , please check your image file names in your [image assets](https://github.com/Virtual-Labs/marine-structures-lab-nitk/tree/master/src/lab/images).
I inspected the element and found filename in code as **coarseflask.png**, but the real file name in images folder is  **coarseflask.PNG**. Thus it shows 404 and no image on webpage.

Please replace all **PNG** with **png** and same for any other extensions.

**Comment by santhoshnitte87** [comment]
Hello,

I have made the changes to **marine-structures-lab-nitk** as specified by you. Please find the following link.
[https://github.com/Virtual-Labs/marine-structures-lab-nitk.git](url)
Please host the lab.

Thank you.
@ashay-maheshwari

**Comment by ashay-maheshwari** [comment]
@santhoshnitte87 , looks like suggested changes were not applied. 
Please visit https://github.com/Virtual-Labs/marine-structures-lab-nitk/blob/master/src/lab/images/.

You must see file names with **PNG** extensions. They must be renamed  to **png**. 
See the screenshot highlighted section (coloured in blue)
![dev-tool](https://cloud.githubusercontent.com/assets/16608791/24696072/d13f61f8-1a05-11e7-80c4-56f0a047789f.png)

Your code expects **form.png** and your file is saved as **form.PNG**.
https://github.com/Virtual-Labs/marine-structures-lab-nitk/blob/master/src/lab/images/form.PNG

**Comment by santhoshnitte87** [comment]
Hello Sir,
I have made the changes as you specified but while uploading, the modifications made to the file names are not getting reflected that is it remains .PNG only even after changing it to .png.

**Comment by santhoshnitte87** [comment]
Hello Sir,

I have made the changes as you specified but while uploading, the modifications made to the file names are not getting reflected that is it remains .PNG only even after changing it to .png.

Thank you 

@ashay-maheshwari

**Comment by santhoshnitte87** [comment]
Hello Sir,

I have made the changes as you specified but while uploading, the modifications made to the file names are not getting reflected that is it remains .PNG only even after changing it to .png. 

(Please find the following link)

[https://github.com/Virtual-Labs/marine-structures-lab-nitk.git](url)

Thank you

@ashay-maheshwari

**Comment by santhoshnitte87** [comment]
Hello Sir,

In this link http://civ02.vlabs.ac.in/ only  the following 2 images are not being displayed.

![hand](https://cloud.githubusercontent.com/assets/13462722/24793689/995c30b2-1ba0-11e7-91be-a8cfb380f751.png) in Simulation of Fineness Modulous of Fine Aggregate.


![sp_cement_10](https://cloud.githubusercontent.com/assets/13462722/24793713/b3780c14-1ba0-11e7-8c82-d36272a51b99.png) in  Procedure of Specific Gravity of Cement


Thank You

@ashay-maheshwari

**Comment by santhoshnitte87** [comment]
Hello Sir,

I have made the changes to the marine structures lab. Please find the following link 
 
[https://github.com/Virtual-Labs/marine-structures-lab-nitk.git](url)

Please re-host the lab as early as possible.

Thank you..

 @ashay-maheshwari

**Comment by santhoshnitte87** [comment]
@ashay-maheshwari 

Can you please re-host the Marine structures lab contents.

Thank you.

**Comment by ashay-maheshwari** [comment]
@santhoshnitte87 , lab is re-hosted. Please check.

**Comment by santhoshnitte87** [comment]
Hello sir,
 I have updated the contents of marine structures lab.Please host this lab.

The link is as follows
[https://github.com/Virtual-Labs/marine-structures-lab-nitk.git](url)

Thank you,

@ashay-maheshwari

**Comment by ashay-maheshwari** [comment]
@sanchita-dixit , sources are update. Please check and confirm.

**Comment by santhoshnitte87** [comment]
Thank you Sir.

@ashay-maheshwari
