### ISSUE TITLE
Request to add new members (NITK-Surathkal)

### ISSUE THREAD

**Issue by santhoshnitte87** [Virtual-Labs/engineers-forum#425]
Here I request you(team) to add new 2 member to the group , so that they can have access to the **Virtual-Labs** ,
currently they cannot upload the repositories to the **Virtual-Labs**. Kindly requesting you to add these 2 people.

members are as follows,
https://github.com/AkshayaAcharya
https://github.com/AnushaSalian

**Comment by sanchita-dixit** [comment]
@kraghupati @shivashanker @ashay-maheshwari Please add the members and give the necessary permissions in the virtual-labs organisation.

**Comment by vleadadmin** [comment]
@santhoshnitte87 , members mentioned are added to ie-nitk-team.  
They need to accept the invitation.

**Comment by santhoshnitte87** [comment]
Thank you 👍
