### ISSUE TITLE
Request to host satellite modelling and simulation lab iitb. 

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#426]
Hi team,
kind request to host the lab from the below repo.

https://github.com/jaimathur/satellite-modelling-and-simulation-lab

**Comment by pushpdeep** [comment]
Hi, can we host this by 25th, so that the lab is up and running. 

Regards

**Comment by ashay-maheshwari** [comment]
@pushpdeep , sorry for the delay. Will host this lab by tomorrow morning.

**Comment by pushpdeep** [comment]
@ashay-maheshwari @vleadadmin  please create a repo for the same in Virtual-Labs org. 
need to host this lab today.

**Comment by vleadadmin** [comment]
@pushpdeep , here is the repository - https://github.com/Virtual-Labs/Satellite-Modelling-and-Simulation
Please push your sources and let me know.

**Comment by pushpdeep** [comment]
@vleadadmin updated the repo with resources. request to host

**Comment by sanchita-dixit** [comment]
@pushpdeep The satellite modelling and simulation lab has been hosted on production. Please follow the URL : http://aero04.vlabs.ac.in to access it.

**Comment by pushpdeep** [comment]
Thanks very much for hosting the same.
Cheers  :)

*---Pushpdeep.Mishra*

**Comment by pushpdeep** [comment]
done !

**Comment by kraghupathi** [comment]
@pushpdeep : Please note that lab URL is changed from http://aero04.virtual-labs.ac.in/ to http://aero04-iitb.virtual-labs.ac.in/
