### ISSUE TITLE
Request to Host Virtual-Satellite-Image-Processing-and-Analysis-Laboratory IITB

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#427]
Hi Team, 

Please host the Virtual-Satellite-Image-Processing-and-Analysis-Laboratory from the below repo link.

https://github.com/jaimathur/Virtual-Satellite-Image-Processing-and-Analysis-Laboratory

Regards

**Comment by vleadadmin** [comment]
@pushpdeep , @jaimathur , Please push your sources to github.com/Virtual-Labs organisation on github.
Here is the link of repository - https://github.com/Virtual-Labs/Virtual-Satellite-Image-Processing-and-Analysis-Laboratory.

**Comment by pushpdeep** [comment]
@vleadadmin  added sources on the above link,
request to host

**Comment by sanchita-dixit** [comment]
@pushpdeep The Virtual-Satellite-Image-Processing-and-Analysis-Laboratory has been hosted on production. Please follow the URL : http://civil11.vlabs.ac.in to access it

**Comment by pushpdeep** [comment]
Thanks a tonne!!! 
cheers :) !!

**Comment by kraghupathi** [comment]
@pushpdeep : Please note that lab URL is changed from http://civil11.virtual-labs.ac.in/ to http://civil11-iitb.virtual-labs.ac.in/
