### ISSUE TITLE
Issue with Hybrid Electronics-COE Pune

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#43]
In Hybrid Electronics Lab, first three experiments are not working properly during an outreach activity in an engineering college due to server error.Please check the server side and client side dependacies and whether it works from client machine or not.

**Comment by sushilmedhe** [comment]
This problem will be sorted out shortly.

**Comment by sanchita-dixit** [comment]
Was this issue resolved?

**Comment by sanchita-dixit** [comment]
@sushilmedhe Was this issue resolved? Kindly close this issue if it is resolved.

**Comment by sushilmedhe** [comment]
The simulators of that three labs are working fine on google chrome only. It will not work on mozilla and other browsers.
