### ISSUE TITLE
Request to Host SBHS Simulation lab IITB

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#430]
Hi Team,

Request to host the Host SBHS Simulation lab IITB
https://github.com/Virtual-Labs/sbhs-lab-iitb

Regards

**Comment by ashay-maheshwari** [comment]
Lab is hosted - http://sbhs-iitb.virtual-labs.ac.in/

**Comment by pushpdeep** [comment]
Thanks a  lot :)
good day!

**Comment by kraghupathi** [comment]
@pushpdeep : Please note that lab URL is changed from http://sbhs-iitb.virtual-labs.ac.in/ to http://ee32-iitb.virtual-labs.ac.in/
