### ISSUE TITLE
Request to create Repo Modern Digital Design Lab IITB

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#431]
Hi Team, 
please create a repo to host the Modern Digital Design Lab IITB

thanks
@ashay-maheshwari @vleadadmin

**Comment by vleadadmin** [comment]
@pushpdeep , repository created - https://github.com/Virtual-Labs/Modern-Digital-Design-Lab-IITB.git

**Comment by pushpdeep** [comment]
populated with resources. 
thanks

**Comment by kraghupathi** [comment]
@pushpdeep : Lab is hosted. Please visit http://mddl-iitb.virtual-labs.ac.in/

**Comment by pushpdeep** [comment]
Thanks Team  :smile:  :clap:
