### ISSUE TITLE
Request to delete repo 

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#432]
Hi,
found this duplicate repo.
request to delete to avoid confusion
https://github.com/Virtual-Labs/sattelite-image-processing-lab-iitb

**Comment by ashay-maheshwari** [comment]
@pushpdeep , it is duplicate of which repo.

**Comment by pushpdeep** [comment]
https://github.com/Virtual-Labs/Virtual-Satellite-Image-Processing-and-Analysis-Laboratory

they both are same lab.
kindly delete the duplicate repo below
https://github.com/Virtual-Labs/sattelite-image-processing-lab-iitb

**Comment by pushpdeep** [comment]
@ashay-maheshwari

**Comment by vleadadmin** [comment]
@pushpdeep , will delete https://github.com/Virtual-Labs/sattelite-image-processing-lab-iitb

**Comment by vleadadmin** [comment]
@pushpdeep , repository deleted.

**Comment by pushpdeep** [comment]
thanks :+1:
