### ISSUE TITLE
Request to Host Modern Digital Design Lab IITB

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#434]
Hi Team,
please host the below lab
https://github.com/Virtual-Labs/Modern-Digital-Design-Lab-IITB

Thanks

**Comment by kraghupathi** [comment]
@pushpdeep : Lab is hosted. Please visit http://mddl-iitb.vlabs.ac.in/ and confirm.

**Comment by pushpdeep** [comment]
Thanks team  :clap:
