### ISSUE TITLE
Kindly create a repository for Control System Lab

### ISSUE THREAD

**Issue by sumitdahiyavlab** [Virtual-Labs/engineers-forum#436]
Kindly create a repository for Control System Lab developed by Nodal Center, Dronacharya College of Engineering Gurgaon.

**Comment by sumitdahiyavlab** [comment]
Kindly do it urgently.

**Comment by vleadadmin** [comment]
@sumitdahiyavlab  We have created new repository for you lab. Here is the GitHub link
https://github.com/Virtual-Labs/control-system-lab-DCE-Gurgaon-Haryana.

**Comment by vleadadmin** [comment]
@sumitdahiyavlab Is that repository name okay for you? Please let me know for any modification.

**Comment by vleadadmin** [comment]
Renamed to https://github.com/Virtual-Labs/control-system-lab-dce-gurgaon-haryana. Please use this repo for your lab.

**Comment by sumitdahiyavlab** [comment]
The name of the repository is okay and fine. Thanks for creating the repository.
