### ISSUE TITLE
Delete the IIIT-H labs on AWS 

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#437]
Dear Systems Team,

Please remove the below mentioned IIIT-H labs from AWS, as their simulations are not working. 
 
Labs are :
1. [Electromagnetic Theory](http://emt-iiith.vlabs.ac.in/)
2. [Physical Sciences](http://phy14-iiith.vlabs.ac.in/)
3. [Geotechnical Engineering](http://eerc05-iiith.virtual-labs.ac.in/)

**Comment by sivashankerN** [comment]
@sravanthimodepu 
Restarted Physical Sciences lab agaoon on your request.  [Physical Sciences](http://phy14-iiith.vlabs.ac.in/).

**Comment by sivashankerN** [comment]
@sravanthimodepu 
Stopped Physical Sciences lab again on your request.  [Physical Sciences](http://phy14-iiith.vlabs.ac.in/).
