### ISSUE TITLE
Add the IIIT-H labs on AWS

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#438]
Dear Systems team,

Please add the below mentioned labs on AWS, as the 2 labs were already ported and all the 3 labs simulations are working fine.

Mobile robotics lab needs to be ported.

Labs are:
1. [Analog CMOS VLSI Circuit Design](http://cse30-iiith.virtual-labs.ac.in/)
2. [Quantum Chemistry](http://ccnsb04-iiith.virtual-labs.ac.in/)
3. [Mobile Robotics](cse17-iiith.virtual-labs.ac.in)

**Comment by sivashankerN** [comment]
@sravanthimodepu ,
These three labs are currently running from IIIT-H( local server .i.e from base3 machine). 
You want us to host these labs on production( AWS),If yes, please share github link of each lab. 

Have you hosted these labs on base4 and tested ?  If not, We request you please host these labs on base4. Then we will host these labs on base1 and then on production.
