### ISSUE TITLE
Request ot host the Analog CMOS VLSI Circuit Design lab on base1

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#442]
Dear System Team,

Please host the Analog CMOS VLSI Circuit Design lab on base1. The source code of the lab is updated.

Below is the github link of analog cmos vlsi circuit design lab : 
"https://github.com/Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith.git"

**Comment by kraghupathi** [comment]
@sravanthimodepu : The lab is hosted on Base1 machine. Please follow the [link](http://cse30-iiith.base1.vlabs.ac.in/)

**Comment by sravanthimodepu** [comment]
Dear System Team,

Please host the Analog CMOS VLSI Circuit Design lab on base1. The source code of the lab is updated.

Below is the github link of analog cmos vlsi circuit design lab :
"https://github.com/Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith.git"

**Comment by kraghupathi** [comment]
@sravanthimodepu : The lab is re-hosted on Base1 machine. Please follow the [link](http://cse30-iiith.base1.vlabs.ac.in/)
