### ISSUE TITLE
Request to host Quantum Chemistry Lab on base1

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#443]
Dear System Team,

Please host the Quantum Chemistry(ccnsbo4-iiith) lab on base1. The source code of the lab is updated.

Below is the github link of quantum chemistry lab : 
"https://github.com/Virtual-Labs/quantum-chemistry-iiith.git"

**Comment by kraghupathi** [comment]
@sravanthimodepu : The lab is hosted on Base1. Please follow the [link](http://ccnsbo4-iiith.base1.vlabs.ac.in/)
