### ISSUE TITLE
Request to host Mobile Robotics lab on base1

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#444]
Dear System Team,

Please host the Mobile Robotics lab on base1. The source code of the lab is updated.

Below is the github link of mobile robotics lab :
"https://github.com/Virtual-Labs/mobile-robotics-iiith.git"

**Comment by sanchita-dixit** [comment]
@kraghupathi Please look into this.

**Comment by sanchita-dixit** [comment]
@kraghupathi Please look into ASAP.

**Comment by kraghupathi** [comment]
@sanchita-dixit :  The lab is already hosted on production the URL is http://cse17-iiith.base1.vlabs.ac.in/
