### ISSUE TITLE
Request to host Mobile Robotics Lab on base1

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#448]
Dear System Team,

Please host the Mobile Robotics Lab on base1. The source code of the lab is updated.

Below is the github link of mobile robotics lab :
"https://github.com/Virtual-Labs/mobile-robotics-iiith.git"

**Comment by kraghupathi** [comment]
@sravanthimodepu : The lab is re-hosted on Base1 machine. Please follow the [link](http://cse17-iiith.base1.vlabs.ac.in/)
