### ISSUE TITLE
Request to host 3 IIIT-H labs on Production

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#449]
Dear System Team,

Please host the below 3 IIIT-H labs on production. The source code of the labs are updated.

Github links of the 3 IIIT-H labs :
1. Analog CMOS VLSI Design Circuit (cse30-iiith)
https://github.com/Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith
2. Quantum Chemistry (ccnsb04-iiith)  
https://github.com/Virtual-Labs/quantum-chemistry-iiith
3. Mobile Robotics (cse17-iiith) 
 https://github.com/Virtual-Labs/mobile-robotics-iiith.git

**Comment by kraghupathi** [comment]
@sravanthimodepu :  The following labs are hosted on production. Please check the labs for the changes which are made by you and get back to us if sources are not updated properly.

1. [Mobile Robotics Virtual Lab](http://cse17-iiith.vlabs.ac.in/)
2. [Analog CMOS VLSI Circuit Design Lab](http://cse30-iiith.vlabs.ac.in)
3. [Quantum chemistry lab](http://ccnsb04-iiith.vlabs.ac.in)
