### ISSUE TITLE
Please check error in the flash labs developed by IIT Guwahati

### ISSUE THREAD

**Issue by hrishikeshbaruah** [virtual-labs/engineers-forum#464]
All the labs developed by IIT Guwahati in flash platform shows a blank window.
Please check the link to "Virtual Electrical Machine lab"

**Comment by hrishikeshbaruah** [comment]
![mechanical lab](https://user-images.githubusercontent.com/12407358/37697356-6bec2618-2d02-11e8-8f67-090b01c1d861.JPG)

**Comment by sravanthimodepu** [comment]
As the "Fullscreen" is loading in another window, it is displaying a blank page. Copy the simulation link and paste in a new tab of lab page, it works fine.

**Comment by hrishikeshbaruah** [comment]
I already tried it but it showed the same white screen

**Comment by sravanthimodepu** [comment]
Below is the screen shot of the simulation:

![iitg](https://user-images.githubusercontent.com/11156924/37705861-5ee487e6-2d23-11e8-8738-96f5677867bc.png)

**Comment by hrishikeshbaruah** [comment]
it worked but need to copy the link in a new window
