### ISSUE TITLE
Request for hosting DEI's Microwave Virtual Lab

### ISSUE THREAD

**Issue by mrikum7** [virtual-labs/engineers-forum#471]
This is to request you to please upload the DEI's Microwave Virtual Lab on your servers. The GitHub link is https://github.com/virtual-labs/virtual-microwave-laboratory-dei.git

**Comment by kraghupathi** [comment]
@mrikum7 :   

Please let us know the lab status. i.e the lab belongs to which phase? Phase II or phase III

**Comment by mrikum7** [comment]
Phase II

**Comment by kraghupathi** [comment]
Working on this. Will let you know, once it is deployed on production

**Comment by kraghupathi** [comment]
@mrikum7 :   

The virtual microwave lab is hosted on production. Please check the [link](http://vm-dei.vlabs.ac.in/)

**Comment by mrikum7** [comment]
Thank You so much for it.
