### ISSUE TITLE
IIT-Guwahati_Digital VLSI Design Virtual lab_MOSFET_experiment page redirecting to blank page

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/engineers-forum#482]
The experiment page is not opening for a long while and later  getting an error "The connection has timed out". In order to get the lab accessed by the end user please fix the issue at the earliest.

**Comment by hrishikeshbaruah** [comment]
The VLSI Design initially hosted in the Amrita University server may be down. We are trying to shift the labs 
to IIT Guwahati server.

**Comment by BSravanthi** [comment]
May we know the status. Still the same issue persisted.

**Comment by hrishikeshbaruah** [comment]
The labs can be accessible in the IIT Guwahati server in the following link  "https://www.iitg.ac.in/cseweb/vlab/vlsi/".

**Comment by hrishikeshbaruah** [comment]
[](https://www.iitg.ac.in/cseweb/vlab/vlsi/)
