### ISSUE TITLE
Issue with Data Structures-IIIT Hyderbad

### ISSUE THREAD

**Issue by sravanthimodepu** [Virtual-Labs/engineers-forum#49]
In Data Structures lab,in Sorting experiments the video’s are running fast and are not understandable ,make the video’s slow to understand by the client.Please check the video’s in the experiment and whether working in the client side machine or not.

**Comment by ecthiender** [comment]
Is the issue that you have reported got fixed? If it has got fixed, then
only close the issue.

**Comment by sanchita-dixit** [comment]
@sravanthimodepu Is this issue resolved? If yes then kindly close this issue.
