### ISSUE TITLE
Request to re-host Basic Structural Analysis Lab on Production

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/engineers-forum#499]
Dear System Team,

Please, re-host the Basic Structural Analysis Lab. The source code of the lab is updated.

Below is the GitHub URL of the lab:
https://github.com/virtual-labs/basic-structural-analysis-iiith

**Comment by sravanthimodepu** [comment]
Updated the sources of the lab and hosted on production.

Hosted URL:
http://bsa-iiith.vlabs.ac.in/

**Comment by pavanchow** [comment]
Duplicate. Post issues related to Basic Structural Analysis on https://github.com/virtual-labs/engineers-forum/issues/600.
