### ISSUE TITLE
Request to re-host Metal Forming Virtual Simulation Lab

### ISSUE THREAD

**Issue by samodk** [virtual-labs/engineers-forum#500]
There are some changes in the file.
Please re-host Metal Forming Virtual Simulation Lab.

github URL
https://github.com/Virtual-Labs/metal-forming-virtual-simulation-lab-dei

The dependencies are php5 and mysql database.
The lab code is mech26

**Comment by pavanchow** [comment]
Duplicate. This has been requested to be closed https://github.com/virtual-labs/engineers-forum/issues/733#issuecomment-927611553
