### ISSUE TITLE
Hosting Request for Problem Solving

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#513]
## *Hosting Details*
*The Request will be deployed Problem Solving lab*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab) Name** : Problem Solving 
1. **Repo URL**: https://github.com/virtual-labs/problem-solving-iiith
1. **Branch/Tag**: msater/v1.1.1
1. **Contact Person**: Balamma/Niranjan

## *Other Details*
No

**Comment by sravanthimodepu** [comment]
@BalammaBoya hosted the lab, please check and let us know if the changes are not reflected.

Hosted URL: http://ps-iiith.vlabs.ac.in/

**Comment by pavanchow** [comment]
Duplicate. Use https://github.com/virtual-labs/engineers-forum/issues/536 for hosting related issues.
