### ISSUE TITLE
Hosting Request for Hydraulics and Fluid Mechanics Lab

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#516]
## *Hosting Details*
*The Request will be deployed Hydraulics and Fluid Mechanics Lab*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name** : Hydraulics and Fluid Mechanics Lab
1. **Repo URL**: https://github.com/virtual-labs/hydraulics-and-fluid-mechanics-iiith
1. **Branch/Tag**: master/v1.1.1
1. **Contact Person**: Balamma/Niranjan

## *Other Details*
No

**Comment by sravanthimodepu** [comment]
@BalammaBoya hosted the lab, please check and let us know if the changes are not reflected.

Hosted URL: http://eerc03-iiith.vlabs.ac.in/

**Comment by pavanchow** [comment]
Duplicate. Use https://github.com/virtual-labs/engineers-forum/issues/717 for Hydraulics and Fluid Mechanics hosting/re-hosting
