### ISSUE TITLE
Hosting Request for Quantum Chemistry Lab

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#519]
## *Hosting Details*
*The Request will be deployed Quantum Chemistry Lab*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name** : Quantum Chemistry Lab
1. **Repo URL**: https://github.com/virtual-labs/quantum-chemistry-iiith
1. **Branch/Tag**:  master/v1.1.1
1. **Contact Person**: Balamma/Niranjan

## *Other Details*
No

**Comment by sravanthimodepu** [comment]
@BalammaBoya hosted the lab, please check and let us know if the changes are not reflected.

**Hosted URL: http://ccnsb04-iiith.vlabs.ac.in/**

**Comment by pavanchow** [comment]
Duplicate. Find Quantum Chemistry issue on https://github.com/virtual-labs/engineers-forum/issues/711 .
