### ISSUE TITLE
Hosting Request for Basic Structural Analysis Lab

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#521]
## *Hosting Details*
*The Request will be deployed Basic Structural Analysis Lab.*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name** : Basic Structural Analysis Lab
1. **Repo URL**: https://github.com/virtual-labs/basic-structural-analysis-iiith
1. **Branch/Tag**: master/v1.1.1
1. **Contact Person**: Balamma/Niranjan

## *Other Details*
No

**Comment by sravanthimodepu** [comment]
@BalammaBoya hosted the lab, please check and let us know if the changes are not reflected.

**Hosted URL: http://bsa-iiith.vlabs.ac.in/**

**Comment by pavanchow** [comment]
Duplicate. Post issues related to Basic Structural Analysis on https://github.com/virtual-labs/engineers-forum/issues/600.
