### ISSUE TITLE
Hosting Request for VLSI Lab IIITH

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#524]
## *Hosting Details*
*The Request will be deployed oVLSI Lab*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name** : VLSI Lab
1. **Repo URL**:  https://github.com/virtual-labs/vlsi-iiith
1. **Branch/Tag**: master/v1.1.1
1. **Contact Person**: Balamma/Niranjan

## *Other Details*
No

**Comment by sravanthimodepu** [comment]
@BalammaBoya hosted the lab, please check and let us know if the changes are not reflected.

**Hosted URL: http://cse14-iiith.vlabs.ac.in/**

**Comment by sravanthimodepu** [comment]
As the lab was hosted, closing the issue

**Comment by pavanchow** [comment]
This is being tracked in issue #583
