### ISSUE TITLE
Hosting Request for Speech Signal Processing Lab

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#528]
## *Hosting Details*
*The Request will be deployed Speech Signal Processing Lab*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name** : Speech Signal Processing Lab
1. **Repo URL**: https://github.com/virtual-labs/speech-signal-processing-iiith
1. **Branch/Tag**: master/v1.1.1
1. **Contact Person**:  Balamma?Niranjan

## *Other Details*
No

**Comment by sravanthimodepu** [comment]
@BalammaBoya hosted the lab, please check and let us know if the changes are not reflected.

**Hosted URL: http://ssp-iiith.vlabs.ac.in**

**Comment by pavanchow** [comment]
Duplicate. Please use issue https://github.com/virtual-labs/engineers-forum/issues/647 for Speech Signal Processing hosting-related issues.
