### ISSUE TITLE
Hosting Request for Natural Language Processing Lab

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#529]
## *Hosting Details*
*The Request will be deployed Natural Language Processing Lab*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name** : Natural Language Processing Lab
1. **Repo URL**: https://github.com/virtual-labs/natural-language-processing-iiith
1. **Branch/Tag**: master/v1.1.1
1. **Contact Person**:  Balamma/Niranjan

## *Other Details*
No

**Comment by sravanthimodepu** [comment]
@BalammaBoya hosted the lab, please check and let us know if the changes are not reflected.

**Hosted URL: http://nlp-iiith.vlabs.ac.in**

**Comment by pavanchow** [comment]
Duplicate. Please use issue https://github.com/virtual-labs/engineers-forum/issues/579 for hosting related issues of Natural Language Processing lab.

**Comment by pavanchow** [comment]
Issue: 
Exp9: Broken link in the further reading page.
