### ISSUE TITLE
Making website responsive 

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#53]
How to make this site to responsive.
Images are not becoming responsive.

**Comment by soujanya123** [comment]
Which site are you talking about? Could you give us some more details on this?

**Comment by sranjanagi** [comment]
Is there  css, we have to include to make the pages (experiments )
responsive in mobile and tablets?
Is it necessary or not?
I am talking about pages of lab experiments.

**Comment by ecthiender** [comment]
No. The UI template does not provide any feature to make your lab responsive.

You have to do that yourself.

https://www.google.co.in/?q=learn+responsive+web+design

https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/

**Comment by soujanya123** [comment]
You could make the experiments responsive, but right now responsiveness is not the priority, atleast from our end. Currently our focus is to get the labs hosted and ensure that they are accessible. However, if you wish to make the experiments responsive you could go with the suggestions mentioned above. 

-Soujanya

**Comment by sranjanagi** [comment]
Thanks for the reply
