### ISSUE TITLE
Hosting Request for Computer-graphics-iiith

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#530]
## *Hosting Details*
*The Request will be deployed Computer-graphics-iiith*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name** : Computer-graphics-iiith
1. **Repo URL**: https://github.com/virtual-labs/computer-graphics-iiith
1. **Branch/Tag**: master/v1.1.1
1. **Contact Person**: Balamma/Niranjan

## *Other Details*
No

**Comment by sravanthimodepu** [comment]
@BalammaBoya hosted the lab, please check and let us know if the changes are not reflected.

**Lab URL:** http://cse18-iiith.vlabs.ac.in/

**Comment by pavanchow** [comment]
Duplicate. Find the main issue at https://github.com/virtual-labs/engineers-forum/issues/597.
