### ISSUE TITLE
Hosting Request forcomputer-organization-iiith

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#532]
## *Hosting Details*
*The Request will be deployed on the infrastructure requested through the latest on-boarding request. Please raise an updated on-boarding request if extra resoures are required for this hosting request.*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name** : computer-organization-iiith
1. **Repo URL**: https://github.com/virtual-labs/computer-organization-iiith
1. **Branch/Tag**: master/v1.1.1
1. **Contact Person**:  Balamma/Niranjan

## *Other Details*
No

**Comment by sravanthimodepu** [comment]
@BalammaBoya hosted the lab, please check and let us know if the changes are not updated

**Comment by BalammaBoya** [comment]
@sravanthimodepu Changes are updated. 

Here is the experiment1 page (same thing effected for all the experiments).

![Screenshot from 2020-03-12 09-49-54](https://user-images.githubusercontent.com/22425444/76486776-68fb2800-6446-11ea-8e9e-421b5d89401f.png)
