### ISSUE TITLE
Hosting Request for Hydraulics and Fluid Mechanics

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/engineers-forum#539]
## *Hosting Details*
*The Request will be deployed on the infrastructure requested through the latest onboarding request. Please raise an updated onboarding request if extra resources are required for this hosting request.*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name**: Hydraulics and Fluid Mechanics
1. **Repo URL**: https://github.com/virtual-labs/hydraulics-and-fluid-mechanics-iiith
1. **Branch/Tag**: master / v1.1.2
1. **Contact Person**: Sravanthi/Mrudhvika

## *Other Details*
No

**Comment by pavanchow** [comment]
Duplicate. Use https://github.com/virtual-labs/engineers-forum/issues/717 for Hydraulics and Fluid Mechanics hosting/re-hosting
