### ISSUE TITLE
Repository for  Population ecology Virtual Lab II

### ISSUE THREAD

**Issue by AmulyaSri** [Virtual-Labs/engineers-forum#54]
Srijith from Amrita university requested to create repository for following lab 

Lab Name: Population ecology Virtual Lab II
Discipline name: Biotechnology and Biomedical Engineering
Institute name: Amrita University

Repository permission needed for the following github usernames
sreejithsr-amrita
sruthimangala
praveenscreate
anuuuanitha​

**Comment by soujanya123** [comment]
Here is the url for the above requested lab https://github.com/Virtual-Labs/population-ecology-virtual-lab-ii-au

Also, all the integrators mentioned above have the permissions to make changes to this repository.
