### ISSUE TITLE
Hosting Request for Basic Engineering Mechanics and Strength of Materials

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/engineers-forum#540]
## *Hosting Details*
*The Request will be deployed on the infrastructure requested through the latest on-boarding request. Please raise an updated on-boarding request if extra resources are required for this hosting request.*

**Request Type**:
  - [ ] Urgent
#### Note: All of the following request parameters are mandatory. Please do not remove or leave blank any fields.

1. **Hosting Unit(Lab/Experiment) Name**: Basic Engineering Mechanics and Strength of Materials
1. **Repo URL**: https://github.com/virtual-labs/basic-engineering-mechanics-and-strength-of-materials-iiith
1. **Branch/Tag**: master / v1.1.2
1. **Contact Person**: Sravanthi/Mrudhvika

## *Other Details*
No

**Comment by pavanchow** [comment]
The issue for Basic Engineering Mechanics and Strength of Materials Lab already exists https://github.com/virtual-labs/engineers-forum/issues/518. Duplicate issue.
