### ISSUE TITLE
Hosting of Metal-Forming Lab and Virtual-Power Lab

### ISSUE THREAD

**Issue by ajaykant00** [Virtual-Labs/engineers-forum#56]
Dear Sir/Madam,
The labs which we have hosted are not running.
Please host these labs again.
Following is the url of Metal Forming Virtual Simulation Lab on Github Portal

https://github.com/Virtual-Labs/metal-forming-virtual-simulation-lab-dei
The dependencies are hph5 and mysql2

The url for Virtual Power Lab on Github Portal is
https://github.com/Virtual-Labs/virtual-power-lab-dei
The dependencies are hph5 and mysql2

**Comment by jayanthsagar** [comment]
Hi ajaykant,

Thanks for version controlling your sources.
We have tried deploying your lab using Automated Deployment service and its taking so much time as your lab source size is big.
Is there any way to reduce the size of your lab?
I think its php5 in your dependencies not hph5. correct it

**Comment by ecthiender** [comment]
I am closing this issue.

Once you have fixed the labs, please raise issues "request for hosting" separately for each lab.

Thanks.
