### ISSUE TITLE
Hosting Request for Hydraulics and Fluid Mechanics Lab

### ISSUE THREAD

**Issue by mrudhvika940** [virtual-labs/engineers-forum#560]
**Hosting details** 
 
- Hosting Unit(Lab) Name : Hydraulics and Fluid Mechanics Lab
- Repository URL: https://github.com/virtual-labs/hydraulics-and-fluid-mechanics-iiith/tree/master
- Branch/Tag : master/v1.1.3
- Contact Person: Mrudhvika/ Sravanthi

**Comment by pavanchow** [comment]
Duplicate. Use https://github.com/virtual-labs/engineers-forum/issues/717 for Hydraulics and Fluid Mechanics hosting/re-hosting
