### ISSUE TITLE
Request to Host Labs IIT Roorkee.

### ISSUE THREAD

**Issue by vikas-kashyap** [Virtual-Labs/engineers-forum#57]
The Following four(4) labs of IIT Roorkee are at Level 5 and successfully tested.

Repo URLs:- 
1. https://github.com/Virtual-Labs/bio-medical-instrumentation-lab-iitr
2. https://github.com/Virtual-Labs/bio-medical-signal-and-image-processing-lab-iitr
3. https://github.com/Virtual-Labs/electrical-machines-lab-iitr
4. https://github.com/Virtual-Labs/surveying-lab-iitr

Please Host these labs and let me know the URLs.

**Comment by ecthiender** [comment]
I think, you have to raise separate issues for each lab.

**Comment by vikas-kashyap** [comment]
Thanks wiil do. 
Actually, I saw the following issues requesting to host multiple labs and hence raised the issue with multiple labs hosting request. 
https://github.com/Virtual-Labs/engineers-forum/issues/18
https://github.com/Virtual-Labs/engineers-forum/issues/20
https://github.com/Virtual-Labs/engineers-forum/issues/24

**Comment by jayanthsagar** [comment]
completed, commented on individual requests.

**Comment by vikas-kashyap** [comment]
Thanks again.
