### ISSUE TITLE
Hosting Request for Cryptography

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#571]
## *Hosting Request*
Use this to request hosting of an already registered lab or experiment.   If the lab or experiment is not registered, please do that by raising a registration request.

- **Hosting Unit(Lab) Name :** Cryptography 

- **Repository URL :** https://github.com/virtual-labs/cryptography-iiith

- **Branch/Tag :** master/[v1.1.1](https://github.com/virtual-labs/cryptography-iiith/releases)

- **Contact Person:** Balamma

**Comment by sravanthimodepu** [comment]
@BalammaBoya 

Hosted URL of Lab: http://cse29-iiith.vlabs.ac.in/
Branch: Master
Tag: v1.1.1

**Comment by pavanchow** [comment]
Duplicate. Please find the Cryptography lab issue at https://github.com/virtual-labs/engineers-forum/issues/574 .
