### ISSUE TITLE
Hosting Request for Hydraulics and Fluid Mechanics Lab 

### ISSUE THREAD

**Issue by mrudhvika940** [virtual-labs/engineers-forum#572]
Hosting details

- Hosting Unit(Lab) Name : Hydraulics and Fluid Mechanics Lab
- Repository URL: https://github.com/virtual-labs/hydraulics-and-fluid-mechanics-iiith/tree/master
- Branch/Tag : master/[v1.1.4](https://github.com/virtual-labs/hydraulics-and-fluid-mechanics-iiith/releases/tag/v1.1.4)
- Contact Person: Mrudhvika/ Sravanthi

**Comment by sravanthimodepu** [comment]
@mrudhvika940 

Hosted URL of Lab: http://eerc03-iiith.vlabs.ac.in/
Branch: Master
Tag: v1.1.4

**Comment by pavanchow** [comment]
Duplicate. Use https://github.com/virtual-labs/engineers-forum/issues/717 for Hydraulics and Fluid Mechanics hosting/re-hosting
