### ISSUE TITLE
Hosting Request for Hydraulics and Fluid Mechanics Lab IIITH

### ISSUE THREAD

**Issue by mrudhvika940** [virtual-labs/engineers-forum#575]
Hosting details : 

- Hosting Unit(Lab) Name : Hydraulics and Fluid Mechanics Lab
- Repository URL: https://github.com/virtual-labs/hydraulics-and-fluid-mechanics-iiith
- Branch/Tag : master/[v1.1.5](https://github.com/virtual-labs/hydraulics-and-fluid-mechanics-iiith/releases/tag/v1.1.5)
- Contact Person: Mrudhvika

**Comment by sravanthimodepu** [comment]
@mrudhvika940 

Hosted URL of Lab: http://eerc03-iiith.vlabs.ac.in/
Branch: Master
Tag: v1.1.5

**Comment by BalammaBoya** [comment]
@pavanchow Request to rehost the experiments:

This issue also is used to host labs and their experiments that have been migrated from flash to JavaScript and updated content. 

 | **S.No**.| **Experiment Name** | **Experiment repository URL** | Branch |Tag |
 |1.  |Bernoulli's Experiment  | https://github.com/virtual-labs/exp-bernoullis-iiith  | main | v1.0.0 |
 |2.  |Venturi Meter Experiment  | https://github.com/virtual-labs/exp-venturi-meter-iiith | main | v1.0.0 |
 |3.  |Orifices Experiment  | https://github.com/virtual-labs/exp-orifices-iiith |main | v1.0.0 |
 |4.  |Mouthpieces Experiment | https://github.com/virtual-labs/exp-mouthpieces-iiith |main | v1.0.0 |
 |5.  |Weirs Experiment  | https://github.com/virtual-labs/exp-weirs-iiith |main | v1.0.0 |
 |6.  |Channels Experiment | https://github.com/virtual-labs/exp-channels-iiith |main | v1.0.0 |
 |7.  |Reynold's Experiment  | https://github.com/virtual-labs/exp-reynolds-iiith |main | v1.0.0 |
 |8.  |Jets Experiment  | https://github.com/virtual-labs/exp-jets-iiith |main | v1.0.0 |
 |9.  |Turbines Experiment  | https://github.com/virtual-labs/exp-turbines-iiith |main | v1.0.0 |

**Note: These new repositories which migrated from flash to java script. So tags started from v1.0.0**

**Comment by pavanchow** [comment]
@BalammaBoya Please create a hosting as shown in this [link](https://github.com/virtual-labs/engineers-forum/issues/647) for converted labs.

**Comment by BalammaBoya** [comment]
Created new [issue](https://github.com/virtual-labs/engineers-forum/issues/717). Please check and rehost.

**Comment by BalammaBoya** [comment]
**Lab Name** : Hydraulics and Fluid Mechanics

**Note :** This lab experiments doesn't have any back end dependence for hosting.

**Comment by pavanchow** [comment]
Duplicate. Use https://github.com/virtual-labs/engineers-forum/issues/717 for Hydraulics and Fluid Mechanics hosting/re-hosting
