### ISSUE TITLE
Request to Host Biomedical Instrumentation Lab IIT Roorkee.

### ISSUE THREAD

**Issue by vikas-kashyap** [Virtual-Labs/engineers-forum#58]
The Biomedical Instrumentation Lab IIT Roorkee is at level 5 and tested.

Repo URL:

https://github.com/Virtual-Labs/bio-medical-instrumentation-lab-iitr

Please Host the lab and let me know the URL.

**Comment by jayanthsagar** [comment]
Hi vikas,

Your lab is deployed.
you can access your lab using http://bmi-iitr.vlabs.ac.in/

Please check it and reply if we are missing anything.

**Comment by jayanthsagar** [comment]
Hi vikas,

Your lab is deployed.
you can access your lab using http://bmi-iitr.vlabs.ac.in/

Please check it and reply if we are missing anything.

**Comment by vikas-kashyap** [comment]
Thanks, It's working Fine.

**Comment by vikas-kashyap** [comment]
Some changes have been made to the code, Please redeploy the bmi lab

Repo URL:

https://github.com/Virtual-Labs/bio-medical-instrumentation-lab-iitr

**Comment by jayanthsagar** [comment]
Redeployed. please check

**Comment by vikas-kashyap** [comment]
Thanks, It's working fine.
