### ISSUE TITLE
@priya100raman @sravanthimodepu Request to rehost  Experiment Name Source URL Branch Tag Build Command

### ISSUE THREAD

**Issue by SOLVE-NITK** [virtual-labs/engineers-forum#581]
Performance Characteristics of Centrifugal Pump - 
http://vlabs.iitb.ac.in/gitlab/vlabs-dev-central-hosting/fluid-machinery-nitk/performance-characteristics-centrifugal-pump-nitk.git, Master Branch, v1.0.1, make all
Performance Characteristics of Hydraulic Ram - http://vlabs.iitb.ac.in/gitlab/vlabs-dev-central-hosting/fluid-machinery-nitk/performance-characteristics-hydraulic-ram-nitk.git, Master Branch, v1.0.1, make all
Performance Characteristics of Kaplan Turbine - http://vlabs.iitb.ac.in/gitlab/vlabs-dev-central-hosting/fluid-machinery-nitk/performance-characteristics-kaplan-turbine-nitk.git, Master Branch, v1.0.1, make all
Double Acting Reciprocating Pump - http://vlabs.iitb.ac.in/gitlab/vlabs-dev-central-hosting/fluid-machinery-nitk/double-acting-reciprocating-pump-nitk.git, Master Branch, v1.0.1, make all
Pipe Bursting - http://vlabs.iitb.ac.in/gitlab/vlabs-dev-central-hosting/fluid-machinery-nitk/pipe-bursting-nitk.git, Master Branch, v1.0.1, make all
Performance Characteristics of Pelton Turbine - http://vlabs.iitb.ac.in/gitlab/vlabs-dev-central-hosting/fluid-machinery-nitk/performance-characteristics-pelton-turbine-nitk.git, Master Branch, v1.0.1, make all
Performance Characteristics of Francis Turbine - http://vlabs.iitb.ac.in/gitlab/vlabs-dev-central-hosting/fluid-machinery-nitk/performance-characteristics-francis-turbine-nitk.git, Master Branch, v1.0.1, make all

**Comment by priya100raman** [comment]
@SOLVE-NITK , we are closing this issue and adding this request as part of the onboarding request of the Fluid Machinery lab so as to preserve the history of the Fluid Machinery Lab hosting  and follow the step 2 of the defined process -. We will be updating the status of the rehosting of these experiments  on [this](https://github.com/virtual-labs/engineers-forum/issues/533) issue. 

The process for changing the content of the experiment and hosting the experiment  was clarified by IIITH
Step 1 -  Make the necessary changes to the experiment content in the experiment repository on GitLab ( IITB server ) as per the process followed during experiment development.  After you make the  changes to the experiment sources , you will need to  tag it.
**Step 2 - Follow the link  and  locate the Phase III Lab/Experiment(s) OnBoarding Request issue corresponding to the lab containing the experiment  that you wish to rehost.**
Step 3 - Comment on the same Phase III Lab/Experiment(s) OnBoarding Request  with the following text  "Request to rehost  the experiment  <exp repo link> with the tag <tag number>" You may include more than one experiment ( belonging to the same lab) rehosting request at a time.
Step 4 - Our hosting engineer will host the experiments  and share the link on the same issue to seek approval from you.
Step 5 - You will need to  test the hosted link and  comment on the same issue stating your approval.
