### ISSUE TITLE
Hosting Request for Structural Dynamics Lab IIITH

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/engineers-forum#594]
## *Hosting Request*
Use this to request the hosting of an already registered lab or experiment.   If the lab or experiment is not registered, please do that by raising a registration request.

- **Hosting Unit(Lab) Name:** Structural Dynamics Lab
- **Repository URL:** https://github.com/virtual-labs/structural-dynamics-iiith
- **Branch/Tag :** master/[v1.1.3](https://github.com/virtual-labs/structural-dynamics-iiith/releases/tag/v1.1.3)
- **Contact Person:** Sravanthi

**Comment by sravanthimodepu** [comment]
@sravanthimodepu 

HOsted URL of Lab: http://sd-iiith.vlabs.ac.in/
Branch: Master
Tag: v1.1.3

**Comment by sravanthimodepu** [comment]
## *Hosting Request*
Use this to request the hosting of an already registered lab or experiment.   If the lab or experiment is not registered, please do that by raising a registration request.

- **Hosting Unit(Lab) Name:** Structural Dynamics Lab
- **Repository URL:** https://github.com/virtual-labs/structural-dynamics-iiith
- **Branch/Tag :** master/[v1.1.499](https://github.com/virtual-labs/structural-dynamics-iiith/releases/tag/v1.1.4)
- **Contact Person:** Sravanthi

**Comment by pavanchow** [comment]
@sravanthimodepu

Hosted URL of Lab: http://sd-iiith.vlabs.ac.in/
Branch: Master
Tag: v1.1.4
Please check and approve

**Comment by sravanthimodepu** [comment]
## * Request to re-host*

- **Hosting Unit(Lab) Name:** Structural Dynamics Lab
- **Repository URL:** https://github.com/virtual-labs/structural-dynamics-iiith
- **Branch/Tag :** master/[v1.1.6](https://github.com/virtual-labs/structural-dynamics-iiith/releases/tag/v1.1.6)
- **Contact Person:** Sravanthi

**Comment by pavanchow** [comment]
@sravanthimodepu 

Hosted **Structural Dynamics Lab**
URL of Lab: https://sd-iiith.vlabs.ac.in/
Branch: Master
Tag: v1.1.6

Please check and approve.
**NOTE: IF NOT APPROVED WITHIN 3 DAYS, SOURCES WILL BE AUTOMATICALLY REVERTED TO OLDER VERSION.**

**Comment by pavanchow** [comment]
@sravanthimodepu 
Due to lack of confirmation sources will be reverted back to the older version on 27-05-2020.

**Comment by sravanthimodepu** [comment]
## Request to re-host

- **Hosting Unit(Lab) Name:** Structural Dynamics Lab
- **Repository URL:** https://github.com/virtual-labs/structural-dynamics-iiith
- **Branch/Tag :** master/[v1.1.7](https://github.com/virtual-labs/structural-dynamics-iiith/releases/tag/v1.1.7)
- **Contact Person:** Sravanthi

**Comment by pavanchow** [comment]
@sravanthimodepu

Hosted Structural Dynamics Lab
URL of Lab: https://sd-iiith.vlabs.ac.in/
Branch: Master
Tag: v1.1.7

Please check and approve.

**Comment by BalammaBoya** [comment]
@pavanchow Request to rehost the experiments:

This issue also is used to host labs and their experiments that have been migrated from flash to JavaScript and updated content. 

 | **S.No**.| **Experiment Name** | **Experiment repository URL** | Branch |Tag |
| 1. | Simple Harmonic Oscillator | https://github.com/virtual-labs/exp-simple-harmonic-oscillator-iiith | main | v1.0.1 |
|  2. | Free Vibration of S.D.O.F System | https://github.com/virtual-labs/exp-free-vibration-iiith | main |   v1.0.0 |
| 3. | Forced Vibration of S.D.O.F System | https://github.com/virtual-labs/exp-forced-vibration-iiith | main |   v1.0.0 |
| 4. | Impulse Response of S.D.O.F System | https://github.com/virtual-labs/exp-impulse-response-iiith | main |   v1.0.1 |
| 5. | Concept of Response Spectrum | https://github.com/virtual-labs/exp-response-spectrum-iiith | main |   v1.0.0 |
| 6. | Vibration of M.D.O.F System | https://github.com/virtual-labs/exp-vibration-of-mdof-iiith | main |   v1.0.0 |
| 7. | Behaviour of Rigid Blocks | https://github.com/virtual-labs/exp-behaviour-rigid-blocks-iiith | main |   v1.0.1 |
| 8. | Torsional Response of Building | https://github.com/virtual-labs/exp-torsional-response-iiith | main |  v1.0.1 |
| 9. | Continuous Systems | https://github.com/virtual-labs/exp-continuous-systems-iiith | main |   v1.0.1 |
| 10. | Vibration Control | https://github.com/virtual-labs/exp-vibration-control-iiith | main |   v1.0.1 |

**Note: These new repositories which migrated from flash to java script. So tags started from v1.0.0 and so**

**Comment by pavanchow** [comment]
Duplicate. Please find the Structural Dynamics issue on   https://github.com/virtual-labs/engineers-forum/issues/718
