### ISSUE TITLE
Request to host Binary Search Tree and KMP Experiments

### ISSUE THREAD

**Issue by niranjanreddy891** [virtual-labs/engineers-forum#595]
| 1. | Binary Search Tree | https://gitlab.com/vlead-projects/experiments/ds/binary-search-trees | master branch | make -k all | content-html | artefacts 

| 2. | KMP Algorithm | https://gitlab.com/vlead-projects/experiments/ds/kmp-algorithm | master branch | make -k all | content-html | artefacts

**Comment by pavanchow** [comment]
DS related hosting requests to be raised on [DS1](https://github.com/virtual-labs/engineers-forum/issues/534) and [DS2](https://github.com/virtual-labs/engineers-forum/issues/535). Please discard this issue and relocate to [DS1](https://github.com/virtual-labs/engineers-forum/issues/534) or [DS2](https://github.com/virtual-labs/engineers-forum/issues/535)

**Comment by priya100raman** [comment]
@niranjanreddy891 , close this issue
