### ISSUE TITLE
Hosting Request for Quantum Chemistry

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/engineers-forum#599]
## *Hosting Request*
Use this to request the hosting of an already registered lab or experiment. If the lab or experiment is not registered, please do that by raising a registration request.

- **Hosting Unit(Lab) Name:** Qunatum Chemistry Lab
- **Repository URL:** https://github.com/virtual-labs/quantum-chemistry-iiith
- **Branch/Tag :** master/[v1.1.3](https://github.com/virtual-labs/quantum-chemistry-iiith/releases/tag/v1.1.3)
- **Contact Person:** Sravanthi

**Comment by sravanthimodepu** [comment]
@sravanthimodepu

Hosted URL of Lab: http://ccnsb04-iiith.vlabs.ac.in/
Branch: Master
Tag: v1.1.4

**Comment by pavanchow** [comment]
Duplicate. Find Quantum Chemistry issue on https://github.com/virtual-labs/engineers-forum/issues/711 .
