### ISSUE TITLE
Artificial Neural Networks Lab

### ISSUE THREAD

**Issue by soujanya123** [Virtual-Labs/engineers-forum#6]
The Artificial Neural Networks Lab is from IIIT-H.
The lab is at level 5.
The lab sources are versioned here at: 
https://github.com/Virtual-Labs/artificial-neural-networks-iiith 
Please host this lab and let us know the url.

**Comment by ecthiender** [comment]
Who has taken this up? Please reply with the current status of the ticket.

**Comment by travula** [comment]
Hello zubair and Prakash, 

Can you pls refer to the 'Integration Processes' on vlead wiki. Can you pls meet at 4:00 pm everyday and assign the tasks to  indivuduals. Anon can also join you.

- Thirumal

**Comment by ayogi** [comment]
I am working on this, I will host the lab and update the status.

**Comment by ayogi** [comment]
Hello All,

Artificial Neural Networks lab is hosted on cloud.
URL of the lab is "artificial-nn.virtual-labs.ac.in".
If there is any other issue please let me know.

Thankyou.
