### ISSUE TITLE
Request to Host Electrical Machines Lab IIT Roorkee.

### ISSUE THREAD

**Issue by vikas-kashyap** [Virtual-Labs/engineers-forum#60]
The Electrical Machines Lab IIT Roorkee is at level 5 and tested.

Repo URL:

https://github.com/Virtual-Labs/electrical-machines-lab-iitr

Please Host the lab and let me know the URL.

**Comment by jayanthsagar** [comment]
Hi vikas,

Your lab is deployed.
you can access your lab using http://em-iitr.vlabs.ac.in/

Please check it and reply if we are missing anything.

**Comment by vikas-kashyap** [comment]
Thanks, It's working Fine.

**Comment by vikas-kashyap** [comment]
Some changes have been made to code, Please redeploy the machine lab

Repo URL:

https://github.com/Virtual-Labs/electrical-machines-lab-iitr

**Comment by jayanthsagar** [comment]
Redeployed. please check

**Comment by vikas-kashyap** [comment]
Thanks, It's working fine.
