### ISSUE TITLE
bio-medical-and-signal-processing-laboratory-coep rehosting request

### ISSUE THREAD

**Issue by sushilmedhe** [virtual-labs/engineers-forum#601]
## *Hosting Request*

lab name : bio-medical-and-signal-processing-laboratory-coep

Repo URL : https://github.com/virtual-labs/bio-medical-and-signal-processing-laboratory-coep

**Comment by sravanthimodepu** [comment]
@sushilmedhe 

Could you please mention the tag and branch to host the lab

**Comment by sushilmedhe** [comment]
New issue created with update.
