### ISSUE TITLE
bio-medical-and-signal-processing-laboratory-coep rehosting request

### ISSUE THREAD

**Issue by sushilmedhe** [virtual-labs/engineers-forum#602]
## *Hosting Request*

lab name : bio-medical-and-signal-processing-laboratory-coep
Repo URL : https://github.com/virtual-labs/bio-medical-and-signal-processing-laboratory-coep
Branch/Tag : master/v1.1.0
Contact Person: Vaibhav

**Comment by sravanthimodepu** [comment]
@sushilmedhe
 
Hosted URL of Lab: https://bmsp-coep.vlabs.ac.in/
Branch: Master
Tag: v1.1.0
