### ISSUE TITLE
bio-medical-and-signal-processing-laboratory-coep

### ISSUE THREAD

**Issue by sushilmedhe** [virtual-labs/engineers-forum#605]
lab name : bio-medical-and-signal-processing-laboratory-coep
Repo URL : https://github.com/virtual-labs/bio-medical-and-signal-processing-laboratory-coep
Branch/Tag : master/v1.2.0
Contact Person: Vaibhav

**Comment by sravanthimodepu** [comment]
@sushilmedhe,

While hosting the lab, it is saying that the sources are up-to-date, couldn't find the latest source and I have hosted the lab 2days back. If you have updated the sources after that, please check whether you have pushed the sources to git.

**Comment by sushilmedhe** [comment]
Two days back I have modified a file on GitHub itself, we hosted the lab but the changes I have done are not reflect.  Then created new version of that source and the new tag is generated. I am modifying a file can you please try to host it again?

**Comment by sravanthimodepu** [comment]
@sushilmedhe 

Hosted URL of Lab: http://bmsp-coep.vlabs.ac.in
Branch: Master
Tag: v1.2.0

**Comment by sushilmedhe** [comment]
Hi,
I have updated code twice and hosted by you with a new release and tag. Still, the changes made by me are not reflected in the latest hosted URL. I can not even clone the lab on my local machine. Other labs from cope I can clone but this lab give me the error as-

git.exe clone --progress -v "https://github.com/virtual-labs/bio-medical-and-signal-processing-laboratory-coep" "C:\Users\Amol\Downloads\WHF_vlab\Github\bio-medical-and-signal-processing-laboratory-coep"
Cloning into 'C:\Users\Amol\Downloads\WHF_vlab\Github\bio-medical-and-signal-processing-laboratory-coep'...
POST git-upload-pack (152 bytes)
POST git-upload-pack (490 bytes)
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 1326 (delta 5), reused 0 (delta 0), pack-reused 1314
Receiving objects: 100% (1326/1326), 15.90 MiB | 616.00 KiB/s, done.
Resolving deltas: 100% (713/713), done.
error: invalid path 'src/lab/LeadECG/?'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

git did not exit cleanly (exit code 128) (30672 ms @ 25-07-2020 09:51:36)

Please do check and give me the suggestion.

**Comment by sravanthimodepu** [comment]
Hi,

I am able to clone the repository and can build the sources. Could you please try the command "git clone https://github.com/virtual-labs/bio-medical-and-signal-processing-laboratory-coep" to clone the repository and ley me know if you finf issues.

I will check and rehost the lab again.

**Comment by sushilmedhe** [comment]
I am getting same error again to clone the lab using tortoise git on the windows machine. I did the same for "programmable-logic-controller-coep" lab its successful.

Please check the screenshot.
![Error](https://user-images.githubusercontent.com/8788705/88505292-b989b100-cff4-11ea-8628-a23c87ce77fc.png)

**Comment by sravanthimodepu** [comment]
I have seen the screenshot shared by you, could you please ask Vaibhav to follow the couple of suggestions to clone the repo which are given below:
1. clone the repository in a different directory or
2. revert and stash the changes -> push to the repo.

After that make the latest changes and push them to git and please let us know still if the issue exists.

**Comment by sravanthimodepu** [comment]
@sushilmedhe

Hosted URL of Lab: http://bmsp-coep.vlabs.ac.in
Branch: Master
Tag: v1.2.0

Please check and confirm

**Comment by sushilmedhe** [comment]
Hosted URL reflects the modificaions. Thank you.
