### ISSUE TITLE
Programmable logic controller - coep

### ISSUE THREAD

**Issue by sushilmedhe** [virtual-labs/engineers-forum#606]
lab name : programmable-logic-controller-coep
Repo URL : https://github.com/virtual-labs/programmable-logic-controller-coep
Branch/Tag : master/v1.2.0
Contact Person: Vaibhav

**Comment by sravanthimodepu** [comment]
@sushilmedhe 

Hosted URL of Lab: http://plc-coep.vlabs.ac.in
Branch: Master
Tag: v1.2.0

**Comment by sushilmedhe** [comment]
Thank you.
