### ISSUE TITLE
Request to Host Surveying Lab IIT Roorkee.

### ISSUE THREAD

**Issue by vikas-kashyap** [Virtual-Labs/engineers-forum#61]
The Surveying Lab IIT Roorkee is at level 5 and tested.

Repo URL:

https://github.com/Virtual-Labs/surveying-lab-iitr

Please Host the lab and let me know the URL.

**Comment by jayanthsagar** [comment]
Hi vikas,

You lab is deployed.
you can access your lab on http://sl-iitr.vlabs.ac.in/

Please check it and reply if we are missing anything.

**Comment by vikas-kashyap** [comment]
Thanks, It's working Fine.
