### ISSUE TITLE
Hosting request for IITG Vlabs

### ISSUE THREAD

**Issue by vlabs-iitg** [Virtual-Labs/engineers-forum#62]
The following 4 Virtual labs (available at https://github.com/vlabs-iitg) are now at level 5. We have tested them on CentOS, Fedora and Ubuntu (using Desktop PCs).

1) Anthropology (available at https://github.com/vlabs-iitg/IITG_anthropology)
2) Ergonomics (available at https://github.com/vlabs-iitg/IITG_ergonomics)
3) Electrical Machines Laboratory (available at https://github.com/vlabs-iitg/IITG_virtual_electrical_mechine)
4) Virtual English (available at https://github.com/vlabs-iitg/IITG_virtual_english)

We feel that they are ready for deployment to the cloud. However, as this is the first time we are going for a cloud implementation there may be some issues. Please do let us know of problems and we will try to solve them.

Regards,
Vlab Integration Team IITG

**Comment by jayanthsagar** [comment]
Hi Vlab integration Team IITG,

Thanks for version controlling your lab sources. 
We are facing issues with deployment of your labs as the labspec.json(a deployment spec for lab) file is not available in your sources.
I am attaching link of a L5 lab, please follow the same https://github.com/Virtual-Labs/computer-programming-iiith
We require labspec.json in scripts folder. verify the labspec.json file given in above repo url.
Please update your repo.

**Comment by bijudas45** [comment]
Hi Jayanth,
Sorry for the late reply as I was on leave.
We are editing the labspec.json files for all our labs and the same will be
uploaded in the scripts folder by 5th May, 2015 as IIT Guwahati remain
closed during the weekend and 4th May is a public holiday.



On Tue, Apr 28, 2015 at 12:34 PM, jayanth sagar <notifications@github.com>
wrote:

> Hi Vlab integration Team IITG,
>
> Thanks for version controlling your lab sources.
> We are facing issues with deployment of your labs as the labspec.json(a
> deployment spec for lab) file is not available in your sources.
> I am attaching link of a L5 lab, please follow the same
> https://github.com/Virtual-Labs/computer-programming-iiith
> We require labspec.json in scripts folder. verify the labspec.json file
> given in above repo url.
> Please update your repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Virtual-Labs/engineers-forum/issues/62#issuecomment-96952059>
> .
>



-- 
Regards,
Biju Das

**Comment by vlabs-iitg** [comment]
Hi Jayanth,

We have uploaded the "labspec.jsoan" file for the Virtual English Lab available at "https://github.com/vlabs-iitg/IITG_virtual_english/tree/master/scripts". Once you confirm that this is ok. We will repeat the same for the other three labs.

Thanks,
IITG Integration Team

**Comment by jayanthsagar** [comment]
A simple fix is required.
Please remove " , " in line 50 after " }".

**Comment by vlabs-iitg** [comment]
We have removed " , " in line 50. Please check now.

Thanks,
IITG VLab Integration Team

**Comment by jayanthsagar** [comment]
[D 150505 06:03:10 Controller:24] test_lab() for lab ID test and git url https://github.com/vlabs-iitg/IITG_virtual_english
[D 150505 06:03:10 LabManager:18] Will return lab spec
[D 150505 06:03:10 git_commands:25] lab_src_url: https://github.com/vlabs-iitg/IITG_virtual_english
[D 150505 06:03:10 git_commands:28] repo_name: IITG_virtual_english
[D 150505 06:03:10 git_commands:51] pull cmd: git --git-dir=/root/labs/IITG_virtual_english/.git pull
[D 150505 06:03:10 execute_commands:27] command: git --git-dir=/root/labs/IITG_virtual_english/.git pull
[D 150505 06:03:11 git_commands:54] Pull repo successful
[D 150505 06:03:11 git_commands:90] spec_file_path: /root/labs/IITG_virtual_english/scripts/labspec.json
[E 150505 06:03:11 git_commands:97] Lab spec JSON invalid: Expecting object: line 52 column 13 (char 1752)
[E 150505 06:03:11 LabManager:31] Error: 
[E 150505 06:03:11 Controller:55] test_lab(): Test failed with error:

**Comment by vlabs-iitg** [comment]
In our "labspec.json" file the line #49 to 53 reads as:
------------------------------------------------------------------------------------------------
49                    "web": ""
50                } 
51
52            ], 
53            "discipline": [
------------------------------------------------------------------------------------------------
We have check for the validity by parsing this file at http://jsonlint.com/, and it shows that it is a valid JSON file. We are unable to debug at our end - Please help.

**Comment by jayanthsagar** [comment]
Hi,
We have deployed your labs on AWS. You can access labs using following links.

http://anthropology-iitg.vlabs.ac.in
http://ergonomics-iitg.vlabs.ac.in
http://vem-iitg.vlabs.ac.in
http://ve-iitg.vlabs.ac.in

Please check it and reply if we are missing anything.
Thanks.
