### ISSUE TITLE
Physical Sciences Error

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/engineers-forum#63]
When I run physical-sciences-iiith lab over ADS and I get the following error:

test_lab() for lab ID physics and git url https://github.com/physical-sciences-iiith
Error: Command 'git --git-dir=/root/labs/physical-sciences-iiith/.git pull' returned non-zero exit status 104/21/2015 09:58:16 AM: 
ERROR: /home/v/ovpl/src/utils/git_commands.py:52  -> Error Pulling the repository: Command 'git --git-dir=/root/labs/physical-sciences-iiith/.git pull' returned non-zero exit status 104/21/2015 09:58:16 AM:
 ERROR: /home/v/ovpl/src/LabManager.py:31  -> Error: Command 'git --git-dir=/root/labs/physical-sciences-iiith/.git pull' returned non-zero exit status 104/21/2015 09:58:16 AM:
 ERROR: /home/v/ovpl/src/Controller.py:55  -> test_lab(): Test failed with error: Command 'git --git-dir=/root/labs/physical-sciences-iiith/.git pull' returned non-zero exit status 1

Could someone please resolve this issue.

**Comment by madhavipuliraju** [comment]
firstly, check your git version by using the following command
$ git --version
if you get the following out put, then upgrade your git version 
git version 1.7.3.4
To upgrade the git version, follow the procedure given below:
1) clone the set-up-centos sources
git clone https://github.com/vlead/setup-ovpl-centos.git
2) checkout the branch to vagrant
git checkout vagrant-setup
3) go to config file and edit the proxy settings
cd scripts
vim config.sh 
4) edit the two lines as follows in config.sh file
export http_proxy="http://proxy.iiit.ac.in:8080"
export https_proxy="http://proxy.iiit.ac.in:8080"
5) and then run install git file to upgrade the git version
./install_git.sh
Now, try deploying the lab once again using ADS

**Comment by madhavipuliraju** [comment]
firstly, check your git version by using the following command
$ git --version
if you get the following out put, then upgrade your git version
git version 1.7.3.4
To upgrade the git version, follow the procedure given below:
1) clone the set-up-centos sources
git clone https://github.com/vlead/setup-ovpl-centos.git
2) checkout the branch to vagrant
git checkout vagrant-setup
3) go to config file and edit the proxy settings
cd scripts
vim config.sh
4) edit the two lines as follows in config.sh file
export http_proxy="http://proxy.iiit.ac.in:8080"
export https_proxy="http://proxy.iiit.ac.in:8080"
5) and then run install git file to upgrade the git version
./install_git.sh
Now, try deploying the lab once again using ADS



Regards,
Madhavi

**Comment by jayanthsagar** [comment]
Hi sadhana,

*Please check these things.*

It is not clear that which lab are you testing. You mentioned that you are
not able to deploy physical sciences lab. But, in mail you specified
Physical-chemistry-iiith.

Please check the git url too. It should be something like this
*https://github.com/Virtual-Labs/physical-chemistry-iiith
<https://github.com/Virtual-Labs/physical-chemistry-iiith>*.


Please check before creating issue on github.

' ' '  When I run *physical-chemistry-iiith* lab over ADS and I get the
following error:

test_lab() for lab ID physics and git url
*https://github.com/physical-sciences-iiith
<https://github.com/physical-sciences-iiith>*
Error: Command 'git --git-dir=/root/labs/physical-sciences-iiith/.git pull'
returned non-zero exit status 104/21/2015 09:58:16 AM:
ERROR: /home/v/ovpl/src/utils/git_commands.py:52 -> Error Pulling the
repository: Command 'git --git-dir=/root/labs/physical-sciences-iiith/.git
pull' returned non-zero exit status 104/21/2015 09:58:16 AM:
ERROR: /home/v/ovpl/src/LabManager.py:31 -> Error: Command 'git
--git-dir=/root/labs/physical-sciences-iiith/.git pull' returned non-zero
exit status 104/21/2015 09:58:16 AM:
ERROR: /home/v/ovpl/src/Controller.py:55 -> test_lab(): Test failed with
error: Command 'git --git-dir=/root/labs/physical-sciences-iiith/.git pull'
returned non-zero exit status 1

Could someone please resolve this issue. ' ' '

PS: The issues on github are increasing day by day, please check before
creating issue.

Regards,
Jayanth sagar.

**Comment by barjatiyasaurabh** [comment]
Test comment.  Please ignore.
