### ISSUE TITLE
request for hosting NITK labs

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#64]
Dear Sir/Madam,

Our labs are at level 5(Chemical, Mechanical,Civil, Electrical).
Please check them and host the labs.

Chemical: - Unit Operation,Reaction Engg. & Process Control .
Civil : - Fluid Mechanics, Strength of Materials .
Electrical : - Substation Automation, Industrial Electric Drives .
Mechanical : - Machine Dynamics and Mechanical Vibrations, Mechanics of Machine.

  Repository name is given below  :-  

" https://github.com/Virtual-Labs/students-online-laboratory-through-virtual-experimentation-nitk.git "

Regards
Vlab, NITK

**Comment by jayanthsagar** [comment]
Hi,

I t looks like you have pushed all your sources to a single repo. We at VLEAD use ADS(Automated Deployment Service) to deploy single lab on single VM. It wont be possible, If  repo is a collective of all your lab sources.

Please split your sources to individual repo and create request for each lab.
Please refer the following link for a better idea https://github.com/Virtual-Labs/computer-programming-iiith

Thanks.
