### ISSUE TITLE
Request to host the lab Population ecology Virtual Lab II - Amrita university

### ISSUE THREAD

**Issue by sreejithsr-amrita** [Virtual-Labs/engineers-forum#65]
Dear Vlead Team,

Please host the lab Population ecology Virtual Lab II of Amrita University.

Github url: https://github.com/Virtual-Labs/population-ecology-virtual-lab-ii-au

**Comment by jayanthsagar** [comment]
Is this a new lab or the old lab(https://github.com/Virtual-Labs/population-ecology-virtual-lab-i-au) with changes pushed to new repo?

**Comment by sreejithsr-amrita** [comment]
new lab

**Comment by jayanthsagar** [comment]
Hi sreejith,

We have hosted your lab. access your lab using http://pevii-au.vlabs.ac.in/
comment, if we are missing anything.
