### ISSUE TITLE
Phase III Lab/Experiment(s) OnBoarding Request for 3D Printer Virtual Simulation Lab

### ISSUE THREAD

**Issue by ajaykant00** [virtual-labs/engineers-forum#651]
Repo Owner Details
Name - Ajay Kant
GitHub handle -
Email id - ajaykant900@gmail.com 

[R0-3D Printing Virtual Simulation Lab.pdf](https://github.com/virtual-labs/engineers-forum/files/5794538/R0-3D.Printing.Virtual.Simulation.Lab.pdf)

Experiment Name Source URL Branch Tag Build Command

FDM Anatomy of 3D Printer Machine
https://github.com/virtual-labs/exp-simulation-anatomy-fdm-dei.git
Dev Branch, v1.0.0, make all

**Comment by pavanchow** [comment]
@ajaykant00 Only 1 experiment needs to be hosted from 3D Printer Virtual Simulation Lab?

**Comment by priya100raman** [comment]
According to the Repository Creation Request (#633), there are 12 experiments.

**Comment by ajaykant00** [comment]
@pavanchow 
@priya100raman 

We want to host only 4 experiments. Three experiments out of 4 are hosted in previouse OnBoarding request #623. Only one experiment was generating permission error. Now we have uploaded it seperately on github.
Other experiments out of 12 are under development.

**Comment by pavanchow** [comment]
This issue is being tracked on [623](https://github.com/virtual-labs/engineers-forum/issues/623). Closing this issue.
