### ISSUE TITLE
Not able to push the repository on GitHub - Help required

### ISSUE THREAD

**Issue by vaibhavkurhe27** [virtual-labs/engineers-forum#657]
@priya100raman @pavanchow 
I am getting this error while I push the code on GitHub using tortoise git on the windows machine. The login details which I am using are working directly on GitHub but the same are not allowing me to upload the content using push operation.

![image_2021_01_18T06_42_29_911Z](https://user-images.githubusercontent.com/75834874/104880955-7ea27d80-5986-11eb-8e6d-25f9cc460886.png)

git.exe push --progress "origin" main:dev

Logon failed, use ctrl+c to cancel basic credential prompt.
remote: Permission to virtual-labs/exp-transmitter-level-control-coep.git denied to vaibhavkurhe27.
fatal: unable to access 'https://github.com/virtual-labs/exp-transmitter-level-control-coep.git/': The requested URL returned error: 403

git did not exit cleanly (exit code 128) (44257 ms @ 1/18/2021 12:01:12 PM)

**Comment by pavanchow** [comment]
@vaibhavkurhe27 Please accept invitations for "Process Loop Components COEP" experiments. {exp-url}+/invitations
exp: https://github.com/virtual-labs/exp-transmitter-level-control-coep/invitations

**Comment by vaibhavkurhe27** [comment]
It says the invitation is expired. Probably All invitations are expired for which I have asked to create the repo in the issue https://github.com/virtual-labs/engineers-forum/issues/629

**Comment by pavanchow** [comment]
@vaibhavkurhe27 Resent invitations to GitHub Handle: @vaibhavkurhe27 Please check and close this issue.

**Comment by vaibhavkurhe27** [comment]
@pavanchow can you please resend invitation for the experiments mentioned in the issue https://github.com/virtual-labs/engineers-forum/issues/629 for vaibhavkurhe27 username.

I need to upload code for all the experiments and it does not allow me.

**Comment by pavanchow** [comment]
@vaibhavkurhe27 
Accept invitations before they expire,

https://github.com/virtual-labs/exp-interlocking-pressure-loop-coep/invitations
https://github.com/virtual-labs/exp-interlocking-flow-loop-coep/invitations
https://github.com/virtual-labs/exp-annunciator-level-control-coep/invitations
https://github.com/virtual-labs/exp-annunciator-temperature-control-coep/invitations
https://github.com/virtual-labs/exp-annunciator-pressure-control-coep/invitations
https://github.com/virtual-labs/exp-annunciator-flow-control-coep/invitations
https://github.com/virtual-labs/exp-time-to-empty-tank-coep/invitations

**Comment by vaibhavkurhe27** [comment]
@pavanchow you have not sent an invitation for this experiment. Please send it to vaibhavkurhe27 username. #629 issue has all experiment list in which for this experiment you have written wrong repo URL. So, it might happen.

https://virtual-labs.github.io/exp-ip-flow-control-coep

**Comment by pavanchow** [comment]
@vaibhavkurhe27 You have already accepted the invitation to that experiment and all the experiments in #629 : https://github.com/virtual-labs/exp-ip-flow-control-coep Coming to the repo URL, we are looking into this issue. 

![image](https://user-images.githubusercontent.com/24794698/105158434-f95ccb80-5b33-11eb-863b-28ea2d790a06.png)

**Comment by vaibhavkurhe27** [comment]
The experiment does not allow me to push the experiment content. 

@pavanchow I need to ask one thing, I have uploaded 7 experiments on dev branch yesterday and merged with the testing branch but I am not able to test it on given lab URL. 

1) https://github.com/virtual-labs/exp-ip-level-control-coep
2) https://github.com/virtual-labs/exp-ip-temperature-control-coep
3) https://github.com/virtual-labs/exp-ip-pressure-control-coep
4) https://github.com/virtual-labs/exp-ip-flow-control-coep (404 - There isn't a GitHub Pages site here - error given)
5) https://github.com/virtual-labs/exp-pe-level-control-coep
6) https://github.com/virtual-labs/exp-pe-temperature-control-coep
7) https://github.com/virtual-labs/exp-pe-pressure-control-coep
8)https://github.com/virtual-labs/exp-pe-flow-control-coep (Still does not allow to push content)

Please check those URL. Inform me if I am wrong somewhere.

**Comment by vaibhavkurhe27** [comment]
@pavanchow Also look into issue #629 for the high/low selector experiment link given. There are 4 experiments available for high/low selector as(level, flow, pressure, temperature). But links are available for flow and pressure only. for level and temperature, the experiment link is given which is about pressure.

**Comment by pavanchow** [comment]
@vaibhavkurhe27 
4 high/low selector experiments are: 
 

1. Design High/Low selector for interlocking in the process industry for temperature loop: https://github.com/virtual-labs/exp-interlocking-temperature-loop-coep
2. Design High/Low selector for interlocking in the process industry for a level loop  https://github.com/virtual-labs/exp-interlocking-level-loop-coep
3. Design High/Low selector for interlocking in the process industry for pressure loop https://github.com/virtual-labs/exp-interlocking-pressure-loop-coep
4. Design High/Low selector for interlocking in the process industry for flow loop https://github.com/virtual-labs/exp-interlocking-flow-loop-coep

**Comment by vaibhavkurhe27** [comment]
I am not able to push the following experiment.
1) Design High/Low selector for interlocking in the process industry for a level loop https://github.com/virtual-labs/exp-interlocking-level-loop-coep
2) Design High/Low selector for interlocking in the process industry for temperature loop: https://github.com/virtual-labs/exp-interlocking-temperature-loop-coep
3) https://github.com/virtual-labs/exp-pe-flow-control-coep

**Comment by pavanchow** [comment]
@vaibhavkurhe27 You hadn't accepted invitations to the below repositories to push code. Please click on each link and accept invitations to push code.

1. Design High/Low selector for interlocking in the process industry for a level loop https://github.com/virtual-labs/exp-interlocking-level-loop-coep/invitations
2. Design High/Low selector for interlocking in the process industry for temperature loop: https://github.com/virtual-labs/exp-interlocking-temperature-loop-coep/invitations
3. https://github.com/virtual-labs/exp-pe-flow-control-coep/invitations

**Comment by vaibhavkurhe27** [comment]
@pavanchow all three lab invitations say the invitation has expired. Please invite me again.

**Comment by pavanchow** [comment]
Send invitations to the following experiments,

- Design High/Low selector for interlocking in the process industry for a level loop https://github.com/virtual-labs/exp-interlocking-level-loop-coep/invitations
- Design High/Low selector for interlocking in the process industry for temperature loop: https://github.com/virtual-labs/exp-interlocking-temperature-loop-coep/invitations
- https://github.com/virtual-labs/exp-pe-flow-control-coep/invitations

**Comment by pavanchow** [comment]
@vaibhavkurhe27 Sent invitations ^

**Comment by vaibhavkurhe27** [comment]
> 
> @pavanchow I need to ask one thing, I have uploaded 7 experiments on dev branch yesterday and merged with the testing branch but I am not able to test it on given lab URL.
> 
> 1. https://github.com/virtual-labs/exp-ip-level-control-coep
> 2. https://github.com/virtual-labs/exp-ip-temperature-control-coep
> 3. https://github.com/virtual-labs/exp-ip-pressure-control-coep
> 4. https://github.com/virtual-labs/exp-ip-flow-control-coep (404 - There isn't a GitHub Pages site here - error given)
> 5. https://github.com/virtual-labs/exp-pe-level-control-coep
> 6. https://github.com/virtual-labs/exp-pe-temperature-control-coep
> 7. https://github.com/virtual-labs/exp-pe-pressure-control-coep

> 
> Please check those URL. Inform me if I am wrong somewhere.


Please check and reply. it was uploaded on Tuesday or Wednesday. Still I am not able to test the lab using URL.

**Comment by priya100raman** [comment]
@vaibhavkurhe27, we are troubleshooting the issue. We will get back to you soon with a resolution.

**Comment by vaibhavkurhe27** [comment]
@pavanchow Ok. Thank you.

**Comment by pavanchow** [comment]
@vaibhavkurhe27 There is a special character in your codebase which is breaking the build process. Please remove that special character to fix this issue. 
GitHub is not accepting this special character and you can see it in the [RAW format](https://raw.githubusercontent.com/virtual-labs/exp-ip-pressure-control-coep/dev/experiment/references.md) of your [references.md](https://github.com/virtual-labs/exp-ip-pressure-control-coep/blob/dev/experiment/references.md).

**RAW**: https://raw.githubusercontent.com/virtual-labs/exp-ip-pressure-control-coep/dev/experiment/references.md
**SOURCE**: https://github.com/virtual-labs/exp-ip-pressure-control-coep/blob/dev/experiment/references.md

**Comment by vaibhavkurhe27** [comment]
@pavanchow Hi, I tried to figure out the error for the following labs but not able to do that. I had uploaded the content but I am not able to test these experiments as they do not show any data. Last time you have suggested me to replace double quotes from reference and procedure which do not support GitHub pages. I did this still the situation is the same. Can you please check one of these experiments and tell me the problem?

1) https://github.com/virtual-labs/exp-pe-level-control-coep
2) https://github.com/virtual-labs/exp-pe-temperature-control-coep
3) https://github.com/virtual-labs/exp-pe-pressure-control-coep
4) https://github.com/virtual-labs/exp-pe-flow-control-coep

**Comment by pavanchow** [comment]
@vaibhavkurhe27 There is a special character in theory.md and it is breaking the build process. 

RAW: https://raw.githubusercontent.com/virtual-labs/exp-pe-level-control-coep/dev/experiment/theory.md
Source: https://github.com/virtual-labs/exp-pe-level-control-coep/blob/dev/experiment/theory.md

**Comment by vaibhavkurhe27** [comment]
Yes, I have seen and replaced those quotes. That is why I deleted the previous comment. Thank you for the immediate response. Will test the experiment now.

**Comment by vaibhavkurhe27** [comment]
@pavanchow 
I need help regarding the procedure tab. When I check on the GitHub page for steps it seems perfect but when I check on the lab link, the steps are in a single row and it does not seem appropriate. Please find the screenshot for both.
GitHub page :
![image](https://user-images.githubusercontent.com/75834874/106711807-11494a80-661e-11eb-8697-c7a538afb0f4.png)

URL page :
![image](https://user-images.githubusercontent.com/75834874/106711846-21612a00-661e-11eb-9017-05ab96e310e8.png)
