### ISSUE TITLE
Request to host the Labs of College Of Engineering Pune

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#66]
Dear Vlead Team,
Please host the following Labs of College Of Engineering Pune (CoE,Pune)

Electrical Engineering:
1. Industrial Automation Laboratory - "https://github.com/Virtual-Labs/industrial-automation-laboratory-coep"
2. Sensor Modeling & simulation - "https://github.com/Virtual-Labs/sensor-laboratory-coep"
3. Programmable logic controller - "https://github.com/Virtual-Labs/programmable-logic-controller-coep"
4. Electrical Machines - "https://github.com/Virtual-Labs/electrical-machines-coep"

Mechanical Engineering: 
1. Vibration Acoustics - "https://github.com/Virtual-Labs/vibration-and-acoustics-coep"
2. Micromachining Laboratory - "https://github.com/Virtual-Labs/micro-machining-laboratory-coep"
3. FAB Laboratory - "https://github.com/Virtual-Labs/fab-laboratory-coep"

Biotechnology & Biomedical Engineering : 
1. Biomedical & Signal processing Laboratory - "https://github.com/Virtual-Labs/bio-medical-and-signal-processing-laboratory-coep"

**Comment by jayanthsagar** [comment]
Hi sushilmedhe,

We have deployed your labs on AWS.
7 of your labs are working fine.
Ther is a issue with Industrial Automation lab.
lib directory in /src/ is missing which basically contains jquery files used by UIkit.
Please add the lib from you working lab sources(copy and paste). and raise request to host it once again.
Here are your rest of the labs URLs
http://sl-coep.vlabs.ac.in
http://plc-coep.vlabs.ac.in
http://em-coep.vlabs.ac.in
http://va-coep.vlabs.ac.in
http://mm-coep.vlabs.ac.in
http://fab-coep.vlabs.ac.in
http://bmsp-coep.vlabs.ac.in

**Comment by jayanthsagar** [comment]
I am tagging this as Invalid. please raise a separate request for separate lab.
