### ISSUE TITLE
Experiment Repository Creation Request for Process Loop Component III COEP

### ISSUE THREAD

**Issue by vaibhavkurhe27** [virtual-labs/engineers-forum#662]
Use this to get your experiment repository created or updated on GitHub under the Virtual Labs organization.

Coordinating Institute: COEP
Approver’s Name: IIT Bombay
Approved Proposal:
proposal-Vlab phase III_Process loop components1 (1).pdf

Primary GitHub Handle Details:

Virtual Labs
Username: @sushilmedhe
Gmail: vaibhav.aniket82@gmail.com
Secondary GitHub Handle Details:
1)Name: Vaibhav Kurhe
GitHub Handle: @vaibhavkurhe27
Email Id: vrk.vlab@coep.ac.in

Refer to the above proposal, as we have divided those labs previously, I need to add 5 repositories to this as follow,
1) Configure a Transmitter for a particular process application
2) Calibration and fault finding of current to pneumatic converter
3) Calibration and fault finding of pneumatic to current converter
4) Design High/Low selector for interlocking in the process industry
5) Design an alarm annunciator

**Comment by priya100raman** [comment]
@vaibhavkurhe27 , please provide an institute specific Primary GitHub handle

**Comment by coepvlab** [comment]
Primary GitHub Handle Details:

Virtual Labs
Username: @coepvlab
Gmail: coevlab@gmail.com

Secondary GitHub Handle Details:
1)Name: Vaibhav Kurhe
GitHub Handle: @vaibhavkurhe27
Email Id: vrk.vlab@coep.ac.in

**Comment by pavanchow** [comment]
@vaibhavkurhe27 @coepvlab   Please find the links for **Process Loop Component III** experiments and populate the repositories with sources of the experiments as detailed in Step 4 of the  [migration document](https://github.com/virtual-labs/engineers-forum/blob/master/migration-process.md).


1. Configure a Transmitter for a particular process application - https://github.com/virtual-labs/exp-transmitter-particular-process-coep

2. Calibration and fault finding of current to pneumatic converter - https://github.com/virtual-labs/exp-current-pneumatic-converter-coep

3. Calibration and fault finding of pneumatic to current converter - https://github.com/virtual-labs/exp-pneumatic-current-converter-coep

4. Design High/Low selector for interlocking in the process industry - https://github.com/virtual-labs/exp-high-low-selector-coep

5. Design an alarm annunciator - https://github.com/virtual-labs/exp-alarm-annunciator-coep

**Comment by pavanchow** [comment]
@vaibhavkurhe27 @coepvlab @sushilmedhe
Please click on each link and accept invitations to push code to Process Loop Component III exp repositories.

1. Configure a Transmitter for a particular process application - https://github.com/virtual-labs/exp-transmitter-particular-process-coep/invitations

2. Calibration and fault finding of current to pneumatic converter - https://github.com/virtual-labs/exp-current-pneumatic-converter-coep/invitations

3. Calibration and fault finding of pneumatic to current converter - https://github.com/virtual-labs/exp-pneumatic-current-converter-coep/invitations

4. Design High/Low selector for interlocking in the process industry - https://github.com/virtual-labs/exp-high-low-selector-coep/invitations

5. Design an alarm annunciator - https://github.com/virtual-labs/exp-alarm-annunciator-coep/invitations
