### ISSUE TITLE
help wanted reg Container

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#67]
I am not able to establish internet connection on the container created . (im not behind proxy)
can anyone help me for the same. 
I am unable to deploy my lab & shift to level 5 because of this issue.

**Comment by sivashankerN** [comment]
can you give us output of 
1. Steps you have done for creating container
2. lsb_release -a
3. ifconfig
4. vim /etc/resolv.conf
5. ping google.com

**Comment by pushpdeep** [comment]
1. vzctl create

2. root@localhost:/# lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:    precise

3.
root@localhost:/# ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:89 errors:0 dropped:0 overruns:0 frame:0
          TX packets:89 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:9608 (9.6 KB)  TX bytes:9608 (9.6 KB)

4. root@localhost:/# ping google.com
ping: unknown host google.com

5 .
193.168.43.1

*---Pushpdeep.Mishra*


*Tuberculosis Daily http://bit.ly/iCACcq <http://bit.ly/iCACcq>*

**Comment by sivashankerN** [comment]
run '''vzctl CTID set --ipadd x.x.x.x --save''' from your host machine.
then restart container

**Comment by ecthiender** [comment]
Closing this. If issue persists, please don't hesitate to repoen.

**Comment by pushpdeep** [comment]
Yes,
Sripati has solved issue
