### ISSUE TITLE
Request to host the Industrial Automation Laboratory of COE Pune

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#68]
Hello Jayanth,
I have updated lib folder in Industrial Automation Laboratory.

Electrical Engineering:
1. Industrial Automation Laboratory- "https://github.com/Virtual-Labs/industrial-automation-laboratory-coep"

**Comment by jayanthsagar** [comment]
Deployed. You can access your lab using http://ial-coep.vlabs.ac.in

**Comment by vxc** [comment]
Your lab requires a plugin to run, but your main page does not list the end
user (browser) requirements.



Sincerely,

Venkatesh Choppella, PhD.
Associate Professor
IIIT Hyderabad
Gachibowli, Hyderabad 500 032
Ph: +91-965-274-0281


http://0.internet.org/unavailable
"Internet.org is currently available only on the Reliance Network"

**Comment by sushilmedhe** [comment]
I am having a problem with the loading images to the tabs. I will sort out shortly and make request again to host the lab.

**Comment by jayanthsagar** [comment]
Updated your lab sources on AWS. Please list the client side dependency on the home page as suggested by @vxc
