### ISSUE TITLE
Grant the permission for the Repository COEP

### ISSUE THREAD

**Issue by sushilmedhe** [virtual-labs/engineers-forum#688]
@priya100raman @pavanchow 
Please grant the permission for the repository to modify the experiment. The link is given below.

Link - https://github.com/virtual-labs/fab-laboratory-coep

Primary github handle details:
1)Name: CoEP 
Username: @coepvlab
Gmail: coevlab@gmail.com

Secondary GitHub Handle Details:
1)Name: Vaibhav Kurhe
GitHub Handle: @vaibhavkurhe27
Email Id: vrk.vlab@coep.ac.in

**Comment by pavanchow** [comment]
@sushilmedhe 
Gave access to https://github.com/virtual-labs/fab-laboratory-coep. Please click on the link below and accept invitations 

URL: https://github.com/virtual-labs/fab-laboratory-coep/invitations
