### ISSUE TITLE
 Request to host the lab of Sensor Modeling & simulation Lab-COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#69]
Hi Jayanth,
Please host the  Sensor Modeling & simulation Lab.

Sensor Modeling & simulation - "https://github.com/Virtual-Labs/sensor-laboratory-coep"

**Comment by jayanthsagar** [comment]
Deployed. You can access your lab using http://sl-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
I am having a problem with the loading images to the tabs. I will sort out shortly and make request again to host the lab.

**Comment by jayanthsagar** [comment]
Updated

**Comment by sushilmedhe** [comment]
Please host the updated sensor lab.

URL : "https://github.com/Virtual-Labs/sensor-laboratory-coep"

**Comment by jayanthsagar** [comment]
Updated

**Comment by sushilmedhe** [comment]
Please host the sensor lab.
URL : "https://github.com/Virtual-Labs/sensor-laboratory-coep"
