### ISSUE TITLE
Lab/Experiment Hosting Request for for Data Structures - 1 IIITH

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#695]
## *Lab/Experiment(s) Hosting Request*
Use this issue to get your lab and experiment repositories hosted on Virtual Labs. This issue also is used to host labs and their experiments that have been migrated to Phase 3 lab/exp format from Phase 2. 

Please provide item 1 for all the experiments of the lab

1. **Hosting Unit**:  
| No.| Experiment Name | Experiment repository URL | Branch/Tag |
|1. |Bubble Sort | https://github.com/virtual-labs/exp-bubble-sort-iiith| v1.0.1 |
|2. |Merge Sort | https://github.com/virtual-labs/exp-merge-sort-iiith|  v1.0.1 |
|3.| Heap Sort | https://github.com/virtual-labs/exp-heap-sort-iiith|   v1.0.1 |
|4. |Quick Sort | https://github.com/virtual-labs/exp-quick-sort-iiith |  v1.0.1 |
|5. |Depth First Search |https://github.com/virtual-labs/exp-dfs-iiith | v1.0.1 |
|6. |Breadth First Search| https://github.com/virtual-labs/exp-bfs-iiith | v1.0.1 |
|7. |Tree Traversal | https://github.com/virtual-labs/exp-tree-traversal-iiith | v1.0.1 |
|8. |Binary Search Trees|https://github.com/virtual-labs/exp-bst-iiith | v1.0.1 |
|9. |Stacks and Queues| https://github.com/virtual-labs/exp-stacks-queues-iiith | v1.0.1 | 
|10.| Infix to Postfix | https://github.com/virtual-labs/exp-infix-postfix-iiith | v1.0.1 |
|11.| Unsorted Arrays | https://github.com/virtual-labs/exp-unsorted-arrays-iiith | v1.0.1 |
|12.| Hashtables| https://github.com/virtual-labs/exp-hashtables-iiith | v1.0.1 | 
|13.| Linked lists | https://github.com/virtual-labs/exp-linked-lists-iiith  | v1.0.1 | 
|14.| Polynomial Arithmetic using linked lists | https://github.com/virtual-labs/exp-polynomial-arithmetic-iiith  | v1.0.1 | 

2. **GitHub Handle**: Balamma Boya
**Name :** Balamma
**Email:** balamma@vlabs.ac.in

**Comment by pavanchow** [comment]
@BalammaBoya An issue for "Data Structures - 1" already exists. Please move this issue to #534 and close this.

**Comment by BalammaBoya** [comment]
This is a duplicate issue of [Data Structures-I](https://github.com/virtual-labs/engineers-forum/issues/534). So closing the duplicate issue.

**Comment by BalammaBoya** [comment]
This is a duplicate issue of [Data Structures-I](https://github.com/virtual-labs/engineers-forum/issues/534). So closing the duplicate issue.

**Comment by mittalshivam2709** [comment]
Hi, please give me access to this lab so that I can fix the bugs.
My github handle is [https://github.com/mittalshivam2709](url)

**Comment by ravikiran2020** [comment]
@mittalshivam2709 Invitation has been. Please accept them.
