### ISSUE TITLE
Issue with designing labspec for database and datamining lab!

### ISSUE THREAD

**Issue by apurv111** [Virtual-Labs/engineers-forum#7]
In my labspec, I need to take care of passing installing 'sage' and creating a 'notebook' in sage for admin.

To do this, I will need to set password for the 'notebook', the procedure is as follows:
```shell
$sage -c 'notebook(interface="",directory="/root/.sage/sage_notebook.sagenb",port=80,accounts=true)'
```
This will ask me to set admin credentials to the sage notebook. This is a mandatory step in deploying database and datamining lab.

So I tried inserting the same command in 
> "build": ["sshpass -p 'mypass' sage -c 'notebook(interface="",directory="/root/.sage/sage_notebook.sagenb",port=80,accounts=true)'", "make all -C ../src", "sh start_sage"], 

The problem with this approach is, sshpass can pass argument only once. But when I am setting password for the first time to sage, it asks to retype the password for confirmation.

example:
```shell
$sage -c 'notebook(interface="",directory="/root/.sage sage_notebook.sagenb",port=80,accounts=true)'
Enter Password : 
Re-Type password:
```
To automate such a senerio, I heard of expect script, but I am not sure if that works. I request systems team and ADS team suggest a simpler solution to this problem?

**Comment by ecthiender** [comment]
The problem is none of us has explored this yet. I think Sai is also trying to install sage and he has dug up something about expect script. Maybe you can talk to him and get to know more.

I don't think there is a simpler solution, unless you can ask sage to not to prompt for re-typing the password.

**Comment by anhsirksai** [comment]
try with autoexpect !!
