### ISSUE TITLE
Request to host the lab of Programmable logic controller Lab-COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#70]
Hi Jayanth,
Please host the Programmable logic Controller Lab

Programmable logic controller - "https://github.com/Virtual-Labs/programmable-logic-controller-coep"

**Comment by jayanthsagar** [comment]
Deployed. You can access your lab using http://plc-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
I am having a problem with the loading images to the tabs. I will sort out shortly and make request again to host the lab.

**Comment by jayanthsagar** [comment]
Updated
