### ISSUE TITLE
The UI issue for simulator page in new uploaded simulator - CoEP

### ISSUE THREAD

**Issue by coepvlab** [virtual-labs/engineers-forum#701]
@pavanchow @priya100raman 
Please find the screenshot console. The simulator page's height is increasing continuously and hence the scrolling is added to the page unnecessarily.  We have not added any iframeresize.js file in our code. Please look into the issue.  All 5 newly added labs have the same issue. Also, inform us if we need to do anything from our side.

![image_2021_04_06T06_25_25_578Z](https://user-images.githubusercontent.com/78401352/113668224-8b09bd00-96cf-11eb-9164-f051e07bb8dd.png)

**Comment by pavanchow** [comment]
@coepvlab We have fixed the issue on all 5 labs. Could you please check and approve? If fixed, please close this issue.

**Comment by coepvlab** [comment]
Approved. Thank you.
