### ISSUE TITLE
Experiment Repository Creation Request for Colloid and Surface Chemistry Lab

### ISSUE THREAD

**Issue by mrudhvika940** [virtual-labs/engineers-forum#703]
## *Repository Creation Request*
Use this to get your experiment repository created or updated on GitHub under Virtual Labs organization.

1. #### Coordinating Institute: IIITH:

2. #### Approver’s Name: 

3. #### Approved Proposal: 

4. #### Primary GitHub Handle Details: 
   ##### Name: Virtual Labs 
   ##### GitHub Handle: virtual-labs
   ##### Email id: hosting@vlabs.ac.in 

5. #### Secondary GitHub Handle Details:  
   ##### Name: Mrudhvika Damaraju
   ##### GitHub Handle: mrudhvika940
   ##### Email id: mrudhvika@vlabs.ac.in 

Following are the 9 experiments in the Colloid and Surface Chemistry Lab

1. Preparation of Sols
2. Preparation of Gels
3. Demonstration of the Preparation and Use of Association Colloids (Micelles)
4. Determination of Critical Micelle Concentration (CMC) of a Surfactant
5. Demonstration of the Surface Tension Lowering of Water by Soaps/Detergents
6. Demonstration of Tyndall Effect or Tyndall Scattering in Colloidal Systems
7. Gel Electrophoresis
8. Demonstration of the Surface-Effect on Chemical Properties of Finely Divided Particles
9. Study of the Catalytic Effects of Finely Divided Particles

**Comment by pavanchow** [comment]
@mrudhvika940  Experiment repositories for Colloid and Surface Chemistry Lab is already on 12, Jan 2021. Please click on the following link to redirect to the initial repository creation request: 
https://github.com/virtual-labs/engineers-forum/issues/652#issuecomment-758484102

Please close this issue.
