### ISSUE TITLE
Experiment Repository Creation Request for Strength of Materials IIITH

### ISSUE THREAD

**Issue by BalammaBoya** [virtual-labs/engineers-forum#709]
## *Repository Creation Request*
Use this to get your experiment repository created or updated on GitHub under Virtual Labs organization.

1. #### Coordinating Institute: IIITH

2. #### Approver’s Name:

3. #### Approved Proposal:

4. #### Primary GitHub Handle Details: 
   ##### Name: Virtual Labs 
   ##### GitHub Handle: virtual-labs
   ##### Email id: hosting@vlabs.ac.in 

5. #### Secondary GitHub Handle Details:  
   ##### Name: Balamma Boya
   ##### GitHub Handle: balammaboya
   ##### Email id: balammaboya@vlabs.ac.in 

Following are the 10 experiments in the Strength of Materials lab :
    
1. Tensile Test Experiment
2. Compression Test Experiment
3. Shear Test Experiment
4. Torsion Test Experiment
5. Impact Test Experiment
6. Creep Test Experiment
7. Fatigue Test Experiment
8. Compression Test on Spring Experiment
9. Principal Stresses Experiment
10. Rockwell Hardness Experiment

**Comment by pavanchow** [comment]
@BalammaBoya Experiment repositories for Strength of Materials Lab are already created on 04, Feb 2021 upon your request. Please click on the following link to redirect to the initial repository creation request:
https://github.com/virtual-labs/engineers-forum/issues/664

Please close this issue.

**Comment by BalammaBoya** [comment]
Duplicate issue.
