### ISSUE TITLE
Request to host the lab of Electrical Machines Lab-COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#71]
Hi Jayanth,
Please host the Electrical Machines Lab.

Electrical Machines - "https://github.com/Virtual-Labs/electrical-machines-coep"

**Comment by jayanthsagar** [comment]
Deployed. you can access your lab using http://em-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
I am having a problem with the loading images to the tabs. I will sort out shortly and make request again to host the lab.

**Comment by jayanthsagar** [comment]
Error in loading of icons still exist. please check it again.

**Comment by sushilmedhe** [comment]
No problem with the icons. They get loaded properly. Check once and tell me the status.

**Comment by jayanthsagar** [comment]
Checked it. Now loading fine.
