### ISSUE TITLE
Request to host the lab of Vibration Acoustics Lab-COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#72]
Hi Jayanth,
please host the Vibration Acoustics Lab.

Vibration Acoustics - "https://github.com/Virtual-Labs/vibration-and-acoustics-coep"

**Comment by jayanthsagar** [comment]
Deployed. You can access your lab using http://va-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
I am having a problem with the loading images to the tabs. I will sort out shortly and make request again to host the lab.

**Comment by jayanthsagar** [comment]
Updated
