### ISSUE TITLE
Request to host the lab of Micromachining Laboratory Lab-COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#73]
Hi Jayanth,
please host the Micromachining Laboratory Lab.

Micromachining Laboratory - "https://github.com/Virtual-Labs/micro-machining-laboratory-coep"

**Comment by jayanthsagar** [comment]
Deployed. You can access your lab using http://mm-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
I am having a problem with the loading images to the tabs. I will sort out shortly and make request again to host the lab.

**Comment by jayanthsagar** [comment]
Updated
