### ISSUE TITLE
Request to host the lab of FAB Laboratory Lab-COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#74]
Hi Jayanth,
please host the FAB Laboratory Lab

FAB Laboratory - "https://github.com/Virtual-Labs/fab-laboratory-coep"

**Comment by jayanthsagar** [comment]
Deployed. you can access your lab using 
http://fab-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
I am having a problem with the loading images to the tabs. I will sort out shortly and make request again to host the lab.

**Comment by jayanthsagar** [comment]
Updated
