### ISSUE TITLE
Request to host the lab of Biomedical & Signal processing Laboratory Lab-COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#75]
Hi Jayanth,
Please host the Biomedical & Signal processing Laboratory Lab.

Biomedical & Signal processing Laboratory - "https://github.com/Virtual-Labs/bio-medical-and-signal-processing-laboratory-coep"

**Comment by jayanthsagar** [comment]
Deployed. youcan access your lab using
http://bmsp-coep.vlabs.ac.in

**Comment by sushilmedhe** [comment]
I am having a problem with the loading images to the tabs. I will sort out shortly and make request again to host the lab.

**Comment by jayanthsagar** [comment]
Updated
