### ISSUE TITLE
Experiment Repository Creation Request for Surveying Lab - IITR 

### ISSUE THREAD

**Issue by rajeevfee** [virtual-labs/engineers-forum#756]
## *Repository Creation Request*
Use this to get your experiment repository created or updated on GitHub under the Virtual Labs organization.

1. #### Coordinating Institute: IIT Roorkee

2. #### Approver’s Name: Dr RS Anand

3. #### Approved Proposal: Request to two more experiments in a currently hosted surveying lab
**Exp-09 To find out elevations of various points on the ground using auto level ( Fly Level).**
**Exp-10 Observations of vertical and horizontal angles using total station  (Total station ).**
*_08 experiments repo has already been created._ 

4. #### Hosted url: http://sl-iitr.vlabs.ac.in/

5. #### Primary GitHub Handle Details: 
    1. Name: Dr RS Anand
        GitHub Handle: @anandfee
        Email id: anandfee@gmail.com

   2. Name: Rajeev Kumar
      GitHub Handle: @rajeevfee
      Email id: rajeevkumar.rke@gmail.com

   3.  Name: Nipun Jain
       GitHub Handle: @jnipun1994
       Email id: nipunjain1305@gmail.com

   4. Name: Jasbir Singh
      GitHub Handle: @jasbir56
      Email id: jasbirjassy6@gmail.com

   5. Name: Virtual Labs
       GitHub Handle: @vlab-iitr
       Email id: virtual-lab@iitr.ac.in

Note -  The last issue request number is #752.

**Comment by rajeevfee** [comment]
@pavanchow I request to add two more experiments in the already hosted Surveying lab. Kindly do needful for the same.

**Comment by pavanchow** [comment]
@rajeevfee Could you please mention the experiment names in a new comment in https://github.com/virtual-labs/engineers-forum/issues/752 and please close this issue. Creating multiple "Experiment Repository Creation Requests" for the same lab would create duplicate issues on engineers' form.

**Comment by rajeevfee** [comment]
@pavanchow Resend the request to #752.
