### ISSUE TITLE
Request to host unit-operation-reaction-engineering-and--process-control lab -nitk

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#77]
Hi Jayanth,
Please host the unit-operation-reaction-engineering-and--process-control lab -nitk.
Repo Url:
https://github.com/Virtual-Labs/unit-operation-reaction-engineering-and--process-control-nitk.git.

Thanks 
Shivakumar

**Comment by jayanthsagar** [comment]
Deployed. you can access lab using http://uorepc-nitk.vlabs.ac.in

**Comment by sranjanagi** [comment]
I have made some changes in the lab, can you redeploy the lab.

**Comment by jayanthsagar** [comment]
Redployed, please check.

**Comment by sranjanagi** [comment]
i have made changes,redeploy the lab.

**Comment by jayanthsagar** [comment]
Redeployed, please check.
