### ISSUE TITLE
Request for hosting machine-dynamics-and-mechanical-vibrations lab -nitk

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#78]
Hi Jayanth,
Please host the  machine-dynamics-and-mechanical-vibrations lab -nitk.
Repo Url:
https://github.com/Virtual-Labs/machine-dynamics-and-mechanical-vibrations-nitk

Thanks 
Shivakumar

**Comment by jayanthsagar** [comment]
Deployed. you can access lab using http://mdmv-nitk.vlabs.ac.in

**Comment by sranjanagi** [comment]
Jayant i have made some changes in lab .please redeploy it.
There was issue with simulation

**Comment by jayanthsagar** [comment]
Updated.

Closed

**Comment by sranjanagi** [comment]
I have made some changes in the lab .Please redeploy the lab.

**Comment by MSSoumya** [comment]
The lab was redeployed.

**Comment by sranjanagi** [comment]
Lab is working fine .
