### ISSUE TITLE
Request to host mechanics-of-machine lab -nitk

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#79]
Hi Jayanth,
Please host the mechanics-of-machine lab -nitk.
Repo Url:
https://github.com/Virtual-Labs/mechanics-of-machine-nitk.

Thanks 
Shivakumar s r

**Comment by jayanthsagar** [comment]
Deployed. you can access lab using http://mm-nitk.vlabs.ac.in

**Comment by sranjanagi** [comment]
In  this lab simulator(javascript,flash ) is not working properly after hosting..
But i tested in ADS ,it worked perfectly.
please see through it .

**Comment by sranjanagi** [comment]
In this lab simulator(javascript,flash ) is not working properly after hosting..
But i tested in ADS ,it worked perfectly.
please see through it .

**Comment by jayanthsagar** [comment]
@soujanya123 . can you please look into this.

**Comment by sranjanagi** [comment]
I have cross verified with my sources ,found file missing and I have made changes in repo.can you redeploy the lab.

**Comment by jayanthsagar** [comment]
Updated.

**Comment by sranjanagi** [comment]
still have same issues with simulators.

**Comment by jayanthsagar** [comment]
Sent mail to IITD to revert back to old URL. closing it for now. please reopen after making necessary changes.

**Comment by sranjanagi** [comment]
I have made some changes .can you redeploy the lab .

**Comment by jayanthsagar** [comment]
Deployed. Please verify whether required changes are reflected.
