### ISSUE TITLE
How-To: When my lab is using a database

### ISSUE THREAD

**Issue by samodk** [Virtual-Labs/engineers-forum#8]
Hi
I m not able to understand level 4 and 5 , Kindly make me inform how to put our remaininf labs at 4 and 5 which contain  database. The two labs are at level 5 right now, But remaning labs has a database.I m working currently on Virtual chemistry lab.

Thanks
Samod
Dayalbagh University

**Comment by apurv111** [comment]
refer to the documentation here: 
https://github.com/Virtual-Labs/lik/wiki/Script-for-lab-using-database

**Comment by ecthiender** [comment]
@samodk please let us know if the above answer solve your solves your issue, we'll close this issue then :)
