### ISSUE TITLE
Request for hosting strength-of-materials lab -nitk

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#80]
Hi Jayanth,
Please host the strength-of-materials lab -nitk.
Repo Url:
https://github.com/Virtual-Labs/strength-of-materials-nitk.

Thanks and regards
Shivakumar s r

**Comment by jayanthsagar** [comment]
Deployed. you can access lab using http://sm-nitk.vlabs.ac.in

**Comment by sranjanagi** [comment]
I have made some changes in the lab, can you redeploy the lab.

**Comment by jayanthsagar** [comment]
Redeployed, please check
