### ISSUE TITLE
Request for hosting fluid-mechanics lab-nitk

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#81]
Hi Jayanth,
Please host the fluid-mechanics lab -nitk.

fluid-mechanics-nitk Repo: - "https://github.com/Virtual-Labs/fluid-mechanics-nitk".

Thanks and Regards,
Shivakumar

**Comment by jayanthsagar** [comment]
Deployed. you can access your lab using http://fm-nitk.vlabs.ac.in

**Comment by sranjanagi** [comment]
I have made some changes in the lab, can you redeploy the lab.

**Comment by jayanthsagar** [comment]
Redeployed, please check.
