### ISSUE TITLE
Request for hosting Substation Automation lab-nitk

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#82]
Hi Jayanth,
Please host the Substation Automation lab-nitk.

Substation Automation-nitk Repo: - "https://github.com/Virtual-Labs/substration-automation-nitk".

Thanks and Regards,
Shivakumar

**Comment by jayanthsagar** [comment]
Deployed sa-nitk.vlabs.ac.in

**Comment by jayanthsagar** [comment]
Redployed. please check.
