### ISSUE TITLE
Request for hosting Industrial Electric Drives lab-nitk

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#83]
Hi Jayanth,
Please host the Industrial Electric Drives lab-nitk.

Industrial Electric Drives lab-nitk Repo: - 
"https://github.com/Virtual-Labs/industrial-electrical-drives-nitk".

Thanks and Regards,
Shivakumar

**Comment by jayanthsagar** [comment]
Deployed. ied-nitk.vlabs.ac.in

**Comment by jayanthsagar** [comment]
Redeployed. Please check
