### ISSUE TITLE
magnetic levitation lab - IITB

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#84]
please host the Magnetic Levitation lab, its at level 6

https://github.com/pushpdeep/maglev_iitb

**Comment by ecthiender** [comment]
All virtual labs are supposed to be under the Virtual Labs organization [https://github.com/virtual-labs]. If your repository does not exist, request for the same and then push your lab there. Once done, please raise the request to host again.

Thanks!
