### ISSUE TITLE
Requesting for resending the invite links for rest of the experiments

### ISSUE THREAD

**Issue by spcrc-sig-pro-vl** [virtual-labs/engineers-forum#870]
Dear Virtual Labs Team Members,

Could you please resend the invite link for the experiments mentioned below. We couldn't accept them earlier, and the previous link expired. We are ready with the experiment details and looking forward to updating the codes on Git.

Experiment 4:
Signal synthesis: synthesize harmonic signals, combine harmonics to generate a musical signal, listen to synthesized audio file - https://github.com/virtual-labs/exp-signal-synthesis-iiith

Experiment 5:
Z-transform (for discrete-time signals & systems): ROC, poles and zeros, system properties, frequency analysis - https://github.com/virtual-labs/exp-z-transform-iiith

Experiment 6:
Laplace transform (for continuous-time signals & systems): eigenfunctions of LTI systems, region of convergence (ROC), effect of poles & zeros on system properties, solve ODE, frequency response using geometric analysis - 
https://github.com/virtual-labs/exp-laplace-transform-iiith

Experiment 7:
Periodic signals: Fourier series of periodic signals, periodic signal inputs to LTI systems, quasi-periodic signals, finding period from convolution and peak picking - 
https://github.com/virtual-labs/exp-periodic-signals-iiith

Experiment 8:
Stability of systems: what is stable system, BIBO stability, stability of LTI systems -
https://github.com/virtual-labs/exp-stability-of-systems-iiith

Thank you

**Comment by pavanchow** [comment]
Hello @spcrc-sig-pro-vl ,
Resent the invitations for the experiments mentioned. Please check and let us know.

**Comment by spcrc-sig-pro-vl** [comment]
Dear sir,

I have accepted the invitation.

Thank you very much,
Sasanka GRS

**Comment by priya100raman** [comment]
Closing this issue and capturing the comments in the original issue #789.
