### ISSUE TITLE
Lab/Experiment Hosting Request for  Network Security Lab - AU

### ISSUE THREAD

**Issue by AmritaValueCS-22** [virtual-labs/engineers-forum#895]
## *Lab/Experiment(s) Hosting Request*
Use this issue to get your lab and experiment repositories hosted on Virtual Labs. This issue also is used to host labs and their experiments that have been migrated to Phase 3 lab/exp format from Phase 2. 

Please provide item 1 for all the experiments of the lab

1. **Hosting Unit**: 
| No.| Experiment Name | Experiment repository URL | Branch/Tag |
|1| Simulation of the Transmission Control Protocol (TCP) communication between two entities|https://github.com/virtual-labs/exp-tcp-au|main|
|2| Active attacks - TCP SYN Flood attack | https://github.com/virtual-labs/exp-active-attacks-au |main|
|3|  Passive attacks - Eavesdropping | https://github.com/virtual-labs/exp-passive-attacks-au |main|
|4|  Combining passive and active attacks - Replay Attacks | https://github.com/virtual-labs/exp-replay-attacks-au |main|
|5| Simulation and working of Kerberos protocol for mutual authentication  | https://github.com/virtual-labs/exp-kerberos-protocol-au|main|
|6| To simulate the Secure Socket Layer (SSL) transmission between a user and a server | https://github.com/virtual-labs/exp-ssl-simulation-au |main|
|7| To understand intrusion prevention systems- Firewall | https://github.com/virtual-labs/exp-intrusion-prevention-systems-au |main|
|8| Understanding Intrusion detection system using firewalls| https://github.com/virtual-labs/exp-intrusion-detection-system-au |main|

2. **GitHub Handle**: @AmritaValueCS-22
3. **Virtual Lab Phase**: Virtual Labs Phase 3 
4. **Existing Hosted URL**:
5. **Approved Proposal**: [Network_Security_proposal_PH-IV.docx](https://github.com/virtual-labs/engineers-forum/files/10489139/Network_Security_proposal_PH-IV.docx)

**Comment by priya100raman** [comment]
@AmritaValueCS-22 , is this an extended Phase 3 Lab?  If so, we can host the lab only when the completed lab has been reviewed and approved by external reviewers. Please provide the approval if this requirement has been met.

**Comment by AmritaValueCS-22** [comment]
Development phase is over ,ready for review
