### ISSUE TITLE
git clone from github gives a 'server certificate verification failed' error

### ISSUE THREAD

**Issue by sranjanagi** [Virtual-Labs/engineers-forum#9]
LabManager: clone_repo(): git clone failed: cse02NewUnit Command '['git', 'clone', 'https://sranjanagi@github.com/sranjanagi/NewUnit.git', '/root/labs/lab-repo-cache/cse02NewUnit']' returned non-zero exit status 128

**Comment by ecthiender** [comment]
I think there is some network issue while cloning. Can you check if internet is working fine inside the container? 

Can you also try this command manually: `git clone https://sranjanagi@github.com/sranjanagi/NewUnit.git` inside the container and see if it git clone works fine. If not, can you paste the output?

**Comment by sranjanagi** [comment]
Hi,


ERROR is :



git clone https://sranjanagi@github.com/sranjanagi/NewUnit.git
Cloning into 'NewUnit'...
error: server certificate verification failed. CAfile:
/etc/ssl/certs/ca-certificates.crt CRLfile: none while accessing
https://sranjanagi@github.com/sranjanagi/NewUnit.git/info/refs
fatal: HTTP request failed


Thanks and Regards,
Shivakumar

**Comment by ecthiender** [comment]
When you paste the repo URL in your OVPL test lab page, can you paste this URL: `https://github.com/sranjanagi/NewUnit.git` instead of `https://sranjanagi@github.com/sranjanagi/NewUnit.git`

Can you please test this and let us know?

**Comment by sranjanagi** [comment]
still getting same error.

**Comment by ecthiender** [comment]
@prakashbh do you know anything about any similar issue?

**Comment by sranjanagi** [comment]
This error, I am facing it first time.

**Comment by AmulyaSri** [comment]
Try, 
 
$git config --global http.sslverify false

This bypasses the SSL Certificate verification. As far as I know, using SSH will resolve these issues. 
Reference : http://unix.stackexchange.com/questions/109880/adding-ssl-certificate-for-github-only-not-all-certificates-from-ca-certificate

**Comment by AmulyaSri** [comment]
Did you try this ?

**Comment by sanchita-dixit** [comment]
@sranjanagi Was this issue resolved? If yes kindly close this issue.
