### ISSUE TITLE
Experiment Repository Creation Request for Adaptive Signal Processing Lab

### ISSUE THREAD

**Issue by rajeevfee** [virtual-labs/engineers-forum#905]
## *Repository Creation Request*
Use this to get your experiment repository created or updated on GitHub under Virtual Labs organization.

1. #### Coordinating Institute: IIT Roorkee

2. #### Approver’s Name:  Dr R S Anand

3. #### Approved Proposal: 

4. #### Hosted url: 

> 1. Simulation and comparative analysis of LMS and RLS algorithms using simulated as well as real time bio-signals. Observe the effect of various adaptation factors like step size, forgetting factor.
> 
> i.	Simulate an Autoregressive stochastic process. 
> ii.	Detect non-stationarity in stochastic processes with LMS and RLS

> 2. Study and implementation of Kalman filter.
> i.	Correspondence between the initial conditions of the Kalman variables and prediction performance
> ii.	With unforced dynamic model and noiseless state space model.
> 
> 3. Simulation of adaptive noise cancellation, interference canceling, channel equalization using appropriate adaptive filters for various scenarios and compare the performance for various other variants of these adaptive algorithms.
> i.	Implementation and analysis of Autoregressive Stochastic processes and Minimum Variance Distortion-less Beamformer using LMS and Monte-Carlo Runs. 
> ii.	Simulate an adaptive prediction and equalization with LMS and RLS Algorithm.
> 4.	Audio synthesis using Differential DSP library

5. #### Primary GitHub Handle Details: 
Name: Dr RS Anand
GitHub Handle: [@anandfee](https://github.com/anandfee)
Email id: [anandfee@gmail.com](mailto:anandfee@gmail.com)

Name: Dr Tharun Reddy
GitHub Handle: tharuniitk
Email id: [tharun@iitk.ac.in](mailto:tharun@iitk.ac.in)

Name: Rajeev Kumar
GitHub Handle: [@rajeevfee](https://github.com/rajeevfee)
Email id: [rajeevkumar.rke@gmail.com](mailto:rajeevkumar.rke@gmail.com)

Name: Nipun Jain
GitHub Handle: [@jnipun1994](https://github.com/jnipun1994)
Email id: [nipunjain1305@gmail.com](mailto:nipunjain1305@gmail.com)

Name: Adarsh
GitHub Handle: adarshvp123
Email id: [adarshvp16@gmail.com](mailto:adarshvp16@gmail.com)

**Comment by ravikiran2020** [comment]
@rajeevfee Request you upload the Approved Proposal for the Adaptive Signal Processing Lab

**Comment by rajeevfee** [comment]
@ravikiran2020 [Approved Proposal](https://docs.google.com/document/d/1Z35iOMbdjhhCEmUa-PR_G3Sa21QJVso3/edit?usp=sharing&ouid=101269617915783460885&rtpof=true&sd=true)

**Comment by priya100raman** [comment]
@rajeevfee , this seems to be a joint proposal between IITR and IITD. 
IITD had already requested for exp repository creation for this lab. We have created the 10 experiments for this lab as per [this](https://github.com/virtual-labs/engineers-forum/issues/859) issue. We assume that this will be one lab and not two separate labs. Let us know if this is not the case.  Please confirm and we will send invites to IITR's 4 experiments repos to the shared GitHub handles.

**Comment by rajeevfee** [comment]
@priya100raman @ravikiran2020 
This is a combined proposal from IIT Delhi (IITD) and IIT Roorkee (IITR), and you can consider it as a single lab. Please send invitations for the requested experimental repos and add the name of IITR as a coordinating Institute.

**Comment by ravikiran2020** [comment]
@rajeevfee Closing this issue as the lab request already created for [Adaptive Singal processing lab](https://github.com/virtual-labs/engineers-forum/issues/859) by IITD
