### ISSUE TITLE
Lab/Experiment Hosting Request for Instrumentation and Control Lab COEPTECH

### ISSUE THREAD

**Issue by vaibhavkurhe27** [virtual-labs/engineers-forum#976]
## *Lab OnBoarding Request*
Use this to register your lab for hosting and/or update the list
of experiments in the lab.

#### Fill the lab name to be displayed on the lab page
1. **Lab Name**: Instrumentation and Control Lab COEPTECH

#### Fill this field to list the experiments that the lab should include

1. **List of Experiments and Repositories**: 
| No.| Experiment Name | Experiment repository URL | Branch | Tag

1) Measurement of shaft Torque and identifying suitable technique for sensing - https://github.com/virtual-labs/exp-shaft-torque-coep, Master Branch, v1.0.0
2) Measurement of flow using a turbine type flow meter for exhaust gas flow measurement - https://github.com/virtual-labs/exp-turbine-type-flow-meter-coep, Master Branch, v1.0.0
3) Measurement of flow using a Rotameter for the fuel supply - https://github.com/virtual-labs/exp-flow-using-rotameter-coep, Master Branch, v1.0.0
4) Power measurement using a dynamometer. - https://github.com/virtual-labs/exp-power-measurement-dynamometer-coep, Master Branch, v1.0.0
5) Calibration of pressure gauge using dead-weight tester - https://github.com/virtual-labs/exp-dead-weight-tester-coep, Master Branch, v1.0.0
6) Identify suitable accelerometer for an application- https://github.com/virtual-labs/exp-accelerometer-coep, Master Branch, v1.0.0
7) Vacuum measurement - Thermal conductivity gauges. - https://github.com/virtual-labs/exp-thermal-conductivity-gauges-coep, Master Branch, v1.0.0
8) Measurement and Control system - Implementation for one application. -https://github.com/virtual-labs/exp-implementation-coep, Master Branch, v1.0.0
9) Identifying building blocks of signal conditioning technique of a sensor. -https://github.com/virtual-labs/exp-building-blocks-of-signal-conditioning-coep, Master Branch, v1.0.0
10) Characterize a density sensor for a particular application - https://github.com/virtual-labs/exp-density-sensor-coep, Master Branch, v1.0.0

#### Optional
1. **Lab Repository url**: 
2. **Introduction**: 

Instrumentation & Control laboratory is developed to understand operation of sensors required for measurements of different industrial parameters. The target audience for the laboratory is second year and third year undergraduate students of engineering. The parameters like flow, density, power, torque, speed, acceleration are described. Total ten experiments are designed to understand sensors’ operation and various competence required to select, design, configure, and maintain these sensors. 
To use this laboratory effectively the users, need to study the fundamentals like working principle of the sensor, operation of the sensor in the field, and troubleshooting methods required. At the end of the experiment a dashboard is displayed to inform the user about his/her areas for improvement.

4. **Objective**: 
- Identify the appropriate sensing technology for the application under test
- Design the sensor by considering all application specific variables
- Characterize the sensor and identify static and dynamic characteristics
- Identify the faults in the sensors and suggest remedial actions

5. **Course Alignment**: All institutes who offer a course in Mechanical Engg, Instrumentation and Control Engg
6. **Target Audience**: 
- UG (2nd Year) 4th Semester
- UG (3rd Year) 5th Semester
- UG (3rd Year) 6th Semester
- UG (4th Year) 7th Semester

**Approval email by reviewer screenshot**
![Hosting approval](https://github.com/user-attachments/assets/cd5bb90f-a14a-4a07-8f70-9b400ace3a9d)

**Comment by ravikiran2020** [comment]
@vaibhavkurhe27 
The Instrumentation and Control Lab is hosted successfully.
Url: https://ic-coep.vlabs.ac.in/
Please check and approve

**Comment by vaibhavkurhe27** [comment]
@ravikiran2020  
Checked and approved. Please host this lab under mechanical engineering.
